/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package dummy.types.impl;

import dummy.common.*;
import dummy.visitation.IVisitor;
import dummy.visitation.IVisitorWithContext;
import dummy.visitation.ITransformer;
import dummy.visitation.ITransformerWithContext;
import dummy.types.enums.*;
import dummy.types.impl.*;
import dummy.types.model.*;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.Objects;
import dummy.types.model.IBag;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

public class Bag implements IBag {
  private String label;

  private List<String> tags;

  public Bag(
    String label,
    List<String> tags) {
    this.label = Objects.requireNonNull(
      label,
      "Argument \"label\" must be non-null.");
    this.tags = Objects.requireNonNull(
      tags,
      "Argument \"tags\" must be non-null.");
  }

  @Override
  public String getLabel() {
    return label;
  }

  @Override
  public void setLabel(String label) {
    this.label = Objects.requireNonNull(
      label,
      "Argument \"label\" must be non-null.");
  }

  @Override
  public List<String> getTags() {
    return tags;
  }

  @Override
  public void setTags(List<String> tags) {
    this.tags = Objects.requireNonNull(
      tags,
      "Argument \"tags\" must be non-null.");
  }

  /**
   * @return a human-readable description of the item.
   */
  public String describe() {
    return "Item with the label " + getLabel();
  }

  /**
   * Iterate recursively over all the class instances referenced from this instance.
   */
  public Iterable<IClass> descend() {
    return Collections.emptyList();
  }

  /**
   * Iterate over all the class instances referenced from this instance.
   */
  public Iterable<IClass> descendOnce() {
    return Collections.emptyList();
  }

  /**
   * Accept the {@code visitor} to visit this instance for double dispatch.
   **/
  @Override
  public void accept(IVisitor visitor) {
    visitor.visitBag(this);
  }

  /**
   * Accept the {@code visitor} to visit this instance for double dispatch
   * with the {@code context}.
   **/
  @Override
  public <ContextT> void accept(
      IVisitorWithContext<ContextT> visitor,
      ContextT context) {
    visitor.visitBag(this, context);
  }

  /**
   * Accept the {@code transformer} to visit this instance for double dispatch.
   **/
  @Override
  public <T> T transform(ITransformer<T> transformer) {
    return transformer.transformBag(this);
  }

  /**
   * Accept the {@code transformer} to visit this instance for double dispatch
   * with the {@code context}.
   **/
  @Override
  public <ContextT, T> T transform(
      ITransformerWithContext<ContextT, T> transformer,
      ContextT context) {
    return transformer.transformBag(this, context);
  }
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
