// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

#include "dummy/common.hpp"
#include "dummy/constants.hpp"
#include "dummy/pattern.hpp"
#include "dummy/revm.hpp"
#include "dummy/verification.hpp"

#pragma warning(push, 0)
#include <map>
#include <set>
#pragma warning(pop)

namespace dummy {
namespace verification {

// region struct Error

Error::Error(
  std::wstring a_cause
) :
  cause(std::move(a_cause)) {
  // Intentionally empty.
}

Error::Error(
  std::wstring a_cause,
  iteration::Path a_path
) :
  cause(std::move(a_cause)),
  path(std::move(a_path)) {
  // Intentionally empty.
}

// endregion struct Error

// region class AlwaysDoneVerificator

class AlwaysDoneVerificator : public impl::IVerificator {
 public:
  void Start() override;
  void Next() override;
  bool Done() const override;
  const Error& Get() const override;
  Error& GetMutable() override;
  long Index() const override;
  std::unique_ptr<impl::IVerificator> Clone() const override;

  virtual ~AlwaysDoneVerificator() = default;
};  // class AlwaysDoneVerificator

void AlwaysDoneVerificator::Start() {
  // Intentionally empty.
}

void AlwaysDoneVerificator::Next() {
  throw std::logic_error(
    "You want to move an AlwaysDoneVerificator, "
    "but the verificator is always done, as its name suggests."
  );
}

bool AlwaysDoneVerificator::Done() const {
  return true;
}

const Error& AlwaysDoneVerificator::Get() const {
    throw std::logic_error(
      "You want to get from an AlwaysDoneVerificator, "
      "but the verificator is always done, as its name suggests."
    );
}

Error& AlwaysDoneVerificator::GetMutable() {
    throw std::logic_error(
      "You want to get mutable from an AlwaysDoneVerificator, "
      "but the verificator is always done, as its name suggests."
    );
}

long AlwaysDoneVerificator::Index() const {
  return -1;
}

std::unique_ptr<impl::IVerificator> AlwaysDoneVerificator::Clone() const {
  return common::make_unique<AlwaysDoneVerificator>(*this);
}

// endregion class AlwaysDoneVerificator

/**
 * Produce a non-recursive verificator of the instance given its runtime model type.
 */
std::unique_ptr<impl::IVerificator> NewNonRecursiveVerificator(
  const std::shared_ptr<types::IClass>& instance
);

// region Non-recursive verificators

namespace non_recursive_verificator {

class OfStructuralFirst : public impl::IVerificator {
 public:
  OfStructuralFirst(
    const std::shared_ptr<types::IClass>& instance
  );

  OfStructuralFirst(
    const OfStructuralFirst& other
  );
  OfStructuralFirst(
    OfStructuralFirst&& other
  );
  OfStructuralFirst& operator=(
    const OfStructuralFirst& other
  );
  OfStructuralFirst& operator=(
    OfStructuralFirst&& other
  );

  void Start() override;
  void Next() override;
  bool Done() const override;
  const Error& Get() const override;
  Error& GetMutable() override;
  long Index() const override;

  std::unique_ptr<impl::IVerificator> Clone() const override;

  ~OfStructuralFirst() override = default;

 private:
  std::shared_ptr<types::IStructuralFirst> instance_;
  bool done_;
  long index_;
  std::unique_ptr<Error> error_;
  std::uint32_t state_;

  void Execute();
};  // class OfStructuralFirst

OfStructuralFirst::OfStructuralFirst(
  const std::shared_ptr<types::IClass>& instance
) :
  // NOTE (mristin)
  // We cast here despite the cost of increasing the use count of the shared pointer.
  // Otherwise, if we didn't cast, we would not be able to have a uniform interface
  // for the verification functions based on the shared pointer.
  instance_(
    std::dynamic_pointer_cast<
      types::IStructuralFirst
    >(
      instance
    )
  ) {
  // Intentionally empty.
}

OfStructuralFirst::OfStructuralFirst(
  const OfStructuralFirst& other
) {
  instance_ = other.instance_;
  done_ = other.done_;
  index_ = other.index_;
  error_ = common::make_unique<Error>(*other.error_);
  state_ = other.state_;
}

OfStructuralFirst::OfStructuralFirst(
  OfStructuralFirst&& other
) {
  instance_ = std::move(other.instance_);
  done_ = other.done_;
  index_ = other.index_;
  error_ = std::move(other.error_);
  state_ = other.state_;
}

OfStructuralFirst& OfStructuralFirst::operator=(
  const OfStructuralFirst& other
) {
  return *this = OfStructuralFirst(other);
}

OfStructuralFirst& OfStructuralFirst::operator=(
  OfStructuralFirst&& other
) {
  if (this != &other) {
    instance_ = std::move(other.instance_);
    done_ = other.done_;
    index_ = other.index_;
    error_ = std::move(other.error_);
    state_ = other.state_;
  }
  return *this;
}

void OfStructuralFirst::Start() {
  state_ = 0;
  Execute();
}

void OfStructuralFirst::Next() {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to move a verificator OfStructuralFirst, "
      "but the verificator was done."
    );
  }
  #endif

  Execute();
}

bool OfStructuralFirst::Done() const {
  return done_;
}

const Error& OfStructuralFirst::Get() const {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to get from a verificator OfStructuralFirst, "
      "but the verificator was done."
    );
  }
  #endif

  return *error_;
}

Error& OfStructuralFirst::GetMutable() {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to get mutable from a verificator OfStructuralFirst, "
      "but the verificator was done."
    );
  }
  #endif

  return *error_;
}

long OfStructuralFirst::Index() const {
  #ifdef DEBUG
  if (Done() && index_ != -1) {
    throw std::logic_error(
      common::Concat(
        "Expected index to be -1 "
        "from a done verificator OfStructuralFirst, "
        "but got: ",
        std::to_string(index_)
      )
    );
  }
  #endif

  return index_;
}

std::unique_ptr<impl::IVerificator> OfStructuralFirst::Clone() const {
  return common::make_unique<
    OfStructuralFirst
  >(*this);
}

void OfStructuralFirst::Execute() {
  while (true) {
    switch (state_) {
      case 0: {
        done_ = false;
        error_ = nullptr;
        index_ = -1;

        if (instance_->unique_to_first().size() > 0) {
          state_ = 1;
          continue;
        }

        error_ = common::make_unique<Error>(
          L"The value must not be empty."
        );
        // No path is prepended as the error refers to the instance itself.
        ++index_;

        state_ = 1;
        return;
      }

      case 1: {
        done_ = true;
        error_ = nullptr;
        index_ = -1;

        // We invalidate the state since we reached the end of the routine.
        state_ = 2;
        return;
      }

      default:
        throw std::logic_error(
          common::Concat(
            "Invalid state_: ",
            std::to_string(state_)
          )
        );
    }
  }
}

class OfStructuralSecond : public impl::IVerificator {
 public:
  OfStructuralSecond(
    const std::shared_ptr<types::IClass>& instance
  );

  OfStructuralSecond(
    const OfStructuralSecond& other
  );
  OfStructuralSecond(
    OfStructuralSecond&& other
  );
  OfStructuralSecond& operator=(
    const OfStructuralSecond& other
  );
  OfStructuralSecond& operator=(
    OfStructuralSecond&& other
  );

  void Start() override;
  void Next() override;
  bool Done() const override;
  const Error& Get() const override;
  Error& GetMutable() override;
  long Index() const override;

  std::unique_ptr<impl::IVerificator> Clone() const override;

  ~OfStructuralSecond() override = default;

 private:
  std::shared_ptr<types::IStructuralSecond> instance_;
  bool done_;
  long index_;
  std::unique_ptr<Error> error_;
  std::uint32_t state_;

  void Execute();
};  // class OfStructuralSecond

OfStructuralSecond::OfStructuralSecond(
  const std::shared_ptr<types::IClass>& instance
) :
  // NOTE (mristin)
  // We cast here despite the cost of increasing the use count of the shared pointer.
  // Otherwise, if we didn't cast, we would not be able to have a uniform interface
  // for the verification functions based on the shared pointer.
  instance_(
    std::dynamic_pointer_cast<
      types::IStructuralSecond
    >(
      instance
    )
  ) {
  // Intentionally empty.
}

OfStructuralSecond::OfStructuralSecond(
  const OfStructuralSecond& other
) {
  instance_ = other.instance_;
  done_ = other.done_;
  index_ = other.index_;
  error_ = common::make_unique<Error>(*other.error_);
  state_ = other.state_;
}

OfStructuralSecond::OfStructuralSecond(
  OfStructuralSecond&& other
) {
  instance_ = std::move(other.instance_);
  done_ = other.done_;
  index_ = other.index_;
  error_ = std::move(other.error_);
  state_ = other.state_;
}

OfStructuralSecond& OfStructuralSecond::operator=(
  const OfStructuralSecond& other
) {
  return *this = OfStructuralSecond(other);
}

OfStructuralSecond& OfStructuralSecond::operator=(
  OfStructuralSecond&& other
) {
  if (this != &other) {
    instance_ = std::move(other.instance_);
    done_ = other.done_;
    index_ = other.index_;
    error_ = std::move(other.error_);
    state_ = other.state_;
  }
  return *this;
}

void OfStructuralSecond::Start() {
  state_ = 0;
  Execute();
}

void OfStructuralSecond::Next() {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to move a verificator OfStructuralSecond, "
      "but the verificator was done."
    );
  }
  #endif

  Execute();
}

bool OfStructuralSecond::Done() const {
  return done_;
}

const Error& OfStructuralSecond::Get() const {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to get from a verificator OfStructuralSecond, "
      "but the verificator was done."
    );
  }
  #endif

  return *error_;
}

Error& OfStructuralSecond::GetMutable() {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to get mutable from a verificator OfStructuralSecond, "
      "but the verificator was done."
    );
  }
  #endif

  return *error_;
}

long OfStructuralSecond::Index() const {
  #ifdef DEBUG
  if (Done() && index_ != -1) {
    throw std::logic_error(
      common::Concat(
        "Expected index to be -1 "
        "from a done verificator OfStructuralSecond, "
        "but got: ",
        std::to_string(index_)
      )
    );
  }
  #endif

  return index_;
}

std::unique_ptr<impl::IVerificator> OfStructuralSecond::Clone() const {
  return common::make_unique<
    OfStructuralSecond
  >(*this);
}

void OfStructuralSecond::Execute() {
  while (true) {
    switch (state_) {
      case 0: {
        done_ = false;
        error_ = nullptr;
        index_ = -1;

        if (instance_->unique_to_second().size() > 0) {
          state_ = 1;
          continue;
        }

        error_ = common::make_unique<Error>(
          L"The value must not be empty."
        );
        // No path is prepended as the error refers to the instance itself.
        ++index_;

        state_ = 1;
        return;
      }

      case 1: {
        done_ = true;
        error_ = nullptr;
        index_ = -1;

        // We invalidate the state since we reached the end of the routine.
        state_ = 2;
        return;
      }

      default:
        throw std::logic_error(
          common::Concat(
            "Invalid state_: ",
            std::to_string(state_)
          )
        );
    }
  }
}

class OfMixedAbstractDescendantOne : public impl::IVerificator {
 public:
  OfMixedAbstractDescendantOne(
    const std::shared_ptr<types::IClass>& instance
  );

  OfMixedAbstractDescendantOne(
    const OfMixedAbstractDescendantOne& other
  );
  OfMixedAbstractDescendantOne(
    OfMixedAbstractDescendantOne&& other
  );
  OfMixedAbstractDescendantOne& operator=(
    const OfMixedAbstractDescendantOne& other
  );
  OfMixedAbstractDescendantOne& operator=(
    OfMixedAbstractDescendantOne&& other
  );

  void Start() override;
  void Next() override;
  bool Done() const override;
  const Error& Get() const override;
  Error& GetMutable() override;
  long Index() const override;

  std::unique_ptr<impl::IVerificator> Clone() const override;

  ~OfMixedAbstractDescendantOne() override = default;

 private:
  std::shared_ptr<types::IMixedAbstractDescendantOne> instance_;
  bool done_;
  long index_;
  std::unique_ptr<Error> error_;
  std::uint32_t state_;

  void Execute();
};  // class OfMixedAbstractDescendantOne

OfMixedAbstractDescendantOne::OfMixedAbstractDescendantOne(
  const std::shared_ptr<types::IClass>& instance
) :
  // NOTE (mristin)
  // We cast here despite the cost of increasing the use count of the shared pointer.
  // Otherwise, if we didn't cast, we would not be able to have a uniform interface
  // for the verification functions based on the shared pointer.
  instance_(
    std::dynamic_pointer_cast<
      types::IMixedAbstractDescendantOne
    >(
      instance
    )
  ) {
  // Intentionally empty.
}

OfMixedAbstractDescendantOne::OfMixedAbstractDescendantOne(
  const OfMixedAbstractDescendantOne& other
) {
  instance_ = other.instance_;
  done_ = other.done_;
  index_ = other.index_;
  error_ = common::make_unique<Error>(*other.error_);
  state_ = other.state_;
}

OfMixedAbstractDescendantOne::OfMixedAbstractDescendantOne(
  OfMixedAbstractDescendantOne&& other
) {
  instance_ = std::move(other.instance_);
  done_ = other.done_;
  index_ = other.index_;
  error_ = std::move(other.error_);
  state_ = other.state_;
}

OfMixedAbstractDescendantOne& OfMixedAbstractDescendantOne::operator=(
  const OfMixedAbstractDescendantOne& other
) {
  return *this = OfMixedAbstractDescendantOne(other);
}

OfMixedAbstractDescendantOne& OfMixedAbstractDescendantOne::operator=(
  OfMixedAbstractDescendantOne&& other
) {
  if (this != &other) {
    instance_ = std::move(other.instance_);
    done_ = other.done_;
    index_ = other.index_;
    error_ = std::move(other.error_);
    state_ = other.state_;
  }
  return *this;
}

void OfMixedAbstractDescendantOne::Start() {
  state_ = 0;
  Execute();
}

void OfMixedAbstractDescendantOne::Next() {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to move a verificator OfMixedAbstractDescendantOne, "
      "but the verificator was done."
    );
  }
  #endif

  Execute();
}

bool OfMixedAbstractDescendantOne::Done() const {
  return done_;
}

const Error& OfMixedAbstractDescendantOne::Get() const {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to get from a verificator OfMixedAbstractDescendantOne, "
      "but the verificator was done."
    );
  }
  #endif

  return *error_;
}

Error& OfMixedAbstractDescendantOne::GetMutable() {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to get mutable from a verificator OfMixedAbstractDescendantOne, "
      "but the verificator was done."
    );
  }
  #endif

  return *error_;
}

long OfMixedAbstractDescendantOne::Index() const {
  #ifdef DEBUG
  if (Done() && index_ != -1) {
    throw std::logic_error(
      common::Concat(
        "Expected index to be -1 "
        "from a done verificator OfMixedAbstractDescendantOne, "
        "but got: ",
        std::to_string(index_)
      )
    );
  }
  #endif

  return index_;
}

std::unique_ptr<impl::IVerificator> OfMixedAbstractDescendantOne::Clone() const {
  return common::make_unique<
    OfMixedAbstractDescendantOne
  >(*this);
}

void OfMixedAbstractDescendantOne::Execute() {
  while (true) {
    switch (state_) {
      case 0: {
        done_ = false;
        error_ = nullptr;
        index_ = -1;

        if (
          instance_->unique_to_abstract_descendant_one().size() > 0
        ) {
          state_ = 1;
          continue;
        }

        error_ = common::make_unique<Error>(
          L"The value must not be empty."
        );
        // No path is prepended as the error refers to the instance itself.
        ++index_;

        state_ = 1;
        return;
      }

      case 1: {
        done_ = true;
        error_ = nullptr;
        index_ = -1;

        // We invalidate the state since we reached the end of the routine.
        state_ = 2;
        return;
      }

      default:
        throw std::logic_error(
          common::Concat(
            "Invalid state_: ",
            std::to_string(state_)
          )
        );
    }
  }
}

class OfMixedAbstractDescendantTwo : public impl::IVerificator {
 public:
  OfMixedAbstractDescendantTwo(
    const std::shared_ptr<types::IClass>& instance
  );

  OfMixedAbstractDescendantTwo(
    const OfMixedAbstractDescendantTwo& other
  );
  OfMixedAbstractDescendantTwo(
    OfMixedAbstractDescendantTwo&& other
  );
  OfMixedAbstractDescendantTwo& operator=(
    const OfMixedAbstractDescendantTwo& other
  );
  OfMixedAbstractDescendantTwo& operator=(
    OfMixedAbstractDescendantTwo&& other
  );

  void Start() override;
  void Next() override;
  bool Done() const override;
  const Error& Get() const override;
  Error& GetMutable() override;
  long Index() const override;

  std::unique_ptr<impl::IVerificator> Clone() const override;

  ~OfMixedAbstractDescendantTwo() override = default;

 private:
  std::shared_ptr<types::IMixedAbstractDescendantTwo> instance_;
  bool done_;
  long index_;
  std::unique_ptr<Error> error_;
  std::uint32_t state_;

  void Execute();
};  // class OfMixedAbstractDescendantTwo

OfMixedAbstractDescendantTwo::OfMixedAbstractDescendantTwo(
  const std::shared_ptr<types::IClass>& instance
) :
  // NOTE (mristin)
  // We cast here despite the cost of increasing the use count of the shared pointer.
  // Otherwise, if we didn't cast, we would not be able to have a uniform interface
  // for the verification functions based on the shared pointer.
  instance_(
    std::dynamic_pointer_cast<
      types::IMixedAbstractDescendantTwo
    >(
      instance
    )
  ) {
  // Intentionally empty.
}

OfMixedAbstractDescendantTwo::OfMixedAbstractDescendantTwo(
  const OfMixedAbstractDescendantTwo& other
) {
  instance_ = other.instance_;
  done_ = other.done_;
  index_ = other.index_;
  error_ = common::make_unique<Error>(*other.error_);
  state_ = other.state_;
}

OfMixedAbstractDescendantTwo::OfMixedAbstractDescendantTwo(
  OfMixedAbstractDescendantTwo&& other
) {
  instance_ = std::move(other.instance_);
  done_ = other.done_;
  index_ = other.index_;
  error_ = std::move(other.error_);
  state_ = other.state_;
}

OfMixedAbstractDescendantTwo& OfMixedAbstractDescendantTwo::operator=(
  const OfMixedAbstractDescendantTwo& other
) {
  return *this = OfMixedAbstractDescendantTwo(other);
}

OfMixedAbstractDescendantTwo& OfMixedAbstractDescendantTwo::operator=(
  OfMixedAbstractDescendantTwo&& other
) {
  if (this != &other) {
    instance_ = std::move(other.instance_);
    done_ = other.done_;
    index_ = other.index_;
    error_ = std::move(other.error_);
    state_ = other.state_;
  }
  return *this;
}

void OfMixedAbstractDescendantTwo::Start() {
  state_ = 0;
  Execute();
}

void OfMixedAbstractDescendantTwo::Next() {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to move a verificator OfMixedAbstractDescendantTwo, "
      "but the verificator was done."
    );
  }
  #endif

  Execute();
}

bool OfMixedAbstractDescendantTwo::Done() const {
  return done_;
}

const Error& OfMixedAbstractDescendantTwo::Get() const {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to get from a verificator OfMixedAbstractDescendantTwo, "
      "but the verificator was done."
    );
  }
  #endif

  return *error_;
}

Error& OfMixedAbstractDescendantTwo::GetMutable() {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to get mutable from a verificator OfMixedAbstractDescendantTwo, "
      "but the verificator was done."
    );
  }
  #endif

  return *error_;
}

long OfMixedAbstractDescendantTwo::Index() const {
  #ifdef DEBUG
  if (Done() && index_ != -1) {
    throw std::logic_error(
      common::Concat(
        "Expected index to be -1 "
        "from a done verificator OfMixedAbstractDescendantTwo, "
        "but got: ",
        std::to_string(index_)
      )
    );
  }
  #endif

  return index_;
}

std::unique_ptr<impl::IVerificator> OfMixedAbstractDescendantTwo::Clone() const {
  return common::make_unique<
    OfMixedAbstractDescendantTwo
  >(*this);
}

void OfMixedAbstractDescendantTwo::Execute() {
  while (true) {
    switch (state_) {
      case 0: {
        done_ = false;
        error_ = nullptr;
        index_ = -1;

        if (
          instance_->unique_to_abstract_descendant_two().size() > 0
        ) {
          state_ = 1;
          continue;
        }

        error_ = common::make_unique<Error>(
          L"The value must not be empty."
        );
        // No path is prepended as the error refers to the instance itself.
        ++index_;

        state_ = 1;
        return;
      }

      case 1: {
        done_ = true;
        error_ = nullptr;
        index_ = -1;

        // We invalidate the state since we reached the end of the routine.
        state_ = 2;
        return;
      }

      default:
        throw std::logic_error(
          common::Concat(
            "Invalid state_: ",
            std::to_string(state_)
          )
        );
    }
  }
}

class OfMixedConcreteWithDescendants : public impl::IVerificator {
 public:
  OfMixedConcreteWithDescendants(
    const std::shared_ptr<types::IClass>& instance
  );

  OfMixedConcreteWithDescendants(
    const OfMixedConcreteWithDescendants& other
  );
  OfMixedConcreteWithDescendants(
    OfMixedConcreteWithDescendants&& other
  );
  OfMixedConcreteWithDescendants& operator=(
    const OfMixedConcreteWithDescendants& other
  );
  OfMixedConcreteWithDescendants& operator=(
    OfMixedConcreteWithDescendants&& other
  );

  void Start() override;
  void Next() override;
  bool Done() const override;
  const Error& Get() const override;
  Error& GetMutable() override;
  long Index() const override;

  std::unique_ptr<impl::IVerificator> Clone() const override;

  ~OfMixedConcreteWithDescendants() override = default;

 private:
  std::shared_ptr<types::IMixedConcreteWithDescendants> instance_;
  bool done_;
  long index_;
  std::unique_ptr<Error> error_;
  std::uint32_t state_;

  void Execute();
};  // class OfMixedConcreteWithDescendants

OfMixedConcreteWithDescendants::OfMixedConcreteWithDescendants(
  const std::shared_ptr<types::IClass>& instance
) :
  // NOTE (mristin)
  // We cast here despite the cost of increasing the use count of the shared pointer.
  // Otherwise, if we didn't cast, we would not be able to have a uniform interface
  // for the verification functions based on the shared pointer.
  instance_(
    std::dynamic_pointer_cast<
      types::IMixedConcreteWithDescendants
    >(
      instance
    )
  ) {
  // Intentionally empty.
}

OfMixedConcreteWithDescendants::OfMixedConcreteWithDescendants(
  const OfMixedConcreteWithDescendants& other
) {
  instance_ = other.instance_;
  done_ = other.done_;
  index_ = other.index_;
  error_ = common::make_unique<Error>(*other.error_);
  state_ = other.state_;
}

OfMixedConcreteWithDescendants::OfMixedConcreteWithDescendants(
  OfMixedConcreteWithDescendants&& other
) {
  instance_ = std::move(other.instance_);
  done_ = other.done_;
  index_ = other.index_;
  error_ = std::move(other.error_);
  state_ = other.state_;
}

OfMixedConcreteWithDescendants& OfMixedConcreteWithDescendants::operator=(
  const OfMixedConcreteWithDescendants& other
) {
  return *this = OfMixedConcreteWithDescendants(other);
}

OfMixedConcreteWithDescendants& OfMixedConcreteWithDescendants::operator=(
  OfMixedConcreteWithDescendants&& other
) {
  if (this != &other) {
    instance_ = std::move(other.instance_);
    done_ = other.done_;
    index_ = other.index_;
    error_ = std::move(other.error_);
    state_ = other.state_;
  }
  return *this;
}

void OfMixedConcreteWithDescendants::Start() {
  state_ = 0;
  Execute();
}

void OfMixedConcreteWithDescendants::Next() {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to move a verificator OfMixedConcreteWithDescendants, "
      "but the verificator was done."
    );
  }
  #endif

  Execute();
}

bool OfMixedConcreteWithDescendants::Done() const {
  return done_;
}

const Error& OfMixedConcreteWithDescendants::Get() const {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to get from a verificator OfMixedConcreteWithDescendants, "
      "but the verificator was done."
    );
  }
  #endif

  return *error_;
}

Error& OfMixedConcreteWithDescendants::GetMutable() {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to get mutable from a verificator OfMixedConcreteWithDescendants, "
      "but the verificator was done."
    );
  }
  #endif

  return *error_;
}

long OfMixedConcreteWithDescendants::Index() const {
  #ifdef DEBUG
  if (Done() && index_ != -1) {
    throw std::logic_error(
      common::Concat(
        "Expected index to be -1 "
        "from a done verificator OfMixedConcreteWithDescendants, "
        "but got: ",
        std::to_string(index_)
      )
    );
  }
  #endif

  return index_;
}

std::unique_ptr<impl::IVerificator> OfMixedConcreteWithDescendants::Clone() const {
  return common::make_unique<
    OfMixedConcreteWithDescendants
  >(*this);
}

void OfMixedConcreteWithDescendants::Execute() {
  while (true) {
    switch (state_) {
      case 0: {
        done_ = false;
        error_ = nullptr;
        index_ = -1;

        if (instance_->some_base_property().size() > 0) {
          state_ = 1;
          continue;
        }

        error_ = common::make_unique<Error>(
          L"The value must not be empty."
        );
        // No path is prepended as the error refers to the instance itself.
        ++index_;

        state_ = 1;
        return;
      }

      case 1: {
        done_ = true;
        error_ = nullptr;
        index_ = -1;

        // We invalidate the state since we reached the end of the routine.
        state_ = 2;
        return;
      }

      default:
        throw std::logic_error(
          common::Concat(
            "Invalid state_: ",
            std::to_string(state_)
          )
        );
    }
  }
}

class OfMixedConcreteWithDescendantsChild : public impl::IVerificator {
 public:
  OfMixedConcreteWithDescendantsChild(
    const std::shared_ptr<types::IClass>& instance
  );

  OfMixedConcreteWithDescendantsChild(
    const OfMixedConcreteWithDescendantsChild& other
  );
  OfMixedConcreteWithDescendantsChild(
    OfMixedConcreteWithDescendantsChild&& other
  );
  OfMixedConcreteWithDescendantsChild& operator=(
    const OfMixedConcreteWithDescendantsChild& other
  );
  OfMixedConcreteWithDescendantsChild& operator=(
    OfMixedConcreteWithDescendantsChild&& other
  );

  void Start() override;
  void Next() override;
  bool Done() const override;
  const Error& Get() const override;
  Error& GetMutable() override;
  long Index() const override;

  std::unique_ptr<impl::IVerificator> Clone() const override;

  ~OfMixedConcreteWithDescendantsChild() override = default;

 private:
  std::shared_ptr<types::IMixedConcreteWithDescendantsChild> instance_;
  bool done_;
  long index_;
  std::unique_ptr<Error> error_;
  std::uint32_t state_;

  void Execute();
};  // class OfMixedConcreteWithDescendantsChild

OfMixedConcreteWithDescendantsChild::OfMixedConcreteWithDescendantsChild(
  const std::shared_ptr<types::IClass>& instance
) :
  // NOTE (mristin)
  // We cast here despite the cost of increasing the use count of the shared pointer.
  // Otherwise, if we didn't cast, we would not be able to have a uniform interface
  // for the verification functions based on the shared pointer.
  instance_(
    std::dynamic_pointer_cast<
      types::IMixedConcreteWithDescendantsChild
    >(
      instance
    )
  ) {
  // Intentionally empty.
}

OfMixedConcreteWithDescendantsChild::OfMixedConcreteWithDescendantsChild(
  const OfMixedConcreteWithDescendantsChild& other
) {
  instance_ = other.instance_;
  done_ = other.done_;
  index_ = other.index_;
  error_ = common::make_unique<Error>(*other.error_);
  state_ = other.state_;
}

OfMixedConcreteWithDescendantsChild::OfMixedConcreteWithDescendantsChild(
  OfMixedConcreteWithDescendantsChild&& other
) {
  instance_ = std::move(other.instance_);
  done_ = other.done_;
  index_ = other.index_;
  error_ = std::move(other.error_);
  state_ = other.state_;
}

OfMixedConcreteWithDescendantsChild& OfMixedConcreteWithDescendantsChild::operator=(
  const OfMixedConcreteWithDescendantsChild& other
) {
  return *this = OfMixedConcreteWithDescendantsChild(other);
}

OfMixedConcreteWithDescendantsChild& OfMixedConcreteWithDescendantsChild::operator=(
  OfMixedConcreteWithDescendantsChild&& other
) {
  if (this != &other) {
    instance_ = std::move(other.instance_);
    done_ = other.done_;
    index_ = other.index_;
    error_ = std::move(other.error_);
    state_ = other.state_;
  }
  return *this;
}

void OfMixedConcreteWithDescendantsChild::Start() {
  state_ = 0;
  Execute();
}

void OfMixedConcreteWithDescendantsChild::Next() {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to move a verificator OfMixedConcreteWithDescendantsChild, "
      "but the verificator was done."
    );
  }
  #endif

  Execute();
}

bool OfMixedConcreteWithDescendantsChild::Done() const {
  return done_;
}

const Error& OfMixedConcreteWithDescendantsChild::Get() const {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to get from a verificator OfMixedConcreteWithDescendantsChild, "
      "but the verificator was done."
    );
  }
  #endif

  return *error_;
}

Error& OfMixedConcreteWithDescendantsChild::GetMutable() {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to get mutable from a verificator OfMixedConcreteWithDescendantsChild, "
      "but the verificator was done."
    );
  }
  #endif

  return *error_;
}

long OfMixedConcreteWithDescendantsChild::Index() const {
  #ifdef DEBUG
  if (Done() && index_ != -1) {
    throw std::logic_error(
      common::Concat(
        "Expected index to be -1 "
        "from a done verificator OfMixedConcreteWithDescendantsChild, "
        "but got: ",
        std::to_string(index_)
      )
    );
  }
  #endif

  return index_;
}

std::unique_ptr<impl::IVerificator> OfMixedConcreteWithDescendantsChild::Clone() const {
  return common::make_unique<
    OfMixedConcreteWithDescendantsChild
  >(*this);
}

void OfMixedConcreteWithDescendantsChild::Execute() {
  while (true) {
    switch (state_) {
      case 0: {
        done_ = false;
        error_ = nullptr;
        index_ = -1;

        if (instance_->some_base_property().size() > 0) {
          state_ = 1;
          continue;
        }

        error_ = common::make_unique<Error>(
          L"The value must not be empty."
        );
        // No path is prepended as the error refers to the instance itself.
        ++index_;

        state_ = 1;
        return;
      }

      case 1: {
        if (instance_->some_child_property().size() > 0) {
          state_ = 2;
          continue;
        }

        error_ = common::make_unique<Error>(
          L"The child value must not be empty."
        );
        // No path is prepended as the error refers to the instance itself.
        ++index_;

        state_ = 2;
        return;
      }

      case 2: {
        done_ = true;
        error_ = nullptr;
        index_ = -1;

        // We invalidate the state since we reached the end of the routine.
        state_ = 3;
        return;
      }

      default:
        throw std::logic_error(
          common::Concat(
            "Invalid state_: ",
            std::to_string(state_)
          )
        );
    }
  }
}

class OfMixedConcreteLeaf : public impl::IVerificator {
 public:
  OfMixedConcreteLeaf(
    const std::shared_ptr<types::IClass>& instance
  );

  OfMixedConcreteLeaf(
    const OfMixedConcreteLeaf& other
  );
  OfMixedConcreteLeaf(
    OfMixedConcreteLeaf&& other
  );
  OfMixedConcreteLeaf& operator=(
    const OfMixedConcreteLeaf& other
  );
  OfMixedConcreteLeaf& operator=(
    OfMixedConcreteLeaf&& other
  );

  void Start() override;
  void Next() override;
  bool Done() const override;
  const Error& Get() const override;
  Error& GetMutable() override;
  long Index() const override;

  std::unique_ptr<impl::IVerificator> Clone() const override;

  ~OfMixedConcreteLeaf() override = default;

 private:
  std::shared_ptr<types::IMixedConcreteLeaf> instance_;
  bool done_;
  long index_;
  std::unique_ptr<Error> error_;
  std::uint32_t state_;

  void Execute();
};  // class OfMixedConcreteLeaf

OfMixedConcreteLeaf::OfMixedConcreteLeaf(
  const std::shared_ptr<types::IClass>& instance
) :
  // NOTE (mristin)
  // We cast here despite the cost of increasing the use count of the shared pointer.
  // Otherwise, if we didn't cast, we would not be able to have a uniform interface
  // for the verification functions based on the shared pointer.
  instance_(
    std::dynamic_pointer_cast<
      types::IMixedConcreteLeaf
    >(
      instance
    )
  ) {
  // Intentionally empty.
}

OfMixedConcreteLeaf::OfMixedConcreteLeaf(
  const OfMixedConcreteLeaf& other
) {
  instance_ = other.instance_;
  done_ = other.done_;
  index_ = other.index_;
  error_ = common::make_unique<Error>(*other.error_);
  state_ = other.state_;
}

OfMixedConcreteLeaf::OfMixedConcreteLeaf(
  OfMixedConcreteLeaf&& other
) {
  instance_ = std::move(other.instance_);
  done_ = other.done_;
  index_ = other.index_;
  error_ = std::move(other.error_);
  state_ = other.state_;
}

OfMixedConcreteLeaf& OfMixedConcreteLeaf::operator=(
  const OfMixedConcreteLeaf& other
) {
  return *this = OfMixedConcreteLeaf(other);
}

OfMixedConcreteLeaf& OfMixedConcreteLeaf::operator=(
  OfMixedConcreteLeaf&& other
) {
  if (this != &other) {
    instance_ = std::move(other.instance_);
    done_ = other.done_;
    index_ = other.index_;
    error_ = std::move(other.error_);
    state_ = other.state_;
  }
  return *this;
}

void OfMixedConcreteLeaf::Start() {
  state_ = 0;
  Execute();
}

void OfMixedConcreteLeaf::Next() {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to move a verificator OfMixedConcreteLeaf, "
      "but the verificator was done."
    );
  }
  #endif

  Execute();
}

bool OfMixedConcreteLeaf::Done() const {
  return done_;
}

const Error& OfMixedConcreteLeaf::Get() const {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to get from a verificator OfMixedConcreteLeaf, "
      "but the verificator was done."
    );
  }
  #endif

  return *error_;
}

Error& OfMixedConcreteLeaf::GetMutable() {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to get mutable from a verificator OfMixedConcreteLeaf, "
      "but the verificator was done."
    );
  }
  #endif

  return *error_;
}

long OfMixedConcreteLeaf::Index() const {
  #ifdef DEBUG
  if (Done() && index_ != -1) {
    throw std::logic_error(
      common::Concat(
        "Expected index to be -1 "
        "from a done verificator OfMixedConcreteLeaf, "
        "but got: ",
        std::to_string(index_)
      )
    );
  }
  #endif

  return index_;
}

std::unique_ptr<impl::IVerificator> OfMixedConcreteLeaf::Clone() const {
  return common::make_unique<
    OfMixedConcreteLeaf
  >(*this);
}

void OfMixedConcreteLeaf::Execute() {
  while (true) {
    switch (state_) {
      case 0: {
        done_ = false;
        error_ = nullptr;
        index_ = -1;

        if (instance_->unique_to_concrete_leaf().size() > 0) {
          state_ = 1;
          continue;
        }

        error_ = common::make_unique<Error>(
          L"The value must not be empty."
        );
        // No path is prepended as the error refers to the instance itself.
        ++index_;

        state_ = 1;
        return;
      }

      case 1: {
        done_ = true;
        error_ = nullptr;
        index_ = -1;

        // We invalidate the state since we reached the end of the routine.
        state_ = 2;
        return;
      }

      default:
        throw std::logic_error(
          common::Concat(
            "Invalid state_: ",
            std::to_string(state_)
          )
        );
    }
  }
}

class OfModelTypedFirst : public impl::IVerificator {
 public:
  OfModelTypedFirst(
    const std::shared_ptr<types::IClass>& instance
  );

  OfModelTypedFirst(
    const OfModelTypedFirst& other
  );
  OfModelTypedFirst(
    OfModelTypedFirst&& other
  );
  OfModelTypedFirst& operator=(
    const OfModelTypedFirst& other
  );
  OfModelTypedFirst& operator=(
    OfModelTypedFirst&& other
  );

  void Start() override;
  void Next() override;
  bool Done() const override;
  const Error& Get() const override;
  Error& GetMutable() override;
  long Index() const override;

  std::unique_ptr<impl::IVerificator> Clone() const override;

  ~OfModelTypedFirst() override = default;

 private:
  std::shared_ptr<types::IModelTypedFirst> instance_;
  bool done_;
  long index_;
  std::unique_ptr<Error> error_;
  std::uint32_t state_;

  void Execute();
};  // class OfModelTypedFirst

OfModelTypedFirst::OfModelTypedFirst(
  const std::shared_ptr<types::IClass>& instance
) :
  // NOTE (mristin)
  // We cast here despite the cost of increasing the use count of the shared pointer.
  // Otherwise, if we didn't cast, we would not be able to have a uniform interface
  // for the verification functions based on the shared pointer.
  instance_(
    std::dynamic_pointer_cast<
      types::IModelTypedFirst
    >(
      instance
    )
  ) {
  // Intentionally empty.
}

OfModelTypedFirst::OfModelTypedFirst(
  const OfModelTypedFirst& other
) {
  instance_ = other.instance_;
  done_ = other.done_;
  index_ = other.index_;
  error_ = common::make_unique<Error>(*other.error_);
  state_ = other.state_;
}

OfModelTypedFirst::OfModelTypedFirst(
  OfModelTypedFirst&& other
) {
  instance_ = std::move(other.instance_);
  done_ = other.done_;
  index_ = other.index_;
  error_ = std::move(other.error_);
  state_ = other.state_;
}

OfModelTypedFirst& OfModelTypedFirst::operator=(
  const OfModelTypedFirst& other
) {
  return *this = OfModelTypedFirst(other);
}

OfModelTypedFirst& OfModelTypedFirst::operator=(
  OfModelTypedFirst&& other
) {
  if (this != &other) {
    instance_ = std::move(other.instance_);
    done_ = other.done_;
    index_ = other.index_;
    error_ = std::move(other.error_);
    state_ = other.state_;
  }
  return *this;
}

void OfModelTypedFirst::Start() {
  state_ = 0;
  Execute();
}

void OfModelTypedFirst::Next() {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to move a verificator OfModelTypedFirst, "
      "but the verificator was done."
    );
  }
  #endif

  Execute();
}

bool OfModelTypedFirst::Done() const {
  return done_;
}

const Error& OfModelTypedFirst::Get() const {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to get from a verificator OfModelTypedFirst, "
      "but the verificator was done."
    );
  }
  #endif

  return *error_;
}

Error& OfModelTypedFirst::GetMutable() {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to get mutable from a verificator OfModelTypedFirst, "
      "but the verificator was done."
    );
  }
  #endif

  return *error_;
}

long OfModelTypedFirst::Index() const {
  #ifdef DEBUG
  if (Done() && index_ != -1) {
    throw std::logic_error(
      common::Concat(
        "Expected index to be -1 "
        "from a done verificator OfModelTypedFirst, "
        "but got: ",
        std::to_string(index_)
      )
    );
  }
  #endif

  return index_;
}

std::unique_ptr<impl::IVerificator> OfModelTypedFirst::Clone() const {
  return common::make_unique<
    OfModelTypedFirst
  >(*this);
}

void OfModelTypedFirst::Execute() {
  while (true) {
    switch (state_) {
      case 0: {
        done_ = false;
        error_ = nullptr;
        index_ = -1;

        if (instance_->some_property().size() > 0) {
          state_ = 1;
          continue;
        }

        error_ = common::make_unique<Error>(
          L"The value must not be empty."
        );
        // No path is prepended as the error refers to the instance itself.
        ++index_;

        state_ = 1;
        return;
      }

      case 1: {
        done_ = true;
        error_ = nullptr;
        index_ = -1;

        // We invalidate the state since we reached the end of the routine.
        state_ = 2;
        return;
      }

      default:
        throw std::logic_error(
          common::Concat(
            "Invalid state_: ",
            std::to_string(state_)
          )
        );
    }
  }
}

class OfModelTypedSecond : public impl::IVerificator {
 public:
  OfModelTypedSecond(
    const std::shared_ptr<types::IClass>& instance
  );

  OfModelTypedSecond(
    const OfModelTypedSecond& other
  );
  OfModelTypedSecond(
    OfModelTypedSecond&& other
  );
  OfModelTypedSecond& operator=(
    const OfModelTypedSecond& other
  );
  OfModelTypedSecond& operator=(
    OfModelTypedSecond&& other
  );

  void Start() override;
  void Next() override;
  bool Done() const override;
  const Error& Get() const override;
  Error& GetMutable() override;
  long Index() const override;

  std::unique_ptr<impl::IVerificator> Clone() const override;

  ~OfModelTypedSecond() override = default;

 private:
  std::shared_ptr<types::IModelTypedSecond> instance_;
  bool done_;
  long index_;
  std::unique_ptr<Error> error_;
  std::uint32_t state_;

  void Execute();
};  // class OfModelTypedSecond

OfModelTypedSecond::OfModelTypedSecond(
  const std::shared_ptr<types::IClass>& instance
) :
  // NOTE (mristin)
  // We cast here despite the cost of increasing the use count of the shared pointer.
  // Otherwise, if we didn't cast, we would not be able to have a uniform interface
  // for the verification functions based on the shared pointer.
  instance_(
    std::dynamic_pointer_cast<
      types::IModelTypedSecond
    >(
      instance
    )
  ) {
  // Intentionally empty.
}

OfModelTypedSecond::OfModelTypedSecond(
  const OfModelTypedSecond& other
) {
  instance_ = other.instance_;
  done_ = other.done_;
  index_ = other.index_;
  error_ = common::make_unique<Error>(*other.error_);
  state_ = other.state_;
}

OfModelTypedSecond::OfModelTypedSecond(
  OfModelTypedSecond&& other
) {
  instance_ = std::move(other.instance_);
  done_ = other.done_;
  index_ = other.index_;
  error_ = std::move(other.error_);
  state_ = other.state_;
}

OfModelTypedSecond& OfModelTypedSecond::operator=(
  const OfModelTypedSecond& other
) {
  return *this = OfModelTypedSecond(other);
}

OfModelTypedSecond& OfModelTypedSecond::operator=(
  OfModelTypedSecond&& other
) {
  if (this != &other) {
    instance_ = std::move(other.instance_);
    done_ = other.done_;
    index_ = other.index_;
    error_ = std::move(other.error_);
    state_ = other.state_;
  }
  return *this;
}

void OfModelTypedSecond::Start() {
  state_ = 0;
  Execute();
}

void OfModelTypedSecond::Next() {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to move a verificator OfModelTypedSecond, "
      "but the verificator was done."
    );
  }
  #endif

  Execute();
}

bool OfModelTypedSecond::Done() const {
  return done_;
}

const Error& OfModelTypedSecond::Get() const {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to get from a verificator OfModelTypedSecond, "
      "but the verificator was done."
    );
  }
  #endif

  return *error_;
}

Error& OfModelTypedSecond::GetMutable() {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to get mutable from a verificator OfModelTypedSecond, "
      "but the verificator was done."
    );
  }
  #endif

  return *error_;
}

long OfModelTypedSecond::Index() const {
  #ifdef DEBUG
  if (Done() && index_ != -1) {
    throw std::logic_error(
      common::Concat(
        "Expected index to be -1 "
        "from a done verificator OfModelTypedSecond, "
        "but got: ",
        std::to_string(index_)
      )
    );
  }
  #endif

  return index_;
}

std::unique_ptr<impl::IVerificator> OfModelTypedSecond::Clone() const {
  return common::make_unique<
    OfModelTypedSecond
  >(*this);
}

void OfModelTypedSecond::Execute() {
  while (true) {
    switch (state_) {
      case 0: {
        done_ = false;
        error_ = nullptr;
        index_ = -1;

        if (instance_->some_property().size() > 0) {
          state_ = 1;
          continue;
        }

        error_ = common::make_unique<Error>(
          L"The value must not be empty."
        );
        // No path is prepended as the error refers to the instance itself.
        ++index_;

        state_ = 1;
        return;
      }

      case 1: {
        done_ = true;
        error_ = nullptr;
        index_ = -1;

        // We invalidate the state since we reached the end of the routine.
        state_ = 2;
        return;
      }

      default:
        throw std::logic_error(
          common::Concat(
            "Invalid state_: ",
            std::to_string(state_)
          )
        );
    }
  }
}

class OfSomething : public impl::IVerificator {
 public:
  OfSomething(
    const std::shared_ptr<types::IClass>& instance
  );

  void Start() override;
  void Next() override;
  bool Done() const override;
  const Error& Get() const override;
  Error& GetMutable() override;
  long Index() const override;

  std::unique_ptr<impl::IVerificator> Clone() const override;

  ~OfSomething() override = default;
};  // class OfSomething

OfSomething::OfSomething(
  const std::shared_ptr<types::IClass>&
) {
  // Intentionally empty.
}

void OfSomething::Start() {
  // Intentionally empty.
}

void OfSomething::Next() {
  throw std::logic_error(
    "You want to move "
    "a verificator OfSomething, "
    "but the verificator is always done as "
    "ISomething "
    "has no invariants defined."
  );
}

bool OfSomething::Done() const {
  return true;
}

const Error& OfSomething::Get() const {
  throw std::logic_error(
    "You want to get from "
    "a verificator OfSomething, "
    "but the verificator is always done as "
    "ISomething "
    "has no invariants defined."
  );
}

Error& OfSomething::GetMutable() {
  throw std::logic_error(
    "You want to get mutable from "
    "a verificator OfSomething, "
    "but the verificator is always done as "
    "ISomething "
    "has no invariants defined."
  );
}

long OfSomething::Index() const {
  return -1;
}

std::unique_ptr<impl::IVerificator> OfSomething::Clone() const {
  return common::make_unique<
    OfSomething
  >(*this);
}

}  // namespace non_recursive_verificator

std::unique_ptr<impl::IVerificator> NewNonRecursiveVerificator(
  const std::shared_ptr<types::IClass>& instance
) {
  switch (instance->model_type()) {
    case types::ModelType::kStructuralFirst:
      return common::make_unique<
        non_recursive_verificator::OfStructuralFirst
      >(
        instance
      );
    case types::ModelType::kStructuralSecond:
      return common::make_unique<
        non_recursive_verificator::OfStructuralSecond
      >(
        instance
      );
    case types::ModelType::kMixedAbstractDescendantOne:
      return common::make_unique<
        non_recursive_verificator::OfMixedAbstractDescendantOne
      >(
        instance
      );
    case types::ModelType::kMixedAbstractDescendantTwo:
      return common::make_unique<
        non_recursive_verificator::OfMixedAbstractDescendantTwo
      >(
        instance
      );
    case types::ModelType::kMixedConcreteWithDescendants:
      return common::make_unique<
        non_recursive_verificator::OfMixedConcreteWithDescendants
      >(
        instance
      );
    case types::ModelType::kMixedConcreteWithDescendantsChild:
      return common::make_unique<
        non_recursive_verificator::OfMixedConcreteWithDescendantsChild
      >(
        instance
      );
    case types::ModelType::kMixedConcreteLeaf:
      return common::make_unique<
        non_recursive_verificator::OfMixedConcreteLeaf
      >(
        instance
      );
    case types::ModelType::kModelTypedFirst:
      return common::make_unique<
        non_recursive_verificator::OfModelTypedFirst
      >(
        instance
      );
    case types::ModelType::kModelTypedSecond:
      return common::make_unique<
        non_recursive_verificator::OfModelTypedSecond
      >(
        instance
      );
    case types::ModelType::kSomething:
      return common::make_unique<
        non_recursive_verificator::OfSomething
      >(
        instance
      );
    default:
      throw std::logic_error(
        common::Concat(
          "Unexpected model type: ",
          std::to_string(
            static_cast<std::uint32_t>(instance->model_type())
          )
        )
      );
  }
}

// endregion Non-recursive verificators

// region Recursive verificators

class RecursiveVerificator : public impl::IVerificator {
 public:
  RecursiveVerificator(
    const std::shared_ptr<types::IClass>& instance
  );

  RecursiveVerificator(const RecursiveVerificator& other);
  RecursiveVerificator(RecursiveVerificator&& other);
  RecursiveVerificator& operator=(const RecursiveVerificator& other);
  RecursiveVerificator& operator=(RecursiveVerificator&& other);

  void Start() override;
  void Next() override;
  bool Done() const override;
  const Error& Get() const override;
  Error& GetMutable() override;
  long Index() const override;

  std::unique_ptr<impl::IVerificator> Clone() const override;

  ~RecursiveVerificator() override = default;

 private:
  // NOTE(mristin):
  // We use a pointer to a shared pointer here so that we can implement
  // copy-assignment and move-assignment. Otherwise, if we used a constant
  // reference here, the assignments could not be implemented as C++ does not
  // allow re-binding of constant references.
  const std::shared_ptr<types::IClass>* instance_;

  std::uint32_t state_;
  std::unique_ptr<impl::IVerificator> verificator_;
  bool done_;
  long index_;
  std::unique_ptr<Error> error_;
  common::optional<iteration::Iterator> iterator_;
  common::optional<iteration::Iterator> iterator_end_;

  void Execute();
};  // class RecursiveVerificator

RecursiveVerificator::RecursiveVerificator(
  const std::shared_ptr<types::IClass>& instance
) : instance_(&instance) {
  // Intentionally empty.
}

RecursiveVerificator::RecursiveVerificator(const RecursiveVerificator& other) {
  instance_ = other.instance_;
  state_ = other.state_;
  verificator_ = other.verificator_->Clone();
  done_ = other.done_;
  index_ = other.index_;
  error_ = common::make_unique<Error>(*(other.error_));
  iterator_ = other.iterator_;
  iterator_end_ = other.iterator_end_;
}

RecursiveVerificator::RecursiveVerificator(RecursiveVerificator&& other) {
  instance_ = other.instance_;
  state_ = other.state_;
  verificator_ = std::move(other.verificator_);
  done_ = other.done_;
  index_ = other.index_;
  error_ = std::move(other.error_);
  iterator_ = std::move(other.iterator_);
  iterator_end_ = std::move(other.iterator_end_);
}

RecursiveVerificator& RecursiveVerificator::operator=(
  const RecursiveVerificator& other
) {
  return *this = RecursiveVerificator(other);
}

RecursiveVerificator& RecursiveVerificator::operator=(RecursiveVerificator&& other) {
  if (this != &other) {
    instance_ = other.instance_;
    state_ = other.state_;
    verificator_ = std::move(other.verificator_);
    done_ = other.done_;
    index_ = other.index_;
    error_ = std::move(other.error_);
    iterator_ = std::move(other.iterator_);
    iterator_end_ = std::move(other.iterator_end_);
  }

  return *this;
}

void RecursiveVerificator::Start() {
  state_ = 0;
  Execute();
}

void RecursiveVerificator::Next() {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to get from a RecursiveVerificator, "
      "but the verificator was done."
    );
  }
  #endif

  Execute();
}

bool RecursiveVerificator::Done() const {
  return done_;
}

const Error& RecursiveVerificator::Get() const {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to get from a RecursiveVerificator, "
      "but the verificator is done."
    );
  }
  #endif

  return *error_;
}

Error& RecursiveVerificator::GetMutable() {
  #ifdef DEBUG
  if (Done()) {
    throw std::logic_error(
      "You want to get mutable from a RecursiveVerificator, "
      "but the verificator is done."
    );
  }
  #endif

  return *error_;
}

long RecursiveVerificator::Index() const {
  #ifdef DEBUG
  if (Done() && index_ != -1) {
    throw std::logic_error(
      common::Concat(
        "Expected index to be -1 "
        "from a done RecursiveVerificator, "
        "but got: ",
        std::to_string(index_)
      )
    );
  }
  #endif

  return index_;
}

std::unique_ptr<impl::IVerificator> RecursiveVerificator::Clone() const {
  return common::make_unique<RecursiveVerificator>(*this);
}

void RecursiveVerificator::Execute() {
  while (true) {
    switch (state_) {
      case 0: {
        error_ = nullptr;
        index_ = -1;
        done_ = false;

        verificator_ = NewNonRecursiveVerificator(*instance_);
        verificator_->Start();
      }

      case 1: {
        if (!(!verificator_->Done())) {
          state_ = 3;
          continue;
        }

        // We intentionally take over the ownership of the errors' data members,
        // as we know the implementation in all the detail, and want to avoid a costly
        // copy.
        error_ = common::make_unique<Error>(
          std::move(
            verificator_->GetMutable()
          )
        );
        // No path is prepended as the error refers to the instance itself.
        ++index_;

        state_ = 2;
        return;
      }

      case 2: {
        verificator_->Next();

        state_ = 1;
        continue;
      }

      case 3: {
        verificator_ = nullptr;

        {
          // NOTE (mristin):
          // We will not need descent, so we introduce it in the scope.
          iteration::Descent descent(
            *instance_
          );
          iterator_ = std::move(descent.begin());

          // NOTE (mristin):
          // descent.end() is a constant reference, so we make an explicit
          // copy here.
          iterator_end_ = descent.end();
        }
      }

      case 4: {
        if (!(*iterator_ != *iterator_end_)) {
          state_ = 8;
          continue;
        }

        verificator_ = NewNonRecursiveVerificator(
          *(*iterator_)
        );
        verificator_->Start();
      }

      case 5: {
        if (!(!verificator_->Done())) {
          state_ = 7;
          continue;
        }

        // We intentionally take over the ownership of the errors' data members,
        // as we know the implementation in all the detail, and want to avoid a costly
        // copy.
        error_ = common::make_unique<Error>(
          std::move(
            verificator_->GetMutable()
          )
        );

        error_->path = std::move(
          iteration::MaterializePath(
            *iterator_
          )
        );

        ++index_;

        state_ = 6;
        return;
      }

      case 6: {
        verificator_->Next();

        state_ = 5;
        continue;
      }

      case 7: {
        verificator_ = nullptr;

        ++(*iterator_);

        state_ = 4;
        continue;
      }

      case 8: {
        iterator_.reset();
        iterator_end_.reset();
        done_ = true;
        index_ = -1;

        // We invalidate the state since we reached the end of the routine.
        state_ = 9;
        return;
      }

      default:
        throw std::logic_error(
          common::Concat(
            "Invalid state_: ",
            std::to_string(state_)
          )
        );
    }
  }
}

// endregion Recursive verificators

// region NonRecursiveVerification

NonRecursiveVerification::NonRecursiveVerification(
  const std::shared_ptr<types::IClass>& instance
) : instance_(instance) {
  // Intentionally empty.
}

Iterator NonRecursiveVerification::begin() const {
  std::unique_ptr<impl::IVerificator> verificator(
    NewNonRecursiveVerificator(instance_)
  );

  verificator->Start();

  // NOTE(mristin):
  // We short-circuit here for efficiency, as we can immediately dispose
  // of the verificator.
  if (verificator->Done()) {
    return Iterator(common::make_unique<AlwaysDoneVerificator>());
  }

  return Iterator(std::move(verificator));
}

const Iterator& NonRecursiveVerification::end() const {
  static Iterator iterator(common::make_unique<AlwaysDoneVerificator>());
  return iterator;
}

// endregion NonRecursiveVerification

// region RecursiveVerification

RecursiveVerification::RecursiveVerification(
  const std::shared_ptr<types::IClass>& instance
) : instance_(instance) {
  // Intentionally empty.
}

Iterator RecursiveVerification::begin() const {
  std::unique_ptr<impl::IVerificator> verificator(
    common::make_unique<RecursiveVerificator>(instance_)
  );

  verificator->Start();

  // NOTE(mristin):
  // We short-circuit here for efficiency, as we can immediately dispose
  // of the verificator.
  if (verificator->Done()) {
    return Iterator(common::make_unique<AlwaysDoneVerificator>());
  }

  return Iterator(std::move(verificator));
}

const Iterator& RecursiveVerification::end() const {
  static Iterator iterator(common::make_unique<AlwaysDoneVerificator>());
  return iterator;
}

// endregion RecursiveVerification

// region struct Iterator

Iterator::Iterator(
  const Iterator& other
) :
  verificator_(other.verificator_->Clone()) {
  // Intentionally empty.
}

Iterator::Iterator(
  Iterator&& other
) :
  verificator_(std::move(other.verificator_)) {
  // Intentionally empty.
}

Iterator& Iterator::operator=(const Iterator& other) {
  return *this = Iterator(other);
}

Iterator& Iterator::operator=(Iterator&& other) {
  if (this != &other) {
    verificator_ = std::move(other.verificator_);
  }

  return *this;
}

const Error& Iterator::operator*() const {
  if (verificator_->Done()) {
    throw std::logic_error(
      "You want to de-reference from a completed iterator "
      "over verification errors."
    );
  }

  return verificator_->Get();
}

const Error* Iterator::operator->() const {
  if (verificator_->Done()) {
    throw std::logic_error(
      "You want to de-reference from a completed iterator "
      "over verification errors."
    );
  }

  return &(verificator_->Get());
}

// Prefix increment
Iterator& Iterator::operator++() {
  if (verificator_->Done()) {
    throw std::logic_error(
      "You want to move a completed iterator "
      "over verification errors."
    );
  }

  verificator_->Next();
  return *this;
}

// Postfix increment
Iterator Iterator::operator++(int) {
  Iterator result(*this);
  ++(*this);
  return result;
}

bool operator==(const Iterator& a, const Iterator& b) {
  return a.verificator_->Index() == b.verificator_->Index();
}

bool operator!=(const Iterator& a, const Iterator& b) {
  return a.verificator_->Index() != b.verificator_->Index();
}

// endregion struct Iterator

}  // namespace verification
}  // namespace dummy

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
