/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package dummy.types.model;

import dummy.common.*;
import dummy.types.enums.*;
import dummy.types.impl.*;
import dummy.types.model.*;
import java.util.List;
import dummy.types.model.IContainer;
import java.util.Optional;

public interface IOrderedContainer extends IContainer {
  Boolean getIsSorted();

  void setIsSorted(Boolean isSorted);
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
