/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package dummy.xmlization;

import javax.xml.stream.events.XMLEvent;
import javax.xml.stream.XMLEventReader;
import javax.xml.stream.XMLStreamConstants;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamWriter;
import java.util.ArrayList;
import java.util.Base64;
import java.util.function.Function;
import java.util.List;
import java.util.Optional;
import dummy.common.*;
import dummy.reporting.Reporting;
import dummy.stringification.Stringification;
import dummy.types.enums.*;
import dummy.types.impl.*;
import dummy.types.model.*;
import dummy.visitation.*;

/**
 * Provide de/serialization of meta-model classes to/from XML.
 */
public class Xmlization {
  /**
   * Represent a critical error during the deserialization.
   */
  @SuppressWarnings("serial")
  public static class DeserializeException extends RuntimeException {
    private final String path;
    private final String reason;

    public DeserializeException(String path, String reason) {
      super(reason + " at: " + ("".equals(path) ? "the beginning" : path));
      this.path = path;
      this.reason = reason;
    }

    public Optional<String> getPath() {
      return Optional.ofNullable(path);
    }

    public Optional<String> getReason() {
      return Optional.ofNullable(reason);
    }
  }

  /**
   * Represent a critical error during the serialization.
   */
  @SuppressWarnings("serial")
  public static class SerializeException extends RuntimeException {
    private final String path;
    private final String reason;

    public SerializeException(String path, String reason) {
      super(reason + " at: " + ("".equals(path) ? "the beginning" : path));
      this.path = path;
      this.reason = reason;
    }

    public Optional<String> getPath() {
      return Optional.ofNullable(path);
    }

    public Optional<String> getReason() {
      return Optional.ofNullable(reason);
    }
  }

  /**
   * The XML namespace of the meta-model
   */
  public static final String AAS_NAME_SPACE =
    "https://dummy.com";

  /**
   * Implement the deserialization of meta-model classes from XML.
   *
   * <p>The implementation propagates an {@link Reporting.Error} instead of
   * relying on exceptions. Under the assumption that incorrect data is much less
   * frequent than correct data, this makes the deserialization more
   * efficient.
   *
   * <p>However, we do not want to force the client to deal with
   * the {@link Reporting.Error} class as this is not intuitive.
   * Therefore we distinguish the implementation, realized in
   * {@link _DeserializeImplementation}, and the facade given in
   * {@link Deserialize} class.
   */
  private static class _DeserializeImplementation
  {
    private static XMLEvent currentEvent(XMLEventReader reader) {
      try {
        return reader.peek();
      } catch (XMLStreamException xmlStreamException) {
        throw new Xmlization.DeserializeException("",
          "Failed in method peek because of: " +
          xmlStreamException.getMessage());
      }
    }

    private static String getEventTypeAsString(XMLEvent event) {
      switch (event.getEventType()) {
        case XMLStreamConstants.START_ELEMENT:
          return "Start-Element";
        case XMLStreamConstants.END_ELEMENT:
          return "End-Element";
        case XMLStreamConstants.PROCESSING_INSTRUCTION:
          return "Processing-Instruction";
        case XMLStreamConstants.CHARACTERS:
          return "Characters";
        case XMLStreamConstants.COMMENT:
          return "Comment";
        case XMLStreamConstants.SPACE:
          return "Space";
        case XMLStreamConstants.START_DOCUMENT:
          return "Start-Document";
        case XMLStreamConstants.END_DOCUMENT:
          return "End-Document";
        case XMLStreamConstants.ENTITY_REFERENCE:
          return "Entity-Reference";
        case XMLStreamConstants.ATTRIBUTE:
          return "Attribute";
        case XMLStreamConstants.NOTATION_DECLARATION:
          return "Notation-Declaration";
        default:
          return "Unknown-Type";
      }
    }

    private static boolean isEmptyElement(XMLEventReader reader) {
      // Skip the element node and go to the content
      try {
        reader.nextEvent();
      } catch (XMLStreamException xmlStreamException) {
        throw new Xmlization.DeserializeException("",
          "Failed in method isEmptyElement because of: " +
          xmlStreamException.getMessage());
      }
      return currentEvent(reader).isEndElement();
    }

    private static void skipWhitespaceAndComments(XMLEventReader reader) {
      while (whiteSpaceOrComment(reader)) {
        reader.next();
      }
    }

    private static boolean whiteSpaceOrComment(XMLEventReader reader) {
      final XMLEvent currentEvent = currentEvent(reader);
      final boolean isComment = (currentEvent != null &&
        currentEvent.getEventType() == XMLStreamConstants.COMMENT);
      final boolean isWhiteSpace = (currentEvent != null &&
        currentEvent.getEventType() == XMLStreamConstants.CHARACTERS &&
        currentEvent.asCharacters().isWhiteSpace());
      return isComment || isWhiteSpace;
    }

    private static void skipStartDocument(XMLEventReader reader){
      if (currentEvent(reader).isStartDocument()){
        reader.next();
      }
    }

    private static boolean invalidNameSpace(XMLEvent event) {
      if (event.isStartElement()) {
        return !AAS_NAME_SPACE.equals(event.asStartElement().getName().getNamespaceURI());
      } else {
        return !AAS_NAME_SPACE.equals(event.asEndElement().getName().getNamespaceURI());
      }
    }

    /**
     * Check the namespace and extract the element's name.
     */
    private static Reporting.Result<String> tryElementName(XMLEventReader reader) {
      final XMLEvent currentEvent = currentEvent(reader);
      final boolean precondition = currentEvent.isStartElement() || currentEvent.isEndElement();
      if (!precondition) {
        throw new IllegalStateException("Expected to be at a start or an end element "
            + "but got: " + getEventTypeAsString(currentEvent));
      }

      if (invalidNameSpace(currentEvent)) {
        String namespace = currentEvent.isStartElement()
            ? currentEvent.asStartElement().getName().getNamespaceURI()
            : currentEvent.asEndElement().getName().getNamespaceURI();
        final Reporting.Error error = new Reporting.Error(
            "Expected an element within a namespace " +
            AAS_NAME_SPACE + ", " + "but got: " + namespace);
        return Reporting.Result.failure(error);
      }
      return Reporting.Result.success(currentEvent.isStartElement()
          ? currentEvent.asStartElement().getName().getLocalPart()
          : currentEvent.asEndElement().getName().getLocalPart());
    }

    /**
     * Read the content of an element which has already been opened.
     *
     * <p>{@code isEmpty} tells whether that element was self-closing.
     */
    @FunctionalInterface
    private interface ContentReader<T> {
      Reporting.Result<? extends T> read(XMLEventReader reader, boolean isEmpty);
    }

    /**
     * Read a whole element, opening and closing it.
     */
    @FunctionalInterface
    private interface ElementReader<T> {
      Reporting.Result<? extends T> read(XMLEventReader reader);
    }

    /**
     * Convert the text content of an element which has already been opened.
     */
    @FunctionalInterface
    private interface ContentConverter<T> {
      T convert(XMLEventReader reader) throws XMLStreamException;
    }

    /**
     * Look up the name of the element which {@code reader} is positioned at.
     *
     * <p>This is the single primitive answering "we are at an element, and this is
     * its name": {@link #readNamedElement} checks that name against the one its
     * container supplied, a dispatcher switches on it, and a property loop uses it
     * to select the property. Nothing is consumed, which is what lets a dispatcher
     * hand the whole element on to the reader it selected.
     */
    private static Reporting.Result<String> peekElementName(XMLEventReader reader) {
      skipWhitespaceAndComments(reader);

      final XMLEvent currentEvent = currentEvent(reader);
      if (currentEvent.isEndDocument()) {
        return Reporting.Result.failure(new Reporting.Error(
          "Expected an XML element, but reached the end-of-file"));
      }

      if (!currentEvent.isStartElement()) {
        return Reporting.Result.failure(new Reporting.Error(
          "Expected an XML element, but got the node of type " +
          getEventTypeAsString(currentEvent) + " with the value " + currentEvent));
      }

      return tryElementName(reader);
    }

    /**
     * Consume the end tag concluding the element called {@code elementName}.
     */
    private static Reporting.Result<XMLEvent> consumeEndElement(
      XMLEventReader reader, String elementName) {
      skipWhitespaceAndComments(reader);

      final XMLEvent currentEvent = currentEvent(reader);
      if (currentEvent.isEndDocument()) {
        return Reporting.Result.failure(new Reporting.Error(
          "Expected an XML end element to conclude the element " + elementName +
          ", but got the end-of-file"));
      }

      if (!currentEvent.isEndElement()) {
        return Reporting.Result.failure(new Reporting.Error(
          "Expected an XML end element to conclude the element " + elementName +
          ", but got the node of type " + getEventTypeAsString(currentEvent) +
          " with the value " + currentEvent));
      }

      final Reporting.Result<String> tryEndElementName = tryElementName(reader);
      if (tryEndElementName.isError()) {
        return tryEndElementName.castTo(XMLEvent.class);
      }

      if (!elementName.equals(tryEndElementName.getResult())) {
        return Reporting.Result.failure(new Reporting.Error(
          "Expected an XML end element to conclude the element " + elementName +
          ", but got the end element with the name " + tryEndElementName.getResult()));
      }

      try {
        return Reporting.Result.success(reader.nextEvent());
      } catch (XMLStreamException xmlStreamException) {
        throw new Xmlization.DeserializeException("",
          "Failed in method consumeEndElement because of: " +
          xmlStreamException.getMessage());
      }
    }

    /**
     * Read a whole element which is expected to be called {@code name}, and read
     * its content with {@code readContent}.
     *
     * <p>The name is data, not a type: an instance reads the XML name of its own
     * class, a list item reads {@code "v"} and a tuple item reads {@code "v1"},
     * {@code "v2"}, ... by position. One framer therefore serves them all.
     */
    private static <T> Reporting.Result<? extends T> readNamedElement(
      XMLEventReader reader, String name, ContentReader<T> readContent) {
      final Reporting.Result<String> tryElementName = peekElementName(reader);
      if (tryElementName.isError()) {
        return Reporting.Result.failure(tryElementName.getError());
      }

      if (!name.equals(tryElementName.getResult())) {
        return Reporting.Result.failure(new Reporting.Error(
          "Expected an XML element " + name + ", but got an XML element " +
          tryElementName.getResult()));
      }

      final boolean isEmpty = isEmptyElement(reader);

      final Reporting.Result<? extends T> result = readContent.read(reader, isEmpty);
      if (result.isError()) {
        return result;
      }

      final Reporting.Result<XMLEvent> endResult = consumeEndElement(reader, name);
      if (endResult.isError()) {
        return Reporting.Result.failure(endResult.getError());
      }

      return result;
    }

    private static String readContentAsString(XMLEventReader reader) throws XMLStreamException {
      final StringBuilder content = new StringBuilder();

      while (reader.peek().isCharacters() || reader.peek().getEventType() == XMLStreamConstants.COMMENT) {
        if (reader.peek().isCharacters()) {
          content.append(reader.peek().asCharacters().getData());
        }
        reader.nextEvent();
      }

      return content.toString();
    }

    /**
     * Read the text content of an element and convert it with
     * {@code convert}.
     *
     * <p>A self-closing element is an error, since there is no text to convert.
     */
    private static <T> Reporting.Result<T> readText(
      XMLEventReader reader,
      boolean isEmpty,
      ContentConverter<T> convert,
      String typeName) {
      if (isEmpty) {
        return Reporting.Result.failure(new Reporting.Error(
          "Expected an XML content representing " + typeName +
          ", but encountered a self-closing element"));
      }

      if (currentEvent(reader).isEndDocument()) {
        return Reporting.Result.failure(new Reporting.Error(
          "Expected an XML content representing " + typeName +
          ", but reached the end-of-file"));
      }

      try {
        return Reporting.Result.success(convert.convert(reader));
      } catch (Exception exception) {
        return Reporting.Result.failure(new Reporting.Error(
          "The XML content could not be de-serialized as " + typeName + ": " +
          exception.getMessage()));
      }
    }

    /**
     * Read the text content of an element and convert it with
     * {@code convert}, giving {@code whenEmpty} for a self-closing element.
     */
    private static <T> Reporting.Result<T> readText(
      XMLEventReader reader,
      boolean isEmpty,
      ContentConverter<T> convert,
      String typeName,
      T whenEmpty) {
      if (isEmpty) {
        return Reporting.Result.success(whenEmpty);
      }

      return readText(reader, isEmpty, convert, typeName);
    }

    /**
     * Read the items of a list, each with {@code readItem}.
     *
     * <p>Every start element is considered to mark the start of an item. Reading
     * stops as soon as a non-start element is encountered.
     */
    private static <T> Reporting.Result<List<T>> readList(
      XMLEventReader reader, boolean isEmpty, ElementReader<T> readItem) {
      final List<T> result = new ArrayList<>();
      if (isEmpty) {
        return Reporting.Result.success(result);
      }

      skipWhitespaceAndComments(reader);
      int index = 0;
      if (!currentEvent(reader).isStartElement()) {
        final Reporting.Error error = new Reporting.Error(
          "Expected a start element opening an item of the list, " +
          "but got an XML " + getEventTypeAsString(currentEvent(reader)));
        error.prependSegment(new Reporting.IndexSegment(index));
        return Reporting.Result.failure(error);
      }

      while (currentEvent(reader).isStartElement()) {
        final Reporting.Result<? extends T> itemResult = readItem.read(reader);
        if (itemResult.isError()) {
          itemResult.getError()
            .prependSegment(
              new Reporting.IndexSegment(index));
          return Reporting.Result.failure(itemResult.getError());
        }

        result.add(itemResult.getResult());
        index++;
        skipWhitespaceAndComments(reader);
      }

      return Reporting.Result.success(result);
    }

    /**
     * Check whether the sequence of the properties has ended.
     *
     * <p>Only the end tag of the enclosing element concludes a sequence. Reaching
     * the end-of-file does not -- that is an error, which
     * {@link #peekElementName} reports when the caller goes on to read the next
     * property.
     */
    private static boolean atEndOfSequence(XMLEventReader reader) {
      skipWhitespaceAndComments(reader);
      return currentEvent(reader).isEndElement();
    }

    /**
     * Report an element which is not a property of the class {@code className}.
     */
    private static <T> Reporting.Result<T> unexpectedProperty(
      String className, String elementName) {
      return Reporting.Result.failure(new Reporting.Error(
        "We expected properties of the class " + className + ", " +
        "but got an unexpected element " +
        "with the name " + elementName));
    }

    /**
     * Report a required property of the class {@code className} which the
     * sequence of the properties did not give.
     */
    private static <T> Reporting.Result<T> missingRequiredProperty(
      String propertyName, String className) {
      return Reporting.Result.failure(new Reporting.Error(
        "The required property " + propertyName + " has not been given " +
        "in the XML representation of an instance of class " + className));
    }

    private static Reporting.Result<String> readTextAs_string(
      XMLEventReader reader, boolean isEmpty) {
      return readText(
        reader,
        isEmpty,
        _DeserializeImplementation::readContentAsString,
        "String",
        "");
    }

    private static Reporting.Result<List<String>> readListOf_string(
      XMLEventReader reader, boolean isEmpty) {
      return readList(
        reader, isEmpty, _DeserializeImplementation::readAtV_string);
    }

    private static Reporting.Result<? extends String> readAtV_string(
      XMLEventReader reader) {
      return readNamedElement(
        reader,
        "v",
        _DeserializeImplementation::readTextAs_string);
    }

    /**
     * Deserialize an instance of class Something from a sequence of XML elements.
     *
     * <p>If {@code isEmptySequence} is set, we should try to deserialize
     * the instance from an empty sequence. That is, the parent element
     * was a self-closing element.
     */
    private static Reporting.Result<Something> readSomethingFromSequence(
      XMLEventReader reader,
      boolean isEmptySequence) {
      List<String> theSomeNames = null;

      if (!isEmptySequence) {
        while (!atEndOfSequence(reader)) {
          final Reporting.Result<String> tryElementName = peekElementName(reader);
          if (tryElementName.isError()) {
            return Reporting.Result.failure(tryElementName.getError());
          }

          final String elementName = tryElementName.getResult();
          final boolean isEmptyProperty = isEmptyElement(reader);

          Reporting.Error valueError = null;

          switch (elementName) {
            case "someNames": {
              final Reporting.Result<List<String>> value =
                readListOf_string(reader, isEmptyProperty);
              if (value.isError()) {
                valueError = value.getError();
              } else {
                theSomeNames = value.getResult();
              }
              break;
            }
            default:
              return unexpectedProperty("Something", elementName);
          }

          if (valueError != null) {
            valueError.prependSegment(
              new Reporting.NameSegment(
                elementName));
            return Reporting.Result.failure(valueError);
          }

          final Reporting.Result<XMLEvent> endResult = consumeEndElement(reader, elementName);
          if (endResult.isError()) {
            return Reporting.Result.failure(endResult.getError());
          }
        }
      }

      if (theSomeNames == null) {
        return missingRequiredProperty("someNames", "Something");
      }

      return Reporting.Result.success(new Something(
        theSomeNames));
    }

    /**
     * Deserialize an instance of class Something from an XML element.
     */
    private static Reporting.Result<? extends Something> readSomethingFromElement(
      XMLEventReader reader) {
      return readNamedElement(
        reader,
        "something",
        _DeserializeImplementation::readSomethingFromSequence);
    }
  }

  /**
   * Deserialize instances of meta-model classes from XML.
   */
  /** <pre>
   * Here is an example how to parse an instance of class Something:
   * {@code
   * XMLEventReader reader = xmlFactory.createXMLEventReader(...some arguments...);
   * Something anInstance = Deserialize.deserializeSomething(
   *   reader);
   * }
   * </pre>
   *
   * <pre>
   * If the elements live in a namespace, you have to supply it. For example:
   * {@code
   * XMLEventReader reader = xmlFactory.createXMLEventReader(...some arguments...);
   * Something anInstance = Deserialize.deserializeSomething(
   *   reader,
   *   "http://www.example.com/5/12");
   * }
   * </pre>
   */
  public static class Deserialize
  {
    /**
     * Deserialize an instance of Something from {@code reader}.
     *
     * @param reader Initialized XML reader with reader.peek() set to the element
     */
    public static Something deserializeSomething(
      XMLEventReader reader) {

      _DeserializeImplementation.skipStartDocument(reader);
      _DeserializeImplementation.skipWhitespaceAndComments(reader);

      Reporting.Result<? extends Something> result =
        _DeserializeImplementation.readSomethingFromElement(
          reader);

      return result.onError(error -> {
        error.prependSegment(new Reporting.NameSegment("something"));
        throw new DeserializeException(
          Reporting.generateRelativeXPath(error.getPathSegments()),
          error.getCause());
      });
    }
  }

  /**
   * Serialize recursively the instances as XML elements.
   */
  static class _VisitorWithWriter
    extends AbstractVisitorWithContext<XMLStreamWriter> {

    private boolean topLevel = true;

    @FunctionalInterface
    private interface ElementContentSerializer<T> {
      void serialize(T that, XMLStreamWriter writer) throws XMLStreamException;
    }

    /**
     * Write {@code that} as an XML element named {@code name}, delegating
     * the content in-between the start and the end tag to
     * {@code serializeContent}.
     *
     * <p>This is shared by all the property kinds (primitive, enumeration,
     * class, interface, list) as they all wrap their content in exactly the
     * same way.
     */
    private <T> void serializeElement(
      String name,
      T that,
      XMLStreamWriter writer,
      ElementContentSerializer<T> serializeContent) {
      try {
        writer.writeStartElement(name);
        if (topLevel) {
          writer.writeNamespace("xmlns", AAS_NAME_SPACE);
          topLevel = false;
        }
        serializeContent.serialize(that, writer);
        writer.writeEndElement();
      } catch (XMLStreamException exception) {
        throw new SerializeException("", exception.getMessage());
      }
    }

    /**
     * Adapt {@code writeItem} to serialize every item of an iterable.
     *
     * <p>This is shared by all the list-typed properties, which only need to
     * supply how a single item is written.
     */
    private <T> ElementContentSerializer<Iterable<T>> serializeItems(
      ElementContentSerializer<T> writeItem) {
      return (items, w) -> {
        for (T item : items) {
          writeItem.serialize(item, w);
        }
      };
    }

    /**
     * Adapt {@code writeContent} to serialize a value wrapped in its own
     * {@code name} element.
     *
     * <p>This is only needed for a scalar item (a primitive or an enumeration
     * literal), which is wrapped in a positional {@code v}/{@code v1}/
     * {@code v2} *etc.* element; a class item is dispatched through its own
     * natural element tag by {@code this::visit} already, so it needs no
     * such wrapping.
     *
     * <p>{@code name} is a plain runtime string, not a type, so it can not be
     * pinned via a generic type parameter -- binding it requires an actual
     * closure, built once here.
     */
    private <T> ElementContentSerializer<T> asNamedElementSerializer(
      String name, ElementContentSerializer<T> writeContent) {
      return (that, w) -> serializeElement(name, that, w, writeContent);
    }

    /**
     * Write {@code that.toString()} as XML content.
     *
     * <p>This is shared by every {@code boolean}/{@code long}/{@code double}/
     * {@code String}-typed property or list item, standing in for the property-
     * or item-specific {@link ElementContentSerializer}.
     */
    private <T> void writeStringifiedContent(T that, XMLStreamWriter writer)
      throws XMLStreamException {
      writer.writeCharacters(that.toString());
    }

    /**
     * Write {@code that} as base64-encoded XML content.
     *
     * <p>This is shared by every {@code byte[]}-typed property or list item,
     * standing in for the property- or item-specific
     * {@link ElementContentSerializer}.
     */
    private void writeByteArrayContent(byte[] that, XMLStreamWriter writer)
      throws XMLStreamException {
      writer.writeCharacters(
        Base64.getEncoder().encodeToString(that));
    }

    private void somethingToSequence(
      ISomething that,
      XMLStreamWriter writer) {
      serializeElement(
        "someNames",
        that.getSomeNames(),
        writer,
        serializeItems(asNamedElementSerializer("v", this::writeStringifiedContent)));
    }

    @Override
    public void visitSomething(
      ISomething that,
      XMLStreamWriter writer) {
      try {
        writer.writeStartElement(
          "something");
        if (topLevel) {
          writer.writeNamespace("xmlns", AAS_NAME_SPACE);
          topLevel = false;
        }
        this.somethingToSequence(
          that,
          writer);
        writer.writeEndElement();
      } catch (XMLStreamException exception) {
        throw new SerializeException("", exception.getMessage());
      }
    }
  }

  /**
   * Serialize instances of meta-model classes to XML.
   */
  /**
   * <pre>
   * Here is an example how to serialize an instance of Something:
   * {@code
   * IClass anInstance = new Something(
   *     ... some constructor arguments ...
   * );
   * XMLStreamWriter writer = xmlWriterFactory.createXMLStreamWriter(...some arguments...);
   * Serialize.to(
   *   anInstance,
   *   writer);
   * }
   * </pre>
   */
  public static class Serialize
  {
    /**
     * Serialize an instance of the meta-model to XML.
     */
    public static void to(
      IClass that,
      XMLStreamWriter writer) throws SerializeException {
      _VisitorWithWriter visitor = new _VisitorWithWriter();
      visitor.visit(
        that, writer);
    }
  }
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
