/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package aas_core.aas3_0.types.enums;

/**
 * Enumeration for denoting whether an entity is a self-managed entity or a co-managed
 * entity.
 */
public enum EntityType implements IEnum {
  /**
   * For co-managed entities there is no separate AAS. Co-managed entities need to be
   * part of a self-managed entity.
   */
  CO_MANAGED_ENTITY("CoManagedEntity"),
  /**
   * Self-Managed Entities have their own AAS but can be part of the bill of material of
   * a composite self-managed entity.
   *
   * <p>The asset of an I4.0 Component is a self-managed entity per definition.
   */
  SELF_MANAGED_ENTITY("SelfManagedEntity");

  private final String literalText;

  EntityType(String literalText) {
    this.literalText = literalText;
  }

  @Override
  public String literalText() {
    return literalText;
  }
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
