/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package aas_core.aas3_0.types.enums;

/**
 * Represent a literal of an enumeration of the meta-model.
 */
public interface IEnum {
  /**
   * Get the string representation of this literal.
   *
   * <p>This is the text the literal is de/serialized as, which is in general
   * not its {@link Enum#name()}.
   */
  String literalText();
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
