/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package aas_core.aas3_0.types.enums;

/**
 * Reference types
 */
public enum ReferenceTypes implements IEnum {
  /**
   * External reference.
   */
  EXTERNAL_REFERENCE("ExternalReference"),
  /**
   * Model reference.
   */
  MODEL_REFERENCE("ModelReference");

  private final String literalText;

  ReferenceTypes(String literalText) {
    this.literalText = literalText;
  }

  @Override
  public String literalText() {
    return literalText;
  }
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
