/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package dummy.enhancing;

import java.lang.Iterable;
import java.util.Optional;
import java.util.List;
import dummy.common.*;
import dummy.visitation.IVisitor;
import dummy.visitation.IVisitorWithContext;
import dummy.visitation.ITransformer;
import dummy.visitation.ITransformerWithContext;
import dummy.types.enums.*;
import dummy.types.impl.*;
import dummy.types.model.*;

public class EnhancedMixedConcreteWithDescendants<EnhancementT>
  extends Enhanced<EnhancementT>
  implements IMixedConcreteWithDescendants {
  private final IMixedConcreteWithDescendants instance;

  public EnhancedMixedConcreteWithDescendants(
    IMixedConcreteWithDescendants instance,
    EnhancementT enhancement
  ) {
    super(enhancement);
    this.instance = instance;
  }

  @Override
  public String getSomeBaseProperty() {
    return instance.getSomeBaseProperty();
  }

  @Override
  public void setSomeBaseProperty(String someBaseProperty) {
    instance.setSomeBaseProperty(someBaseProperty);
  }

  public Iterable<IClass> descendOnce() {
    return instance.descendOnce();
  }

  public Iterable<IClass> descend() {
    return instance.descend();
  }

  public void accept(IVisitor visitor) {
    visitor.visitMixedConcreteWithDescendants(instance);
  }

  public <ContextT> void accept(
    IVisitorWithContext<ContextT> visitor,
    ContextT context
  ) {
    visitor.visitMixedConcreteWithDescendants(instance, context);
  }

  public <T> T transform(ITransformer<T> transformer) {
    return transformer.transformMixedConcreteWithDescendants(instance);
  }

  public <ContextT, T> T transform(
    ITransformerWithContext<ContextT, T> transformer,
    ContextT context
  ) {
    return transformer.transformMixedConcreteWithDescendants(instance, context);
  }
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
