package aastesting

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import (
	"fmt"
	"path"
	aasjsonization "github.com/dummy-works/dummy/jsonization"
	aastypes "github.com/dummy-works/dummy/types"
)

// Load a maximal example of [aastypes.ILangString] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMaximalLangString(
) (result aastypes.ILangString) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"LangString",
		"maximal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.LangStringFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of ILangString " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.ILangString)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of ILangString at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a minimal example of [aastypes.ILangString] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMinimalLangString(
) (result aastypes.ILangString) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"LangString",
		"minimal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.LangStringFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of ILangString " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.ILangString)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of ILangString at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a maximal example of [aastypes.ILangStringSet] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMaximalLangStringSet(
) (result aastypes.ILangStringSet) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"LangStringSet",
		"maximal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.LangStringSetFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of ILangStringSet " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.ILangStringSet)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of ILangStringSet at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a minimal example of [aastypes.ILangStringSet] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMinimalLangStringSet(
) (result aastypes.ILangStringSet) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"LangStringSet",
		"minimal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.LangStringSetFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of ILangStringSet " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.ILangStringSet)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of ILangStringSet at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a maximal example of [aastypes.IIecContent] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMaximalIecContent(
) (result aastypes.IIecContent) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"IecContent",
		"maximal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.IecContentFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IIecContent " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IIecContent)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IIecContent at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a minimal example of [aastypes.IIecContent] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMinimalIecContent(
) (result aastypes.IIecContent) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"IecContent",
		"minimal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.IecContentFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IIecContent " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IIecContent)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IIecContent at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a maximal example of [aastypes.IOtherContent] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMaximalOtherContent(
) (result aastypes.IOtherContent) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"OtherContent",
		"maximal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.OtherContentFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IOtherContent " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IOtherContent)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IOtherContent at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a minimal example of [aastypes.IOtherContent] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMinimalOtherContent(
) (result aastypes.IOtherContent) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"OtherContent",
		"minimal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.OtherContentFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IOtherContent " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IOtherContent)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IOtherContent at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a maximal example of [aastypes.ISpecification] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMaximalSpecification(
) (result aastypes.ISpecification) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"Specification",
		"maximal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.SpecificationFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of ISpecification " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.ISpecification)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of ISpecification at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a minimal example of [aastypes.ISpecification] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMinimalSpecification(
) (result aastypes.ISpecification) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"Specification",
		"minimal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.SpecificationFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of ISpecification " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.ISpecification)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of ISpecification at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a maximal example of [aastypes.ISomething] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMaximalSomething(
) (result aastypes.ISomething) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"Something",
		"maximal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.SomethingFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of ISomething " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.ISomething)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of ISomething at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a minimal example of [aastypes.ISomething] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMinimalSomething(
) (result aastypes.ISomething) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"Something",
		"minimal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.SomethingFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of ISomething " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.ISomething)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of ISomething at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
