// Package common provides common functions shared among the other packages.
package common

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import (
	"strings"
)

func Concat(
	parts ...string,
) string {
	b := new(strings.Builder)
	for _, part := range parts {
		b.WriteString(part)
	}
	return b.String()
}

// Check if the map contains the given key.
func MapContains[K comparable, V any](m map[K]V, k K) bool {
	_, ok := m[k]
	return ok
}

// Check if any of the elements satisfy the condition.
func Some[V any](condition func(V) bool, l []V) bool {
	ok := false
	for _, v := range l {
		ok = ok || condition(v)
	}
	return ok
}

// Check if all the elements satisfy the condition.
func All[V any](condition func(V) bool, l []V) bool {
	for _, v := range l {
		if !condition(v) {
			return false
		}
	}
	return true
}

// Check if some of the elements in the given range satisfy the condition.
func SomeRange(condition func(int) bool, start int, end int) bool {
	for i := start; i < end; i++ {
		if condition(i) {
			return true
		}
	}
	return false
}

// Check if all the elements in the given range satisfy the condition.
func AllRange(condition func(int) bool, start int, end int) bool {
	for i := start; i < end; i++ {
		if !condition(i) {
			return false
		}
	}
	return true
}

// Create a new instance of the `value` and return the pointer to it.
func NewBool(value bool) *bool {
	return &value
}

// Create a new instance of the `value` and return the pointer to it.
func NewInt(value int) *int {
	return &value
}

// Create a new instance of the `value` and return the pointer to it.
func NewInt64(value int64) *int64 {
	return &value
}

// Create a new instance of the `value` and return the pointer to it.
func NewFloat64(value float64) *float64 {
	return &value
}

// Create a new instance of the `value` and return the pointer to it.
func NewString(value string) *string {
	return &value
}

// Represent a fixed-size heterogeneous tuple of 1 item(s).
type Tuple1[T1 any] struct {
	Item1 T1
}

// Represent a fixed-size heterogeneous tuple of 2 item(s).
type Tuple2[T1 any, T2 any] struct {
	Item1 T1
	Item2 T2
}

// Represent a fixed-size heterogeneous tuple of 3 item(s).
type Tuple3[T1 any, T2 any, T3 any] struct {
	Item1 T1
	Item2 T2
	Item3 T3
}

// Represent a fixed-size heterogeneous tuple of 4 item(s).
type Tuple4[T1 any, T2 any, T3 any, T4 any] struct {
	Item1 T1
	Item2 T2
	Item3 T3
	Item4 T4
}

// Represent a fixed-size heterogeneous tuple of 5 item(s).
type Tuple5[T1 any, T2 any, T3 any, T4 any, T5 any] struct {
	Item1 T1
	Item2 T2
	Item3 T3
	Item4 T4
	Item5 T5
}

// Represent a fixed-size heterogeneous tuple of 6 item(s).
type Tuple6[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any] struct {
	Item1 T1
	Item2 T2
	Item3 T3
	Item4 T4
	Item5 T5
	Item6 T6
}

// Represent a fixed-size heterogeneous tuple of 7 item(s).
type Tuple7[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any] struct {
	Item1 T1
	Item2 T2
	Item3 T3
	Item4 T4
	Item5 T5
	Item6 T6
	Item7 T7
}

// Represent a fixed-size heterogeneous tuple of 8 item(s).
type Tuple8[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any] struct {
	Item1 T1
	Item2 T2
	Item3 T3
	Item4 T4
	Item5 T5
	Item6 T6
	Item7 T7
	Item8 T8
}

// Resolve `position` in a string of `length` as Python does in slicing.
//
// A negative position counts from the end, and the positions out of range are
// clamped to the string.
func resolvePosition(position int64, length int) int {
	if position < 0 {
		position += int64(length)
		if position < 0 {
			return 0
		}
		return int(position)
	}

	if position > int64(length) {
		return length
	}
	return int(position)
}

// Slice `text` from `start` up to `end`, exclusive.
//
// We follow the Python implementation of slicing, since Python is
// the language of the meta-model specifications. Hence, a negative position
// counts from the end, the positions out of range are clamped to the string,
// and the slice is empty if `start` is not before `end`.
func SliceStr(text string, start int64, end int64) string {
	theStart := resolvePosition(start, len(text))
	theEnd := resolvePosition(end, len(text))

	if theStart >= theEnd {
		return ""
	}

	return text[theStart:theEnd]
}

// Slice `text` from `start` up to its end.
//
// See [SliceStr] for the semantics.
func SliceStrFrom(text string, start int64) string {
	return text[resolvePosition(start, len(text)):]
}

// Find the first `sub` in `text` from `start` on.
//
// Return the position of `sub` in `text`, or -1 if `sub` could not be found.
//
// We follow the Python implementation of `str.find`, since Python is
// the language of the meta-model specifications. Hence, a negative `start`
// counts from the end, and a `start` beyond the end of `text` gives -1.
func FindStr(text string, sub string, start int64) int64 {
	if start < 0 {
		start += int64(len(text))
		if start < 0 {
			start = 0
		}
	}

	if start > int64(len(text)) {
		return -1
	}

	index := strings.Index(text[start:], sub)
	if index == -1 {
		return -1
	}

	return start + int64(index)
}

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
