/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package dummy.types.model;

import dummy.common.*;
import dummy.types.enums.*;
import dummy.types.impl.*;
import dummy.types.model.*;
import java.util.List;
import dummy.types.model.IClass;
import java.util.Optional;

public interface ISomething extends IClass {
  String getDefaultLanguage();

  void setDefaultLanguage(String defaultLanguage);

  List<ILangStringSet> getLangStringSets();

  void setLangStringSets(List<ILangStringSet> langStringSets);

  Optional<List<ISpecification>> getSpecifications();

  void setSpecifications(List<ISpecification> specifications);

  /**
   * Iterate over specifications, if set, and otherwise return an empty enumerable.
   */
  Iterable<ISpecification> overSpecificationsOrEmpty();
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
