/**
 * Execute all common XMLization loader helpers once.
 */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import * as TestCommonXmlization from "./commonXmlization";

test("commonXmlization loaders for Leaf", () => {
  expect(TestCommonXmlization.loadMinimalLeaf()).not.toBeNull();
  expect(TestCommonXmlization.loadMaximalLeaf()).not.toBeNull();
});

test("commonXmlization loaders for OrderedContainer", () => {
  expect(TestCommonXmlization.loadMinimalOrderedContainer()).not.toBeNull();
  expect(TestCommonXmlization.loadMaximalOrderedContainer()).not.toBeNull();
});

test("commonXmlization loaders for UnorderedContainer", () => {
  expect(TestCommonXmlization.loadMinimalUnorderedContainer()).not.toBeNull();
  expect(TestCommonXmlization.loadMaximalUnorderedContainer()).not.toBeNull();
});

test("commonXmlization loaders for GlobalAttribute", () => {
  expect(TestCommonXmlization.loadMinimalGlobalAttribute()).not.toBeNull();
  expect(TestCommonXmlization.loadMaximalGlobalAttribute()).not.toBeNull();
});

test("commonXmlization loaders for LocalAttribute", () => {
  expect(TestCommonXmlization.loadMinimalLocalAttribute()).not.toBeNull();
  expect(TestCommonXmlization.loadMaximalLocalAttribute()).not.toBeNull();
});

test("commonXmlization loaders for AttributeOperand", () => {
  expect(TestCommonXmlization.loadMinimalAttributeOperand()).not.toBeNull();
  expect(TestCommonXmlization.loadMaximalAttributeOperand()).not.toBeNull();
});

test("commonXmlization loaders for StringLiteral", () => {
  expect(TestCommonXmlization.loadMinimalStringLiteral()).not.toBeNull();
  expect(TestCommonXmlization.loadMaximalStringLiteral()).not.toBeNull();
});

test("commonXmlization loaders for NumberLiteral", () => {
  expect(TestCommonXmlization.loadMinimalNumberLiteral()).not.toBeNull();
  expect(TestCommonXmlization.loadMaximalNumberLiteral()).not.toBeNull();
});

test("commonXmlization loaders for Something", () => {
  expect(TestCommonXmlization.loadMinimalSomething()).not.toBeNull();
  expect(TestCommonXmlization.loadMaximalSomething()).not.toBeNull();
});

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
