// Package enhancing allows for enhancement of model instances with your custom data.
package enhancing

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import (
	"fmt"
	aastypes "github.com/dummy-works/dummy/types"
)

type enhanced[E any] interface {
	// Get the enhancement from the enhanced instance.
	getEnhancement() E

	// Set the enhancement of the enhanced instance.
	setEnhancement(E)
}

type enhancedLangString[E any] struct {
	instance aastypes.ILangString
	enhancement E
}

func (els *enhancedLangString[E]) ModelType(
) aastypes.ModelType {
	return els.instance.ModelType()
}

func (els *enhancedLangString[E]) DescendOnce(
	action func(aastypes.IClass)bool,
) bool {
	return els.instance.DescendOnce(action)
}

func (els *enhancedLangString[E]) Descend(
	action func(aastypes.IClass) bool,
) bool {
	return els.instance.Descend(action)
}

func (els *enhancedLangString[E]) Language(
) string {
	return els.instance.Language()
}

func (els *enhancedLangString[E]) SetLanguage(
	value string,
) {
	els.instance.SetLanguage(value)
}

func (els *enhancedLangString[E]) Text(
) string {
	return els.instance.Text()
}

func (els *enhancedLangString[E]) SetText(
	value string,
) {
	els.instance.SetText(value)
}

func (els *enhancedLangString[E]) getEnhancement(
) E {
	return els.enhancement
}

func (els *enhancedLangString[E]) setEnhancement(
	value E,
) {
	els.enhancement = value
}

func wrapLangString[E any](
	that aastypes.ILangString,
	factory func(aastypes.IClass) (E, bool),
) (result aastypes.ILangString) {
	// We assume that we already checked whether `that` has been enhanced
	// in the caller.

	enh, shouldEnhance := factory(that)
	if shouldEnhance {
		result = &enhancedLangString[E]{
			instance: that,
			enhancement: enh,
		}
	} else {
		result = that
	}

	return
}

type enhancedLangStringSet[E any] struct {
	instance aastypes.ILangStringSet
	enhancement E
}

func (elss *enhancedLangStringSet[E]) ModelType(
) aastypes.ModelType {
	return elss.instance.ModelType()
}

func (elss *enhancedLangStringSet[E]) DescendOnce(
	action func(aastypes.IClass)bool,
) bool {
	return elss.instance.DescendOnce(action)
}

func (elss *enhancedLangStringSet[E]) Descend(
	action func(aastypes.IClass) bool,
) bool {
	return elss.instance.Descend(action)
}

func (elss *enhancedLangStringSet[E]) LangStrings(
) []aastypes.ILangString {
	return elss.instance.LangStrings()
}

func (elss *enhancedLangStringSet[E]) SetLangStrings(
	value []aastypes.ILangString,
) {
	elss.instance.SetLangStrings(value)
}

func (elss *enhancedLangStringSet[E]) getEnhancement(
) E {
	return elss.enhancement
}

func (elss *enhancedLangStringSet[E]) setEnhancement(
	value E,
) {
	elss.enhancement = value
}

func wrapLangStringSet[E any](
	that aastypes.ILangStringSet,
	factory func(aastypes.IClass) (E, bool),
) (result aastypes.ILangStringSet) {
	// We assume that we already checked whether `that` has been enhanced
	// in the caller.

	enh, shouldEnhance := factory(that)
	if shouldEnhance {
		result = &enhancedLangStringSet[E]{
			instance: that,
			enhancement: enh,
		}
	} else {
		result = that
	}

	theLangStrings := that.LangStrings()
	for i, v := range theLangStrings {
		// Update in-situ
		theLangStrings[i] = Wrap[E](
			v,
			factory,
		).(aastypes.ILangString)
	}

	return
}

type enhancedIecContent[E any] struct {
	instance aastypes.IIecContent
	enhancement E
}

func (eic *enhancedIecContent[E]) ModelType(
) aastypes.ModelType {
	return eic.instance.ModelType()
}

func (eic *enhancedIecContent[E]) DescendOnce(
	action func(aastypes.IClass)bool,
) bool {
	return eic.instance.DescendOnce(action)
}

func (eic *enhancedIecContent[E]) Descend(
	action func(aastypes.IClass) bool,
) bool {
	return eic.instance.Descend(action)
}

func (eic *enhancedIecContent[E]) Definition(
) []aastypes.ILangString {
	return eic.instance.Definition()
}

func (eic *enhancedIecContent[E]) SetDefinition(
	value []aastypes.ILangString,
) {
	eic.instance.SetDefinition(value)
}

func (eic *enhancedIecContent[E]) getEnhancement(
) E {
	return eic.enhancement
}

func (eic *enhancedIecContent[E]) setEnhancement(
	value E,
) {
	eic.enhancement = value
}

func wrapIecContent[E any](
	that aastypes.IIecContent,
	factory func(aastypes.IClass) (E, bool),
) (result aastypes.IIecContent) {
	// We assume that we already checked whether `that` has been enhanced
	// in the caller.

	enh, shouldEnhance := factory(that)
	if shouldEnhance {
		result = &enhancedIecContent[E]{
			instance: that,
			enhancement: enh,
		}
	} else {
		result = that
	}

	theDefinition := that.Definition()
	if theDefinition != nil {
		for i, v := range theDefinition {
			// Update in-situ
			theDefinition[i] = Wrap[E](
				v,
				factory,
			).(aastypes.ILangString)
		}
	}

	return
}

type enhancedOtherContent[E any] struct {
	instance aastypes.IOtherContent
	enhancement E
}

func (eoc *enhancedOtherContent[E]) ModelType(
) aastypes.ModelType {
	return eoc.instance.ModelType()
}

func (eoc *enhancedOtherContent[E]) DescendOnce(
	action func(aastypes.IClass)bool,
) bool {
	return eoc.instance.DescendOnce(action)
}

func (eoc *enhancedOtherContent[E]) Descend(
	action func(aastypes.IClass) bool,
) bool {
	return eoc.instance.Descend(action)
}

func (eoc *enhancedOtherContent[E]) getEnhancement(
) E {
	return eoc.enhancement
}

func (eoc *enhancedOtherContent[E]) setEnhancement(
	value E,
) {
	eoc.enhancement = value
}

func wrapOtherContent[E any](
	that aastypes.IOtherContent,
	factory func(aastypes.IClass) (E, bool),
) (result aastypes.IOtherContent) {
	// We assume that we already checked whether `that` has been enhanced
	// in the caller.

	enh, shouldEnhance := factory(that)
	if shouldEnhance {
		result = &enhancedOtherContent[E]{
			instance: that,
			enhancement: enh,
		}
	} else {
		result = that
	}

	return
}

type enhancedSpecification[E any] struct {
	instance aastypes.ISpecification
	enhancement E
}

func (es *enhancedSpecification[E]) ModelType(
) aastypes.ModelType {
	return es.instance.ModelType()
}

func (es *enhancedSpecification[E]) DescendOnce(
	action func(aastypes.IClass)bool,
) bool {
	return es.instance.DescendOnce(action)
}

func (es *enhancedSpecification[E]) Descend(
	action func(aastypes.IClass) bool,
) bool {
	return es.instance.Descend(action)
}

func (es *enhancedSpecification[E]) Content(
) aastypes.IContent {
	return es.instance.Content()
}

func (es *enhancedSpecification[E]) SetContent(
	value aastypes.IContent,
) {
	es.instance.SetContent(value)
}

func (es *enhancedSpecification[E]) getEnhancement(
) E {
	return es.enhancement
}

func (es *enhancedSpecification[E]) setEnhancement(
	value E,
) {
	es.enhancement = value
}

func wrapSpecification[E any](
	that aastypes.ISpecification,
	factory func(aastypes.IClass) (E, bool),
) (result aastypes.ISpecification) {
	// We assume that we already checked whether `that` has been enhanced
	// in the caller.

	enh, shouldEnhance := factory(that)
	if shouldEnhance {
		result = &enhancedSpecification[E]{
			instance: that,
			enhancement: enh,
		}
	} else {
		result = that
	}

	theContent := that.Content()
	that.SetContent(
		Wrap[E](
			theContent,
			factory,
		).(aastypes.IContent),
	)

	return
}

type enhancedSomething[E any] struct {
	instance aastypes.ISomething
	enhancement E
}

func (es *enhancedSomething[E]) ModelType(
) aastypes.ModelType {
	return es.instance.ModelType()
}

func (es *enhancedSomething[E]) DescendOnce(
	action func(aastypes.IClass)bool,
) bool {
	return es.instance.DescendOnce(action)
}

func (es *enhancedSomething[E]) Descend(
	action func(aastypes.IClass) bool,
) bool {
	return es.instance.Descend(action)
}

func (es *enhancedSomething[E]) DefaultLanguage(
) string {
	return es.instance.DefaultLanguage()
}

func (es *enhancedSomething[E]) SetDefaultLanguage(
	value string,
) {
	es.instance.SetDefaultLanguage(value)
}

func (es *enhancedSomething[E]) LangStringSets(
) []aastypes.ILangStringSet {
	return es.instance.LangStringSets()
}

func (es *enhancedSomething[E]) SetLangStringSets(
	value []aastypes.ILangStringSet,
) {
	es.instance.SetLangStringSets(value)
}

func (es *enhancedSomething[E]) Specifications(
) []aastypes.ISpecification {
	return es.instance.Specifications()
}

func (es *enhancedSomething[E]) SetSpecifications(
	value []aastypes.ISpecification,
) {
	es.instance.SetSpecifications(value)
}

func (es *enhancedSomething[E]) getEnhancement(
) E {
	return es.enhancement
}

func (es *enhancedSomething[E]) setEnhancement(
	value E,
) {
	es.enhancement = value
}

func wrapSomething[E any](
	that aastypes.ISomething,
	factory func(aastypes.IClass) (E, bool),
) (result aastypes.ISomething) {
	// We assume that we already checked whether `that` has been enhanced
	// in the caller.

	enh, shouldEnhance := factory(that)
	if shouldEnhance {
		result = &enhancedSomething[E]{
			instance: that,
			enhancement: enh,
		}
	} else {
		result = that
	}

	theLangStringSets := that.LangStringSets()
	for i, v := range theLangStringSets {
		// Update in-situ
		theLangStringSets[i] = Wrap[E](
			v,
			factory,
		).(aastypes.ILangStringSet)
	}

	theSpecifications := that.Specifications()
	if theSpecifications != nil {
		for i, v := range theSpecifications {
			// Update in-situ
			theSpecifications[i] = Wrap[E](
				v,
				factory,
			).(aastypes.ISpecification)
		}
	}

	return
}

// Wrap `that` instance recursively with the enhancement produced by the `factory`.
//
// The factory returns the enhancement, and a boolean "should-enhance". If
// the "should-enhance" is false, `that` instance is not enhance, and we simply
// return it. However, we will still continue to enhance the instances referenced
// by `that` instance recursively.
//
// If `that` instance has been already wrapped, panic.
func Wrap[E any](
	that aastypes.IClass,
	factory func(aastypes.IClass) (E, bool),
) (result aastypes.IClass) {
	_, ok := that.(enhanced[E])
	if ok {
		panic(
			fmt.Sprintf(
				"An instance of %T has been already wrapped: %v",
				that, that,
			),
		)
	}

	switch that.ModelType() {
	case aastypes.ModelTypeLangString:
		result = wrapLangString[E](
			that.(aastypes.ILangString),
			factory,
		)
	case aastypes.ModelTypeLangStringSet:
		result = wrapLangStringSet[E](
			that.(aastypes.ILangStringSet),
			factory,
		)
	case aastypes.ModelTypeIecContent:
		result = wrapIecContent[E](
			that.(aastypes.IIecContent),
			factory,
		)
	case aastypes.ModelTypeOtherContent:
		result = wrapOtherContent[E](
			that.(aastypes.IOtherContent),
			factory,
		)
	case aastypes.ModelTypeSpecification:
		result = wrapSpecification[E](
			that.(aastypes.ISpecification),
			factory,
		)
	case aastypes.ModelTypeSomething:
		result = wrapSomething[E](
			that.(aastypes.ISomething),
			factory,
		)
	default:
		panic(
			fmt.Sprintf(
				"Unexpected model type: %v",
				that.ModelType(),
			),
		)
	}

	return
}

// Retrieve the enhancement from `that` instance.
//
// Return the enhancement, or `ok` false, if `that` instance has not been
// enhanced.
func Unwrap[E any](that aastypes.IClass) (enhancement E, ok bool) {
	var enh enhanced[E]
	enh, ok = that.(enhanced[E])
	if !ok {
		return
	}
	enhancement = enh.getEnhancement()
	return
}

// Retrieve the enhancement from `that` instance.
//
// If `that` instance has not been enhanced yet, panic.
func MustUnwrap[E any](that aastypes.IClass) (enhancement E) {
	var ok bool
	enhancement, ok = Unwrap[E](that)
	if !ok {
		panic(
			fmt.Sprintf(
				"An instance of %T has not been wrapped: %v",
				that, that,
			),
		)
	}
	return
}

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
