"""
Verify that the instances of the meta-model satisfy the invariants.

Here is an example how to verify an instance of :py:class:`dummy.types.StructuralFirst`:

.. code-block::

    import dummy.types as aas_types
    import dummy.verification as aas_verification

    an_instance = aas_types.StructuralFirst(
        # ... some constructor arguments ...
    )

    for error in aas_verification.verify(an_instance):
        print(f"{error.cause} at: {error.path}")
"""


# This code has been automatically generated by aas-core-codegen.
# Do NOT edit or append.


import math
import re
import struct
import sys
from typing import (
    Any,
    Callable,
    Iterable,
    Iterator,
    List,
    Mapping,
    Optional,
    Pattern,
    Sequence,
    Set,
    Union
)

if sys.version_info >= (3, 8):
    from typing import Final
else:
    from typing_extensions import Final

from dummy import (
    constants as aas_constants,
    types as aas_types,
)


class PropertySegment:
    """Represent a property access on a path to an erroneous value."""

    #: Instance containing the property
    instance: Final[aas_types.Class]

    #: Name of the property
    name: Final[str]

    def __init__(
            self,
            instance: aas_types.Class,
            name: str
    ) -> None:
        """Initialize with the given values."""
        self.instance = instance
        self.name = name

    def __str__(self) -> str:
        return f'.{self.name}'


class IndexSegment:
    """Represent an index access on a path to an erroneous value."""

    #: Sequence containing the item at :py:attr:`~index`
    sequence: Final[Sequence[Any]]

    #: Index of the item
    index: Final[int]

    def __init__(
            self,
            sequence: Sequence[Any],
            index: int
    ) -> None:
        """Initialize with the given values."""
        self.sequence = sequence
        self.index = index

    def __str__(self) -> str:
        return f'[{self.index}]'


Segment = Union[PropertySegment, IndexSegment]


class Path:
    """Represent the relative path to the erroneous value."""

    def __init__(self) -> None:
        """Initialize as an empty path."""
        self._segments = []  # type: List[Segment]

    @property
    def segments(self) -> Sequence[Segment]:
        """Get the segments of the path."""
        return self._segments

    def _prepend(self, segment: Segment) -> None:
        """Insert the :paramref:`segment` in front of other segments."""
        self._segments.insert(0, segment)

    def __str__(self) -> str:
        return "".join(str(segment) for segment in self._segments)


class Error:
    """Represent a verification error in the data."""

    #: Human-readable description of the error
    cause: Final[str]

    #: Path to the erroneous value
    path: Final[Path]

    def __init__(self, cause: str) -> None:
        """Initialize as an error with an empty path."""
        self.cause = cause
        self.path = Path()

    def __repr__(self) -> str:
        return f"Error(path={self.path}, cause={self.cause})"


class _Transformer(
        aas_types.AbstractTransformer[
            Iterator[Error]
        ]
):
    # noinspection PyMethodMayBeStatic
    def transform_structural_first(
            self,
            that: aas_types.StructuralFirst
    ) -> Iterator[Error]:
        if not (len(that.unique_to_first) > 0):
            yield Error(
                'The value must not be empty.'
            )

    # noinspection PyMethodMayBeStatic
    def transform_structural_second(
            self,
            that: aas_types.StructuralSecond
    ) -> Iterator[Error]:
        if not (len(that.unique_to_second) > 0):
            yield Error(
                'The value must not be empty.'
            )

    # noinspection PyMethodMayBeStatic
    def transform_mixed_abstract_descendant_one(
            self,
            that: aas_types.MixedAbstractDescendantOne
    ) -> Iterator[Error]:
        if not (len(that.unique_to_abstract_descendant_one) > 0):
            yield Error(
                'The value must not be empty.'
            )

    # noinspection PyMethodMayBeStatic
    def transform_mixed_abstract_descendant_two(
            self,
            that: aas_types.MixedAbstractDescendantTwo
    ) -> Iterator[Error]:
        if not (len(that.unique_to_abstract_descendant_two) > 0):
            yield Error(
                'The value must not be empty.'
            )

    # noinspection PyMethodMayBeStatic
    def transform_mixed_concrete_with_descendants(
            self,
            that: aas_types.MixedConcreteWithDescendants
    ) -> Iterator[Error]:
        if not (len(that.some_base_property) > 0):
            yield Error(
                'The value must not be empty.'
            )

    # noinspection PyMethodMayBeStatic
    def transform_mixed_concrete_with_descendants_child(
            self,
            that: aas_types.MixedConcreteWithDescendantsChild
    ) -> Iterator[Error]:
        if not (len(that.some_base_property) > 0):
            yield Error(
                'The value must not be empty.'
            )

        if not (len(that.some_child_property) > 0):
            yield Error(
                'The child value must not be empty.'
            )

    # noinspection PyMethodMayBeStatic
    def transform_mixed_concrete_leaf(
            self,
            that: aas_types.MixedConcreteLeaf
    ) -> Iterator[Error]:
        if not (len(that.unique_to_concrete_leaf) > 0):
            yield Error(
                'The value must not be empty.'
            )

    # noinspection PyMethodMayBeStatic
    def transform_model_typed_first(
            self,
            that: aas_types.ModelTypedFirst
    ) -> Iterator[Error]:
        if not (len(that.some_property) > 0):
            yield Error(
                'The value must not be empty.'
            )

    # noinspection PyMethodMayBeStatic
    def transform_model_typed_second(
            self,
            that: aas_types.ModelTypedSecond
    ) -> Iterator[Error]:
        if not (len(that.some_property) > 0):
            yield Error(
                'The value must not be empty.'
            )

    # noinspection PyMethodMayBeStatic
    def transform_something(
            self,
            that: aas_types.Something
    ) -> Iterator[Error]:
        for error in self.transform(that.structural_property):
            error.path._prepend(
                PropertySegment(
                    that,
                    'structural_property'
                )
            )
            yield error

        for error in self.transform(that.mixed_property):
            error.path._prepend(
                PropertySegment(
                    that,
                    'mixed_property'
                )
            )
            yield error

        for error in self.transform(that.model_typed_property):
            error.path._prepend(
                PropertySegment(
                    that,
                    'model_typed_property'
                )
            )
            yield error

        for i, an_item in enumerate(that.list_structural_property):
            for error in self.transform(an_item):
                error.path._prepend(
                    IndexSegment(
                        that.list_structural_property,
                        i
                    )
                )
                error.path._prepend(
                    PropertySegment(
                        that,
                        'list_structural_property'
                    )
                )
                yield error

        for i, another_item in enumerate(that.list_mixed_property):
            for error in self.transform(another_item):
                error.path._prepend(
                    IndexSegment(
                        that.list_mixed_property,
                        i
                    )
                )
                error.path._prepend(
                    PropertySegment(
                        that,
                        'list_mixed_property'
                    )
                )
                yield error

        for i, yet_another_item in enumerate(that.list_model_typed_property):
            for error in self.transform(yet_another_item):
                error.path._prepend(
                    IndexSegment(
                        that.list_model_typed_property,
                        i
                    )
                )
                error.path._prepend(
                    PropertySegment(
                        that,
                        'list_model_typed_property'
                    )
                )
                yield error

        for error in self.transform(that.tuple_property[0]):
            error.path._prepend(
                IndexSegment(
                    that.tuple_property,
                    0
                )
            )
            error.path._prepend(
                PropertySegment(
                    that,
                    'tuple_property'
                )
            )
            yield error
        for error in self.transform(that.tuple_property[1]):
            error.path._prepend(
                IndexSegment(
                    that.tuple_property,
                    1
                )
            )
            error.path._prepend(
                PropertySegment(
                    that,
                    'tuple_property'
                )
            )
            yield error
        for error in self.transform(that.tuple_property[2]):
            error.path._prepend(
                IndexSegment(
                    that.tuple_property,
                    2
                )
            )
            error.path._prepend(
                PropertySegment(
                    that,
                    'tuple_property'
                )
            )
            yield error

        if that.optional_structural_property is not None:
            for error in self.transform(that.optional_structural_property):
                error.path._prepend(
                    PropertySegment(
                        that,
                        'optional_structural_property'
                    )
                )
                yield error

        if that.optional_mixed_property is not None:
            for error in self.transform(that.optional_mixed_property):
                error.path._prepend(
                    PropertySegment(
                        that,
                        'optional_mixed_property'
                    )
                )
                yield error

        if that.optional_model_typed_property is not None:
            for error in self.transform(that.optional_model_typed_property):
                error.path._prepend(
                    PropertySegment(
                        that,
                        'optional_model_typed_property'
                    )
                )
                yield error


_TRANSFORMER = _Transformer()


def verify(
        that: aas_types.Class
) -> Iterator[Error]:
    """
    Verify the constraints of :paramref:`that` recursively.

    :param that: instance whose constraints we want to verify
    :yield: constraint violations
    """
    yield from _TRANSFORMER.transform(that)


# This code has been automatically generated by aas-core-codegen.
# Do NOT edit or append.
