/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package dummy.xmlization;

import javax.xml.stream.events.XMLEvent;
import javax.xml.stream.XMLEventReader;
import javax.xml.stream.XMLStreamConstants;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamWriter;
import java.util.ArrayList;
import java.util.Base64;
import java.util.function.Function;
import java.util.List;
import java.util.Optional;
import java.util.regex.Pattern;
import dummy.common.*;
import dummy.reporting.Reporting;
import dummy.stringification.Stringification;
import dummy.types.enums.*;
import dummy.types.impl.*;
import dummy.types.model.*;
import dummy.visitation.*;

/**
 * Provide de/serialization of meta-model classes to/from XML.
 */
public class Xmlization {
  /**
   * Represent a critical error during the deserialization.
   */
  @SuppressWarnings("serial")
  public static class DeserializeException extends RuntimeException {
    private final String path;
    private final String reason;

    public DeserializeException(String path, String reason) {
      super(reason + " at: " + ("".equals(path) ? "the beginning" : path));
      this.path = path;
      this.reason = reason;
    }

    public Optional<String> getPath() {
      return Optional.ofNullable(path);
    }

    public Optional<String> getReason() {
      return Optional.ofNullable(reason);
    }
  }

  /**
   * Represent a critical error during the serialization.
   */
  @SuppressWarnings("serial")
  public static class SerializeException extends RuntimeException {
    private final String path;
    private final String reason;

    public SerializeException(String path, String reason) {
      super(reason + " at: " + ("".equals(path) ? "the beginning" : path));
      this.path = path;
      this.reason = reason;
    }

    public Optional<String> getPath() {
      return Optional.ofNullable(path);
    }

    public Optional<String> getReason() {
      return Optional.ofNullable(reason);
    }
  }

  /**
   * Signal a failure of the serialization, carrying the path to the culprit.
   *
   * <p>The path is built as the stack unwinds -- every container prepends
   * the one segment it knows, the property its name and the list the index
   * of the item -- which is why this can not be a
   * {@link SerializeException} already: that one renders its message in
   * its constructor, so its path has to be complete by then.
   * {@link Serialize#to} renders and converts.
   */
  @SuppressWarnings("serial")
  private static class _SerializeFailure extends RuntimeException {
    private final Reporting.Error error;

    _SerializeFailure(Reporting.Error error) {
      super(error.getCause());
      this.error = error;
    }

    Reporting.Error getError() {
      return error;
    }
  }

  /**
   * The XML namespace of the meta-model
   */
  public static final String AAS_NAME_SPACE =
    "https://dummy.com";

  /**
   * Implement the deserialization of meta-model classes from XML.
   *
   * <p>The implementation propagates an {@link Reporting.Error} instead of
   * relying on exceptions. Under the assumption that incorrect data is much less
   * frequent than correct data, this makes the deserialization more
   * efficient.
   *
   * <p>However, we do not want to force the client to deal with
   * the {@link Reporting.Error} class as this is not intuitive.
   * Therefore we distinguish the implementation, realized in
   * {@link _DeserializeImplementation}, and the facade given in
   * {@link Deserialize} class.
   */
  private static class _DeserializeImplementation
  {
    private static XMLEvent currentEvent(XMLEventReader reader) {
      try {
        return reader.peek();
      } catch (XMLStreamException xmlStreamException) {
        throw new Xmlization.DeserializeException("",
          "Failed in method peek because of: " +
          xmlStreamException.getMessage());
      }
    }

    private static String getEventTypeAsString(XMLEvent event) {
      switch (event.getEventType()) {
        case XMLStreamConstants.START_ELEMENT:
          return "Start-Element";
        case XMLStreamConstants.END_ELEMENT:
          return "End-Element";
        case XMLStreamConstants.PROCESSING_INSTRUCTION:
          return "Processing-Instruction";
        case XMLStreamConstants.CHARACTERS:
          return "Characters";
        case XMLStreamConstants.COMMENT:
          return "Comment";
        case XMLStreamConstants.SPACE:
          return "Space";
        case XMLStreamConstants.START_DOCUMENT:
          return "Start-Document";
        case XMLStreamConstants.END_DOCUMENT:
          return "End-Document";
        case XMLStreamConstants.ENTITY_REFERENCE:
          return "Entity-Reference";
        case XMLStreamConstants.ATTRIBUTE:
          return "Attribute";
        case XMLStreamConstants.NOTATION_DECLARATION:
          return "Notation-Declaration";
        default:
          return "Unknown-Type";
      }
    }

    private static boolean isEmptyElement(XMLEventReader reader) {
      // Skip the element node and go to the content
      try {
        reader.nextEvent();
      } catch (XMLStreamException xmlStreamException) {
        throw new Xmlization.DeserializeException("",
          "Failed in method isEmptyElement because of: " +
          xmlStreamException.getMessage());
      }
      return currentEvent(reader).isEndElement();
    }

    private static void skipWhitespaceAndComments(XMLEventReader reader) {
      while (whiteSpaceOrComment(reader)) {
        reader.next();
      }
    }

    private static boolean whiteSpaceOrComment(XMLEventReader reader) {
      final XMLEvent currentEvent = currentEvent(reader);
      final boolean isComment = (currentEvent != null &&
        currentEvent.getEventType() == XMLStreamConstants.COMMENT);
      final boolean isWhiteSpace = (currentEvent != null &&
        currentEvent.getEventType() == XMLStreamConstants.CHARACTERS &&
        currentEvent.asCharacters().isWhiteSpace());
      return isComment || isWhiteSpace;
    }

    private static void skipStartDocument(XMLEventReader reader){
      if (currentEvent(reader).isStartDocument()){
        reader.next();
      }
    }

    private static boolean invalidNameSpace(XMLEvent event) {
      if (event.isStartElement()) {
        return !AAS_NAME_SPACE.equals(event.asStartElement().getName().getNamespaceURI());
      } else {
        return !AAS_NAME_SPACE.equals(event.asEndElement().getName().getNamespaceURI());
      }
    }

    /**
     * Check the namespace and extract the element's name.
     */
    private static Reporting.Result<String> tryElementName(XMLEventReader reader) {
      final XMLEvent currentEvent = currentEvent(reader);
      final boolean precondition = currentEvent.isStartElement() || currentEvent.isEndElement();
      if (!precondition) {
        throw new IllegalStateException("Expected to be at a start or an end element "
            + "but got: " + getEventTypeAsString(currentEvent));
      }

      if (invalidNameSpace(currentEvent)) {
        String namespace = currentEvent.isStartElement()
            ? currentEvent.asStartElement().getName().getNamespaceURI()
            : currentEvent.asEndElement().getName().getNamespaceURI();
        final Reporting.Error error = new Reporting.Error(
            "Expected an element within a namespace " +
            AAS_NAME_SPACE + ", " + "but got: " + namespace);
        return Reporting.Result.failure(error);
      }
      return Reporting.Result.success(currentEvent.isStartElement()
          ? currentEvent.asStartElement().getName().getLocalPart()
          : currentEvent.asEndElement().getName().getLocalPart());
    }

    /**
     * Read the content of an element which has already been opened.
     *
     * <p>{@code isEmpty} tells whether that element was self-closing.
     */
    @FunctionalInterface
    private interface ContentReader<T> {
      Reporting.Result<? extends T> read(XMLEventReader reader, boolean isEmpty);
    }

    /**
     * Read a whole element, opening and closing it.
     */
    @FunctionalInterface
    private interface ElementReader<T> {
      Reporting.Result<? extends T> read(XMLEventReader reader);
    }

    /**
     * Convert the text content of an element which has already been opened.
     */
    @FunctionalInterface
    private interface ContentConverter<T> {
      T convert(XMLEventReader reader) throws XMLStreamException;
    }

    /**
     * Look up the name of the element which {@code reader} is positioned at.
     *
     * <p>This is the single primitive answering "we are at an element, and this is
     * its name": {@link #readNamedElement} checks that name against the one its
     * container supplied, a dispatcher switches on it, and a property loop uses it
     * to select the property. Nothing is consumed, which is what lets a dispatcher
     * hand the whole element on to the reader it selected.
     */
    private static Reporting.Result<String> peekElementName(XMLEventReader reader) {
      skipWhitespaceAndComments(reader);

      final XMLEvent currentEvent = currentEvent(reader);
      if (currentEvent.isEndDocument()) {
        return Reporting.Result.failure(new Reporting.Error(
          "Expected an XML element, but reached the end-of-file"));
      }

      if (!currentEvent.isStartElement()) {
        return Reporting.Result.failure(new Reporting.Error(
          "Expected an XML element, but got the node of type " +
          getEventTypeAsString(currentEvent) + " with the value " + currentEvent));
      }

      return tryElementName(reader);
    }

    /**
     * Consume the end tag concluding the element called {@code elementName}.
     */
    private static Reporting.Result<XMLEvent> consumeEndElement(
      XMLEventReader reader, String elementName) {
      skipWhitespaceAndComments(reader);

      final XMLEvent currentEvent = currentEvent(reader);
      if (currentEvent.isEndDocument()) {
        return Reporting.Result.failure(new Reporting.Error(
          "Expected an XML end element to conclude the element " + elementName +
          ", but got the end-of-file"));
      }

      if (!currentEvent.isEndElement()) {
        return Reporting.Result.failure(new Reporting.Error(
          "Expected an XML end element to conclude the element " + elementName +
          ", but got the node of type " + getEventTypeAsString(currentEvent) +
          " with the value " + currentEvent));
      }

      final Reporting.Result<String> tryEndElementName = tryElementName(reader);
      if (tryEndElementName.isError()) {
        return tryEndElementName.castTo(XMLEvent.class);
      }

      if (!elementName.equals(tryEndElementName.getResult())) {
        return Reporting.Result.failure(new Reporting.Error(
          "Expected an XML end element to conclude the element " + elementName +
          ", but got the end element with the name " + tryEndElementName.getResult()));
      }

      try {
        return Reporting.Result.success(reader.nextEvent());
      } catch (XMLStreamException xmlStreamException) {
        throw new Xmlization.DeserializeException("",
          "Failed in method consumeEndElement because of: " +
          xmlStreamException.getMessage());
      }
    }

    /**
     * Read a whole element which is expected to be called {@code name}, and read
     * its content with {@code readContent}.
     *
     * <p>The name is data, not a type: an instance reads the XML name of its own
     * class, a list item reads {@code "v"} and a tuple item reads {@code "v1"},
     * {@code "v2"}, ... by position. One framer therefore serves them all.
     */
    private static <T> Reporting.Result<? extends T> readNamedElement(
      XMLEventReader reader, String name, ContentReader<T> readContent) {
      final Reporting.Result<String> tryElementName = peekElementName(reader);
      if (tryElementName.isError()) {
        return Reporting.Result.failure(tryElementName.getError());
      }

      if (!name.equals(tryElementName.getResult())) {
        return Reporting.Result.failure(new Reporting.Error(
          "Expected an XML element " + name + ", but got an XML element " +
          tryElementName.getResult()));
      }

      final boolean isEmpty = isEmptyElement(reader);

      final Reporting.Result<? extends T> result = readContent.read(reader, isEmpty);
      if (result.isError()) {
        return result;
      }

      final Reporting.Result<XMLEvent> endResult = consumeEndElement(reader, name);
      if (endResult.isError()) {
        return Reporting.Result.failure(endResult.getError());
      }

      return result;
    }

    private static String readContentAsString(XMLEventReader reader) throws XMLStreamException {
      final StringBuilder content = new StringBuilder();

      while (reader.peek().isCharacters() || reader.peek().getEventType() == XMLStreamConstants.COMMENT) {
        if (reader.peek().isCharacters()) {
          content.append(reader.peek().asCharacters().getData());
        }
        reader.nextEvent();
      }

      return content.toString();
    }

    /**
     * Read the text content of an element and convert it with
     * {@code convert}.
     *
     * <p>A self-closing element is an error, since there is no text to convert.
     */
    private static <T> Reporting.Result<T> readText(
      XMLEventReader reader,
      boolean isEmpty,
      ContentConverter<T> convert,
      String typeName) {
      if (isEmpty) {
        return Reporting.Result.failure(new Reporting.Error(
          "Expected an XML content representing " + typeName +
          ", but encountered a self-closing element"));
      }

      if (currentEvent(reader).isEndDocument()) {
        return Reporting.Result.failure(new Reporting.Error(
          "Expected an XML content representing " + typeName +
          ", but reached the end-of-file"));
      }

      try {
        return Reporting.Result.success(convert.convert(reader));
      } catch (Exception exception) {
        return Reporting.Result.failure(new Reporting.Error(
          "The XML content could not be de-serialized as " + typeName + ": " +
          exception.getMessage()));
      }
    }

    /**
     * Read the text content of an element and convert it with
     * {@code convert}, giving {@code whenEmpty} for a self-closing element.
     */
    private static <T> Reporting.Result<T> readText(
      XMLEventReader reader,
      boolean isEmpty,
      ContentConverter<T> convert,
      String typeName,
      T whenEmpty) {
      if (isEmpty) {
        return Reporting.Result.success(whenEmpty);
      }

      return readText(reader, isEmpty, convert, typeName);
    }

    /**
     * Read the text content of an element and parse it as a literal of
     * the enumeration called {@code enumName}.
     */
    private static <T> Reporting.Result<T> readEnum(
      XMLEventReader reader,
      boolean isEmpty,
      Function<String, Optional<T>> parseLiteral,
      String enumName) {
      final Reporting.Result<String> tryText = readText(
        reader, isEmpty, _DeserializeImplementation::readContentAsString, enumName);
      if (tryText.isError()) {
        return Reporting.Result.failure(tryText.getError());
      }

      final Optional<T> literal = parseLiteral.apply(tryText.getResult());
      if (!literal.isPresent()) {
        return Reporting.Result.failure(new Reporting.Error(
          "The text could not be parsed as a literal of " + enumName + ": " +
          tryText.getResult()));
      }

      return Reporting.Result.success(literal.get());
    }

    /**
     * Read the items of a list, each with {@code readItem}.
     *
     * <p>Every start element is considered to mark the start of an item. Reading
     * stops as soon as a non-start element is encountered.
     */
    private static <T> Reporting.Result<List<T>> readList(
      XMLEventReader reader, boolean isEmpty, ElementReader<T> readItem) {
      final List<T> result = new ArrayList<>();
      if (isEmpty) {
        return Reporting.Result.success(result);
      }

      skipWhitespaceAndComments(reader);
      int index = 0;
      if (!currentEvent(reader).isStartElement()) {
        final Reporting.Error error = new Reporting.Error(
          "Expected a start element opening an item of the list, " +
          "but got an XML " + getEventTypeAsString(currentEvent(reader)));
        error.prependSegment(new Reporting.IndexSegment(index));
        return Reporting.Result.failure(error);
      }

      while (currentEvent(reader).isStartElement()) {
        final Reporting.Result<? extends T> itemResult = readItem.read(reader);
        if (itemResult.isError()) {
          itemResult.getError()
            .prependSegment(
              new Reporting.IndexSegment(index));
          return Reporting.Result.failure(itemResult.getError());
        }

        result.add(itemResult.getResult());
        index++;
        skipWhitespaceAndComments(reader);
      }

      return Reporting.Result.success(result);
    }

    /**
     * Check whether the sequence of the properties has ended.
     *
     * <p>Only the end tag of the enclosing element concludes a sequence. Reaching
     * the end-of-file does not -- that is an error, which
     * {@link #peekElementName} reports when the caller goes on to read the next
     * property.
     */
    private static boolean atEndOfSequence(XMLEventReader reader) {
      skipWhitespaceAndComments(reader);
      return currentEvent(reader).isEndElement();
    }

    /**
     * Report an element which is not a property of the class {@code className}.
     */
    private static <T> Reporting.Result<T> unexpectedProperty(
      String className, String elementName) {
      return Reporting.Result.failure(new Reporting.Error(
        "We expected properties of the class " + className + ", " +
        "but got an unexpected element " +
        "with the name " + elementName));
    }

    /**
     * Report a property which the sequence of the properties gave more than once.
     */
    private static Reporting.Error duplicatePropertyError(String elementName) {
      return new Reporting.Error(
        "Property " + elementName + " occurred more than once");
    }

    /**
     * Report a required property of the class {@code className} which the
     * sequence of the properties did not give.
     */
    private static <T> Reporting.Result<T> missingRequiredProperty(
      String propertyName, String className) {
      return Reporting.Result.failure(new Reporting.Error(
        "The required property " + propertyName + " has not been given " +
        "in the XML representation of an instance of class " + className));
    }

    private static Reporting.Result<Result> readTextAs_Result(
      XMLEventReader reader, boolean isEmpty) {
      return readEnum(
        reader,
        isEmpty,
        Stringification::resultFromString,
        "Result");
    }

    private static Reporting.Result<List<Result>> readListOf_Result(
      XMLEventReader reader, boolean isEmpty) {
      return readList(
        reader, isEmpty, _DeserializeImplementation::readAtV_Result);
    }

    private static Reporting.Result<? extends Result> readAtV_Result(
      XMLEventReader reader) {
      return readNamedElement(
        reader,
        "v",
        _DeserializeImplementation::readTextAs_Result);
    }

    /**
     * Deserialize an instance of class Something from a sequence of XML elements.
     *
     * <p>If {@code isEmptySequence} is set, we should try to deserialize
     * the instance from an empty sequence. That is, the parent element
     * was a self-closing element.
     */
    private static Reporting.Result<Something> readSomethingFromSequence(
      XMLEventReader reader,
      boolean isEmptySequence) {
      List<Result> theSomeResults = null;

      if (!isEmptySequence) {
        while (!atEndOfSequence(reader)) {
          final Reporting.Result<String> tryElementName = peekElementName(reader);
          if (tryElementName.isError()) {
            return Reporting.Result.failure(tryElementName.getError());
          }

          final String elementName = tryElementName.getResult();
          final boolean isEmptyProperty = isEmptyElement(reader);

          Reporting.Error valueError = null;

          switch (elementName) {
            case "someResults": {
              if (theSomeResults != null) {
                valueError = duplicatePropertyError(elementName);
                break;
              }

              final Reporting.Result<List<Result>> value =
                readListOf_Result(reader, isEmptyProperty);
              if (value.isError()) {
                valueError = value.getError();
              } else {
                theSomeResults = value.getResult();
              }
              break;
            }
            default:
              return unexpectedProperty("Something", elementName);
          }

          if (valueError != null) {
            valueError.prependSegment(
              new Reporting.NameSegment(
                elementName));
            return Reporting.Result.failure(valueError);
          }

          final Reporting.Result<XMLEvent> endResult = consumeEndElement(reader, elementName);
          if (endResult.isError()) {
            return Reporting.Result.failure(endResult.getError());
          }
        }
      }

      if (theSomeResults == null) {
        return missingRequiredProperty("someResults", "Something");
      }

      return Reporting.Result.success(new Something(
        theSomeResults));
    }

    /**
     * Deserialize an instance of class Something from an XML element.
     */
    private static Reporting.Result<? extends Something> readSomethingFromElement(
      XMLEventReader reader) {
      return readNamedElement(
        reader,
        "something",
        _DeserializeImplementation::readSomethingFromSequence);
    }
  }

  /**
   * Deserialize instances of meta-model classes from XML.
   */
  /** <pre>
   * Here is an example how to parse an instance of class Something:
   * {@code
   * XMLEventReader reader = xmlFactory.createXMLEventReader(...some arguments...);
   * Something anInstance = Deserialize.deserializeSomething(
   *   reader);
   * }
   * </pre>
   *
   * <pre>
   * If the elements live in a namespace, you have to supply it. For example:
   * {@code
   * XMLEventReader reader = xmlFactory.createXMLEventReader(...some arguments...);
   * Something anInstance = Deserialize.deserializeSomething(
   *   reader,
   *   "http://www.example.com/5/12");
   * }
   * </pre>
   */
  public static class Deserialize
  {
    /**
     * Deserialize an instance of Something from {@code reader}.
     *
     * @param reader Initialized XML reader with reader.peek() set to the element
     */
    public static Something deserializeSomething(
      XMLEventReader reader) {

      _DeserializeImplementation.skipStartDocument(reader);
      _DeserializeImplementation.skipWhitespaceAndComments(reader);

      Reporting.Result<? extends Something> result =
        _DeserializeImplementation.readSomethingFromElement(
          reader);

      return result.onError(error -> {
        error.prependSegment(new Reporting.NameSegment("something"));
        throw new DeserializeException(
          Reporting.generateRelativeXPath(error.getPathSegments()),
          error.getCause());
      });
    }
  }

  /**
   * Serialize recursively the instances as XML elements.
   */
  static class _VisitorWithWriter
    extends AbstractVisitorWithContext<XMLStreamWriter> {

    /**
     * Declare the XML namespace on the element which this visitor writes.
     *
     * <p>Only the outermost element carries the declaration. The obvious
     * alternative -- a flag cleared once the first element has been written --
     * would be mutable state, and state forces every method of this class to be
     * an instance method, which in turn makes every method reference to it
     * capture {@code this} and allocate. Pinning the flag in the constructor
     * instead costs one visitor per case, allocated once for the whole program,
     * and lets everything else here be {@code static}.
     */
    private final boolean withNamespace;

    private _VisitorWithWriter(boolean withNamespace) {
      this.withNamespace = withNamespace;
    }

    /**
     * Write the outermost element, which declares the XML namespace.
     */
    private static final _VisitorWithWriter ROOT =
      new _VisitorWithWriter(true);

    /**
     * Write {@code that} where {@code writer} already is.
     *
     * <p>Every value is written through this one shape, so that the writing
     * composes: {@link #writeElement} frames it in a start and an end tag, and
     * a class's own {@code write...AsSequence} already is one.
     *
     * <p>There is deliberately no second shape for a whole element, as there is
     * on the reading side. An element differs from a content only in what it
     * writes, never in its shape; the reading needs the distinction because
     * a content reader has to be told whether its element was self-closing, and
     * a writer has nothing to be told.
     *
     * <p>Use sites take a {@code ContentWriter<? super T>} -- Java's spelling
     * of the contravariance -- so that the single writer of an {@link IClass}
     * serves wherever the writer of a more specific interface is expected.
     */
    @FunctionalInterface
    private interface ContentWriter<T> {
      void write(T that, XMLStreamWriter writer) throws XMLStreamException;
    }

    /**
     * Write {@code that} as an XML element named {@code name}, its content
     * written by {@code writeContent}.
     *
     * <p>An element is nothing but a start and an end tag around a content, so
     * there is no writer per property kind: only the content writer differs,
     * and the type of the value alone decides which one it is.
     *
     * <p>{@code withNamespace} declares the XML namespace on the element,
     * which only the outermost element does.
     */
    private static <T> void writeElement(
      String name,
      T that,
      XMLStreamWriter writer,
      boolean withNamespace,
      ContentWriter<? super T> writeContent) {
      try {
        writer.writeStartElement(name);
        if (withNamespace) {
          writer.writeNamespace("xmlns", AAS_NAME_SPACE);
        }
        writeContent.write(that, writer);
        writer.writeEndElement();
      } catch (XMLStreamException exception) {
        throw new _SerializeFailure(
          new Reporting.Error(exception.getMessage()));
      }
    }

    /**
     * Write {@code that} as an XML element named {@code name} nested in
     * another element, so that the XML namespace is not re-declared.
     *
     * <p>This is what an item of a list or of a tuple is written with. It
     * contributes no segment to the error path: its container has already
     * contributed the item's index, and the index selects this very element
     * (see {@link #writeListOf} in the generated writers).
     */
    private static <T> void writeElement(
      String name,
      T that,
      XMLStreamWriter writer,
      ContentWriter<? super T> writeContent) {
      writeElement(name, that, writer, false, writeContent);
    }

    /**
     * Write {@code that} as the XML element of a property called
     * {@code name}.
     *
     * <p>This is {@link #writeElement} plus the one thing a property knows
     * which nothing below it does: its own name. Prepending it here, once,
     * saves a {@code try} around every one of the property writes.
     */
    private static <T> void writeProperty(
      String name,
      T that,
      XMLStreamWriter writer,
      ContentWriter<? super T> writeContent) {
      try {
        writeElement(name, that, writer, false, writeContent);
      } catch (_SerializeFailure failure) {
        failure.getError().prependSegment(
          new Reporting.NameSegment(name));
        throw failure;
      }
    }

    /**
     * Write the text of {@code that} as XML content.
     *
     * <p>This is the {@link ContentWriter} of every enumeration-typed value, be
     * it a property, a list item or a tuple item. There is one writer, and not
     * one per enumeration, since a literal carries its own text -- see
     * {@link IEnum#literalText()} -- so nothing here is specific to
     * an enumeration.
     */
    private static void writeEnum(
      IEnum that,
      XMLStreamWriter writer) throws XMLStreamException {
      writer.writeCharacters(that.literalText());
    }

    private static void writeListOf_IEnum(
      List<? extends IEnum> that,
      XMLStreamWriter writer) {
      int index = 0;
      try {
        for (IEnum item : that) {
          writeAtV_IEnum(item, writer);
          index++;
        }
      } catch (_SerializeFailure failure) {
        failure.getError().prependSegment(
          new Reporting.IndexSegment(index));
        throw failure;
      }
    }

    private static void writeAtV_IEnum(
      IEnum that,
      XMLStreamWriter writer) {
      writeElement(
        "v",
        that,
        writer,
        _VisitorWithWriter::writeEnum);
    }

    private static void writeSomethingAsSequence(
      ISomething that,
      XMLStreamWriter writer) {
      writeProperty(
        "someResults",
        that.getSomeResults(),
        writer,
        _VisitorWithWriter::writeListOf_IEnum);
    }

    @Override
    public void visitSomething(
      ISomething that,
      XMLStreamWriter writer) {
      writeElement(
        "something",
        that,
        writer,
        withNamespace,
        _VisitorWithWriter::writeSomethingAsSequence);
    }
  }

  /**
   * Serialize instances of meta-model classes to XML.
   */
  /**
   * <pre>
   * Here is an example how to serialize an instance of Something:
   * {@code
   * IClass anInstance = new Something(
   *     ... some constructor arguments ...
   * );
   * XMLStreamWriter writer = xmlWriterFactory.createXMLStreamWriter(...some arguments...);
   * Serialize.to(
   *   anInstance,
   *   writer);
   * }
   * </pre>
   */
  public static class Serialize
  {
    /**
     * Serialize an instance of the meta-model to XML.
     *
     * <p>{@code writer} is flushed exactly once, here at the end. Nothing is
     * flushed in-between, which is what lets {@link XMLStreamWriter} buffer,
     * and the single flush at the end is what lets a failure of the underlying
     * stream be reported as a {@link SerializeException} from this method --
     * were it left to the caller, the failure would surface at their own flush,
     * after the serialization has long returned.
     *
     * <p>The path of a {@link SerializeException} is rendered as a relative
     * XPath, the same spelling the de-serialization reports, and names
     * the properties and the list indices leading to the culprit --
     * {@code submodelElements/*[0]/value}. Two things it deliberately does not
     * name: the outermost element, since this method takes any
     * {@link IClass} and the name would say nothing the caller does not
     * already know; and the discriminator element of a polymorphic property,
     * which the de-serialization does prepend. The de-serialization is pointing
     * into a document it is reading, where that element is a real extra level;
     * this is pointing into the instance the caller handed over, where it is
     * not -- {@code value/idShort} here is exactly
     * {@code getValue().getIdShort()}.
     */
    public static void to(
      IClass that,
      XMLStreamWriter writer) throws SerializeException {
      try {
        _VisitorWithWriter.ROOT.visit(
          that, writer);
        writer.flush();
      } catch (XMLStreamException exception) {
        throw new SerializeException("", exception.getMessage());
      } catch (_SerializeFailure failure) {
        final Reporting.Error error = failure.getError();
        throw new SerializeException(
          Reporting.generateRelativeXPath(error.getPathSegments()),
          error.getCause());
      }
    }
  }
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
