/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package dummy.stringification;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import dummy.types.enums.*;

public class Stringification {
  /**
   * Retrieve the string representation of {@code that}.
   *
   * <p>If {@code that} is not a valid literal, return {@code Optional#empty()}.
   */
  public static Optional<String> toString(SomeEnum that)
  {
    return (that == null)
      ? Optional.empty()
      : Optional.of(that.literalText());
  }

  /**
   * Retrieve the string representation of {@code that}.
   *
   * @throws IllegalArgumentException if {@code that} is not a valid literal
   */
  public static String mustToString(SomeEnum that)
  {
    if (that == null) {
      throw new IllegalArgumentException("Invalid literal of SomeEnum: " + that);
    }
    return that.literalText();
  }

  private static final Map<String, SomeEnum> someEnumFromString;
  static {
    final Map<String, SomeEnum> temp = new HashMap<>();

    temp.put("first", SomeEnum.FIRST);
    temp.put("second", SomeEnum.SECOND);
    temp.put("third", SomeEnum.THIRD);

    if (!temp.values().containsAll(Arrays.asList(SomeEnum.values()))) {
      throw new IllegalStateException("Unmapped SomeEnum");
    }

    someEnumFromString = Collections.unmodifiableMap(temp);
  }

  /**
   * Parse the string representation of {@link SomeEnum}.
   *
   * <p>If {@code text} is not a valid string representation
   * of a literal of {@link SomeEnum},
   * return {@code Optional#empty()}.
   */
  public static Optional<SomeEnum> someEnumFromString(String text)
  {
    SomeEnum value = someEnumFromString.get(text);
    if (value == null) {
      return Optional.empty();
    } else {
      return Optional.of(value);
    }
  }
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
