// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

#include "dummy/wstringification.hpp"

#define CATCH_CONFIG_MAIN
#include <catch2/catch.hpp>

namespace aas = dummy;

TEST_CASE("Test ModelType round-trip") {
  REQUIRE(
    aas::types::ModelType::kInstance
    == aas::wstringification::MustModelTypeFromWstring(
      L"Instance"
    )
  );

  REQUIRE(
    aas::wstringification::to_wstring(
      aas::types::ModelType::kInstance
    )
    == L"Instance"
  );

  REQUIRE(
    aas::types::ModelType::kPointer
    == aas::wstringification::MustModelTypeFromWstring(
      L"Pointer"
    )
  );

  REQUIRE(
    aas::wstringification::to_wstring(
      aas::types::ModelType::kPointer
    )
    == L"Pointer"
  );

  REQUIRE(
    aas::types::ModelType::kJsonObjectOfName
    == aas::wstringification::MustModelTypeFromWstring(
      L"JsonObjectOfName"
    )
  );

  REQUIRE(
    aas::wstringification::to_wstring(
      aas::types::ModelType::kJsonObjectOfName
    )
    == L"JsonObjectOfName"
  );

  REQUIRE(
    aas::types::ModelType::kListOf
    == aas::wstringification::MustModelTypeFromWstring(
      L"ListOf"
    )
  );

  REQUIRE(
    aas::wstringification::to_wstring(
      aas::types::ModelType::kListOf
    )
    == L"ListOf"
  );

  REQUIRE(
    aas::types::ModelType::kSomething
    == aas::wstringification::MustModelTypeFromWstring(
      L"Something"
    )
  );

  REQUIRE(
    aas::wstringification::to_wstring(
      aas::types::ModelType::kSomething
    )
    == L"Something"
  );
}

TEST_CASE("Test failure on ModelType") {
  CHECK(
    !aas::wstringification::ModelTypeFromWstring(
      L"Totally utterly invalid"
    ).has_value()
  );

  REQUIRE_THROWS_WITH(
    aas::wstringification::MustModelTypeFromWstring(
      L"Totally utterly invalid"
    ),
    "Unexpected ModelType literal: Totally utterly invalid"
  );
}

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
