/**
 * Execute all common JSONization loader helpers once.
 */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import * as TestCommonJsonization from "./commonJsonization";

test("commonJsonization loaders for Box", () => {
  expect(TestCommonJsonization.loadMinimalBox()).not.toBeNull();
  expect(TestCommonJsonization.loadMaximalBox()).not.toBeNull();
});

test("commonJsonization loaders for Bag", () => {
  expect(TestCommonJsonization.loadMinimalBag()).not.toBeNull();
  expect(TestCommonJsonization.loadMaximalBag()).not.toBeNull();
});

test("commonJsonization loaders for Container", () => {
  expect(TestCommonJsonization.loadMinimalContainer()).not.toBeNull();
  expect(TestCommonJsonization.loadMaximalContainer()).not.toBeNull();
});

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
