/**
 * Provide de/serialization of AAS classes to/from XML.
 *
 * The implementation is incremental and follows a SAX-style parsing approach.
 */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import * as AasCommon from "./common";
import * as AasTypes from "./types";
import * as AasStringification from "./stringification";

import {
  CdataToken,
  CloseTagToken,
  CommentToken,
  EndToken,
  OpenTagToken,
  TextToken,
  XmlAnyToken,
  XmlSaxParser
} from "xmlsax-typescript";

const NAMESPACE = "https://dummy.com";

/**
 * Represent a property name segment in an XML path.
 */
export class NameSegment {
  readonly name: string;

  constructor(name: string) {
    this.name = name;
  }
}

/**
 * Represent an index segment in an XML path.
 */
export class IndexSegment {
  readonly index: number;

  constructor(index: number) {
    this.index = index;
  }
}

export type Segment = NameSegment | IndexSegment;

/**
 * Represent a relative path to the erroneous XML value.
 */
export class Path {
  private readonly _segments = new Array<Segment>();

  segments(): Array<Segment> {
    return this._segments;
  }

  prepend(segment: Segment): void {
    this._segments.unshift(segment);
  }

  toString(): string {
    if (this._segments.length === 0) {
      return "";
    }

    const parts = new Array<string>();
    for (const segment of this._segments) {
      if (segment instanceof NameSegment) {
        if (parts.length === 0) {
          parts.push(segment.name);
        } else {
          parts.push(`.${segment.name}`);
        }
      } else if (segment instanceof IndexSegment) {
        parts.push(`[${segment.index}]`);
      }
    }

    return parts.join("");
  }
}

/**
 * Signal that XML de-serialization could not be performed.
 */
export class DeserializationError {
  readonly message: string;
  readonly path: Path;

  constructor(message: string, path: Path | null = null) {
    this.message = message;
    this.path = path ?? new Path();
  }
}

/**
 * Signal that XML serialization could not be performed.
 */
export class SerializationError {
  readonly message: string;
  readonly path: Path;

  constructor(message: string, path: Path | null = null) {
    this.message = message;
    this.path = path ?? new Path();
  }
}

function newDeserializationError<T>(
  message: string
): AasCommon.Either<T, DeserializationError> {
  return new AasCommon.Either<T, DeserializationError>(
    null,
    new DeserializationError(message)
  );
}

/**
 * Parse a value from `cursor`.
 *
 * Every parser in this module wears this one shape, which is what lets them
 * compose: a parser can be given to another parser without a closure, since
 * everything it needs comes from the `cursor` and from its own definition.
 * The name says what a parser consumes -- a `parse*Content` stops right before
 * the closing tag of the element which the caller has opened, while
 * a `parse*Element` and a `dispatchParse*Element` read an element of their own,
 * its tags included.
 *
 * @typeParam T - type of the parsed value
 */
type ContentParser<T> = (
  cursor: XmlCursor
) => AasCommon.Either<T, DeserializationError>;

function currentTokenKind(cursor: XmlCursor): string {
  const token = cursor.current();
  if (token === null) {
    return "end-of-token-stream";
  }

  return token.kind;
}

function localNameOfTag(tag: unknown): string {
  const aTag = tag as {
    name?: unknown,
    local?: unknown,
    localName?: unknown
  };

  if (typeof aTag.local === "string") {
    return aTag.local;
  }
  if (typeof aTag.localName === "string") {
    return aTag.localName;
  }
  if (typeof aTag.name === "string") {
    const colonIndex = aTag.name.indexOf(":");
    if (colonIndex >= 0) {
      return aTag.name.substring(colonIndex + 1);
    }
    return aTag.name;
  }

  return "";
}

function namespaceOfTag(tag: unknown): string {
  const aTag = tag as { uri?: unknown, namespaceURI?: unknown };
  if (typeof aTag.uri === "string") {
    return aTag.uri;
  }
  if (typeof aTag.namespaceURI === "string") {
    return aTag.namespaceURI;
  }
  return "";
}

function checkExpectedOpenTagNamespace(
  openTag: OpenTagToken
): DeserializationError | null {
  const namespace = namespaceOfTag(openTag.tag);
  if (namespace !== NAMESPACE) {
    return new DeserializationError(
      "Expected XML namespace " +
        `'${NAMESPACE}', but got '${namespace}'`
    );
  }

  return null;
}

/**
 * Read the next property's opening tag while parsing the sequence of
 * properties of `className`, advancing `cursor` past it.
 *
 * @param cursor - to be read from
 * @param className - name of the class being parsed, for error reporting
 * @returns
 * the next property's opening tag, or `null` if the closing tag of
 * `className` was reached instead, or an error
 */
function nextPropertyOpenTag(
  cursor: XmlCursor,
  className: string
): OpenTagToken | DeserializationError | null {
  const token = cursor.current();
  if (token === null) {
    return new DeserializationError(
      `Unexpected end of token stream while parsing ${className}`
    );
  }

  if (token instanceof CloseTagToken) {
    return null;
  }

  if (!(token instanceof OpenTagToken)) {
    return new DeserializationError(
      "Expected an XML property start element or the closing element of " +
      `${className}, but got token kind: ${token.kind}`
    );
  }

  const namespaceError = checkExpectedOpenTagNamespace(token);
  if (namespaceError !== null) {
    return namespaceError;
  }

  cursor.advance();
  return token;
}

function checkExpectedCloseTag(
  closeTag: CloseTagToken,
  expectedLocalName: string
): DeserializationError | null {
  const namespace = namespaceOfTag(closeTag.tag);
  if (namespace !== NAMESPACE) {
    return new DeserializationError(
      "Expected XML namespace " +
        `'${NAMESPACE}', but got '${namespace}'`
    );
  }

  const observedLocalName = localNameOfTag(closeTag.tag);
  if (observedLocalName !== expectedLocalName) {
    return new DeserializationError(
      `Expected closing XML element '${expectedLocalName}', ` +
      `but got '${observedLocalName}'`
    );
  }

  return null;
}

/**
 * Read the next token from `cursor`, expecting it to be the closing XML
 * element named `expectedLocalName`, and consume it.
 */
function consumeCloseTag(
  cursor: XmlCursor,
  expectedLocalName: string
): DeserializationError | null {
  const closeTag = cursor.current();
  if (!(closeTag instanceof CloseTagToken)) {
    return new DeserializationError(
      `Expected a closing element '${expectedLocalName}', ` +
      `but got token kind: ${currentTokenKind(cursor)}`
    );
  }

  const closeError = checkExpectedCloseTag(closeTag, expectedLocalName);
  if (closeError !== null) {
    return closeError;
  }

  cursor.advance();
  return null;
}

/**
 * Read the next non-ignorable token from `cursor`, expecting it to be
 * an opening XML element in the expected namespace.
 *
 * This is shared by the parsing of a single list item, a single tuple
 * item, and the dispatch-parsing of an interface.
 *
 * @param cursor - to read from
 * @returns the opening tag, or an error
 */
function readNextOpenTag(
  cursor: XmlCursor
): AasCommon.Either<OpenTagToken, DeserializationError> {
  cursor.skipIgnorable();
  const token = cursor.current();
  if (token === null) {
    return newDeserializationError<OpenTagToken>(
      "Expected an XML element, but got end of token stream"
    );
  }
  if (!(token instanceof OpenTagToken)) {
    return newDeserializationError<OpenTagToken>(
      `Expected an XML element, but got token kind: ${token.kind}`
    );
  }

  const namespaceError = checkExpectedOpenTagNamespace(token);
  if (namespaceError !== null) {
    return new AasCommon.Either<OpenTagToken, DeserializationError>(
      null,
      namespaceError
    );
  }

  return new AasCommon.Either<OpenTagToken, DeserializationError>(token, null);
}

/**
 * Parse the content of the XML element which the caller has opened, and consume
 * the corresponding closing element named `localName`.
 *
 * This is the one thing which every value of an XML element has in common,
 * whatever it holds: the property loop of a class calls it directly, since
 * it has already read the opening tag and switched on its local name, and
 * `parseNamedElement` calls it after reading an opening tag of its own.
 *
 * A property loop assigns *both* halves of the result -- the value as well as
 * the error -- without looking at either first. The loop returns as soon as
 * the error is set, so the `null` value which comes with an error is never
 * read, and the property's variable needs no guard.
 *
 * @param cursor - to read from
 * @param localName - local name of the element which the caller has opened
 * @param parseContent - parses the content of the element
 * @returns parsed value, or an error
 * @typeParam T - type of the parsed value
 */
function parseElementContent<T>(
  cursor: XmlCursor,
  localName: string,
  parseContent: ContentParser<T>
): AasCommon.Either<T, DeserializationError> {
  const parsedOrError = parseContent(cursor);
  if (parsedOrError.error !== null) {
    return parsedOrError;
  }

  const closeError = consumeCloseTag(cursor, localName);
  if (closeError !== null) {
    return new AasCommon.Either<T, DeserializationError>(null, closeError);
  }

  return parsedOrError;
}

/**
 * Read the next XML element from `cursor`, expecting it to be named
 * `expectedLocalName`, parse its content with `parseContent` and consume
 * the matching closing element.
 *
 * This is what an item of a list or of a tuple is parsed with -- a scalar item
 * in an element tagged `"v"`, `"v1"`, `"v2"`, *etc.*, and an item whose concrete
 * class is statically known in an element named after that class. Rejecting
 * an unexpected element on its local name alone spares us parsing its full
 * (possibly deeply nested) content only to discover the mismatch afterwards.
 *
 * @param cursor - to read from
 * @param expectedLocalName - the expected local name of the element
 * @param parseContent - parses the content of the element
 * @returns parsed value, or an error
 * @typeParam T - type of the parsed value
 */
function parseNamedElement<T>(
  cursor: XmlCursor,
  expectedLocalName: string,
  parseContent: ContentParser<T>
): AasCommon.Either<T, DeserializationError> {
  const startTagOrError = readNextOpenTag(cursor);
  if (startTagOrError.error !== null) {
    return new AasCommon.Either<T, DeserializationError>(
      null,
      startTagOrError.error
    );
  }
  const startTag = startTagOrError.mustValue();

  const observedLocalName = localNameOfTag(startTag.tag);
  if (observedLocalName !== expectedLocalName) {
    return newDeserializationError<T>(
      `Expected the element '${expectedLocalName}', ` +
        `but got '${observedLocalName}'`
    );
  }

  cursor.advance();

  return parseElementContent(cursor, expectedLocalName, parseContent);
}

/**
 * Parse a sequence of list items from `cursor`, stopping (without consuming)
 * at the first closing element.
 *
 * The caller is expected to read and verify the property's own closing
 * element afterwards.
 *
 * @param cursor - to read from
 * @param parseItem - parses a single list item
 * @returns the parsed items, or an error
 * @typeParam T - type of a single list item
 */
function parseList<T>(
  cursor: XmlCursor,
  parseItem: ContentParser<T>
): AasCommon.Either<Array<T>, DeserializationError> {
  const items = new Array<T>();
  let itemIndex = 0;

  cursor.skipIgnorable();
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const maybeClose = cursor.current();
    if (maybeClose === null) {
      return newDeserializationError<Array<T>>(
        "Expected an XML element corresponding to a list item " +
          "or property closing element, but got end of token stream"
      );
    }

    if (maybeClose instanceof CloseTagToken) {
      break;
    }

    const itemOrError = parseItem(cursor);
    if (itemOrError.error !== null) {
      itemOrError.error.path.prepend(new IndexSegment(itemIndex));
      return new AasCommon.Either<Array<T>, DeserializationError>(
        null,
        itemOrError.error
      );
    }

    items.push(itemOrError.mustValue());
    itemIndex++;
    cursor.skipIgnorable();
  }

  return new AasCommon.Either<Array<T>, DeserializationError>(items, null);
}

/**
 * Cursor over parsed XML SAX tokens.
 */
class XmlCursor {
  private readonly _tokens: Array<XmlAnyToken>;
  private _index = 0;

  constructor(tokens: Array<XmlAnyToken>) {
    this._tokens = tokens;
  }

  current(): XmlAnyToken | null {
    if (this._index >= this._tokens.length) {
      return null;
    }
    return this._tokens[this._index];
  }

  advance(): void {
    if (this._index < this._tokens.length) {
      this._index++;
    }
  }

  skipIgnorable(): void {
    // eslint-disable-next-line no-constant-condition
    while (true) {
      const token = this.current();
      if (token === null) {
        break;
      }

      if (token instanceof CommentToken) {
        this.advance();
        continue;
      }

      if (token instanceof TextToken || token instanceof CdataToken) {
        if (token.text.trim().length === 0) {
          this.advance();
          continue;
        }
      }

      break;
    }
  }
}

function tokenizeXml(
  xml: string
): AasCommon.Either<Array<XmlAnyToken>, DeserializationError> {
  const parser = new XmlSaxParser({ allowDoctype: false, xmlns: true });
  const tokens = new Array<XmlAnyToken>();

  try {
    for (const token of parser.feed(xml)) {
      tokens.push(token);
    }
    for (const token of parser.close()) {
      if (!(token instanceof EndToken)) {
        tokens.push(token);
      }
    }
  } catch (error) {
    return newDeserializationError<Array<XmlAnyToken>>(
      `Failed to parse XML: ${error}`
    );
  }

  return new AasCommon.Either<Array<XmlAnyToken>, DeserializationError>(
    tokens,
    null
  );
}

function readRequiredRootOpenTag(
  cursor: XmlCursor
): AasCommon.Either<OpenTagToken, DeserializationError> {
  cursor.skipIgnorable();

  const token = cursor.current();
  if (token === null) {
    return newDeserializationError<OpenTagToken>(
      "Expected a root XML element, but got an empty token stream"
    );
  }

  if (!(token instanceof OpenTagToken)) {
    return newDeserializationError<OpenTagToken>(
      `Expected a root XML start element, but got token kind: ${token.kind}`
    );
  }

  const namespaceError = checkExpectedOpenTagNamespace(token);
  if (namespaceError !== null) {
    return new AasCommon.Either<OpenTagToken, DeserializationError>(
      null,
      namespaceError
    );
  }

  cursor.advance();

  return new AasCommon.Either<OpenTagToken, DeserializationError>(
    token,
    null
  );
}

/**
 * Consume the text (or CDATA) content at `cursor`, if any.
 *
 * The caller is responsible for reading and verifying the closing element
 * afterwards.
 */
function parseTextContent(cursor: XmlCursor): string {
  cursor.skipIgnorable();

  let text = "";
  const maybeText = cursor.current();
  if (maybeText instanceof TextToken || maybeText instanceof CdataToken) {
    text = maybeText.text;
    cursor.advance();
    cursor.skipIgnorable();
  }

  return text;
}

/**
 * Read the next XML element from `cursor` and parse it with the parser which
 * `parsersByLocalName` gives for the element's local name.
 *
 * An abstract class, a concrete class with descendants and a named union all
 * prescribe no element tag of their own, so the tag is what tells us which
 * parser to use. The set of local names which are accepted is the only thing
 * which distinguishes one such dispatch from another, so it is the only thing
 * which is generated -- the reading itself lives here.
 *
 * @param cursor - to read from
 * @param expectedWhat - what we expected to read, for the error message
 * @param parsersByLocalName - parser of the content, by the element's local name
 * @returns parsed instance, or an error
 * @typeParam T - type of the parsed instance
 */
function dispatchParseElement<T>(
  cursor: XmlCursor,
  expectedWhat: string,
  parsersByLocalName: ReadonlyMap<string, ContentParser<T>>
): AasCommon.Either<T, DeserializationError> {
  const startTagOrError = readNextOpenTag(cursor);
  if (startTagOrError.error !== null) {
    return new AasCommon.Either<T, DeserializationError>(
      null,
      startTagOrError.error
    );
  }

  const localName = localNameOfTag(startTagOrError.mustValue().tag);

  const parseContent = parsersByLocalName.get(localName);
  if (parseContent === undefined) {
    return newDeserializationError<T>(
      `Expected an instance of ${expectedWhat}, but got: ${localName}`
    );
  }

  cursor.advance();

  return parseElementContent(cursor, localName, parseContent);
}

/**
 * Report that the property `localName` occurred more than once.
 *
 * The check itself sits in the property loop, right in front of the parse, since
 * only the loop knows whether the property's variable has been set already. This
 * is only the error, so that the message is written once instead of at every one
 * of the property cases.
 */
function duplicatePropertyError(localName: string): DeserializationError {
  return new DeserializationError(
    "Property " + localName + " occurred more than once"
  );
}

function parseBooleanContent(
  cursor: XmlCursor
): AasCommon.Either<boolean, DeserializationError> {
  const text = parseTextContent(cursor);

  if (text === "true" || text === "1") {
    return new AasCommon.Either<boolean, DeserializationError>(true, null);
  }
  if (text === "false" || text === "0") {
    return new AasCommon.Either<boolean, DeserializationError>(false, null);
  }

  return newDeserializationError<boolean>(
    `Expected xs:boolean text, but got: ${text}`
  );
}

function parseIntegerContent(
  cursor: XmlCursor
): AasCommon.Either<number, DeserializationError> {
  const text = parseTextContent(cursor);

  if (!/^[+-]?\d+$/.test(text)) {
    return newDeserializationError<number>(
      `Expected integer text, but got: ${text}`
    );
  }

  const value = Number(text);
  if (!Number.isInteger(value)) {
    return newDeserializationError<number>(
      `Expected integer text, but got: ${text}`
    );
  }

  return new AasCommon.Either<number, DeserializationError>(value, null);
}

function parseFloatContent(
  cursor: XmlCursor
): AasCommon.Either<number, DeserializationError> {
  const text = parseTextContent(cursor);

  if (text === "INF") {
    return new AasCommon.Either<number, DeserializationError>(Infinity, null);
  }
  if (text === "-INF") {
    return new AasCommon.Either<number, DeserializationError>(-Infinity, null);
  }
  if (text === "NaN") {
    return new AasCommon.Either<number, DeserializationError>(NaN, null);
  }

  const value = Number(text);
  if (Number.isNaN(value)) {
    return newDeserializationError<number>(
      `Expected xs:double text, but got: ${text}`
    );
  }

  return new AasCommon.Either<number, DeserializationError>(value, null);
}

function parseStringContent(
  cursor: XmlCursor
): AasCommon.Either<string, DeserializationError> {
  return new AasCommon.Either<string, DeserializationError>(
    parseTextContent(cursor),
    null
  );
}

function parseBase64EncodedBytesContent(
  cursor: XmlCursor
): AasCommon.Either<Uint8Array, DeserializationError> {
  const decodedOrError = AasCommon.base64Decode(parseTextContent(cursor));
  if (decodedOrError.error !== null) {
    return newDeserializationError<Uint8Array>(
      decodedOrError.error
    );
  }

  return new AasCommon.Either<Uint8Array, DeserializationError>(
    decodedOrError.mustValue(),
    null
  );
}

/**
 * Parse the sequence of properties of an instance
 * of {@link types!Branch}.
 *
 * The opening tag is expected to have been already read by the caller, and
 * the caller is expected to read and verify the corresponding closing tag
 * after this function returns successfully. This is the contract of
 * a `ContentParser`, so this function is used as one wherever an instance
 * of {@link types!Branch} is embedded.
 */
function parseBranchFromSequence(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.Branch, DeserializationError> {
  let theIdentifier: string | null = null;
  let theDescription: string | null = null;

  const className = AasTypes.Branch.name;

  cursor.skipIgnorable();
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const nextTagOrError = nextPropertyOpenTag(cursor, className);
    if (nextTagOrError === null) {
      break;
    }
    if (nextTagOrError instanceof DeserializationError) {
      return new AasCommon.Either<AasTypes.Branch, DeserializationError>(
        null,
        nextTagOrError
      );
    }

    const propertyLocalName = localNameOfTag(nextTagOrError.tag);

    let propertyError: DeserializationError | null = null;
    switch (propertyLocalName) {
      case "identifier": {
        if (theIdentifier !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, parseStringContent);
        propertyError = parsed.error;
        theIdentifier = parsed.value;
        break;
      }

      case "description": {
        if (theDescription !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, parseStringContent);
        propertyError = parsed.error;
        theDescription = parsed.value;
        break;
      }

      default: {
        propertyError = new DeserializationError(
          `Unexpected XML property: ${propertyLocalName}`
        );
        break;
      }
    }

    if (propertyError !== null) {
      propertyError.path.prepend(new NameSegment(propertyLocalName));
      return new AasCommon.Either<AasTypes.Branch, DeserializationError>(
        null,
        propertyError
      );
    }

    cursor.skipIgnorable();
  }

  if (theIdentifier === null) {
    return newDeserializationError<AasTypes.Branch>(
      "The required property 'identifier' is missing"
    );
  }

  if (theDescription === null) {
    return newDeserializationError<AasTypes.Branch>(
      "The required property 'description' is missing"
    );
  }

  const instance = new AasTypes.Branch(
    theIdentifier,
    theDescription
  );
  return new AasCommon.Either<AasTypes.Branch, DeserializationError>(
    instance,
    null
  );
}

/**
 * Parse the sequence of properties of an instance
 * of {@link types!Leaf}.
 *
 * The opening tag is expected to have been already read by the caller, and
 * the caller is expected to read and verify the corresponding closing tag
 * after this function returns successfully. This is the contract of
 * a `ContentParser`, so this function is used as one wherever an instance
 * of {@link types!Leaf} is embedded.
 */
function parseLeafFromSequence(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.Leaf, DeserializationError> {
  let theIdentifier: string | null = null;
  let theDescription: string | null = null;
  let theValue: number | null = null;

  const className = AasTypes.Leaf.name;

  cursor.skipIgnorable();
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const nextTagOrError = nextPropertyOpenTag(cursor, className);
    if (nextTagOrError === null) {
      break;
    }
    if (nextTagOrError instanceof DeserializationError) {
      return new AasCommon.Either<AasTypes.Leaf, DeserializationError>(
        null,
        nextTagOrError
      );
    }

    const propertyLocalName = localNameOfTag(nextTagOrError.tag);

    let propertyError: DeserializationError | null = null;
    switch (propertyLocalName) {
      case "identifier": {
        if (theIdentifier !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, parseStringContent);
        propertyError = parsed.error;
        theIdentifier = parsed.value;
        break;
      }

      case "description": {
        if (theDescription !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, parseStringContent);
        propertyError = parsed.error;
        theDescription = parsed.value;
        break;
      }

      case "value": {
        if (theValue !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, parseIntegerContent);
        propertyError = parsed.error;
        theValue = parsed.value;
        break;
      }

      default: {
        propertyError = new DeserializationError(
          `Unexpected XML property: ${propertyLocalName}`
        );
        break;
      }
    }

    if (propertyError !== null) {
      propertyError.path.prepend(new NameSegment(propertyLocalName));
      return new AasCommon.Either<AasTypes.Leaf, DeserializationError>(
        null,
        propertyError
      );
    }

    cursor.skipIgnorable();
  }

  if (theIdentifier === null) {
    return newDeserializationError<AasTypes.Leaf>(
      "The required property 'identifier' is missing"
    );
  }

  if (theDescription === null) {
    return newDeserializationError<AasTypes.Leaf>(
      "The required property 'description' is missing"
    );
  }

  if (theValue === null) {
    return newDeserializationError<AasTypes.Leaf>(
      "The required property 'value' is missing"
    );
  }

  const instance = new AasTypes.Leaf(
    theIdentifier,
    theDescription,
    theValue
  );
  return new AasCommon.Either<AasTypes.Leaf, DeserializationError>(
    instance,
    null
  );
}

/**
 * Parse the sequence of properties of an instance
 * of {@link types!Blossom}.
 *
 * The opening tag is expected to have been already read by the caller, and
 * the caller is expected to read and verify the corresponding closing tag
 * after this function returns successfully. This is the contract of
 * a `ContentParser`, so this function is used as one wherever an instance
 * of {@link types!Blossom} is embedded.
 */
function parseBlossomFromSequence(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.Blossom, DeserializationError> {
  let theIdentifier: string | null = null;
  let theDescription: string | null = null;
  let theValue: number | null = null;
  let theDetails: string | null = null;

  const className = AasTypes.Blossom.name;

  cursor.skipIgnorable();
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const nextTagOrError = nextPropertyOpenTag(cursor, className);
    if (nextTagOrError === null) {
      break;
    }
    if (nextTagOrError instanceof DeserializationError) {
      return new AasCommon.Either<AasTypes.Blossom, DeserializationError>(
        null,
        nextTagOrError
      );
    }

    const propertyLocalName = localNameOfTag(nextTagOrError.tag);

    let propertyError: DeserializationError | null = null;
    switch (propertyLocalName) {
      case "identifier": {
        if (theIdentifier !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, parseStringContent);
        propertyError = parsed.error;
        theIdentifier = parsed.value;
        break;
      }

      case "description": {
        if (theDescription !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, parseStringContent);
        propertyError = parsed.error;
        theDescription = parsed.value;
        break;
      }

      case "value": {
        if (theValue !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, parseIntegerContent);
        propertyError = parsed.error;
        theValue = parsed.value;
        break;
      }

      case "details": {
        if (theDetails !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, parseStringContent);
        propertyError = parsed.error;
        theDetails = parsed.value;
        break;
      }

      default: {
        propertyError = new DeserializationError(
          `Unexpected XML property: ${propertyLocalName}`
        );
        break;
      }
    }

    if (propertyError !== null) {
      propertyError.path.prepend(new NameSegment(propertyLocalName));
      return new AasCommon.Either<AasTypes.Blossom, DeserializationError>(
        null,
        propertyError
      );
    }

    cursor.skipIgnorable();
  }

  if (theIdentifier === null) {
    return newDeserializationError<AasTypes.Blossom>(
      "The required property 'identifier' is missing"
    );
  }

  if (theDescription === null) {
    return newDeserializationError<AasTypes.Blossom>(
      "The required property 'description' is missing"
    );
  }

  if (theValue === null) {
    return newDeserializationError<AasTypes.Blossom>(
      "The required property 'value' is missing"
    );
  }

  if (theDetails === null) {
    return newDeserializationError<AasTypes.Blossom>(
      "The required property 'details' is missing"
    );
  }

  const instance = new AasTypes.Blossom(
    theIdentifier,
    theDescription,
    theValue,
    theDetails
  );
  return new AasCommon.Either<AasTypes.Blossom, DeserializationError>(
    instance,
    null
  );
}

/**
 * Parse the sequence of properties of an instance
 * of {@link types!Something}.
 *
 * The opening tag is expected to have been already read by the caller, and
 * the caller is expected to read and verify the corresponding closing tag
 * after this function returns successfully. This is the contract of
 * a `ContentParser`, so this function is used as one wherever an instance
 * of {@link types!Something} is embedded.
 */
function parseSomethingFromSequence(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.Something, DeserializationError> {
  let theSomeChoice: AasTypes.INode | null = null;
  let theSomethingWithoutChoice: AasTypes.Branch | null = null;

  const className = AasTypes.Something.name;

  cursor.skipIgnorable();
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const nextTagOrError = nextPropertyOpenTag(cursor, className);
    if (nextTagOrError === null) {
      break;
    }
    if (nextTagOrError instanceof DeserializationError) {
      return new AasCommon.Either<AasTypes.Something, DeserializationError>(
        null,
        nextTagOrError
      );
    }

    const propertyLocalName = localNameOfTag(nextTagOrError.tag);

    let propertyError: DeserializationError | null = null;
    switch (propertyLocalName) {
      case "someChoice": {
        if (theSomeChoice !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, dispatchParseNodeElement);
        propertyError = parsed.error;
        theSomeChoice = parsed.value;
        break;
      }

      case "somethingWithoutChoice": {
        if (theSomethingWithoutChoice !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, dispatchParseBranchElement);
        propertyError = parsed.error;
        theSomethingWithoutChoice = parsed.value;
        break;
      }

      default: {
        propertyError = new DeserializationError(
          `Unexpected XML property: ${propertyLocalName}`
        );
        break;
      }
    }

    if (propertyError !== null) {
      propertyError.path.prepend(new NameSegment(propertyLocalName));
      return new AasCommon.Either<AasTypes.Something, DeserializationError>(
        null,
        propertyError
      );
    }

    cursor.skipIgnorable();
  }

  if (theSomeChoice === null) {
    return newDeserializationError<AasTypes.Something>(
      "The required property 'someChoice' is missing"
    );
  }

  if (theSomethingWithoutChoice === null) {
    return newDeserializationError<AasTypes.Something>(
      "The required property 'somethingWithoutChoice' is missing"
    );
  }

  const instance = new AasTypes.Something(
    theSomeChoice,
    theSomethingWithoutChoice
  );
  return new AasCommon.Either<AasTypes.Something, DeserializationError>(
    instance,
    null
  );
}

/**
 * Parse the sequence of properties of an instance
 * of {@link types!Container}.
 *
 * The opening tag is expected to have been already read by the caller, and
 * the caller is expected to read and verify the corresponding closing tag
 * after this function returns successfully. This is the contract of
 * a `ContentParser`, so this function is used as one wherever an instance
 * of {@link types!Container} is embedded.
 */
function parseContainerFromSequence(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.Container, DeserializationError> {
  let theNode: AasTypes.INode | null = null;
  let theSomething: AasTypes.Something | null = null;

  const className = AasTypes.Container.name;

  cursor.skipIgnorable();
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const nextTagOrError = nextPropertyOpenTag(cursor, className);
    if (nextTagOrError === null) {
      break;
    }
    if (nextTagOrError instanceof DeserializationError) {
      return new AasCommon.Either<AasTypes.Container, DeserializationError>(
        null,
        nextTagOrError
      );
    }

    const propertyLocalName = localNameOfTag(nextTagOrError.tag);

    let propertyError: DeserializationError | null = null;
    switch (propertyLocalName) {
      case "node": {
        if (theNode !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, dispatchParseNodeElement);
        propertyError = parsed.error;
        theNode = parsed.value;
        break;
      }

      case "something": {
        if (theSomething !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, parseSomethingFromSequence);
        propertyError = parsed.error;
        theSomething = parsed.value;
        break;
      }

      default: {
        propertyError = new DeserializationError(
          `Unexpected XML property: ${propertyLocalName}`
        );
        break;
      }
    }

    if (propertyError !== null) {
      propertyError.path.prepend(new NameSegment(propertyLocalName));
      return new AasCommon.Either<AasTypes.Container, DeserializationError>(
        null,
        propertyError
      );
    }

    cursor.skipIgnorable();
  }

  if (theNode === null) {
    return newDeserializationError<AasTypes.Container>(
      "The required property 'node' is missing"
    );
  }

  if (theSomething === null) {
    return newDeserializationError<AasTypes.Container>(
      "The required property 'something' is missing"
    );
  }

  const instance = new AasTypes.Container(
    theNode,
    theSomething
  );
  return new AasCommon.Either<AasTypes.Container, DeserializationError>(
    instance,
    null
  );
}

const PARSERS_OF_NODE = new Map<
  string,
  ContentParser<AasTypes.INode>
>([
  ["branch", parseBranchFromSequence],
  ["leaf", parseLeafFromSequence],
  ["blossom", parseBlossomFromSequence]
]);

/**
 * Dispatch-parse an instance
 * of {@link types!INode} from the next
 * XML element in `cursor`, based on the element's local name.
 *
 * @param cursor - to read from
 * @returns the parsed instance, or an error
 */
function dispatchParseNodeElement(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.INode, DeserializationError> {
  return dispatchParseElement(cursor, "INode", PARSERS_OF_NODE);
}

/**
 * Parse an XML string as an instance
 * of {@link types!INode}.
 *
 * @param xml - XML string to parse
 * @returns parsed instance, or an error
 */
export function nodeFromXmlString(
  xml: string
): AasCommon.Either<AasTypes.INode, DeserializationError> {
  if (xml.length === 0) {
    return newDeserializationError<AasTypes.INode>(
      "Expected an XML document, but got an empty string"
    );
  }

  const tokensOrError = tokenizeXml(xml);
  if (tokensOrError.error !== null) {
    return new AasCommon.Either<AasTypes.INode, DeserializationError>(
      null,
      tokensOrError.error
    );
  }

  const cursor = new XmlCursor(tokensOrError.mustValue());

  const instanceOrError = dispatchParseNodeElement(cursor);
  if (instanceOrError.error !== null) {
    return instanceOrError;
  }

  cursor.skipIgnorable();
  if (cursor.current() !== null) {
    return newDeserializationError<AasTypes.INode>(
      "Expected no tokens after the root XML element, but got token kind: " +
        currentTokenKind(cursor)
    );
  }

  return instanceOrError;
}

const PARSERS_OF_BRANCH = new Map<
  string,
  ContentParser<AasTypes.Branch>
>([
  ["leaf", parseLeafFromSequence],
  ["blossom", parseBlossomFromSequence],
  ["branch", parseBranchFromSequence]
]);

/**
 * Dispatch-parse an instance
 * of {@link types!Branch} from the next
 * XML element in `cursor`, based on the element's local name.
 *
 * @param cursor - to read from
 * @returns the parsed instance, or an error
 */
function dispatchParseBranchElement(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.Branch, DeserializationError> {
  return dispatchParseElement(cursor, "Branch", PARSERS_OF_BRANCH);
}

/**
 * Parse an XML string as an instance
 * of {@link types!Branch}.
 *
 * @param xml - XML string to parse
 * @returns parsed instance, or an error
 */
export function branchFromXmlString(
  xml: string
): AasCommon.Either<AasTypes.Branch, DeserializationError> {
  if (xml.length === 0) {
    return newDeserializationError<AasTypes.Branch>(
      "Expected an XML document, but got an empty string"
    );
  }

  const tokensOrError = tokenizeXml(xml);
  if (tokensOrError.error !== null) {
    return new AasCommon.Either<AasTypes.Branch, DeserializationError>(
      null,
      tokensOrError.error
    );
  }

  const cursor = new XmlCursor(tokensOrError.mustValue());

  const instanceOrError = dispatchParseBranchElement(cursor);
  if (instanceOrError.error !== null) {
    return instanceOrError;
  }

  cursor.skipIgnorable();
  if (cursor.current() !== null) {
    return newDeserializationError<AasTypes.Branch>(
      "Expected no tokens after the root XML element, but got token kind: " +
        currentTokenKind(cursor)
    );
  }

  return instanceOrError;
}

const PARSERS_OF_LEAF = new Map<
  string,
  ContentParser<AasTypes.Leaf>
>([
  ["blossom", parseBlossomFromSequence],
  ["leaf", parseLeafFromSequence]
]);

/**
 * Dispatch-parse an instance
 * of {@link types!Leaf} from the next
 * XML element in `cursor`, based on the element's local name.
 *
 * @param cursor - to read from
 * @returns the parsed instance, or an error
 */
function dispatchParseLeafElement(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.Leaf, DeserializationError> {
  return dispatchParseElement(cursor, "Leaf", PARSERS_OF_LEAF);
}

/**
 * Parse an XML string as an instance
 * of {@link types!Leaf}.
 *
 * @param xml - XML string to parse
 * @returns parsed instance, or an error
 */
export function leafFromXmlString(
  xml: string
): AasCommon.Either<AasTypes.Leaf, DeserializationError> {
  if (xml.length === 0) {
    return newDeserializationError<AasTypes.Leaf>(
      "Expected an XML document, but got an empty string"
    );
  }

  const tokensOrError = tokenizeXml(xml);
  if (tokensOrError.error !== null) {
    return new AasCommon.Either<AasTypes.Leaf, DeserializationError>(
      null,
      tokensOrError.error
    );
  }

  const cursor = new XmlCursor(tokensOrError.mustValue());

  const instanceOrError = dispatchParseLeafElement(cursor);
  if (instanceOrError.error !== null) {
    return instanceOrError;
  }

  cursor.skipIgnorable();
  if (cursor.current() !== null) {
    return newDeserializationError<AasTypes.Leaf>(
      "Expected no tokens after the root XML element, but got token kind: " +
        currentTokenKind(cursor)
    );
  }

  return instanceOrError;
}

const ROOT_DISPATCH_BY_LOCAL_NAME = new Map<
  string,
  ContentParser<AasTypes.Class>
>([
  ["branch", parseBranchFromSequence],
  ["leaf", parseLeafFromSequence],
  ["blossom", parseBlossomFromSequence],
  ["something", parseSomethingFromSequence],
  ["container", parseContainerFromSequence]
]);

/**
 * Parse an XML string as an AAS instance.
 *
 * @param xml - XML string to parse
 * @returns parsed AAS instance or an error
 */
export function fromXmlString(
  xml: string
): AasCommon.Either<AasTypes.Class, DeserializationError> {
  if (xml.length === 0) {
    return newDeserializationError<AasTypes.Class>(
      "Expected an XML document, but got an empty string"
    );
  }

  const tokensOrError = tokenizeXml(xml);
  if (tokensOrError.error !== null) {
    return new AasCommon.Either<AasTypes.Class, DeserializationError>(
      null,
      tokensOrError.error
    );
  }

  const cursor = new XmlCursor(tokensOrError.mustValue());

  const rootOpenTagOrError = readRequiredRootOpenTag(cursor);
  if (rootOpenTagOrError.error !== null) {
    return new AasCommon.Either<AasTypes.Class, DeserializationError>(
      null,
      rootOpenTagOrError.error
    );
  }

  const rootOpenTag = rootOpenTagOrError.mustValue();
  const rootLocalName = localNameOfTag(rootOpenTag.tag);

  const dispatch = ROOT_DISPATCH_BY_LOCAL_NAME.get(rootLocalName);
  if (dispatch === undefined) {
    return newDeserializationError<AasTypes.Class>(
      `Unexpected root XML element: ${rootLocalName}`
    );
  }

  const instanceOrError = dispatch(cursor);
  if (instanceOrError.error !== null) {
    return instanceOrError;
  }

  const closeError = consumeCloseTag(cursor, rootLocalName);
  if (closeError !== null) {
    return new AasCommon.Either<AasTypes.Class, DeserializationError>(
      null,
      closeError
    );
  }

  cursor.skipIgnorable();
  if (cursor.current() !== null) {
    return newDeserializationError<AasTypes.Class>(
      "Expected no tokens after the root XML element, but got token kind: " +
        currentTokenKind(cursor)
    );
  }

  return instanceOrError;
}

type SerializedElement = {
  localName: string;
  innerXml: string;
};

function openTag(localName: string, withNamespace = false): string {
  if (withNamespace) {
    return `<${localName} xmlns="${NAMESPACE}">`;
  }

  return `<${localName}>`;
}

function closeTag(localName: string): string {
  return `</${localName}>`;
}

/**
 * Push `content` wrapped in its own `localName` element onto `parts`.
 *
 * We push the opening tag, the content and the closing tag as three separate
 * entries instead of pre-concatenating them, so that ``parts.join("")`` at
 * the top level copies the (possibly large, deeply nested) `content` exactly
 * once.
 */
function writeVElement(
  parts: Array<string>,
  localName: string,
  content: string
): void {
  parts.push(openTag(localName));
  parts.push(content);
  parts.push(closeTag(localName));
}

/**
 * Push a class instance already serialized to XML parts onto `parts`, wrapped
 * in its own element as given by {@link SerializedElement.localName}.
 */
function writeClassElement(
  parts: Array<string>,
  serialized: SerializedElement
): void {
  parts.push(openTag(serialized.localName));
  parts.push(serialized.innerXml);
  parts.push(closeTag(serialized.localName));
}

function escapeXmlText(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function serializeBooleanText(value: boolean): string {
  return value ? "true" : "false";
}

function serializeIntegerText(value: number): string {
  if (!Number.isInteger(value)) {
    throw new Error(`Expected an integer, but got: ${value}`);
  }

  return `${value}`;
}

function serializeFloatText(value: number): string {
  if (Number.isNaN(value)) {
    return "NaN";
  }
  if (value === Infinity) {
    return "INF";
  }
  if (value === -Infinity) {
    return "-INF";
  }

  return `${value}`;
}

function serializeStringText(value: string): string {
  return escapeXmlText(value);
}

function serializeBase64EncodedBytesText(value: Uint8Array): string {
  return escapeXmlText(AasCommon.base64Encode(value));
}

/**
 * Serialize an AAS instance to XML parts.
 */
class Serializer extends AasTypes.AbstractTransformer<SerializedElement> {


/**
   * Serialize `that` to an XML element representation.
   *
   * @param that - instance to be serialized
   * @returns serialized XML element representation
   */
  transformBranch(
    that: AasTypes.Branch
  ): SerializedElement {
  const parts = new Array<string>();

  writeVElement(parts, "identifier", serializeStringText(that.identifier));

  writeVElement(parts, "description", serializeStringText(that.description));

  return {
      localName: "branch",
      innerXml: parts.join("")
    };
  }

/**
   * Serialize `that` to an XML element representation.
   *
   * @param that - instance to be serialized
   * @returns serialized XML element representation
   */
  transformLeaf(
    that: AasTypes.Leaf
  ): SerializedElement {
  const parts = new Array<string>();

  writeVElement(parts, "identifier", serializeStringText(that.identifier));

  writeVElement(parts, "description", serializeStringText(that.description));

  writeVElement(parts, "value", serializeIntegerText(that.value));

  return {
      localName: "leaf",
      innerXml: parts.join("")
    };
  }

/**
   * Serialize `that` to an XML element representation.
   *
   * @param that - instance to be serialized
   * @returns serialized XML element representation
   */
  transformBlossom(
    that: AasTypes.Blossom
  ): SerializedElement {
  const parts = new Array<string>();

  writeVElement(parts, "identifier", serializeStringText(that.identifier));

  writeVElement(parts, "description", serializeStringText(that.description));

  writeVElement(parts, "value", serializeIntegerText(that.value));

  writeVElement(parts, "details", serializeStringText(that.details));

  return {
      localName: "blossom",
      innerXml: parts.join("")
    };
  }

/**
   * Serialize `that` to an XML element representation.
   *
   * @param that - instance to be serialized
   * @returns serialized XML element representation
   */
  transformSomething(
    that: AasTypes.Something
  ): SerializedElement {
  const parts = new Array<string>();

  parts.push(openTag("someChoice"));
    writeClassElement(parts, this.transform(that.someChoice));
    parts.push(closeTag("someChoice"));

  parts.push(openTag("somethingWithoutChoice"));
    writeClassElement(parts, this.transform(that.somethingWithoutChoice));
    parts.push(closeTag("somethingWithoutChoice"));

  return {
      localName: "something",
      innerXml: parts.join("")
    };
  }

/**
   * Serialize `that` to an XML element representation.
   *
   * @param that - instance to be serialized
   * @returns serialized XML element representation
   */
  transformContainer(
    that: AasTypes.Container
  ): SerializedElement {
  const parts = new Array<string>();

  parts.push(openTag("node"));
    writeClassElement(parts, this.transform(that.node));
    parts.push(closeTag("node"));

  const serializedSomething = this.transform(that.something);
    parts.push(openTag("something"));
    parts.push(serializedSomething.innerXml);
    parts.push(closeTag("something"));

  return {
      localName: "container",
      innerXml: parts.join("")
    };
  }
}

const SERIALIZER = new Serializer();

/**
 * Serialize an AAS instance as an XML string.
 *
 * @param that - AAS instance to serialize
 * @returns serialized XML string
 */
export function toXmlString(that: AasTypes.Class): string {
  const serialized = SERIALIZER.transform(that);
  const parts = new Array<string>();
  parts.push(openTag(serialized.localName, true));
  parts.push(serialized.innerXml);
  parts.push(closeTag(serialized.localName));
  return parts.join("");
}

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
