// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

#include "dummy/jsonization.hpp"
#include "dummy/stringification.hpp"
#include "dummy/wstringification.hpp"

#pragma warning(push, 0)
#include <cmath>
#include <set>
#include <sstream>
#include <unordered_map>
#pragma warning(pop)

namespace dummy {
namespace jsonization {

// region PropertySegment

PropertySegment::PropertySegment(
  std::wstring a_name
) :
  name(std::move(a_name)) {
  // Intentionally empty.
}

std::wstring PropertySegment::ToWstring() const {
  return common::Concat(
    L".",
    name
  );
}

std::unique_ptr<ISegment> PropertySegment::Clone() const {
  return common::make_unique<PropertySegment>(*this);
}

// endregion PropertySegment

// region IndexSegment

IndexSegment::IndexSegment(
  size_t an_index
) :
  index(an_index) {
  // Intentionally empty.
}

std::wstring IndexSegment::ToWstring() const {
  return common::Concat(
    L"[",
    std::to_wstring(index),
    L"]"
  );
}

std::unique_ptr<ISegment> IndexSegment::Clone() const {
  return common::make_unique<IndexSegment>(*this);
}

// endregion IndexSegment

// region struct Path

Path::Path() {
  // Intentionally empty.
}

Path::Path(const Path& other) {
  for (const std::unique_ptr<ISegment>& segment : other.segments) {
    segments.emplace_back(segment->Clone());
  }
}

Path::Path(Path&& other) {
  segments = std::move(other.segments);
}

Path& Path::operator=(const Path& other) {
  segments.clear();
  for (const std::unique_ptr<ISegment>& segment : other.segments) {
    segments.emplace_back(segment->Clone());
  }
  return *this;
}

Path& Path::operator=(Path&& other) {
  if (this != &other) {
    segments = std::move(other.segments);
  }
  return *this;
}

std::wstring Path::ToWstring() const {
  if (segments.empty()) {
    return L"";
  }

  std::deque<std::wstring> parts;
  for (const std::unique_ptr<ISegment>& segment : segments ) {
    parts.emplace_back(segment->ToWstring());
  }

  size_t out_len = 0;
  for (const std::wstring& part : parts) {
    out_len += part.size();
  }

  std::wstring out;
  out.reserve(out_len);
  for (const std::wstring& part : parts) {
    out.append(part);
  }

  return out;
}

// endregion struct Path

// region De-serialization

// region class DeserializationError

DeserializationError::DeserializationError(
  std::wstring a_cause
) :
  cause(a_cause) {
  // Intentionally empty.
}

DeserializationError::DeserializationError(
  std::wstring a_cause,
  Path a_path
) :
  cause(a_cause),
  path(a_path) {
  // Intentionally empty.
}

// endregion class DeserializationError

std::pair<
  common::optional<bool>,
  common::optional<DeserializationError>
> DeserializeBool(
  const nlohmann::json& json
) {
  if (!json.is_boolean()) {
    std::wstring message = common::Concat(
      L"Expected a boolean, but got a value of type: ",
      common::Utf8ToWstring(json.type_name())
    );

    return std::make_pair<
      common::optional<bool>,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      common::make_optional<DeserializationError>(
        message
      )
    );
  }

  return std::make_pair<
    common::optional<bool>,
    common::optional<DeserializationError>
  >(
    json.get<bool>(),
    common::nullopt
  );
}

std::pair<
  common::optional<int64_t>,
  common::optional<DeserializationError>
> DeserializeInt64(
  const nlohmann::json& json
) {
  if (!json.is_number()) {
    std::wstring message = common::Concat(
      L"Expected an integer number, but got a value of type: ",
      common::Utf8ToWstring(json.type_name())
    );

    return std::make_pair<
      common::optional<int64_t>,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      common::make_optional<DeserializationError>(
        message
      )
    );
  }

  static_assert(
    std::is_same<nlohmann::json::number_integer_t, int64_t>::value,
    "Expected nlohmann::json::number_integer_t to equal int64_t, "
    "but it does not."
  );

  if (json.is_number_integer()) {
    return std::make_pair<
      common::optional<int64_t>,
      common::optional<DeserializationError>
    >(
      json.get<int64_t>(),
      common::nullopt
    );
  }

  if (json.is_number_unsigned()) {
    std::wstring message = common::Concat(
      L"Expected a 64-bit integer number, "
      L"but got an unsigned integer number which does not fit in that range: ",
      std::to_wstring(json.get<nlohmann::json::number_unsigned_t>())
    );

    return std::make_pair<
      common::optional<int64_t>,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      common::make_optional<DeserializationError>(
        message
      )
    );
  }

  // NOTE (mristin):
  // We have to check that the number is an integer even though it can
  // not be stored in int64_t in order to give an informative message.

  const nlohmann::json::number_float_t number(
    json.get<nlohmann::json::number_float_t>()
  );

  nlohmann::json::number_float_t integer_part;
  const bool is_integer(
    std::modf(number, &integer_part) == 0
  );
  if (is_integer) {
    std::wstring message = common::Concat(
      L"Expected a 64-bit integer number, "
      L"but got an integer number which does not fit in that range: ",
      std::to_wstring(number)
    );

    return std::make_pair<
      common::optional<int64_t>,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      common::make_optional<DeserializationError>(
        message
      )
    );
  } else {
    std::wstring message = common::Concat(
      L"Expected a 64-bit integer number, "
      L"but got a non-integer number: ",
      std::to_wstring(number)
    );

    return std::make_pair<
      common::optional<int64_t>,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      common::make_optional<DeserializationError>(
        message
      )
    );
  }
}

std::pair<
  common::optional<double>,
  common::optional<DeserializationError>
> DeserializeDouble(
  const nlohmann::json& json
) {
  if (!json.is_number()) {
    std::wstring message = common::Concat(
      L"Expected a number, but got a value of type: ",
      common::Utf8ToWstring(json.type_name())
    );

    return std::make_pair<
      common::optional<double>,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      common::make_optional<DeserializationError>(
        message
      )
    );
  }

  static_assert(
    std::is_same<nlohmann::json::number_float_t, double>::value,
    "Expected nlohmann::json::number_float_t to equal double, "
    "but it does not."
  );

  const double value(json.get<double>());

  // NOTE (mristin):
  // JSON knows neither an infinity nor a not-a-number, so a conformant parser
  // can never give us one. The caller can still hand us a JSON value which
  // has been constructed programmatically, so we have to check here.

  if (!std::isfinite(value)) {
    std::wstring message = common::Concat(
      L"Expected a finite number, but got: ",
      std::to_wstring(value)
    );

    return std::make_pair<
      common::optional<double>,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      common::make_optional<DeserializationError>(
        message
      )
    );
  }

  return std::make_pair<
    common::optional<double>,
    common::optional<DeserializationError>
  >(
    value,
    common::nullopt
  );
}

std::pair<
  common::optional<std::wstring>,
  common::optional<DeserializationError>
> DeserializeWstring(
  const nlohmann::json& json
) {
  if (!json.is_string()) {
    std::wstring message = common::Concat(
      L"Expected a string, but got a value of type: ",
      common::Utf8ToWstring(json.type_name())
    );

    return std::make_pair<
      common::optional<std::wstring>,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      common::make_optional<DeserializationError>(
        message
      )
    );
  }

  return std::make_pair<
    common::optional<std::wstring>,
    common::optional<DeserializationError>
  >(
    common::Utf8ToWstring(*(json.get_ptr<const std::string*>())),
    common::nullopt
  );
}

std::pair<
  common::optional<std::vector<std::uint8_t> >,
  common::optional<DeserializationError>
> DeserializeByteArray(
  const nlohmann::json& json
) {
  if (!json.is_string()) {
    std::wstring message = common::Concat(
      L"Expected a base64-encoded byte array as a string, "
      L"but got a value of type: ",
      common::Utf8ToWstring(json.type_name())
    );;

    return std::make_pair<
      common::optional<std::vector<std::uint8_t> >,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      common::make_optional<DeserializationError>(
        message
      )
    );
  }

  common::expected<
    std::vector<std::uint8_t>,
    std::string
  > bytes = stringification::Base64Decode(
    *(json.get_ptr<const std::string*>())
  );

  if (!bytes.has_value()) {
    std::wstring message = common::Concat(
      L"Failed to base64-decode the bytes from a string: ",
      common::Utf8ToWstring(bytes.error())
    );

    return std::make_pair<
      common::optional<std::vector<std::uint8_t> >,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      common::make_optional<DeserializationError>(
        message
      )
    );
  }

  return std::make_pair<
    common::optional<std::vector<std::uint8_t> >,
    common::optional<DeserializationError>
  >(
    std::move(*bytes),
    common::nullopt
  );
}

/**
 * Get the property `modelType` from the JSON value expected as a JSON object.
 */
std::pair<
  const std::string*,
  common::optional<DeserializationError>
> GetModelTypeFrom(
  const nlohmann::json& json
) {
  if (!json.is_object()) {
    std::wstring message = common::Concat(
      L"Expected an object, but got: ",
      common::Utf8ToWstring(json.type_name())
    );

    return std::make_pair<
      const std::string*,
      common::optional<DeserializationError>
    >(
      nullptr,
      common::make_optional<DeserializationError>(
        message
      )
    );
  }

  if (!json.contains("modelType")) {
    return std::make_pair<
      const std::string*,
      common::optional<DeserializationError>
    >(
      nullptr,
      common::make_optional<DeserializationError>(
        L"The required property modelType is missing"
      )
    );
  }

  const nlohmann::json& model_type_prop = json["modelType"];
  if (!model_type_prop.is_string()) {
    std::wstring message = common::Concat(
      L"Expected modelType to be a string, but got: ",
      common::Utf8ToWstring(model_type_prop.type_name())
    );

    common::optional<DeserializationError> error(
      common::make_optional<DeserializationError>(
        message
      )
    );
    error->path.segments.emplace_front(
      common::make_unique<PropertySegment>(
        L"modelType"
      )
    );

    // NOTE (mristin):
    // We have to explicitly use the constructor instead of std::make_pair
    // as `const std::string*` can not be automatically converted to a rvalue.
    return std::pair<
      const std::string*,
      common::optional<DeserializationError>
    >(
      nullptr,
      error
    );
  }

  static_assert(
    std::is_same<nlohmann::json::string_t, std::string>::value,
    "Expected nlohmann::json::string_t to equal std::string, but it does not."
  );

  const std::string* model_type(
    model_type_prop.get_ptr<const std::string*>()
  );

  // NOTE (mristin):
  // We have to explicitly use the constructor instead of std::make_pair
  // as `const std::string*` can not be automatically converted to a rvalue.
  return std::pair<
    const std::string*,
    common::optional<DeserializationError>
  >(
    model_type,
    common::nullopt
  );
}

std::pair<
  common::optional<nlohmann::json>,
  common::optional<DeserializationError>
> DeserializeJsonValue(
  const nlohmann::json& json
) {
  if (json.is_null() || json.is_binary() || json.is_discarded()) {
    return std::make_pair<
      common::optional<nlohmann::json>,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      common::make_optional<DeserializationError>(
        common::Concat(
          L"Expected a JSON-able value (a boolean, a number, a string, "
          L"an array or an object), but got a value of type: ",
          common::Utf8ToWstring(json.type_name())
        )
      )
    );
  }

  if (json.is_array()) {
    nlohmann::json result(nlohmann::json::array());
    result.get_ref<nlohmann::json::array_t&>().reserve(json.size());

    size_t index = 0;
    for (const nlohmann::json& item : json) {
      common::optional<nlohmann::json> deserialized_item;
      common::optional<DeserializationError> error;
      std::tie(deserialized_item, error) = DeserializeJsonValue(item);

      if (error.has_value()) {
        error->path.segments.emplace_front(
          common::make_unique<IndexSegment>(index)
        );

        return std::make_pair(common::nullopt, std::move(error));
      }

      result.push_back(std::move(*deserialized_item));
      ++index;
    }

    return std::make_pair(std::move(result), common::nullopt);
  }

  if (json.is_object()) {
    nlohmann::json result(nlohmann::json::object());

    for (const auto& item : json.items()) {
      common::optional<nlohmann::json> deserialized_value;
      common::optional<DeserializationError> error;
      std::tie(deserialized_value, error) = DeserializeJsonValue(item.value());

      if (error.has_value()) {
        error->path.segments.emplace_front(
          common::make_unique<PropertySegment>(
            common::Utf8ToWstring(item.key())
          )
        );

        return std::make_pair(common::nullopt, std::move(error));
      }

      result[item.key()] = std::move(*deserialized_value);
    }

    return std::make_pair(std::move(result), common::nullopt);
  }

  // NOTE (mristin):
  // JSON knows neither an infinity nor a not-a-number, so we refuse both
  // instead of silently writing them out as ``null``, mirroring
  // ``DeserializeDouble`` for the floating-point properties of the model.
  // The caller gives us an ``nlohmann::json`` which may well have been
  // constructed programmatically, so a non-finite number can reach us
  // even though no conformant parser would ever produce one.
  if (json.is_number_float() && !std::isfinite(json.get<double>())) {
    return std::make_pair<
      common::optional<nlohmann::json>,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      common::make_optional<DeserializationError>(
        common::Concat(
          L"Expected a JSON-able value, but got the number ",
          std::to_wstring(json.get<double>()),
          L", which is neither finite nor representable in JSON"
        )
      )
    );
  }

  // NOTE (mristin):
  // The value is a boolean, a number or a string, all of which are already
  // JSON-able as-is.
  return std::make_pair(json, common::nullopt);
}

std::pair<
  common::optional<nlohmann::json>,
  common::optional<DeserializationError>
> DeserializeJsonArray(
  const nlohmann::json& json
) {
  if (!json.is_array()) {
    return std::make_pair<
      common::optional<nlohmann::json>,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      common::make_optional<DeserializationError>(
        common::Concat(
          L"Expected a JSON array, but got a value of type: ",
          common::Utf8ToWstring(json.type_name())
        )
      )
    );
  }

  return DeserializeJsonValue(json);
}

std::pair<
  common::optional<nlohmann::json>,
  common::optional<DeserializationError>
> DeserializeJsonObject(
  const nlohmann::json& json
) {
  if (!json.is_object()) {
    return std::make_pair<
      common::optional<nlohmann::json>,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      common::make_optional<DeserializationError>(
        common::Concat(
          L"Expected a JSON object, but got a value of type: ",
          common::Utf8ToWstring(json.type_name())
        )
      )
    );
  }

  return DeserializeJsonValue(json);
}

template <typename T, typename DeserializeItemT>
std::pair<
  common::optional<std::vector<T> >,
  common::optional<DeserializationError>
> DeserializeList(
  const nlohmann::json& json,
  DeserializeItemT&& deserialize_item
) {
  if (!json.is_array()) {
    std::wstring message = common::Concat(
      L"Expected an array, but got: ",
      common::Utf8ToWstring(
        json.type_name()
      )
    );

    return std::make_pair<
      common::optional<std::vector<T> >,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      common::make_optional<DeserializationError>(
        message
      )
    );
  }

  common::optional<std::vector<T> > list(
    common::make_optional<std::vector<T> >()
  );

  list->reserve(json.size());

  size_t index = 0;

  for(const nlohmann::json& item : json) {
    common::optional<T> deserialized;
    common::optional<DeserializationError> error;

    std::tie(deserialized, error) = deserialize_item(item);

    if (error.has_value()) {
      error->path.segments.emplace_front(
        common::make_unique<IndexSegment>(
          index
        )
      );

      return std::make_pair<
        common::optional<std::vector<T> >,
        common::optional<DeserializationError>
      >(
        common::nullopt,
        std::move(error)
      );
    }

    list->emplace_back(std::move(*deserialized));

    ++index;
  }

  return std::make_pair(
    list,
    common::nullopt
  );
}

template <
  typename T0,
  typename T1,
  typename T2,
  typename T3,
  typename DeserializeItemT0,
  typename DeserializeItemT1,
  typename DeserializeItemT2,
  typename DeserializeItemT3
>
std::pair<
  common::optional<std::tuple<
    T0,
    T1,
    T2,
    T3
  > >,
  common::optional<DeserializationError>
> DeserializeTuple4(
  const nlohmann::json& json,
  DeserializeItemT0&& deserialize_item0,
  DeserializeItemT1&& deserialize_item1,
  DeserializeItemT2&& deserialize_item2,
  DeserializeItemT3&& deserialize_item3
) {
  if (!json.is_array()) {
    std::wstring message = common::Concat(
      L"Expected an array, but got: ",
      common::Utf8ToWstring(
        json.type_name()
      )
    );

    return std::make_pair<
      common::optional<std::tuple<
        T0,
        T1,
        T2,
        T3
      > >,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      common::make_optional<DeserializationError>(
        message
      )
    );
  }

  if (json.size() != 4) {
    std::wstring message = common::Concat(
      L"Expected exactly 4 item(s) in the array, "
      L"but got: ",
      std::to_wstring(json.size())
    );

    return std::make_pair<
      common::optional<std::tuple<
        T0,
        T1,
        T2,
        T3
      > >,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      common::make_optional<DeserializationError>(
        message
      )
    );
  }

  common::optional<DeserializationError> error;

  common::optional<T0> item0;
  common::optional<T1> item1;
  common::optional<T2> item2;
  common::optional<T3> item3;

  std::tie(
    item0,
    error
  ) = deserialize_item0(
    json[0]
  );

  if (error.has_value()) {
    error->path.segments.emplace_front(
      common::make_unique<IndexSegment>(
        0
      )
    );
    return std::make_pair<
      common::optional<std::tuple<
        T0,
        T1,
        T2,
        T3
      > >,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      std::move(error)
    );
  }

  std::tie(
    item1,
    error
  ) = deserialize_item1(
    json[1]
  );

  if (error.has_value()) {
    error->path.segments.emplace_front(
      common::make_unique<IndexSegment>(
        1
      )
    );
    return std::make_pair<
      common::optional<std::tuple<
        T0,
        T1,
        T2,
        T3
      > >,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      std::move(error)
    );
  }

  std::tie(
    item2,
    error
  ) = deserialize_item2(
    json[2]
  );

  if (error.has_value()) {
    error->path.segments.emplace_front(
      common::make_unique<IndexSegment>(
        2
      )
    );
    return std::make_pair<
      common::optional<std::tuple<
        T0,
        T1,
        T2,
        T3
      > >,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      std::move(error)
    );
  }

  std::tie(
    item3,
    error
  ) = deserialize_item3(
    json[3]
  );

  if (error.has_value()) {
    error->path.segments.emplace_front(
      common::make_unique<IndexSegment>(
        3
      )
    );
    return std::make_pair<
      common::optional<std::tuple<
        T0,
        T1,
        T2,
        T3
      > >,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      std::move(error)
    );
  }

  return std::make_pair(
    common::make_optional<std::tuple<
      T0,
      T1,
      T2,
      T3
    > >(
      std::make_tuple(
        std::move(*item0),
        std::move(*item1),
        std::move(*item2),
        std::move(*item3)
      )
    ),
    common::nullopt
  );
}

/**
 * \brief Deserialize concretely an instance
 * of types::ISomething.
 *
 * \param json value to be de-serialized
 * \param additional_properties if not set, check that \p json contains
 * no additional properties
 * \return the deserialized instance, or an error, if any
 */
std::pair<
  common::optional<
    std::shared_ptr<types::ISomething>
  >,
  common::optional<DeserializationError>
> DeserializeSomething(
  const nlohmann::json& json,
  bool additional_properties
);

std::set<std::string> kPropertiesInSomething = {
  "values",
  "tupleWithJson"
};

std::pair<
  common::optional<
    std::shared_ptr<types::ISomething>
  >,
  common::optional<DeserializationError>
> DeserializeSomething(
  const nlohmann::json& json,
  bool additional_properties
) {
  if (!json.is_object()) {
    std::wstring message = common::Concat(
      L"Expected an object, but got: ",
      common::Utf8ToWstring(json.type_name())
    );

    return std::make_pair<
      common::optional<std::shared_ptr<types::ISomething> >,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      common::make_optional<DeserializationError>(
        message
      )
    );
  }

  if (!additional_properties) {
    for (const auto& key_val : json.items()) {
      auto it(
        kPropertiesInSomething.find(key_val.key())
      );
      if (it == kPropertiesInSomething.end()) {
        std::wstring message = common::Concat(
          L"Unexpected additional property: ",
          common::Utf8ToWstring(key_val.key())
        );

        return std::make_pair<
          common::optional<std::shared_ptr<types::ISomething> >,
          common::optional<DeserializationError>
        >(
          common::nullopt,
          common::make_optional<DeserializationError>(
            message
          )
        );
      }
    }
  }

  // region Check required properties

  if (!json.contains("values")) {
    return std::make_pair<
      common::optional<std::shared_ptr<types::ISomething> >,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      common::make_optional<DeserializationError>(
        L"The required property values is missing"
      )
    );
  }

  if (!json.contains("tupleWithJson")) {
    return std::make_pair<
      common::optional<std::shared_ptr<types::ISomething> >,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      common::make_optional<DeserializationError>(
        L"The required property tupleWithJson is missing"
      )
    );
  }

  // endregion Check required properties

  // region Initialization

  common::optional<DeserializationError> error;

  common::optional<std::vector<nlohmann::json> > the_values;

  common::optional<
    std::tuple<
      std::wstring,
      nlohmann::json,
      nlohmann::json,
      nlohmann::json
    >
  > the_tuple_with_json;

  // endregion Initialization

  // region De-serialize values

  std::tie(
    the_values,
    error
  ) = DeserializeList<nlohmann::json>(
    json["values"],
    DeserializeJsonValue
  );

  if (error.has_value()) {
    error->path.segments.emplace_front(
      common::make_unique<PropertySegment>(
        L"values"
      )
    );

    return std::make_pair<
      common::optional<std::shared_ptr<types::ISomething> >,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      std::move(error)
    );
  }

  // endregion De-serialize values

  // region De-serialize tupleWithJson

  std::tie(
    the_tuple_with_json,
    error
  ) = DeserializeTuple4<
    std::wstring,
    nlohmann::json,
    nlohmann::json,
    nlohmann::json
  >(
    json["tupleWithJson"],
    DeserializeWstring,
    DeserializeJsonValue,
    DeserializeJsonArray,
    DeserializeJsonObject
  );

  if (error.has_value()) {
    error->path.segments.emplace_front(
      common::make_unique<PropertySegment>(
        L"tupleWithJson"
      )
    );

    return std::make_pair<
      common::optional<std::shared_ptr<types::ISomething> >,
      common::optional<DeserializationError>
    >(
      common::nullopt,
      std::move(error)
    );
  }

  // endregion De-serialize tupleWithJson

  return std::make_pair(
    common::make_optional<
      std::shared_ptr<types::ISomething>
    >(
      // NOTE (mristin):
      // We deliberately do not use std::make_shared here to avoid an unnecessary
      // upcast.
      new types::Something(
        std::move(*the_values),
        std::move(*the_tuple_with_json)
      )
    ),
    common::nullopt
  );
}

common::expected<
  std::shared_ptr<types::ISomething>,
  DeserializationError
> SomethingFrom(
  const nlohmann::json& json,
  bool additional_properties
) {
  common::optional<
    std::shared_ptr<types::ISomething>
  > instance;

  common::optional<DeserializationError> error;

  std::tie(
    instance,
    error
  ) = DeserializeSomething(
    json,
    additional_properties
  );

  if (instance.has_value()) {
    return std::move(*instance);
  }

  if (!error.has_value()) {
    throw std::logic_error(
      "Unexpected null error when null instance."
    );
  }
  return common::make_unexpected(
    std::move(*error)
  );
}

// endregion De-serialization

// region Serialization

/**
 * \brief Represent a serialization error.
 *
 * We use this error internally to avoid unnecessary stack unwinding,
 * but throw the \ref SerializationException at the final site of
 * the serialization for the user.
 */
struct SerializationError {
  /**
   * Human-readable description of the error
   */
  std::wstring cause;

  /**
   * Path to the value that caused the error
   */
  iteration::Path path;

  explicit SerializationError(
    std::wstring a_cause
  ) : cause(std::move(a_cause)) {
    // Intentionally empty.
  }
};  // struct SerializationError

// region SerializationException

std::string RenderSerializationErrorMessage(
  const std::wstring& cause,
  const iteration::Path& path
) {
  return common::WstringToUtf8(
    common::Concat(
      L"Serialization failed at ",
      path.ToWstring(),
      L": ",
      cause
    )
  );
}

SerializationException::SerializationException(
  std::wstring cause,
  iteration::Path path
) :
  cause_(std::move(cause)),
  path_(std::move(path)),
  msg_(RenderSerializationErrorMessage(cause, path)) {
  // Intentionally empty.
}

const char* SerializationException::what() const noexcept {
  return msg_.c_str();
}

const std::wstring& SerializationException::cause() const noexcept {
  return cause_;
}

const iteration::Path& SerializationException::path() const noexcept {
  return path_;
}

// endregion SerializationException

/**
 * Serialize the given boolean to a JSON value.
 */
nlohmann::json SerializeBool(
  bool value
) {
  return value;
}

/**
 * \brief Serialize the given number to a JSON value.
 *
 * We verify that the integer is within the range representable by 64-bit floats
 * for interoperability with other de-serializers.
 */
std::pair<
  common::optional<nlohmann::json>,
  common::optional<SerializationError>
> SerializeInt64(int64_t value) {
  if (
    value < -9007199254740991L
    || value > 9007199254740991L
  ) {
    const std::wstring message = common::Concat(
      L"The integer ",
      std::to_wstring(value),
      L" can not be serialized to JSON "
      L"as it is outside the range [-2^53 + 1, 2^53 - 1] and can not "
      L"be exactly represented as a 64-bit floating point number."
    );

    return std::make_pair<
      common::optional<nlohmann::json>,
      common::optional<SerializationError>
    >(
      common::nullopt,
      common::make_optional<SerializationError>(
        message
      )
    );
  }

  return std::make_pair<
    common::optional<nlohmann::json>,
    common::optional<SerializationError>
  >(
    common::make_optional<nlohmann::json>(value),
    common::nullopt
  );
}

/**
 * \brief Serialize the given floating-point number to a JSON value.
 *
 * JSON knows neither an infinity nor a not-a-number, so we refuse to serialize
 * them instead of silently writing them out as ``null``.
 */
std::pair<
  common::optional<nlohmann::json>,
  common::optional<SerializationError>
> SerializeDouble(double value) {
  if (!std::isfinite(value)) {
    const std::wstring message = common::Concat(
      L"The floating-point number ",
      std::to_wstring(value),
      L" can not be serialized to JSON as JSON knows no infinity "
      L"and no not-a-number."
    );

    return std::make_pair<
      common::optional<nlohmann::json>,
      common::optional<SerializationError>
    >(
      common::nullopt,
      common::make_optional<SerializationError>(
        message
      )
    );
  }

  return std::make_pair<
    common::optional<nlohmann::json>,
    common::optional<SerializationError>
  >(
    common::make_optional<nlohmann::json>(value),
    common::nullopt
  );
}

/**
 * Serialize the given text to a JSON value.
 */
nlohmann::json SerializeWstring(
  const std::wstring& text
) {
  return nlohmann::json(
    common::WstringToUtf8(text)
  );
}

/**
 * Serialize the given bytes to a JSON value.
 */
nlohmann::json SerializeByteArray(
  const std::vector<std::uint8_t>& bytes
) {
  return nlohmann::json(
    std::move(
      stringification::Base64Encode(bytes)
    )
  );
}

/**
 * Serialize the given list to a JSON array where item serialization might fail.
 */
template<typename T, typename FallibleSerializeItemT>
std::pair<
  common::optional<nlohmann::json>,
  common::optional<SerializationError>
> SerializeListWithFallible(
  const std::vector<T>& list,
  FallibleSerializeItemT&& fallible_serialize_item
) {
  nlohmann::json serialized = nlohmann::json::array();

  serialized.get_ptr<nlohmann::json::array_t*>()->reserve(
    list.size()
  );

  size_t index = 0;

  for (const T& item : list) {
    common::optional<nlohmann::json> json_item;
    common::optional<SerializationError> error;

    std::tie(
      json_item,
      error
    ) = fallible_serialize_item(item);

    if (error.has_value()) {
      error->path.segments.emplace_front(
        common::make_unique<iteration::IndexSegment>(
          index
        )
      );

      return std::make_pair<
        common::optional<nlohmann::json>,
        common::optional<SerializationError>
      >(
        common::nullopt,
        std::move(error)
      );
    }

    serialized.emplace_back(
      std::move(*json_item)
    );

    ++index;
  }

  return std::make_pair(
    std::move(serialized),
    common::nullopt
  );
}

/**
 * Serialize the given list to a JSON array where item serialization can not fail.
 */
template<typename T, typename InfallibleSerializeItemT>
nlohmann::json SerializeListWithInfallible(
  const std::vector<T>& list,
  InfallibleSerializeItemT&& infallible_serialize_item
) {
  nlohmann::json serialized = nlohmann::json::array();

  serialized.get_ptr<nlohmann::json::array_t*>()->reserve(
    list.size()
  );

  for (const T& item : list) {
    serialized.emplace_back(
      infallible_serialize_item(item)
    );
  }

  return serialized;
}

std::pair<
  common::optional<nlohmann::json>,
  common::optional<SerializationError>
> SerializeJsonValue(
  const nlohmann::json& value
) {
  if (value.is_null() || value.is_binary() || value.is_discarded()) {
    return std::make_pair(
      common::nullopt,
      common::make_optional<SerializationError>(
        common::Concat(
          L"Expected a JSON-able value (a boolean, a number, a string, "
          L"an array or an object), but got a value of type: ",
          common::Utf8ToWstring(value.type_name())
        )
      )
    );
  }

  if (value.is_array()) {
    nlohmann::json result(nlohmann::json::array());
    result.get_ref<nlohmann::json::array_t&>().reserve(value.size());

    size_t index = 0;
    for (const nlohmann::json& item : value) {
      common::optional<nlohmann::json> serialized_item;
      common::optional<SerializationError> error;
      std::tie(serialized_item, error) = SerializeJsonValue(item);

      if (error.has_value()) {
        error->path.segments.emplace_front(
          common::make_unique<iteration::IndexSegment>(index)
        );

        return std::make_pair(common::nullopt, std::move(error));
      }

      result.push_back(std::move(*serialized_item));
      ++index;
    }

    return std::make_pair(std::move(result), common::nullopt);
  }

  if (value.is_object()) {
    nlohmann::json result(nlohmann::json::object());

    for (const auto& item : value.items()) {
      common::optional<nlohmann::json> serialized_value;
      common::optional<SerializationError> error;
      std::tie(serialized_value, error) = SerializeJsonValue(item.value());

      if (error.has_value()) {
        error->path.segments.emplace_front(
          common::make_unique<iteration::KeySegment>(
            common::Utf8ToWstring(item.key())
          )
        );

        return std::make_pair(common::nullopt, std::move(error));
      }

      result[item.key()] = std::move(*serialized_value);
    }

    return std::make_pair(std::move(result), common::nullopt);
  }

  // NOTE (mristin):
  // JSON knows neither an infinity nor a not-a-number, so we refuse both
  // instead of silently writing them out as ``null``, mirroring
  // ``SerializeDouble`` for the floating-point properties of the model.
  // The caller gives us an ``nlohmann::json`` which may well have been
  // constructed programmatically, so a non-finite number can reach us
  // even though no conformant parser would ever produce one.
  if (value.is_number_float() && !std::isfinite(value.get<double>())) {
    return std::make_pair<
      common::optional<nlohmann::json>,
      common::optional<SerializationError>
    >(
      common::nullopt,
      common::make_optional<SerializationError>(
        common::Concat(
          L"Expected a JSON-able value, but got the number ",
          std::to_wstring(value.get<double>()),
          L", which is neither finite nor representable in JSON"
        )
      )
    );
  }

  // NOTE (mristin):
  // The value is a boolean, a number or a string, all of which are already
  // JSON-able as-is.
  return std::make_pair(value, common::nullopt);
}

std::pair<
  common::optional<nlohmann::json>,
  common::optional<SerializationError>
> SerializeJsonArray(
  const nlohmann::json& value
) {
  if (!value.is_array()) {
    return std::make_pair(
      common::nullopt,
      common::make_optional<SerializationError>(
        common::Concat(
          L"Expected a JSON array, but got a value of type: ",
          common::Utf8ToWstring(value.type_name())
        )
      )
    );
  }

  return SerializeJsonValue(value);
}

std::pair<
  common::optional<nlohmann::json>,
  common::optional<SerializationError>
> SerializeJsonObject(
  const nlohmann::json& value
) {
  if (!value.is_object()) {
    return std::make_pair(
      common::nullopt,
      common::make_optional<SerializationError>(
        common::Concat(
          L"Expected a JSON object, but got a value of type: ",
          common::Utf8ToWstring(value.type_name())
        )
      )
    );
  }

  return SerializeJsonValue(value);
}

/**
 * Serialize a tuple of 4 item(s) to a JSON array.
 */
template <
  typename T0,
  typename T1,
  typename T2,
  typename T3,
  typename SerializeItemT0,
  typename SerializeItemT1,
  typename SerializeItemT2,
  typename SerializeItemT3
>
std::pair<
  common::optional<nlohmann::json>,
  common::optional<SerializationError>
> SerializeTuple4(
  const std::tuple<
    T0,
    T1,
    T2,
    T3
  >& value,
  SerializeItemT0&& serialize_item0,
  SerializeItemT1&& serialize_item1,
  SerializeItemT2&& serialize_item2,
  SerializeItemT3&& serialize_item3
) {
  nlohmann::json serialized = nlohmann::json::array();
  serialized.get_ptr<nlohmann::json::array_t*>()->reserve(
    4
  );

  common::optional<SerializationError> error;

  common::optional<nlohmann::json> json_item0;
  std::tie(
    json_item0,
    error
  ) = serialize_item0(
    std::get<0>(value)
  );
  if (error.has_value()) {
    error->path.segments.emplace_front(
      common::make_unique<iteration::IndexSegment>(
        0
      )
    );
    return std::make_pair<
      common::optional<nlohmann::json>,
      common::optional<SerializationError>
    >(
      common::nullopt,
      std::move(error)
    );
  }

  serialized.emplace_back(
    std::move(*json_item0)
  );

  common::optional<nlohmann::json> json_item1;
  std::tie(
    json_item1,
    error
  ) = serialize_item1(
    std::get<1>(value)
  );
  if (error.has_value()) {
    error->path.segments.emplace_front(
      common::make_unique<iteration::IndexSegment>(
        1
      )
    );
    return std::make_pair<
      common::optional<nlohmann::json>,
      common::optional<SerializationError>
    >(
      common::nullopt,
      std::move(error)
    );
  }

  serialized.emplace_back(
    std::move(*json_item1)
  );

  common::optional<nlohmann::json> json_item2;
  std::tie(
    json_item2,
    error
  ) = serialize_item2(
    std::get<2>(value)
  );
  if (error.has_value()) {
    error->path.segments.emplace_front(
      common::make_unique<iteration::IndexSegment>(
        2
      )
    );
    return std::make_pair<
      common::optional<nlohmann::json>,
      common::optional<SerializationError>
    >(
      common::nullopt,
      std::move(error)
    );
  }

  serialized.emplace_back(
    std::move(*json_item2)
  );

  common::optional<nlohmann::json> json_item3;
  std::tie(
    json_item3,
    error
  ) = serialize_item3(
    std::get<3>(value)
  );
  if (error.has_value()) {
    error->path.segments.emplace_front(
      common::make_unique<iteration::IndexSegment>(
        3
      )
    );
    return std::make_pair<
      common::optional<nlohmann::json>,
      common::optional<SerializationError>
    >(
      common::nullopt,
      std::move(error)
    );
  }

  serialized.emplace_back(
    std::move(*json_item3)
  );

  return std::make_pair(
    std::move(serialized),
    common::nullopt
  );
}

std::pair<
  common::optional<nlohmann::json>,
  common::optional<SerializationError>
> SerializeIClass(
  const types::IClass& that
);

std::pair<
  common::optional<nlohmann::json>,
  common::optional<SerializationError>
> SerializeIClassPtr(
  const std::shared_ptr<types::IClass>& that
);

std::pair<
  common::optional<nlohmann::json>,
  common::optional<SerializationError>
> SerializeSomething(
  const types::ISomething& that
) {
  nlohmann::json result = nlohmann::json::object();

  common::optional<SerializationError> error;

  common::optional<nlohmann::json> json_values;
  std::tie(
    json_values,
    error
  ) = SerializeListWithFallible(
    that.values(),
    SerializeJsonValue
  );
  if (error.has_value()) {
    error->path.segments.emplace_front(
      common::make_unique<iteration::PropertySegment>(
        iteration::Property::kValues
      )
    );

    return std::make_pair<
      common::optional<nlohmann::json>,
      common::optional<SerializationError>
    >(
      common::nullopt,
      std::move(error)
    );
  }

  result["values"] = std::move(
    json_values.value()
  );

  common::optional<nlohmann::json> json_tuple_with_json;
  std::tie(
    json_tuple_with_json,
    error
  ) = SerializeTuple4(
    that.tuple_with_json(),
    [](const std::wstring& item) {
      return std::make_pair(
        common::make_optional<nlohmann::json>(
          SerializeWstring(item)
        ),
        common::nullopt
      );
    },
    SerializeJsonValue,
    SerializeJsonArray,
    SerializeJsonObject
  );
  if (error.has_value()) {
    error->path.segments.emplace_front(
      common::make_unique<iteration::PropertySegment>(
        iteration::Property::kTupleWithJson
      )
    );

    return std::make_pair<
      common::optional<nlohmann::json>,
      common::optional<SerializationError>
    >(
      common::nullopt,
      std::move(error)
    );
  }

  result["tupleWithJson"] = std::move(
    *json_tuple_with_json
  );

  return std::make_pair<
    common::optional<nlohmann::json>,
    common::optional<SerializationError>
  >(
    common::make_optional<nlohmann::json>(std::move(result)),
    common::nullopt
  );
}

std::pair<
  common::optional<nlohmann::json>,
  common::optional<SerializationError>
> SerializeIClass(
  const types::IClass& that
) {
  switch (that.model_type()) {
    case types::ModelType::kSomething:
      return SerializeSomething(
        dynamic_cast<const types::ISomething&>(that)
      );
    default: {
      std::string message = common::Concat(
        "Unexpected model type: ",
        std::to_string(
          static_cast<std::uint32_t>(
            that.model_type()
          )
        )
      );

      throw std::invalid_argument(message);
    }
  };
}

std::pair<
  common::optional<nlohmann::json>,
  common::optional<SerializationError>
> SerializeIClassPtr(
  const std::shared_ptr<types::IClass>& that
) {
  return SerializeIClass(*that);
}

nlohmann::json Serialize(
  const types::IClass& that
) {
  common::optional<nlohmann::json> result;
  common::optional<SerializationError> error;

  std::tie(
    result,
    error
  ) = SerializeIClass(that);

  if (error.has_value()) {
    throw SerializationException(
      std::move(error->cause),
      std::move(error->path)
    );
  }

  return std::move(*result);
}

// endregion Serialization

}  // namespace jsonization
}  // namespace dummy

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
