/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package dummy.visitation;

import dummy.types.model.*;
import dummy.visitation.IVisitor;

/**
 * Perform double-dispatch to visit the concrete instances.
 */
public abstract class AbstractVisitor implements IVisitor
{
  public void visit(IClass that)
  {
    that.accept(this);
  }
  public abstract void visitStructuralFirst(
    IStructuralFirst that
  );
  public abstract void visitStructuralSecond(
    IStructuralSecond that
  );
  public abstract void visitMixedAbstractDescendantOne(
    IMixedAbstractDescendantOne that
  );
  public abstract void visitMixedAbstractDescendantTwo(
    IMixedAbstractDescendantTwo that
  );
  public abstract void visitMixedConcreteWithDescendants(
    IMixedConcreteWithDescendants that
  );
  public abstract void visitMixedConcreteWithDescendantsChild(
    IMixedConcreteWithDescendantsChild that
  );
  public abstract void visitMixedConcreteLeaf(
    IMixedConcreteLeaf that
  );
  public abstract void visitModelTypedFirst(
    IModelTypedFirst that
  );
  public abstract void visitModelTypedSecond(
    IModelTypedSecond that
  );
  public abstract void visitSomething(
    ISomething that
  );
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
