// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

#include "./common.hpp"
#include "./common_examples.hpp"
#include "./common_xmlization.hpp"

#include <dummy/iteration.hpp>
#include <dummy/stringification.hpp>

#include <filesystem>

namespace aas = dummy;

namespace test {
namespace common {
namespace examples {

template<typename T>
struct StaticTypeName;

template<>
struct StaticTypeName<
  aas::types::IAbstractDescendantWithoutNumbers
> {
  static const char* name;
};
const char* StaticTypeName<
  aas::types::IAbstractDescendantWithoutNumbers
>::name = "IAbstractDescendantWithoutNumbers";

template<>
struct StaticTypeName<
  aas::types::IParentWithoutNumbers
> {
  static const char* name;
};
const char* StaticTypeName<
  aas::types::IParentWithoutNumbers
>::name = "IParentWithoutNumbers";

template<>
struct StaticTypeName<
  aas::types::IChildWithoutNumbers
> {
  static const char* name;
};
const char* StaticTypeName<
  aas::types::IChildWithoutNumbers
>::name = "IChildWithoutNumbers";

template<>
struct StaticTypeName<
  aas::types::IWithNumber
> {
  static const char* name;
};
const char* StaticTypeName<
  aas::types::IWithNumber
>::name = "IWithNumber";

template<>
struct StaticTypeName<
  aas::types::ISomething
> {
  static const char* name;
};
const char* StaticTypeName<
  aas::types::ISomething
>::name = "ISomething";

std::shared_ptr<
  aas::types::IAbstractDescendantWithoutNumbers
> LoadAbstractDescendantWithoutNumbers(
  const std::filesystem::path& path
) {
  

  std::shared_ptr<
    aas::types::IClass
  > abstract = test::common::xmlization::MustReadInstance(
    path
  );

  std::shared_ptr<
    aas::types::IAbstractDescendantWithoutNumbers
  > instance(
    std::dynamic_pointer_cast<
      aas::types::IAbstractDescendantWithoutNumbers
    >(
      abstract
    )
  );

  if (instance == nullptr) {
    throw std::runtime_error(
      aas::common::Concat(
        "Failed to cast the instance to IAbstractDescendantWithoutNumbers from ",
        path.string()
      )
    );
  }

  return instance;
}

std::shared_ptr<
  aas::types::IAbstractDescendantWithoutNumbers
> LoadMinAbstractDescendantWithoutNumbers() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "abstractDescendantWithoutNumbers"
      / "minimal.xml"
  );

  return LoadAbstractDescendantWithoutNumbers(
    path
  );
}

std::shared_ptr<
  aas::types::IAbstractDescendantWithoutNumbers
> LoadMaxAbstractDescendantWithoutNumbers() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "abstractDescendantWithoutNumbers"
      / "maximal.xml"
  );

  return LoadAbstractDescendantWithoutNumbers(
    path
  );
}

std::shared_ptr<
  aas::types::IParentWithoutNumbers
> LoadParentWithoutNumbers(
  const std::filesystem::path& path
) {
  

  std::shared_ptr<
    aas::types::IClass
  > abstract = test::common::xmlization::MustReadInstance(
    path
  );

  std::shared_ptr<
    aas::types::IParentWithoutNumbers
  > instance(
    std::dynamic_pointer_cast<
      aas::types::IParentWithoutNumbers
    >(
      abstract
    )
  );

  if (instance == nullptr) {
    throw std::runtime_error(
      aas::common::Concat(
        "Failed to cast the instance to IParentWithoutNumbers from ",
        path.string()
      )
    );
  }

  return instance;
}

std::shared_ptr<
  aas::types::IParentWithoutNumbers
> LoadMinParentWithoutNumbers() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "parentWithoutNumbers"
      / "minimal.xml"
  );

  return LoadParentWithoutNumbers(
    path
  );
}

std::shared_ptr<
  aas::types::IParentWithoutNumbers
> LoadMaxParentWithoutNumbers() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "parentWithoutNumbers"
      / "maximal.xml"
  );

  return LoadParentWithoutNumbers(
    path
  );
}

std::shared_ptr<
  aas::types::IChildWithoutNumbers
> LoadChildWithoutNumbers(
  const std::filesystem::path& path
) {
  

  std::shared_ptr<
    aas::types::IClass
  > abstract = test::common::xmlization::MustReadInstance(
    path
  );

  std::shared_ptr<
    aas::types::IChildWithoutNumbers
  > instance(
    std::dynamic_pointer_cast<
      aas::types::IChildWithoutNumbers
    >(
      abstract
    )
  );

  if (instance == nullptr) {
    throw std::runtime_error(
      aas::common::Concat(
        "Failed to cast the instance to IChildWithoutNumbers from ",
        path.string()
      )
    );
  }

  return instance;
}

std::shared_ptr<
  aas::types::IChildWithoutNumbers
> LoadMinChildWithoutNumbers() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "childWithoutNumbers"
      / "minimal.xml"
  );

  return LoadChildWithoutNumbers(
    path
  );
}

std::shared_ptr<
  aas::types::IChildWithoutNumbers
> LoadMaxChildWithoutNumbers() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "childWithoutNumbers"
      / "maximal.xml"
  );

  return LoadChildWithoutNumbers(
    path
  );
}

std::shared_ptr<
  aas::types::IWithNumber
> LoadWithNumber(
  const std::filesystem::path& path
) {
  

  std::shared_ptr<
    aas::types::IClass
  > abstract = test::common::xmlization::MustReadInstance(
    path
  );

  std::shared_ptr<
    aas::types::IWithNumber
  > instance(
    std::dynamic_pointer_cast<
      aas::types::IWithNumber
    >(
      abstract
    )
  );

  if (instance == nullptr) {
    throw std::runtime_error(
      aas::common::Concat(
        "Failed to cast the instance to IWithNumber from ",
        path.string()
      )
    );
  }

  return instance;
}

std::shared_ptr<
  aas::types::IWithNumber
> LoadMinWithNumber() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "withNumber"
      / "minimal.xml"
  );

  return LoadWithNumber(
    path
  );
}

std::shared_ptr<
  aas::types::IWithNumber
> LoadMaxWithNumber() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "withNumber"
      / "maximal.xml"
  );

  return LoadWithNumber(
    path
  );
}

std::shared_ptr<
  aas::types::ISomething
> LoadSomething(
  const std::filesystem::path& path
) {
  

  std::shared_ptr<
    aas::types::IClass
  > abstract = test::common::xmlization::MustReadInstance(
    path
  );

  std::shared_ptr<
    aas::types::ISomething
  > instance(
    std::dynamic_pointer_cast<
      aas::types::ISomething
    >(
      abstract
    )
  );

  if (instance == nullptr) {
    throw std::runtime_error(
      aas::common::Concat(
        "Failed to cast the instance to ISomething from ",
        path.string()
      )
    );
  }

  return instance;
}

std::shared_ptr<
  aas::types::ISomething
> LoadMinSomething() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "something"
      / "minimal.xml"
  );

  return LoadSomething(
    path
  );
}

std::shared_ptr<
  aas::types::ISomething
> LoadMaxSomething() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "something"
      / "maximal.xml"
  );

  return LoadSomething(
    path
  );
}

}  // namespace examples
}  // namespace common
}  // namespace test

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
