"""
Read and write AAS models as XML.

For reading, we provide different reading functions, each handling a different kind
of input. All the reading functions operate in one pass, *i.e.*, the source is read
incrementally and the complete XML is not held in memory.

We provide the following four reading functions (where ``X`` represents the name of
the class):

1) ``X_from_iterparse`` reads from a stream of ``(event, element)`` tuples coming from
   :py:func:`xml.etree.ElementTree.iterparse` with the argument
   ``events=["start", "end"]``. If you do not trust the source, please consider
   using `defusedxml.ElementTree`_.
2) ``X_from_stream`` reads from the given text stream.
3) ``X_from_file`` reads from a file on disk.
4) ``X_from_str`` reads from the given string.

The functions ``X_from_stream``, ``X_from_file`` and ``X_from_str`` provide
an extra parameter, ``has_iterparse``, which allows you to use a parsing library
different from :py:mod:`xml.etree.ElementTree`. For example, you can pass in
`defusedxml.ElementTree`_.

.. _defusedxml.ElementTree: https://pypi.org/project/defusedxml/#defusedxml-elementtree

All XML elements are expected to live in the :py:attr:`~NAMESPACE`.

For writing, use the function :py:func:`dummy.xmlization.write` which
translates the instance of the model into an XML document and writes it in one pass
to the stream.

The writing raises a :py:class:`SerializationException` if it can not serialize
the instance, be it because the stream failed or because a value could not be
written. The path of the exception points to the culprit as a Python access
expression, *e.g.*, ``.submodels[0].id``, so that you can find it in the instance
which you handed over.

Here is an example usage how to de-serialize from a file:

.. code-block::

    import pathlib
    import xml.etree.ElementTree as ET

    import dummy.xmlization as aas_xmlization

    path = pathlib.Path(...)
    instance = aas_xmlization.read_some_item_from_file(
        path
    )

    # Do something with the ``instance``

Here is another code example where we serialize the instance:

.. code-block::

    import pathlib

    import dummy.types as aas_types
    import dummy.xmlization as aas_xmlization

    instance = SomeItem(
       ... # some constructor arguments
    )

    pth = pathlib.Path(...)
    with pth.open("wt") as fid:
        aas_xmlization.write(instance, fid)
"""


# This code has been automatically generated by aas-core-codegen.
# Do NOT edit or append.


import base64
import enum
import io
import math
import os
import re
import sys
from typing import (
    Any,
    Callable,
    Dict,
    Iterator,
    List,
    Mapping,
    NoReturn,
    Optional,
    Sequence,
    TextIO,
    Tuple,
    TypeVar,
    Union,
    TYPE_CHECKING
)
import xml.etree.ElementTree

if sys.version_info >= (3, 8):
    from typing import (
        Final,
        Protocol
    )
else:
    from typing_extensions import (
        Final,
        Protocol
    )

import dummy.stringification as aas_stringification
import dummy.types as aas_types

# See: https://stackoverflow.com/questions/55076778/why-isnt-this-function-type-annotated-correctly-error-missing-type-parameters
if TYPE_CHECKING:
    PathLike = os.PathLike[Any]
else:
    PathLike = os.PathLike


#: XML namespace in which all the elements are expected to reside
NAMESPACE = 'https://dummy.com'


# region De-serialization


#: XML namespace as a prefix specially tailored for
#: :py:mod:`xml.etree.ElementTree`
_NAMESPACE_IN_CURLY_BRACKETS = f'{{{NAMESPACE}}}'


class Element(Protocol):
    """Behave like :py:meth:`xml.etree.ElementTree.Element`."""

    @property
    def attrib(self) -> Optional[Mapping[str, str]]:
        """Attributes of the element"""
        raise NotImplementedError()

    @property
    def text(self) -> Optional[str]:
        """Text content of the element"""
        raise NotImplementedError()

    @property
    def tail(self) -> Optional[str]:
        """Tail text of the element"""
        raise NotImplementedError()

    @property
    def tag(self) -> str:
        """Tag of the element; with a namespace provided as a ``{...}`` prefix"""
        raise NotImplementedError()

    def clear(self) -> None:
        """Behave like :py:meth:`xml.etree.ElementTree.Element.clear`."""
        raise NotImplementedError()


class HasIterparse(Protocol):
    """Parse an XML document incrementally."""

    # NOTE (mristin):
    # ``self`` is not used in this context, but is necessary for Mypy,
    # see: https://github.com/python/mypy/issues/5018 and
    # https://github.com/python/mypy/commit/3efbc5c5e910296a60ed5b9e0e7eb11dd912c3ed#diff-e165eb7aed9dca0a5ebd93985c8cd263a6462d36ac185f9461348dc5a1396d76R9937

    def iterparse(
            self,
            source: TextIO,
            events: Optional[Sequence[str]] = None
    ) -> Iterator[Tuple[str, Element]]:
        """Behave like :py:func:`xml.etree.ElementTree.iterparse`."""


class ElementSegment:
    """Represent an element on a path to the erroneous value."""
    #: Erroneous element
    element: Final[Element]

    def __init__(
            self,
            element: Element
    ) -> None:
        """Initialize with the given values."""
        self.element = element

    def __str__(self) -> str:
        """
        Render the segment as a tag without the namespace.

        We deliberately omit the namespace in the tag names. If you want to actually
        query with the resulting XPath, you have to insert the namespaces manually.
        We did not know how to include the namespace in a meaningful way, as XPath
        assumes namespace prefixes to be defined *outside* of the document. At least
        the path thus rendered is informative, and you should be able to descend it
        manually.
        """
        _, has_namespace, tag_wo_ns = self.element.tag.rpartition('}')
        if not has_namespace:
            return self.element.tag
        else:
            return tag_wo_ns


class IndexSegment:
    """Represent an element in a sequence on a path to the erroneous value."""
    #: Erroneous element
    element: Final[Element]

    #: Index of the element in the sequence
    index: Final[int]

    def __init__(
            self,
            element: Element,
            index: int
    ) -> None:
        """Initialize with the given values."""
        self.element = element
        self.index = index

    def __str__(self) -> str:
        """Render the segment as an element wildcard with the index."""
        return f'*[{self.index}]'


Segment = Union[ElementSegment, IndexSegment]


class Path:
    """Represent the relative path to the erroneous element."""

    def __init__(self) -> None:
        """Initialize as an empty path."""
        self._segments = []  # type: List[Segment]

    @property
    def segments(self) -> Sequence[Segment]:
        """Get the segments of the path."""
        return self._segments

    def _prepend(self, segment: Segment) -> None:
        """Insert the :paramref:`segment` in front of other segments."""
        self._segments.insert(0, segment)

    def __str__(self) -> str:
        """Render the path as a relative XPath.

        We omit the leading ``/`` so that you can easily prefix it as you need.
        """
        return "/".join(str(segment) for segment in self._segments)


class DeserializationException(Exception):
    """Signal that the XML de-serialization could not be performed."""

    #: Human-readable explanation of the exception's cause
    cause: Final[str]

    #: Relative path to the erroneous value
    path: Final[Path]

    def __init__(
            self,
            cause: str
    ) -> None:
        """Initialize with the given :paramref:`cause` and an empty path."""
        self.cause = cause
        self.path = Path()


def _with_elements_cleared_after_yield(
        iterator: Iterator[Tuple[str, Element]]
) -> Iterator[Tuple[str, Element]]:
    """
    Map the :paramref:`iterator` such that the element is ``clear()``'ed
    *after* every ``yield``.

    :param iterator: to be mapped
    :yield: event and element from :paramref:`iterator`
    """
    for event, element in iterator:
        yield event, element
        element.clear()


def abstract_item_from_iterparse(
    iterator: Iterator[Tuple[str, Element]]
) -> aas_types.AbstractItem:
    """
    Read an instance of :py:class:`.types.AbstractItem` from
    the :paramref:`iterator`.

    Example usage:

    .. code-block::

        import pathlib
        import xml.etree.ElementTree as ET

        import dummy.xmlization as aas_xmlization

        path = pathlib.Path(...)
        with path.open("rt") as fid:
            iterator = ET.iterparse(
                source=fid,
                events=['start', 'end']
            )
            instance = aas_xmlization.abstract_item_from_iterparse(
                iterator
            )

        # Do something with the ``instance``

    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.AbstractItem` read from
        :paramref:`iterator`
    """
    return _read_instance_from_iterparse(
        iterator,
        _read_abstract_item_as_element,
        'AbstractItem'
    )


def abstract_item_from_stream(
    stream: TextIO,
    has_iterparse: HasIterparse = xml.etree.ElementTree
) -> aas_types.AbstractItem:
    """
    Read an instance of :py:class:`.types.AbstractItem` from
    the :paramref:`stream`.

    Example usage:

    .. code-block::

        import dummy.xmlization as aas_xmlization

        with open_some_stream_over_network(...) as stream:
            instance = aas_xmlization.abstract_item_from_stream(
                stream
            )

        # Do something with the ``instance``

    :param stream:
        representing an instance of
        :py:class:`.types.AbstractItem` in XML
    :param has_iterparse:
        Module containing ``iterparse`` function.

        Default is to use :py:mod:`xml.etree.ElementTree` from the standard
        library. If you have to deal with malicious input, consider using
        a library such as `defusedxml.ElementTree`_.
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.AbstractItem` read from
        :paramref:`stream`
    """
    iterator = has_iterparse.iterparse(
        stream,
        ['start', 'end']
    )
    return abstract_item_from_iterparse(
        _with_elements_cleared_after_yield(iterator)
    )


def abstract_item_from_file(
    path: PathLike,
    has_iterparse: HasIterparse = xml.etree.ElementTree
) -> aas_types.AbstractItem:
    """
    Read an instance of :py:class:`.types.AbstractItem` from
    the :paramref:`path`.

    Example usage:

    .. code-block::

        import pathlib
        import dummy.xmlization as aas_xmlization

        path = pathlib.Path(...)
        instance = aas_xmlization.abstract_item_from_file(
            path
        )

        # Do something with the ``instance``

    :param path:
        to the file representing an instance of
        :py:class:`.types.AbstractItem` in XML
    :param has_iterparse:
        Module containing ``iterparse`` function.

        Default is to use :py:mod:`xml.etree.ElementTree` from the standard
        library. If you have to deal with malicious input, consider using
        a library such as `defusedxml.ElementTree`_.
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.AbstractItem` read from
        :paramref:`path`
    """
    with open(os.fspath(path), "rt", encoding='utf-8') as fid:
        iterator = has_iterparse.iterparse(
            fid,
            ['start', 'end']
        )
        return abstract_item_from_iterparse(
            _with_elements_cleared_after_yield(iterator)
        )


def abstract_item_from_str(
    text: str,
    has_iterparse: HasIterparse = xml.etree.ElementTree
) -> aas_types.AbstractItem:
    """
    Read an instance of :py:class:`.types.AbstractItem` from
    the :paramref:`text`.

    Example usage:

    .. code-block::

        import pathlib
        import dummy.xmlization as aas_xmlization

        text = "<...>...</...>"
        instance = aas_xmlization.abstract_item_from_str(
            text
        )

        # Do something with the ``instance``

    :param text:
        representing an instance of
        :py:class:`.types.AbstractItem` in XML
    :param has_iterparse:
        Module containing ``iterparse`` function.

        Default is to use :py:mod:`xml.etree.ElementTree` from the standard
        library. If you have to deal with malicious input, consider using
        a library such as `defusedxml.ElementTree`_.
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.AbstractItem` read from
        :paramref:`text`
    """
    iterator = has_iterparse.iterparse(
        io.StringIO(text),
        ['start', 'end']
    )
    return abstract_item_from_iterparse(
        _with_elements_cleared_after_yield(iterator)
    )


def some_item_from_iterparse(
    iterator: Iterator[Tuple[str, Element]]
) -> aas_types.SomeItem:
    """
    Read an instance of :py:class:`.types.SomeItem` from
    the :paramref:`iterator`.

    Example usage:

    .. code-block::

        import pathlib
        import xml.etree.ElementTree as ET

        import dummy.xmlization as aas_xmlization

        path = pathlib.Path(...)
        with path.open("rt") as fid:
            iterator = ET.iterparse(
                source=fid,
                events=['start', 'end']
            )
            instance = aas_xmlization.some_item_from_iterparse(
                iterator
            )

        # Do something with the ``instance``

    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.SomeItem` read from
        :paramref:`iterator`
    """
    return _read_instance_from_iterparse(
        iterator,
        _read_some_item_as_element,
        'SomeItem'
    )


def some_item_from_stream(
    stream: TextIO,
    has_iterparse: HasIterparse = xml.etree.ElementTree
) -> aas_types.SomeItem:
    """
    Read an instance of :py:class:`.types.SomeItem` from
    the :paramref:`stream`.

    Example usage:

    .. code-block::

        import dummy.xmlization as aas_xmlization

        with open_some_stream_over_network(...) as stream:
            instance = aas_xmlization.some_item_from_stream(
                stream
            )

        # Do something with the ``instance``

    :param stream:
        representing an instance of
        :py:class:`.types.SomeItem` in XML
    :param has_iterparse:
        Module containing ``iterparse`` function.

        Default is to use :py:mod:`xml.etree.ElementTree` from the standard
        library. If you have to deal with malicious input, consider using
        a library such as `defusedxml.ElementTree`_.
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.SomeItem` read from
        :paramref:`stream`
    """
    iterator = has_iterparse.iterparse(
        stream,
        ['start', 'end']
    )
    return some_item_from_iterparse(
        _with_elements_cleared_after_yield(iterator)
    )


def some_item_from_file(
    path: PathLike,
    has_iterparse: HasIterparse = xml.etree.ElementTree
) -> aas_types.SomeItem:
    """
    Read an instance of :py:class:`.types.SomeItem` from
    the :paramref:`path`.

    Example usage:

    .. code-block::

        import pathlib
        import dummy.xmlization as aas_xmlization

        path = pathlib.Path(...)
        instance = aas_xmlization.some_item_from_file(
            path
        )

        # Do something with the ``instance``

    :param path:
        to the file representing an instance of
        :py:class:`.types.SomeItem` in XML
    :param has_iterparse:
        Module containing ``iterparse`` function.

        Default is to use :py:mod:`xml.etree.ElementTree` from the standard
        library. If you have to deal with malicious input, consider using
        a library such as `defusedxml.ElementTree`_.
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.SomeItem` read from
        :paramref:`path`
    """
    with open(os.fspath(path), "rt", encoding='utf-8') as fid:
        iterator = has_iterparse.iterparse(
            fid,
            ['start', 'end']
        )
        return some_item_from_iterparse(
            _with_elements_cleared_after_yield(iterator)
        )


def some_item_from_str(
    text: str,
    has_iterparse: HasIterparse = xml.etree.ElementTree
) -> aas_types.SomeItem:
    """
    Read an instance of :py:class:`.types.SomeItem` from
    the :paramref:`text`.

    Example usage:

    .. code-block::

        import pathlib
        import dummy.xmlization as aas_xmlization

        text = "<...>...</...>"
        instance = aas_xmlization.some_item_from_str(
            text
        )

        # Do something with the ``instance``

    :param text:
        representing an instance of
        :py:class:`.types.SomeItem` in XML
    :param has_iterparse:
        Module containing ``iterparse`` function.

        Default is to use :py:mod:`xml.etree.ElementTree` from the standard
        library. If you have to deal with malicious input, consider using
        a library such as `defusedxml.ElementTree`_.
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.SomeItem` read from
        :paramref:`text`
    """
    iterator = has_iterparse.iterparse(
        io.StringIO(text),
        ['start', 'end']
    )
    return some_item_from_iterparse(
        _with_elements_cleared_after_yield(iterator)
    )


def another_item_from_iterparse(
    iterator: Iterator[Tuple[str, Element]]
) -> aas_types.AnotherItem:
    """
    Read an instance of :py:class:`.types.AnotherItem` from
    the :paramref:`iterator`.

    Example usage:

    .. code-block::

        import pathlib
        import xml.etree.ElementTree as ET

        import dummy.xmlization as aas_xmlization

        path = pathlib.Path(...)
        with path.open("rt") as fid:
            iterator = ET.iterparse(
                source=fid,
                events=['start', 'end']
            )
            instance = aas_xmlization.another_item_from_iterparse(
                iterator
            )

        # Do something with the ``instance``

    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.AnotherItem` read from
        :paramref:`iterator`
    """
    return _read_instance_from_iterparse(
        iterator,
        _read_another_item_as_element,
        'AnotherItem'
    )


def another_item_from_stream(
    stream: TextIO,
    has_iterparse: HasIterparse = xml.etree.ElementTree
) -> aas_types.AnotherItem:
    """
    Read an instance of :py:class:`.types.AnotherItem` from
    the :paramref:`stream`.

    Example usage:

    .. code-block::

        import dummy.xmlization as aas_xmlization

        with open_some_stream_over_network(...) as stream:
            instance = aas_xmlization.another_item_from_stream(
                stream
            )

        # Do something with the ``instance``

    :param stream:
        representing an instance of
        :py:class:`.types.AnotherItem` in XML
    :param has_iterparse:
        Module containing ``iterparse`` function.

        Default is to use :py:mod:`xml.etree.ElementTree` from the standard
        library. If you have to deal with malicious input, consider using
        a library such as `defusedxml.ElementTree`_.
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.AnotherItem` read from
        :paramref:`stream`
    """
    iterator = has_iterparse.iterparse(
        stream,
        ['start', 'end']
    )
    return another_item_from_iterparse(
        _with_elements_cleared_after_yield(iterator)
    )


def another_item_from_file(
    path: PathLike,
    has_iterparse: HasIterparse = xml.etree.ElementTree
) -> aas_types.AnotherItem:
    """
    Read an instance of :py:class:`.types.AnotherItem` from
    the :paramref:`path`.

    Example usage:

    .. code-block::

        import pathlib
        import dummy.xmlization as aas_xmlization

        path = pathlib.Path(...)
        instance = aas_xmlization.another_item_from_file(
            path
        )

        # Do something with the ``instance``

    :param path:
        to the file representing an instance of
        :py:class:`.types.AnotherItem` in XML
    :param has_iterparse:
        Module containing ``iterparse`` function.

        Default is to use :py:mod:`xml.etree.ElementTree` from the standard
        library. If you have to deal with malicious input, consider using
        a library such as `defusedxml.ElementTree`_.
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.AnotherItem` read from
        :paramref:`path`
    """
    with open(os.fspath(path), "rt", encoding='utf-8') as fid:
        iterator = has_iterparse.iterparse(
            fid,
            ['start', 'end']
        )
        return another_item_from_iterparse(
            _with_elements_cleared_after_yield(iterator)
        )


def another_item_from_str(
    text: str,
    has_iterparse: HasIterparse = xml.etree.ElementTree
) -> aas_types.AnotherItem:
    """
    Read an instance of :py:class:`.types.AnotherItem` from
    the :paramref:`text`.

    Example usage:

    .. code-block::

        import pathlib
        import dummy.xmlization as aas_xmlization

        text = "<...>...</...>"
        instance = aas_xmlization.another_item_from_str(
            text
        )

        # Do something with the ``instance``

    :param text:
        representing an instance of
        :py:class:`.types.AnotherItem` in XML
    :param has_iterparse:
        Module containing ``iterparse`` function.

        Default is to use :py:mod:`xml.etree.ElementTree` from the standard
        library. If you have to deal with malicious input, consider using
        a library such as `defusedxml.ElementTree`_.
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.AnotherItem` read from
        :paramref:`text`
    """
    iterator = has_iterparse.iterparse(
        io.StringIO(text),
        ['start', 'end']
    )
    return another_item_from_iterparse(
        _with_elements_cleared_after_yield(iterator)
    )


def something_from_iterparse(
    iterator: Iterator[Tuple[str, Element]]
) -> aas_types.Something:
    """
    Read an instance of :py:class:`.types.Something` from
    the :paramref:`iterator`.

    Example usage:

    .. code-block::

        import pathlib
        import xml.etree.ElementTree as ET

        import dummy.xmlization as aas_xmlization

        path = pathlib.Path(...)
        with path.open("rt") as fid:
            iterator = ET.iterparse(
                source=fid,
                events=['start', 'end']
            )
            instance = aas_xmlization.something_from_iterparse(
                iterator
            )

        # Do something with the ``instance``

    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.Something` read from
        :paramref:`iterator`
    """
    return _read_instance_from_iterparse(
        iterator,
        _read_something_as_element,
        'Something'
    )


def something_from_stream(
    stream: TextIO,
    has_iterparse: HasIterparse = xml.etree.ElementTree
) -> aas_types.Something:
    """
    Read an instance of :py:class:`.types.Something` from
    the :paramref:`stream`.

    Example usage:

    .. code-block::

        import dummy.xmlization as aas_xmlization

        with open_some_stream_over_network(...) as stream:
            instance = aas_xmlization.something_from_stream(
                stream
            )

        # Do something with the ``instance``

    :param stream:
        representing an instance of
        :py:class:`.types.Something` in XML
    :param has_iterparse:
        Module containing ``iterparse`` function.

        Default is to use :py:mod:`xml.etree.ElementTree` from the standard
        library. If you have to deal with malicious input, consider using
        a library such as `defusedxml.ElementTree`_.
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.Something` read from
        :paramref:`stream`
    """
    iterator = has_iterparse.iterparse(
        stream,
        ['start', 'end']
    )
    return something_from_iterparse(
        _with_elements_cleared_after_yield(iterator)
    )


def something_from_file(
    path: PathLike,
    has_iterparse: HasIterparse = xml.etree.ElementTree
) -> aas_types.Something:
    """
    Read an instance of :py:class:`.types.Something` from
    the :paramref:`path`.

    Example usage:

    .. code-block::

        import pathlib
        import dummy.xmlization as aas_xmlization

        path = pathlib.Path(...)
        instance = aas_xmlization.something_from_file(
            path
        )

        # Do something with the ``instance``

    :param path:
        to the file representing an instance of
        :py:class:`.types.Something` in XML
    :param has_iterparse:
        Module containing ``iterparse`` function.

        Default is to use :py:mod:`xml.etree.ElementTree` from the standard
        library. If you have to deal with malicious input, consider using
        a library such as `defusedxml.ElementTree`_.
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.Something` read from
        :paramref:`path`
    """
    with open(os.fspath(path), "rt", encoding='utf-8') as fid:
        iterator = has_iterparse.iterparse(
            fid,
            ['start', 'end']
        )
        return something_from_iterparse(
            _with_elements_cleared_after_yield(iterator)
        )


def something_from_str(
    text: str,
    has_iterparse: HasIterparse = xml.etree.ElementTree
) -> aas_types.Something:
    """
    Read an instance of :py:class:`.types.Something` from
    the :paramref:`text`.

    Example usage:

    .. code-block::

        import pathlib
        import dummy.xmlization as aas_xmlization

        text = "<...>...</...>"
        instance = aas_xmlization.something_from_str(
            text
        )

        # Do something with the ``instance``

    :param text:
        representing an instance of
        :py:class:`.types.Something` in XML
    :param has_iterparse:
        Module containing ``iterparse`` function.

        Default is to use :py:mod:`xml.etree.ElementTree` from the standard
        library. If you have to deal with malicious input, consider using
        a library such as `defusedxml.ElementTree`_.
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.Something` read from
        :paramref:`text`
    """
    iterator = has_iterparse.iterparse(
        io.StringIO(text),
        ['start', 'end']
    )
    return something_from_iterparse(
        _with_elements_cleared_after_yield(iterator)
    )


def from_iterparse(
    iterator: Iterator[Tuple[str, Element]]
) -> aas_types.Class:
    """
    Read an instance from the :paramref:`iterator`.

    The type of the instance is determined by the very first start element.

    Example usage:

    .. code-block::

        import pathlib
        import xml.etree.ElementTree as ET

        import dummy.xmlization as aas_xmlization

        path = pathlib.Path(...)
        with path.open("rt") as fid:
            iterator = ET.iterparse(
                source=fid,
                events=['start', 'end']
            )
            instance = aas_xmlization.from_iterparse(
                iterator
            )

        # Do something with the ``instance``

    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.Class` read from the :paramref:`iterator`
    """
    return _read_instance_from_iterparse(
        iterator,
        _read_as_element,
        'an instance'
    )


def from_stream(
    stream: TextIO,
    has_iterparse: HasIterparse = xml.etree.ElementTree
) -> aas_types.Class:
    """
    Read an instance from the :paramref:`stream`.

    The type of the instance is determined by the very first start element.

    Example usage:

    .. code-block::

        import dummy.xmlization as aas_xmlization

        with open_some_stream_over_network(...) as stream:
            instance = aas_xmlization.from_stream(
                stream
            )

        # Do something with the ``instance``

    :param stream:
        representing an instance in XML
    :param has_iterparse:
        Module containing ``iterparse`` function.

        Default is to use :py:mod:`xml.etree.ElementTree` from the standard
        library. If you have to deal with malicious input, consider using
        a library such as `defusedxml.ElementTree`_.
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance read from :paramref:`stream`
    """
    iterator = has_iterparse.iterparse(
        stream,
        ['start', 'end']
    )
    return from_iterparse(
        _with_elements_cleared_after_yield(iterator)
    )


def from_file(
    path: PathLike,
    has_iterparse: HasIterparse = xml.etree.ElementTree
) -> aas_types.Class:
    """
    Read an instance from the file at the :paramref:`path`.

    Example usage:

    .. code-block::

        import pathlib
        import dummy.xmlization as aas_xmlization

        path = pathlib.Path(...)
        instance = aas_xmlization.from_file(
            path
        )

        # Do something with the ``instance``

    :param path:
        to the file representing an instance in XML
    :param has_iterparse:
        Module containing ``iterparse`` function.

        Default is to use :py:mod:`xml.etree.ElementTree` from the standard
        library. If you have to deal with malicious input, consider using
        a library such as `defusedxml.ElementTree`_.
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance read from the file at :paramref:`path`
    """
    with open(os.fspath(path), "rt", encoding='utf-8') as fid:
        iterator = has_iterparse.iterparse(
            fid,
            ['start', 'end']
        )
        return from_iterparse(
            _with_elements_cleared_after_yield(iterator)
        )


def from_str(
    text: str,
    has_iterparse: HasIterparse = xml.etree.ElementTree
) -> aas_types.Class:
    """
    Read an instance from the :paramref:`text`.

    Example usage:

    .. code-block::

        import pathlib
        import dummy.xmlization as aas_xmlization

        text = "<...>...</...>"
        instance = aas_xmlization.from_str(
            text
        )

        # Do something with the ``instance``

    :param text:
        representing an instance in XML
    :param has_iterparse:
        Module containing ``iterparse`` function.

        Default is to use :py:mod:`xml.etree.ElementTree` from the standard
        library. If you have to deal with malicious input, consider using
        a library such as `defusedxml.ElementTree`_.
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance read from :paramref:`text`
    """
    iterator = has_iterparse.iterparse(
        io.StringIO(text),
        ['start', 'end']
    )
    return from_iterparse(
        _with_elements_cleared_after_yield(iterator)
    )


# NOTE (mristin):
# Directly using the iterator turned out to result in very complex function
# designs. The design became much simpler as soon as we considered one look-ahead
# element. We came up finally with the following pattern which all the protected
# reading functions below roughly follow:
#
# ..code-block::
#
#    _read_*(
#       look-ahead element,
#       iterator
#    ) -> result
#
# The reading functions all read from the ``iterator`` coming from
# :py:func:`xml.etree.ElementTree.iterparse` with the argument
# ``events=["start", "end"]``. The exception :py:class:`.DeserializationException`
# is raised in case of unexpected input.
#
# The reading functions are responsible to read the end element corresponding to the
# start look-ahead element.
#
# When it comes to error reporting, we use exceptions. The exceptions are raised in
# the *callee*, as usual. However, the context of the exception, such as the error path,
# is added in the *caller*, as only the caller knows the context of
# the lookahead-element. In particular, prepending the path segment corresponding to
# the lookahead-element is the responsibility of the *caller*, and not of
# the *callee*.


_ValueT = TypeVar("_ValueT")

#: Read the content of an element which has already been opened, and read
#: the corresponding end element as well
_ContentReader = Callable[
    [Element, Iterator[Tuple[str, Element]]],
    _ValueT
]


def _parse_element_tag(element: Element) -> str:
    """
    Extract the tag name without the namespace prefix from :paramref:`element`.

    :param element: whose tag without namespace we want to extract
    :return: tag name without the namespace prefix
    :raise: :py:class:`DeserializationException` if unexpected :paramref:`element`
    """
    if not element.tag.startswith(_NAMESPACE_IN_CURLY_BRACKETS):
        namespace, got_namespace, tag_wo_ns = (
            element.tag.rpartition('}')
        )
        if got_namespace:
            if namespace.startswith('{'):
                namespace = namespace[1:]

            raise DeserializationException(
                f"Expected the element in the namespace {NAMESPACE!r}, "
                f"but got the element {tag_wo_ns!r} in the namespace {namespace!r}"
            )
        else:
            raise DeserializationException(
                f"Expected the element in the namespace {NAMESPACE!r}, "
                f"but got the element {tag_wo_ns!r} without the namespace prefix"
            )

    return element.tag[len(_NAMESPACE_IN_CURLY_BRACKETS):]


def _raise_if_has_tail_or_attrib(
        element: Element
) -> None:
    """
    Check that :paramref:`element` has no trailing text and no attributes.

    :param element: to be verified
    :raise:
        :py:class:`.DeserializationException` if trailing text or attributes;
        conforming to the convention about handling error paths,
        the exception path is left empty.
    """
    if element.tail is not None and len(element.tail.strip()) != 0:
        raise DeserializationException(
            f"Expected no trailing text, but got: {element.tail!r}"
        )

    if element.attrib is not None and len(element.attrib) > 0:
        raise DeserializationException(
            f"Expected no attributes, but got: {element.attrib}"
        )


def _read_end_element(
        element: Element,
        iterator: Iterator[Tuple[str, Element]]
) -> Element:
    """
    Read the end element corresponding to the start :paramref:`element`
    from :paramref:`iterator`.

    :param element: corresponding start element
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    """
    next_event_element = next(iterator, None)
    if next_event_element is None:
        raise DeserializationException(
            f"Expected the end element for {element.tag}, "
            f"but got the end-of-input"
        )

    next_event, next_element = next_event_element
    if next_event != "end" or next_element.tag != element.tag:
        raise DeserializationException(
            f"Expected the end element for {element.tag!r}, "
            f"but got the event {next_event!r} and element {next_element.tag!r}"
        )

    _raise_if_has_tail_or_attrib(next_element)

    return next_element


def _read_named_element(
    element: Element,
    iterator: Iterator[Tuple[str, Element]],
    expected_tag: str,
    read_content: _ContentReader[_ValueT]
) -> _ValueT:
    """
    Verify that :paramref:`element` bears the :paramref:`expected_tag`, and
    delegate the reading of its content to :paramref:`read_content`.

    This is the only place where an element's tag is checked against the tag which
    its container prescribes -- the XML name of a class, ``<v>`` for a list item, or
    ``<v1>``, ``<v2>``, *etc.* for a tuple item.

    :param element: look-ahead element
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :param expected_tag: expected tag of :paramref:`element`
    :param read_content: to read the content of :paramref:`element`
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed value
    """
    tag_wo_ns = _parse_element_tag(element)
    if tag_wo_ns != expected_tag:
        raise DeserializationException(
            f"Expected an element with the tag {expected_tag!r}, "
            f"but got an element with tag: {tag_wo_ns!r}"
        )

    return read_content(element, iterator)


def _read_dispatched(
    element: Element,
    iterator: Iterator[Tuple[str, Element]],
    dispatch: Mapping[str, _ContentReader[_ValueT]],
    expected_what: str
) -> _ValueT:
    """
    Read the instance of :paramref:`element` by dispatching on its own tag.

    An instance element is self-describing: its tag *is* its model type.

    The end element corresponding to :paramref:`element` will be read as well.

    :param element: start element of the instance
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :param dispatch: to read the instance as a sequence, by its model type
    :param expected_what: what we expected to read, for the error messages
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed instance
    """
    tag_wo_ns = _parse_element_tag(element)

    read_as_sequence = dispatch.get(tag_wo_ns, None)
    if read_as_sequence is None:
        raise DeserializationException(
            f"Expected the element tag to be a valid model type "
            f"of {expected_what}, "
            f"but got tag {tag_wo_ns!r}"
        )

    return read_as_sequence(element, iterator)


def _read_properties(
    element: Element,
    iterator: Iterator[Tuple[str, Element]],
    readers: Mapping[str, _ContentReader[Any]]
) -> Mapping[str, Any]:
    """
    Read the properties of an instance as the children of :paramref:`element`.

    The end element corresponding to :paramref:`element` will be read as well.

    The property is marked on the error path here, once for all the properties,
    instead of in every reader: the tag of the child element *is* the XML name of
    the property which we are reading.

    :param element: start element, parent of the properties
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :param readers: to read the content of a property, by its XML name
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed values, by the XML name of the property
    """
    if element.text is not None and len(element.text.strip()) != 0:
        raise DeserializationException(
            f"Expected only XML elements representing the properties "
            f"and whitespace text, but got text: {element.text!r}"
        )

    _raise_if_has_tail_or_attrib(element)

    values = dict()  # type: Dict[str, Any]

    while True:
        # NOTE (mristin):
        # We pull the next property element here instead of delegating it to
        # a helper. A call is not free in Python, and this loop runs once for
        # every property of every instance.
        next_event_element = next(iterator, None)
        if next_event_element is None:
            raise DeserializationException(
                f"Expected a property element or the end element corresponding "
                f"to {element.tag}, but got the end-of-input"
            )

        next_event, prop_element = next_event_element
        if next_event == 'end' and prop_element.tag == element.tag:
            # We reached the end element enclosing the properties.
            break

        if next_event != 'start':
            raise DeserializationException(
                f"Expected a start element corresponding to a property, "
                f"but got event {next_event!r} "
                f"and element {prop_element.tag!r}"
            )

        try:
            tag_wo_ns = _parse_element_tag(prop_element)

            reader = readers.get(tag_wo_ns, None)
            if reader is None:
                raise DeserializationException(
                    f"Expected an element representing a property, "
                    f"but got an element with unexpected tag: {tag_wo_ns!r}"
                )

            values[tag_wo_ns] = reader(prop_element, iterator)
        except DeserializationException as exception:
            exception.path._prepend(ElementSegment(prop_element))
            raise

    return values


def _read_tuple_item(
    element: Element,
    iterator: Iterator[Tuple[str, Element]],
    index: int,
    read_item: _ContentReader[_ValueT]
) -> _ValueT:
    """
    Read the item at :paramref:`index` of the tuple enclosed in :paramref:`element`.

    :param element: start element enclosing the tuple
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :param index: index of the item in the tuple
    :param read_item: to read the item, including its own end element
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed item
    """
    next_event_element = next(iterator, None)
    if next_event_element is None:
        raise DeserializationException(
            f"Expected the item {index} of the tuple, "
            f"but got end-of-input"
        )

    next_event, item_element = next_event_element
    if next_event != 'start':
        raise DeserializationException(
            f"Expected a start element corresponding to the item {index} "
            f"of the tuple, but got event {next_event!r} "
            f"and element {item_element.tag!r}"
        )

    try:
        return read_item(item_element, iterator)
    except DeserializationException as exception:
        exception.path._prepend(IndexSegment(item_element, index))
        raise


def _read_instance_from_iterparse(
    iterator: Iterator[Tuple[str, Element]],
    read_as_element: _ContentReader[_ValueT],
    expected_what: str
) -> _ValueT:
    """
    Read an instance from :paramref:`iterator`, starting at its start element.

    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :param read_as_element: to read the instance, including its end element
    :param expected_what: what we expected to read, for the error messages
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed instance
    """
    next_event_element = next(iterator, None)
    if next_event_element is None:
        raise DeserializationException(
            f"Expected the start element for {expected_what}, "
            f"but got the end-of-input"
        )

    next_event, next_element = next_event_element
    if next_event != 'start':
        raise DeserializationException(
            f"Expected the start element for {expected_what}, "
            f"but got event {next_event!r} and element {next_element.tag!r}"
        )

    try:
        return read_as_element(next_element, iterator)
    except DeserializationException as exception:
        exception.path._prepend(ElementSegment(next_element))
        raise exception


_XS_WHITESPACE_RE = re.compile(r"[ \t\n\r]+")


def _collapse_whitespace(text: str) -> str:
    """
    Normalize :paramref:`text` the way ``whiteSpace="collapse"`` prescribes.

    Every atomic XSD type except a string, and every type derived from one
    by restriction, fixes ``whiteSpace`` to ``collapse``, and a schema author
    can not change it. A tab, a line feed and a carriage return each become
    a space, a run of spaces becomes one space, and the leading and trailing
    spaces go. Only then is the result a lexical representation to be matched.

    Mind that this strips only the whitespace *around* the value: a space
    within it survives as a single space, so ``2  3`` becomes ``2 3``, which
    is still no number.

    See: https://www.w3.org/TR/xmlschema-2/#rf-whiteSpace

    :param text: to be normalized
    :return: normalized text
    """
    return _XS_WHITESPACE_RE.sub(" ", text).strip(" ")


def _read_text_from_element(
    element: Element,
    iterator: Iterator[Tuple[str, Element]]
) -> str:
    """
    Extract the text from the :paramref:`element`, and read
    the end element from :paramref:`iterator`.

    The :paramref:`element` is expected to contain text. Otherwise,
    it is considered as unexpected input.

    :param element: start element enclosing the text
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    """
    _raise_if_has_tail_or_attrib(element)

    text = element.text

    end_element = _read_end_element(
        element,
        iterator,
    )

    if text is None:
        if end_element.text is None:
            raise DeserializationException(
                "Expected an element with text, but got an element with no text."
            )

        text = end_element.text

    return text


#: Match the lexical space of ``xs:long``.
#:
#: Mind the explicit ``[0-9]``: ``\d`` would match a digit of any script.
#:
#: See: https://www.w3.org/TR/xmlschema-2/#long
_XS_LONG_RE = re.compile(r"(\+|-)?[0-9]+")


def _read_int_from_element_text(
    element: Element,
    iterator: Iterator[Tuple[str, Element]]
) -> int:
    """
    Parse the text of :paramref:`element` as an integer, and
    read the corresponding end element from :paramref:`iterator`.

    :param element: start element
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed value
    """
    text = _collapse_whitespace(
        _read_text_from_element(
            element,
            iterator
        )
    )

    # NOTE (mristin):
    # ``int`` is far too permissive to be handed the text directly: it takes
    # a digit group separator as in ``1_0``, surrounding whitespace, and
    # a digit of any script -- the Arabic-Indic ``۵`` would be read as 5.
    # Mind that it is checked with ``fullmatch`` and not with ``match``: ``$``
    # would also match just before a trailing newline.
    #
    # See: https://www.w3.org/TR/xmlschema-2/#long
    if _XS_LONG_RE.fullmatch(text) is None:
        raise DeserializationException(
            f"Expected a value as xs:long, "
            f"but got an element with text: {text!r}"
        )

    try:
        value = int(text)
    except ValueError:
        # pylint: disable=raise-missing-from
        raise DeserializationException(
            f"Expected an integer, "
            f"but got an element with text: {text!r}"
        )

    return value


def _read_str_from_element_text(
    element: Element,
    iterator: Iterator[Tuple[str, Element]]
) -> str:
    """
    Parse the text of :paramref:`element` as a string, and
    read the corresponding end element from :paramref:`iterator`.

    If there is no text, empty string is returned.

    :param element: start element
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed value
    """
    # NOTE (mristin):
    # We do not use ``_read_text_from_element`` as that function expects
    # the ``element`` to contain *some* text. In contrast, this function
    # can also deal with empty text, in which case it returns an empty string.

    text = element.text

    end_element = _read_end_element(
        element,
        iterator
    )

    if text is None:
        text = end_element.text

    _raise_if_has_tail_or_attrib(element)
    result = (
        text
        if text is not None
        else ""
    )

    return result


def _read_enum_from_element_text(
    element: Element,
    iterator: Iterator[Tuple[str, Element]],
    literal_from_str: Callable[[str], Optional[_ValueT]],
    enum_name: str
) -> _ValueT:
    """
    Parse the text of :paramref:`element` as an enumeration literal, and read
    the corresponding end element from :paramref:`iterator`.

    :param element: start element
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :param literal_from_str: to parse the literal from its string representation
    :param enum_name: name of the enumeration, for the error messages
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed literal
    """
    text = _read_text_from_element(
        element,
        iterator
    )

    literal = literal_from_str(text)
    if literal is None:
        raise DeserializationException(
            f"Not a valid string representation of "
            f"a literal of {enum_name}: {text}"
        )

    return literal


_TupleItem1T = TypeVar("_TupleItem1T")
_TupleItem2T = TypeVar("_TupleItem2T")
_TupleItem3T = TypeVar("_TupleItem3T")
_TupleItem4T = TypeVar("_TupleItem4T")
_TupleItem5T = TypeVar("_TupleItem5T")
_TupleItem6T = TypeVar("_TupleItem6T")


def _tuple2_from_element(
    element: Element,
    iterator: Iterator[Tuple[str, Element]],
    read_item_1: _ContentReader[_TupleItem1T],
    read_item_2: _ContentReader[_TupleItem2T]
) -> Tuple[_TupleItem1T, _TupleItem2T]:
    """
    Read a tuple of 2 item(s) from :paramref:`iterator`.

    Each ``read_item_*`` function is responsible for verifying the tag of its
    own item element -- *e.g.*, by wrapping a scalar/enumeration reader with
    :py:func:`_read_named_element`, or by relying on a class's own dispatch by
    its natural element tag.

    The end element corresponding to :paramref:`element` will be read as well.

    :param element: start element enclosing the tuple
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :param read_item_1: to read the item at the position 0, including its own end element
    :param read_item_2: to read the item at the position 1, including its own end element
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed tuple
    """
    if element.text is not None and len(element.text.strip()) != 0:
        raise DeserializationException(
            f"Expected only item elements and whitespace text, "
            f"but got text: {element.text!r}"
        )

    item_1 = _read_tuple_item(
        element,
        iterator,
        0,
        read_item_1
    )

    item_2 = _read_tuple_item(
        element,
        iterator,
        1,
        read_item_2
    )

    _read_end_element(element, iterator)

    return (
        item_1,
        item_2
    )


def _tuple6_from_element(
    element: Element,
    iterator: Iterator[Tuple[str, Element]],
    read_item_1: _ContentReader[_TupleItem1T],
    read_item_2: _ContentReader[_TupleItem2T],
    read_item_3: _ContentReader[_TupleItem3T],
    read_item_4: _ContentReader[_TupleItem4T],
    read_item_5: _ContentReader[_TupleItem5T],
    read_item_6: _ContentReader[_TupleItem6T]
) -> Tuple[_TupleItem1T, _TupleItem2T, _TupleItem3T, _TupleItem4T, _TupleItem5T, _TupleItem6T]:
    """
    Read a tuple of 6 item(s) from :paramref:`iterator`.

    Each ``read_item_*`` function is responsible for verifying the tag of its
    own item element -- *e.g.*, by wrapping a scalar/enumeration reader with
    :py:func:`_read_named_element`, or by relying on a class's own dispatch by
    its natural element tag.

    The end element corresponding to :paramref:`element` will be read as well.

    :param element: start element enclosing the tuple
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :param read_item_1: to read the item at the position 0, including its own end element
    :param read_item_2: to read the item at the position 1, including its own end element
    :param read_item_3: to read the item at the position 2, including its own end element
    :param read_item_4: to read the item at the position 3, including its own end element
    :param read_item_5: to read the item at the position 4, including its own end element
    :param read_item_6: to read the item at the position 5, including its own end element
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed tuple
    """
    if element.text is not None and len(element.text.strip()) != 0:
        raise DeserializationException(
            f"Expected only item elements and whitespace text, "
            f"but got text: {element.text!r}"
        )

    item_1 = _read_tuple_item(
        element,
        iterator,
        0,
        read_item_1
    )

    item_2 = _read_tuple_item(
        element,
        iterator,
        1,
        read_item_2
    )

    item_3 = _read_tuple_item(
        element,
        iterator,
        2,
        read_item_3
    )

    item_4 = _read_tuple_item(
        element,
        iterator,
        3,
        read_item_4
    )

    item_5 = _read_tuple_item(
        element,
        iterator,
        4,
        read_item_5
    )

    item_6 = _read_tuple_item(
        element,
        iterator,
        5,
        read_item_6
    )

    _read_end_element(element, iterator)

    return (
        item_1,
        item_2,
        item_3,
        item_4,
        item_5,
        item_6
    )


def _read_int__at_v1(
    element: Element,
    iterator: Iterator[Tuple[str, Element]]
) -> int:
    """
    Read the content of :paramref:`element`, which must be tagged
    ``v1``, as ``int``.
    """
    return _read_named_element(
        element,
        iterator,
        'v1',
        _read_int_from_element_text
    )


def _read_int__at_v2(
    element: Element,
    iterator: Iterator[Tuple[str, Element]]
) -> int:
    """
    Read the content of :paramref:`element`, which must be tagged
    ``v2``, as ``int``.
    """
    return _read_named_element(
        element,
        iterator,
        'v2',
        _read_int_from_element_text
    )


def _read_int__at_v5(
    element: Element,
    iterator: Iterator[Tuple[str, Element]]
) -> int:
    """
    Read the content of :paramref:`element`, which must be tagged
    ``v5``, as :py:class:`.types.PositiveInt`.
    """
    return _read_named_element(
        element,
        iterator,
        'v5',
        _read_int_from_element_text
    )


def _read_result__at_v6(
    element: Element,
    iterator: Iterator[Tuple[str, Element]]
) -> aas_types.Result:
    """
    Read the content of :paramref:`element`, which must be tagged
    ``v6``, as :py:class:`.types.Result`.
    """
    return _read_named_element(
        element,
        iterator,
        'v6',
        _read_result_from_element_text
    )


def _read_str__at_v1(
    element: Element,
    iterator: Iterator[Tuple[str, Element]]
) -> str:
    """
    Read the content of :paramref:`element`, which must be tagged
    ``v1``, as ``str``.
    """
    return _read_named_element(
        element,
        iterator,
        'v1',
        _read_str_from_element_text
    )


def _read_tuple2_of__abstract_item__abstract_item(
    element: Element,
    iterator: Iterator[Tuple[str, Element]]
) -> Tuple[aas_types.AbstractItem, aas_types.AbstractItem]:
    """
    Read the items of :paramref:`element` as a tuple of 2 item(s).
    """
    return _tuple2_from_element(
        element,
        iterator,
        _read_abstract_item_as_element,
        _read_abstract_item_as_element
    )


def _read_tuple2_of__str__int(
    element: Element,
    iterator: Iterator[Tuple[str, Element]]
) -> Tuple[str, int]:
    """
    Read the items of :paramref:`element` as a tuple of 2 item(s).
    """
    return _tuple2_from_element(
        element,
        iterator,
        _read_str__at_v1,
        _read_int__at_v2
    )


def _read_tuple6_of__int__some_item__abstract_item__some_item__int__result(
    element: Element,
    iterator: Iterator[Tuple[str, Element]]
) -> Tuple[
    int,
    aas_types.SomeItem,
    aas_types.AbstractItem,
    aas_types.SomeItem,
    int,
    aas_types.Result
]:
    """
    Read the items of :paramref:`element` as a tuple of 6 item(s).
    """
    return _tuple6_from_element(
        element,
        iterator,
        _read_int__at_v1,
        _read_some_item_as_element,
        _read_abstract_item_as_element,
        _read_some_item_as_element,
        _read_int__at_v5,
        _read_result__at_v6
    )


def _read_result_from_element_text(
    element: Element,
    iterator: Iterator[Tuple[str, Element]]
) -> aas_types.Result:
    """
    Parse the text of :paramref:`element` as a literal of
    :py:class:`.types.Result`, and read the corresponding
    end element from :paramref:`iterator`.

    :param element: start element
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed value
    """
    return _read_enum_from_element_text(
        element,
        iterator,
        aas_stringification.result_from_str,
        'Result'
    )


def _read_abstract_item_as_element(
    element: Element,
    iterator: Iterator[Tuple[str, Element]]
) -> aas_types.AbstractItem:
    """
    Read an instance of :py:class:`.types.AbstractItem` from
    :paramref:`iterator`, including the end element.

    :param element: start element
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed instance
    """
    return _read_dispatched(
        element,
        iterator,
        _DISPATCH_FOR_ABSTRACT_ITEM,
        "a concrete instance of 'AbstractItem'"
    )


def _read_some_item_as_sequence(
        element: Element,
        iterator: Iterator[Tuple[str, Element]]
) -> aas_types.SomeItem:
    """
    Read an instance of :py:class:`.types.SomeItem`
    as a sequence of XML-encoded properties.

    The end element corresponding to the :paramref:`element` will be
    read as well.

    :param element: start element, parent of the sequence
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed instance
    """
    values = _read_properties(
        element,
        iterator,
        _READERS_FOR_SOME_ITEM
    )

    the_name: Optional[str] = values.get('name')

    if the_name is None:
        raise DeserializationException(
            "The required property 'name' is missing"
        )

    return aas_types.SomeItem(
        the_name
    )


def _read_some_item_as_element(
    element: Element,
    iterator: Iterator[Tuple[str, Element]]
) -> aas_types.SomeItem:
    """
    Read an instance of :py:class:`.types.SomeItem` from
    :paramref:`iterator`, including the end element.

    :param element: start element
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed instance
    """
    return _read_named_element(
        element,
        iterator,
        'someItem',
        _read_some_item_as_sequence
    )


def _read_another_item_as_sequence(
        element: Element,
        iterator: Iterator[Tuple[str, Element]]
) -> aas_types.AnotherItem:
    """
    Read an instance of :py:class:`.types.AnotherItem`
    as a sequence of XML-encoded properties.

    The end element corresponding to the :paramref:`element` will be
    read as well.

    :param element: start element, parent of the sequence
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed instance
    """
    values = _read_properties(
        element,
        iterator,
        _READERS_FOR_ANOTHER_ITEM
    )

    the_serial_number: Optional[int] = values.get('serialNumber')

    if the_serial_number is None:
        raise DeserializationException(
            "The required property 'serialNumber' is missing"
        )

    return aas_types.AnotherItem(
        the_serial_number
    )


def _read_another_item_as_element(
    element: Element,
    iterator: Iterator[Tuple[str, Element]]
) -> aas_types.AnotherItem:
    """
    Read an instance of :py:class:`.types.AnotherItem` from
    :paramref:`iterator`, including the end element.

    :param element: start element
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed instance
    """
    return _read_named_element(
        element,
        iterator,
        'anotherItem',
        _read_another_item_as_sequence
    )


def _read_something_as_sequence(
        element: Element,
        iterator: Iterator[Tuple[str, Element]]
) -> aas_types.Something:
    """
    Read an instance of :py:class:`.types.Something`
    as a sequence of XML-encoded properties.

    The end element corresponding to the :paramref:`element` will be
    read as well.

    :param element: start element, parent of the sequence
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed instance
    """
    values = _read_properties(
        element,
        iterator,
        _READERS_FOR_SOMETHING
    )

    the_pair: Optional[Tuple[str, int]] = values.get('pair')
    the_items: Optional[Tuple[aas_types.AbstractItem, aas_types.AbstractItem]] = values.get(
        'items'
    )
    the_tricky: Optional[
        Tuple[
            int,
            aas_types.SomeItem,
            aas_types.AbstractItem,
            aas_types.SomeItem,
            int,
            aas_types.Result,
        ]
    ] = values.get(
        'tricky'
    )

    if the_pair is None:
        raise DeserializationException(
            "The required property 'pair' is missing"
        )

    if the_items is None:
        raise DeserializationException(
            "The required property 'items' is missing"
        )

    if the_tricky is None:
        raise DeserializationException(
            "The required property 'tricky' is missing"
        )

    return aas_types.Something(
        the_pair,
        the_items,
        the_tricky
    )


def _read_something_as_element(
    element: Element,
    iterator: Iterator[Tuple[str, Element]]
) -> aas_types.Something:
    """
    Read an instance of :py:class:`.types.Something` from
    :paramref:`iterator`, including the end element.

    :param element: start element
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed instance
    """
    return _read_named_element(
        element,
        iterator,
        'something',
        _read_something_as_sequence
    )


def _read_as_element(
    element: Element,
    iterator: Iterator[Tuple[str, Element]]
) -> aas_types.Class:
    """
    Read an instance from :paramref:`iterator`, including the end element.

    :param element: start element
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed instance
    """
    return _read_dispatched(
        element,
        iterator,
        _GENERAL_DISPATCH,
        'a concrete instance'
    )


#: Dispatch XML class names to read-as-sequence functions
#: corresponding to concrete descendants of AbstractItem
_DISPATCH_FOR_ABSTRACT_ITEM: Mapping[
    str,
    Callable[
        [
            Element,
            Iterator[Tuple[str, Element]]
        ],
        aas_types.AbstractItem
    ]
] = {
    'anotherItem': _read_another_item_as_sequence,
    'someItem': _read_some_item_as_sequence,
}


#: Dispatch XML class names to read-as-sequence functions
#: corresponding to the concrete classes
_GENERAL_DISPATCH: Mapping[
    str,
    Callable[
        [
            Element,
            Iterator[Tuple[str, Element]]
        ],
        aas_types.Class
    ]
] = {
    'someItem': _read_some_item_as_sequence,
    'anotherItem': _read_another_item_as_sequence,
    'something': _read_something_as_sequence,
}


#: Read the content of a property of
#: :py:class:`.types.SomeItem`, by the XML name of the property
_READERS_FOR_SOME_ITEM: Mapping[
    str,
    _ContentReader[Any]
] = {
    'name': _read_str_from_element_text,
}


#: Read the content of a property of
#: :py:class:`.types.AnotherItem`, by the XML name of the property
_READERS_FOR_ANOTHER_ITEM: Mapping[
    str,
    _ContentReader[Any]
] = {
    'serialNumber': _read_int_from_element_text,
}


#: Read the content of a property of
#: :py:class:`.types.Something`, by the XML name of the property
_READERS_FOR_SOMETHING: Mapping[
    str,
    _ContentReader[Any]
] = {
    'pair': _read_tuple2_of__str__int,
    'items': _read_tuple2_of__abstract_item__abstract_item,
    'tricky': _read_tuple6_of__int__some_item__abstract_item__some_item__int__result,
}


# endregion


# region Serialization


class SerializationException(Exception):
    """Signal that the XML serialization could not be performed."""

    #: Human-readable explanation of the exception's cause
    cause: Final[str]

    def __init__(
            self,
            cause: str
    ) -> None:
        """Initialize with the given :paramref:`cause` and an empty path."""
        self.cause = cause
        self._segments = []  # type: List[str]

    @property
    def path(self) -> str:
        """
        Render the path to the erroneous value as a Python access expression.

        The path points into the instance which you handed over for
        the serialization, and *not* into an XML document -- at the point of
        the failure, there is no document yet. For example, ``.submodels[0].id``
        tells you that the serialization broke on ``that.submodels[0].id``.

        Mind that the elements which the XML representation adds on top of
        the instance contribute no segment, as they correspond to no attribute
        access. This concerns the element enclosing the instance itself, and
        the element which designates the model type of the value of a property.
        """
        return ''.join(self._segments)

    def _prepend_property(self, name: str) -> None:
        """Insert the access to the property :paramref:`name` before the path."""
        self._segments.insert(0, f'.{name}')

    def _prepend_index(self, index: int) -> None:
        """Insert the access to the item at :paramref:`index` before the path."""
        self._segments.insert(0, f'[{index}]')

    def __str__(self) -> str:
        if len(self._segments) == 0:
            return self.cause

        return f'{self.path}: {self.cause}'


def _attribute_to_property(
        exception: Exception,
        prop_name: Optional[str]
) -> NoReturn:
    """
    Re-raise the :paramref:`exception` as a failure of the property
    :paramref:`prop_name`.

    Every writer funnels its failures through this function, so that the path to
    the culprit is built up as the stack unwinds: a writer knows the property whose
    value it writes, and nothing below it does.

    A :paramref:`prop_name` of ``None`` prepends nothing to the path. It does *not*
    mean that no property is involved. It means that the access which leads to
    the value is recorded by a writer further up the stack, so recording it here
    as well would spell one step of the path twice.

    For example, the writer of an item of a list is given no property name. The list
    writer records its own property and the loop over the items records the index, so
    that ``.submodel_elements[3]`` is assembled from ``submodel_elements`` above and
    ``3`` around the item. Were the item to contribute ``submodel_elements`` as well,
    the path would read ``.submodel_elements[3].submodel_elements``.

    Likewise, an instance nested in the element of a property is written by
    a dispatch on its run-time type, and a dispatch knows nothing about where
    the instance came from. It is :py:func:`_write_nested_element` above it which
    knows that the instance sits in ``.value``, so the writer which the dispatch
    selects contributes no segment of its own.

    The path therefore stays empty only when the value which broke *is* the one you
    handed over, which is the failure :py:func:`write` funnels here: there is no
    access leading to it to report.

    We deliberately catch *any* exception, and not only the failures of
    the underlying stream. The type annotations are not enforced at run-time, so
    a property can hold a value which we can not serialize, and telling you where
    that value sits is much more helpful than the bare exception. The original
    exception is kept as the cause of the raised one.

    :param exception: to be re-raised
    :param prop_name:
        name of the property, as spelled in Python, whose value is written, or
        ``None`` if the access to the value is recorded by an enclosing writer
    :raise: :py:class:`SerializationException` always
    """
    if isinstance(exception, SerializationException):
        if prop_name is not None:
            exception._prepend_property(prop_name)

        raise exception

    failure = SerializationException(str(exception))
    if prop_name is not None:
        failure._prepend_property(prop_name)

    raise failure from exception


def _attribute_to_item(
        exception: Exception,
        index: int
) -> NoReturn:
    """
    Re-raise the :paramref:`exception` as a failure of the item at
    :paramref:`index`.

    This is the counterpart of :py:func:`_attribute_to_property` for the items of
    a list and of a tuple. The item's own element contributes no segment to
    the path: an item is selected by its position, and not by its element tag.

    :param exception: to be re-raised
    :param index: of the item which was being written
    :raise: :py:class:`SerializationException` always
    """
    if isinstance(exception, SerializationException):
        exception._prepend_index(index)
        raise exception

    failure = SerializationException(str(exception))
    failure._prepend_index(index)
    raise failure from exception


def _write_int_as_element(
    name: str,
    prop_name: Optional[str],
    value: int,
    serializer: '_Serializer'
) -> None:
    """
    Write the :paramref:`value` of an integer enclosed in
    the :paramref:`name` element.

    :param name: of the corresponding element tag
    :param prop_name:
        name of the property, as spelled in Python, whose value is written, or
        ``None`` if the access to the value is recorded by an enclosing writer
    :param value: to be serialized
    :param serializer: to write to
    :raise: :py:class:`SerializationException` if the value could not be written
    """
    try:
        serializer._write_start_element(name)
        serializer.stream.write(str(value))
        serializer._write_end_element(name)
    except Exception as exception:
        _attribute_to_property(exception, prop_name)


def _write_str_as_element(
    name: str,
    prop_name: Optional[str],
    value: str,
    serializer: '_Serializer'
) -> None:
    """
    Write the :paramref:`value` of a string enclosed in
    the :paramref:`name` element.

    :param name: of the corresponding element tag
    :param prop_name:
        name of the property, as spelled in Python, whose value is written, or
        ``None`` if the access to the value is recorded by an enclosing writer
    :param value: to be serialized
    :param serializer: to write to
    :raise: :py:class:`SerializationException` if the value could not be written
    """
    try:
        serializer._write_start_element(name)

        # NOTE (mristin):
        # We ran ``timeit`` on manual code which escaped XML special characters with
        # a dictionary, and on another snippet which called three ``.replace()``.
        # The code with ``.replace()`` was an order of magnitude faster on our
        # computers.
        #
        # The escaping is written out here, and not put in a function of its own,
        # since a string is the commonest value in a meta-model and a call is not free.
        serializer.stream.write(
            value.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        )

        serializer._write_end_element(name)
    except Exception as exception:
        _attribute_to_property(exception, prop_name)


def _write_enum_as_element(
    name: str,
    prop_name: Optional[str],
    value: enum.Enum,
    serializer: '_Serializer'
) -> None:
    """
    Write the literal :paramref:`value` enclosed in the :paramref:`name` element.

    A literal is written as the text of the element, so this one writer serves every
    enumeration of the meta-model. The access to the literal's value is deliberately
    *not* spelled out at the call site: a :paramref:`value` which is not a literal
    of the enumeration would then break *before* this function is entered, and
    the failure could no longer be attributed to :paramref:`prop_name`.

    :param name: of the corresponding element tag
    :param prop_name:
        name of the property, as spelled in Python, whose value is written, or
        ``None`` if the access to the value is recorded by an enclosing writer
    :param value: to be serialized
    :param serializer: to write to
    :raise: :py:class:`SerializationException` if the value could not be written
    """
    try:
        _write_str_as_element(name, None, value.value, serializer)
    except Exception as exception:
        _attribute_to_property(exception, prop_name)


def _write_tuple2_of__abstract_item__abstract_item(
    name: str,
    prop_name: Optional[str],
    value: Tuple[aas_types.AbstractItem, aas_types.AbstractItem],
    serializer: '_Serializer'
) -> None:
    """
    Write the 2 item(s) of :paramref:`value` enclosed in
    the :paramref:`name` element.

    :param name: of the enclosing element
    :param prop_name:
        name of the property, as spelled in Python, whose value is written, or
        ``None`` if the access to the value is recorded by an enclosing writer
    :param value: to be serialized
    :param serializer: to write to
    :raise: :py:class:`SerializationException` if the value could not be written
    """
    try:
        serializer._write_start_element(name)

        try:
            serializer.visit(value[0])
        except Exception as exception:
            _attribute_to_item(exception, 0)

        try:
            serializer.visit(value[1])
        except Exception as exception:
            _attribute_to_item(exception, 1)

        serializer._write_end_element(name)
    except Exception as exception:
        _attribute_to_property(exception, prop_name)


def _write_tuple2_of__str__int(
    name: str,
    prop_name: Optional[str],
    value: Tuple[str, int],
    serializer: '_Serializer'
) -> None:
    """
    Write the 2 item(s) of :paramref:`value` enclosed in
    the :paramref:`name` element.

    :param name: of the enclosing element
    :param prop_name:
        name of the property, as spelled in Python, whose value is written, or
        ``None`` if the access to the value is recorded by an enclosing writer
    :param value: to be serialized
    :param serializer: to write to
    :raise: :py:class:`SerializationException` if the value could not be written
    """
    try:
        serializer._write_start_element(name)

        try:
            _write_str_as_element('v1', None, value[0], serializer)
        except Exception as exception:
            _attribute_to_item(exception, 0)

        try:
            _write_int_as_element('v2', None, value[1], serializer)
        except Exception as exception:
            _attribute_to_item(exception, 1)

        serializer._write_end_element(name)
    except Exception as exception:
        _attribute_to_property(exception, prop_name)


def _write_tuple6_of__int__some_item__abstract_item__some_item__int__result(
    name: str,
    prop_name: Optional[str],
    value: Tuple[
        int,
        aas_types.SomeItem,
        aas_types.AbstractItem,
        aas_types.SomeItem,
        int,
        aas_types.Result,
    ],
    serializer: '_Serializer'
) -> None:
    """
    Write the 6 item(s) of :paramref:`value` enclosed in
    the :paramref:`name` element.

    :param name: of the enclosing element
    :param prop_name:
        name of the property, as spelled in Python, whose value is written, or
        ``None`` if the access to the value is recorded by an enclosing writer
    :param value: to be serialized
    :param serializer: to write to
    :raise: :py:class:`SerializationException` if the value could not be written
    """
    try:
        serializer._write_start_element(name)

        try:
            _write_int_as_element('v1', None, value[0], serializer)
        except Exception as exception:
            _attribute_to_item(exception, 0)

        try:
            serializer.visit(value[1])
        except Exception as exception:
            _attribute_to_item(exception, 1)

        try:
            serializer.visit(value[2])
        except Exception as exception:
            _attribute_to_item(exception, 2)

        try:
            serializer.visit(value[3])
        except Exception as exception:
            _attribute_to_item(exception, 3)

        try:
            _write_int_as_element('v5', None, value[4], serializer)
        except Exception as exception:
            _attribute_to_item(exception, 4)

        try:
            _write_enum_as_element('v6', None, value[5], serializer)
        except Exception as exception:
            _attribute_to_item(exception, 5)

        serializer._write_end_element(name)
    except Exception as exception:
        _attribute_to_property(exception, prop_name)


def _write_some_item_as_element(
    name: str,
    prop_name: Optional[str],
    that: aas_types.SomeItem,
    serializer: '_Serializer'
) -> None:
    """
    Write :paramref:`that` enclosed in the :paramref:`name` element.

    :param name: of the element tag. Expected to contain no XML special characters.
    :param prop_name:
        name of the property, as spelled in Python, whose value is written, or
        ``None`` if the access to the value is recorded by an enclosing writer
    :param that: instance to be serialized
    :param serializer: to write to
    :raise: :py:class:`SerializationException` if the value could not be written
    """
    try:
        serializer._write_start_element(name)
        _write_str_as_element('name', 'name', that.name, serializer)
        serializer._write_end_element(name)
    except Exception as exception:
        _attribute_to_property(exception, prop_name)


def _write_another_item_as_element(
    name: str,
    prop_name: Optional[str],
    that: aas_types.AnotherItem,
    serializer: '_Serializer'
) -> None:
    """
    Write :paramref:`that` enclosed in the :paramref:`name` element.

    :param name: of the element tag. Expected to contain no XML special characters.
    :param prop_name:
        name of the property, as spelled in Python, whose value is written, or
        ``None`` if the access to the value is recorded by an enclosing writer
    :param that: instance to be serialized
    :param serializer: to write to
    :raise: :py:class:`SerializationException` if the value could not be written
    """
    try:
        serializer._write_start_element(name)
        _write_int_as_element(
            'serialNumber', 'serial_number', that.serial_number, serializer
        )
        serializer._write_end_element(name)
    except Exception as exception:
        _attribute_to_property(exception, prop_name)


def _write_something_as_element(
    name: str,
    prop_name: Optional[str],
    that: aas_types.Something,
    serializer: '_Serializer'
) -> None:
    """
    Write :paramref:`that` enclosed in the :paramref:`name` element.

    :param name: of the element tag. Expected to contain no XML special characters.
    :param prop_name:
        name of the property, as spelled in Python, whose value is written, or
        ``None`` if the access to the value is recorded by an enclosing writer
    :param that: instance to be serialized
    :param serializer: to write to
    :raise: :py:class:`SerializationException` if the value could not be written
    """
    try:
        serializer._write_start_element(name)
        _write_tuple2_of__str__int('pair', 'pair', that.pair, serializer)
        _write_tuple2_of__abstract_item__abstract_item(
            'items', 'items', that.items, serializer
        )
        _write_tuple6_of__int__some_item__abstract_item__some_item__int__result(
            'tricky', 'tricky', that.tricky, serializer
        )
        serializer._write_end_element(name)
    except Exception as exception:
        _attribute_to_property(exception, prop_name)


class _Serializer(aas_types.AbstractVisitor):
    """Encode instances as XML and write them to :py:attr:`~stream`."""

    #: Stream to be written to when we visit the instances
    stream: Final[TextIO]

    #: Method pointer to be invoked for writing the start element with or without
    #: specifying a namespace (depending on the state of the serializer)
    _write_start_element: Callable[
        [str],
        None
    ]

    #: Method pointer to be invoked for writing an empty element with or without
    #: specifying a namespace (depending on the state of the serializer)
    _write_empty_element: Callable[
        [str],
        None
    ]

    # NOTE (mristin):
    # The serialization procedure is quite rigid. We leverage the specifics of
    # the serialization procedure to optimize the code a bit.
    #
    # Namely, we model the writing of the XML elements as a state machine.
    # The namespace is only specified for the very first element. All the subsequent
    # elements will *not* have the namespace specified. We implement that behavior by
    # using pointers to methods, as Python treats the methods as first-class citizens.
    #
    # The ``_write_start_element`` will point to
    # ``_write_first_start_element_with_namespace`` on the *first* invocation.
    # Afterwards, it will be redirected to ``_write_start_element_without_namespace``.
    #
    # Analogously for ``_write_empty_element``.
    #
    # Please see the implementation for the details, but this should give you at least
    # a rough overview.

    def _write_first_start_element_with_namespace(
            self,
            name: str
    ) -> None:
        """
        Write the start element with the tag name :paramref:`name` and specify
        its namespace.

        The :py:attr:`~_write_start_element` is set to
        :py:meth:`~_write_start_element_without_namespace` after the first invocation
        of this method.

        :param name: of the element tag. Expected to contain no XML special characters.
        """
        self.stream.write(f'<{name} xmlns="{NAMESPACE}">')

        # NOTE (mristin):
        # Any subsequence call to `_write_start_element` or `_write_empty_element`
        # should not specify the namespace of the element as we specified now already
        # specified it.
        self._write_start_element = self._write_start_element_without_namespace
        self._write_empty_element = self._write_empty_element_without_namespace

    def _write_start_element_without_namespace(
            self,
            name: str
    ) -> None:
        """
        Write the start element with the tag name :paramref:`name`.

        The first element, written *before* this one, is expected to have been
        already written with the namespace specified.

        :param name: of the element tag. Expected to contain no XML special characters.
        """
        self.stream.write(f'<{name}>')

    def _write_end_element(
            self,
            name: str
    ) -> None:
        """
        Write the end element with the tag name :paramref:`name`.

        :param name: of the element tag. Expected to contain no XML special characters.
        """
        self.stream.write(f'</{name}>')

    def _write_first_empty_element_with_namespace(
            self,
            name: str
    ) -> None:
        """
        Write the first (and only) empty element with the tag name :paramref:`name`.

        No elements are expected to be written to the stream afterwards. The element
        includes the namespace specification.

        :param name: of the element tag. Expected to contain no XML special characters.
        """
        self.stream.write(f'<{name} xmlns="{NAMESPACE}"/>')
        self._write_empty_element = self._rase_if_write_element_called_again
        self._write_start_element = self._rase_if_write_element_called_again

    def _rase_if_write_element_called_again(
            self,
            name: str
    ) -> None:
        raise AssertionError(
            f"We expected to call ``_write_first_empty_element_with_namespace`` "
            f"only once. This is an unexpected second call for writing "
            f"an (empty or non-empty) element with the tag name: {name!r}"
        )

    def _write_empty_element_without_namespace(
            self,
            name: str
    ) -> None:
        """
        Write the empty element with the tag name :paramref:`name`.

        The call to this method is expected to occur *after* the enclosing element with
        a specified namespace has been written.

        :param name: of the element tag. Expected to contain no XML special characters.
        """
        self.stream.write(f'<{name}/>')

    def __init__(
        self,
        stream: TextIO
    ) -> None:
        """
        Initialize the visitor to write to :paramref:`stream`.

        The first element will include the :py:attr:`~.NAMESPACE`. Every other
        element will not have the namespace specified.

        :param stream: where to write to
        """
        self.stream = stream
        self._write_start_element = (
            self._write_first_start_element_with_namespace
        )
        self._write_empty_element = (
            self._write_first_empty_element_with_namespace
        )

    def visit_some_item(
        self,
        that: aas_types.SomeItem
    ) -> None:
        """
        Serialize :paramref:`that` to :py:attr:`~stream` as an XML element.

        The enclosing XML element designates the class of the instance, where its
        children correspond to the properties of the instance.

        :param that: instance to be serialized
        """
        _write_some_item_as_element('someItem', None, that, self)

    def visit_another_item(
        self,
        that: aas_types.AnotherItem
    ) -> None:
        """
        Serialize :paramref:`that` to :py:attr:`~stream` as an XML element.

        The enclosing XML element designates the class of the instance, where its
        children correspond to the properties of the instance.

        :param that: instance to be serialized
        """
        _write_another_item_as_element('anotherItem', None, that, self)

    def visit_something(
        self,
        that: aas_types.Something
    ) -> None:
        """
        Serialize :paramref:`that` to :py:attr:`~stream` as an XML element.

        The enclosing XML element designates the class of the instance, where its
        children correspond to the properties of the instance.

        :param that: instance to be serialized
        """
        _write_something_as_element('something', None, that, self)


def write(instance: aas_types.Class, stream: TextIO) -> None:
    """
    Write the XML representation of :paramref:`instance` to :paramref:`stream`.

    Example usage:

    .. code-block::

        import pathlib

        import dummy.types as aas_types
        import dummy.xmlization as aas_xmlization

        instance = SomeItem(
           ... # some constructor arguments
        )

        pth = pathlib.Path(...)
        with pth.open("wt") as fid:
            aas_xmlization.write(instance, fid)

    :param instance: to be serialized
    :param stream: to write to
    :raise:
        :py:class:`SerializationException` if :paramref:`instance` could not be
        serialized
    """
    serializer = _Serializer(stream)

    try:
        serializer.visit(instance)
    except Exception as exception:
        _attribute_to_property(exception, None)


def to_str(that: aas_types.Class) -> str:
    """
    Serialize :paramref:`that` to an XML-encoded text.

    :param that: instance to be serialized
    :raise:
        :py:class:`SerializationException` if :paramref:`that` could not be
        serialized
    :return: :paramref:`that` serialized to XML serialized to text
    """
    writer = io.StringIO()
    write(that, writer)
    return writer.getvalue()


# endregion
