/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package dummy.enhancing;

import java.lang.Iterable;
import java.util.Optional;
import java.util.List;
import dummy.common.*;
import dummy.visitation.IVisitor;
import dummy.visitation.IVisitorWithContext;
import dummy.visitation.ITransformer;
import dummy.visitation.ITransformerWithContext;
import dummy.types.enums.*;
import dummy.types.impl.*;
import dummy.types.model.*;

public class EnhancedLeaf<EnhancementT>
  extends Enhanced<EnhancementT>
  implements ILeaf {
  private final ILeaf instance;

  public EnhancedLeaf(
    ILeaf instance,
    EnhancementT enhancement
  ) {
    super(enhancement);
    this.instance = instance;
  }

  @Override
  public String getIdentifier() {
    return instance.getIdentifier();
  }

  @Override
  public void setIdentifier(String identifier) {
    instance.setIdentifier(identifier);
  }

  @Override
  public String getText() {
    return instance.getText();
  }

  @Override
  public void setText(String text) {
    instance.setText(text);
  }

  public Iterable<IClass> descendOnce() {
    return instance.descendOnce();
  }

  public Iterable<IClass> descend() {
    return instance.descend();
  }

  public void accept(IVisitor visitor) {
    visitor.visitLeaf(instance);
  }

  public <ContextT> void accept(
    IVisitorWithContext<ContextT> visitor,
    ContextT context
  ) {
    visitor.visitLeaf(instance, context);
  }

  public <T> T transform(ITransformer<T> transformer) {
    return transformer.transformLeaf(instance);
  }

  public <ContextT, T> T transform(
    ITransformerWithContext<ContextT, T> transformer,
    ContextT context
  ) {
    return transformer.transformLeaf(instance, context);
  }
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
