/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package dummy.enhancing;

import java.lang.Iterable;
import java.util.Optional;
import java.util.List;
import dummy.common.*;
import dummy.visitation.IVisitor;
import dummy.visitation.IVisitorWithContext;
import dummy.visitation.ITransformer;
import dummy.visitation.ITransformerWithContext;
import dummy.types.enums.*;
import dummy.types.impl.*;
import dummy.types.model.*;

public class EnhancedGlobalAttribute<EnhancementT>
  extends Enhanced<EnhancementT>
  implements IGlobalAttribute {
  private final IGlobalAttribute instance;

  public EnhancedGlobalAttribute(
    IGlobalAttribute instance,
    EnhancementT enhancement
  ) {
    super(enhancement);
    this.instance = instance;
  }

  @Override
  public String getKind() {
    return instance.getKind();
  }

  @Override
  public void setKind(String kind) {
    instance.setKind(kind);
  }

  public Iterable<IClass> descendOnce() {
    return instance.descendOnce();
  }

  public Iterable<IClass> descend() {
    return instance.descend();
  }

  public void accept(IVisitor visitor) {
    visitor.visitGlobalAttribute(instance);
  }

  public <ContextT> void accept(
    IVisitorWithContext<ContextT> visitor,
    ContextT context
  ) {
    visitor.visitGlobalAttribute(instance, context);
  }

  public <T> T transform(ITransformer<T> transformer) {
    return transformer.transformGlobalAttribute(instance);
  }

  public <ContextT, T> T transform(
    ITransformerWithContext<ContextT, T> transformer,
    ContextT context
  ) {
    return transformer.transformGlobalAttribute(instance, context);
  }
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
