/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package dummy.visitation;

import dummy.types.model.*;
import dummy.visitation.IVisitorWithContext;

/**
 * Perform double-dispatch to visit the concrete instances
 * with context.
 *
 * @param <ContextT> structure of the context
 */
public abstract class AbstractVisitorWithContext<ContextT>
  implements IVisitorWithContext<ContextT>
{
  public void visit(IClass that, ContextT context)
  {
    that.accept(this, context);
  }
  public abstract void visitLeaf(
    ILeaf that,
    ContextT context
  );
  public abstract void visitOrderedContainer(
    IOrderedContainer that,
    ContextT context
  );
  public abstract void visitUnorderedContainer(
    IUnorderedContainer that,
    ContextT context
  );
  public abstract void visitGlobalAttribute(
    IGlobalAttribute that,
    ContextT context
  );
  public abstract void visitLocalAttribute(
    ILocalAttribute that,
    ContextT context
  );
  public abstract void visitAttributeOperand(
    IAttributeOperand that,
    ContextT context
  );
  public abstract void visitStringLiteral(
    IStringLiteral that,
    ContextT context
  );
  public abstract void visitNumberLiteral(
    INumberLiteral that,
    ContextT context
  );
  public abstract void visitSomething(
    ISomething that,
    ContextT context
  );
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
