package aastesting

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import (
	"fmt"
	aastypes "github.com/dummy-works/dummy/types"
)

// Perform a comparison for deep equality between `that` and `other` instance.
//
// The deep equality means that all the properties are checked for equality recursively.
func deepEqualLeaf(
	that aastypes.ILeaf,
	other aastypes.ILeaf,
) bool {
	thatIdentifier := that.Identifier()
	otherIdentifier := other.Identifier()
	if thatIdentifier != otherIdentifier {
		return false
	}

	thatText := that.Text()
	otherText := other.Text()
	if thatText != otherText {
		return false
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` instance.
//
// The deep equality means that all the properties are checked for equality recursively.
func deepEqualOrderedContainer(
	that aastypes.IOrderedContainer,
	other aastypes.IOrderedContainer,
) bool {
	thatIdentifier := that.Identifier()
	otherIdentifier := other.Identifier()
	if thatIdentifier != otherIdentifier {
		return false
	}

	thatChildren := that.Children()
	otherChildren := other.Children()
	if 
		len(thatChildren) !=
		len(otherChildren) {
		return false
	}
	for i := range thatChildren {
		if !DeepEqual(
			thatChildren[i],
			otherChildren[i],
		) {
			return false
		}
	}

	thatIsSorted := that.IsSorted()
	otherIsSorted := other.IsSorted()
	if thatIsSorted != otherIsSorted {
		return false
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` instance.
//
// The deep equality means that all the properties are checked for equality recursively.
func deepEqualUnorderedContainer(
	that aastypes.IUnorderedContainer,
	other aastypes.IUnorderedContainer,
) bool {
	thatIdentifier := that.Identifier()
	otherIdentifier := other.Identifier()
	if thatIdentifier != otherIdentifier {
		return false
	}

	thatChildren := that.Children()
	otherChildren := other.Children()
	if 
		len(thatChildren) !=
		len(otherChildren) {
		return false
	}
	for i := range thatChildren {
		if !DeepEqual(
			thatChildren[i],
			otherChildren[i],
		) {
			return false
		}
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` instance.
//
// The deep equality means that all the properties are checked for equality recursively.
func deepEqualGlobalAttribute(
	that aastypes.IGlobalAttribute,
	other aastypes.IGlobalAttribute,
) bool {
	thatKind := that.Kind()
	otherKind := other.Kind()
	if thatKind != otherKind {
		return false
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` instance.
//
// The deep equality means that all the properties are checked for equality recursively.
func deepEqualLocalAttribute(
	that aastypes.ILocalAttribute,
	other aastypes.ILocalAttribute,
) bool {
	thatName := that.Name()
	otherName := other.Name()
	if thatName != otherName {
		return false
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` instance.
//
// The deep equality means that all the properties are checked for equality recursively.
func deepEqualAttributeOperand(
	that aastypes.IAttributeOperand,
	other aastypes.IAttributeOperand,
) bool {
	thatAttribute := that.Attribute()
	otherAttribute := other.Attribute()
	if !DeepEqual(
		thatAttribute.Underlying(),
		otherAttribute.Underlying(),
	) {
		return false
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` instance.
//
// The deep equality means that all the properties are checked for equality recursively.
func deepEqualStringLiteral(
	that aastypes.IStringLiteral,
	other aastypes.IStringLiteral,
) bool {
	thatText := that.Text()
	otherText := other.Text()
	if thatText != otherText {
		return false
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` instance.
//
// The deep equality means that all the properties are checked for equality recursively.
func deepEqualNumberLiteral(
	that aastypes.INumberLiteral,
	other aastypes.INumberLiteral,
) bool {
	thatNumber := that.Number()
	otherNumber := other.Number()
	if thatNumber != otherNumber {
		return false
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` instance.
//
// The deep equality means that all the properties are checked for equality recursively.
func deepEqualSomething(
	that aastypes.ISomething,
	other aastypes.ISomething,
) bool {
	thatRoot := that.Root()
	otherRoot := other.Root()
	if !DeepEqual(
		thatRoot,
		otherRoot,
	) {
		return false
	}

	thatOptionalElement := that.OptionalElement()
	otherOptionalElement := other.OptionalElement()
	if
		(thatOptionalElement == nil && otherOptionalElement != nil) ||
		(thatOptionalElement != nil && otherOptionalElement == nil) {
		return false
	}
	if thatOptionalElement != nil {
		if !DeepEqual(
			thatOptionalElement,
			otherOptionalElement,
		) {
			return false
		}
	}

	thatValue := that.Value()
	otherValue := other.Value()
	if !DeepEqual(
		thatValue.Underlying(),
		otherValue.Underlying(),
	) {
		return false
	}

	thatValues := that.Values()
	otherValues := other.Values()
	if 
		len(thatValues) !=
		len(otherValues) {
		return false
	}
	for i := range thatValues {
		if !DeepEqual(
			thatValues[i].Underlying(),
			otherValues[i].Underlying(),
		) {
			return false
		}
	}

	return true
}

func DeepEqual(
	that aastypes.IClass,
	other aastypes.IClass,
) bool {
	if that.ModelType() != other.ModelType() {
		return false
	}

	switch that.ModelType() {
	case aastypes.ModelTypeLeaf:
		return deepEqualLeaf(
			that.(aastypes.ILeaf),
			other.(aastypes.ILeaf),
		)
	case aastypes.ModelTypeOrderedContainer:
		return deepEqualOrderedContainer(
			that.(aastypes.IOrderedContainer),
			other.(aastypes.IOrderedContainer),
		)
	case aastypes.ModelTypeUnorderedContainer:
		return deepEqualUnorderedContainer(
			that.(aastypes.IUnorderedContainer),
			other.(aastypes.IUnorderedContainer),
		)
	case aastypes.ModelTypeGlobalAttribute:
		return deepEqualGlobalAttribute(
			that.(aastypes.IGlobalAttribute),
			other.(aastypes.IGlobalAttribute),
		)
	case aastypes.ModelTypeLocalAttribute:
		return deepEqualLocalAttribute(
			that.(aastypes.ILocalAttribute),
			other.(aastypes.ILocalAttribute),
		)
	case aastypes.ModelTypeAttributeOperand:
		return deepEqualAttributeOperand(
			that.(aastypes.IAttributeOperand),
			other.(aastypes.IAttributeOperand),
		)
	case aastypes.ModelTypeStringLiteral:
		return deepEqualStringLiteral(
			that.(aastypes.IStringLiteral),
			other.(aastypes.IStringLiteral),
		)
	case aastypes.ModelTypeNumberLiteral:
		return deepEqualNumberLiteral(
			that.(aastypes.INumberLiteral),
			other.(aastypes.INumberLiteral),
		)
	case aastypes.ModelTypeSomething:
		return deepEqualSomething(
			that.(aastypes.ISomething),
			other.(aastypes.ISomething),
		)
	}

	panic(fmt.Sprintf("Unexpected model type: %d", that.ModelType()))
}

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
