/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package dummy.tests;

import static org.junit.jupiter.api.Assertions.assertEquals;

import dummy.jsonization.Jsonization;
import dummy.reporting.*;
import dummy.types.impl.*;
import dummy.types.model.*;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import org.junit.jupiter.api.Test;

public class TestJsonizationOfInterfaces {
  @Test
  public void testRoundTripIElementFromLeaf()
    throws IOException, JsonProcessingException {
    final ObjectMapper objectMapper = new ObjectMapper();

    Leaf instance = CommonJsonization.loadMaximalLeaf();
    final JsonNode jsonObject = Jsonization.Serialize.toJsonObject(instance);

    IElement anotherInstance = Jsonization.Deserialize.deserializeIElement(
      jsonObject);
    final JsonNode anotherJsonObject = Jsonization.Serialize.toJsonObject(anotherInstance);

    assertEquals(
      objectMapper.readTree(jsonObject.toString()), objectMapper.readTree(anotherJsonObject.toString()));
  } // void testRoundTripIElementFromLeaf

  @Test
  public void testRoundTripIElementFromOrderedContainer()
    throws IOException, JsonProcessingException {
    final ObjectMapper objectMapper = new ObjectMapper();

    OrderedContainer instance = CommonJsonization.loadMaximalOrderedContainer();
    final JsonNode jsonObject = Jsonization.Serialize.toJsonObject(instance);

    IElement anotherInstance = Jsonization.Deserialize.deserializeIElement(
      jsonObject);
    final JsonNode anotherJsonObject = Jsonization.Serialize.toJsonObject(anotherInstance);

    assertEquals(
      objectMapper.readTree(jsonObject.toString()), objectMapper.readTree(anotherJsonObject.toString()));
  } // void testRoundTripIElementFromOrderedContainer

  @Test
  public void testRoundTripIElementFromUnorderedContainer()
    throws IOException, JsonProcessingException {
    final ObjectMapper objectMapper = new ObjectMapper();

    UnorderedContainer instance = CommonJsonization.loadMaximalUnorderedContainer();
    final JsonNode jsonObject = Jsonization.Serialize.toJsonObject(instance);

    IElement anotherInstance = Jsonization.Deserialize.deserializeIElement(
      jsonObject);
    final JsonNode anotherJsonObject = Jsonization.Serialize.toJsonObject(anotherInstance);

    assertEquals(
      objectMapper.readTree(jsonObject.toString()), objectMapper.readTree(anotherJsonObject.toString()));
  } // void testRoundTripIElementFromUnorderedContainer

  @Test
  public void testRoundTripIContainerFromOrderedContainer()
    throws IOException, JsonProcessingException {
    final ObjectMapper objectMapper = new ObjectMapper();

    OrderedContainer instance = CommonJsonization.loadMaximalOrderedContainer();
    final JsonNode jsonObject = Jsonization.Serialize.toJsonObject(instance);

    IContainer anotherInstance = Jsonization.Deserialize.deserializeIContainer(
      jsonObject);
    final JsonNode anotherJsonObject = Jsonization.Serialize.toJsonObject(anotherInstance);

    assertEquals(
      objectMapper.readTree(jsonObject.toString()), objectMapper.readTree(anotherJsonObject.toString()));
  } // void testRoundTripIContainerFromOrderedContainer

  @Test
  public void testRoundTripIContainerFromUnorderedContainer()
    throws IOException, JsonProcessingException {
    final ObjectMapper objectMapper = new ObjectMapper();

    UnorderedContainer instance = CommonJsonization.loadMaximalUnorderedContainer();
    final JsonNode jsonObject = Jsonization.Serialize.toJsonObject(instance);

    IContainer anotherInstance = Jsonization.Deserialize.deserializeIContainer(
      jsonObject);
    final JsonNode anotherJsonObject = Jsonization.Serialize.toJsonObject(anotherInstance);

    assertEquals(
      objectMapper.readTree(jsonObject.toString()), objectMapper.readTree(anotherJsonObject.toString()));
  } // void testRoundTripIContainerFromUnorderedContainer
} // class TestJsonizationOfInterfaces

// package dummy.tests

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
