"""
Read and write AAS models as XML.

For reading, we provide different reading functions, each handling a different kind
of input. All the reading functions operate in one pass, *i.e.*, the source is read
incrementally and the complete XML is not held in memory.

We provide the following four reading functions (where ``X`` represents the name of
the class):

1) ``X_from_iterparse`` reads from a stream of ``(event, element)`` tuples coming from
   :py:func:`xml.etree.ElementTree.iterparse` with the argument
   ``events=["start", "end"]``. If you do not trust the source, please consider
   using `defusedxml.ElementTree`_.
2) ``X_from_stream`` reads from the given text stream.
3) ``X_from_file`` reads from a file on disk.
4) ``X_from_str`` reads from the given string.

The functions ``X_from_stream``, ``X_from_file`` and ``X_from_str`` provide
an extra parameter, ``has_iterparse``, which allows you to use a parsing library
different from :py:mod:`xml.etree.ElementTree`. For example, you can pass in
`defusedxml.ElementTree`_.

.. _defusedxml.ElementTree: https://pypi.org/project/defusedxml/#defusedxml-elementtree

All XML elements are expected to live in the :py:attr:`~NAMESPACE`.

For writing, use the function :py:func:`dummy.xmlization.write` which
translates the instance of the model into an XML document and writes it in one pass
to the stream.

Here is an example usage how to de-serialize from a file:

.. code-block::

    import pathlib
    import xml.etree.ElementTree as ET

    import dummy.xmlization as aas_xmlization

    path = pathlib.Path(...)
    instance = aas_xmlization.read_something_from_file(
        path
    )

    # Do something with the ``instance``

Here is another code example where we serialize the instance:

.. code-block::

    import pathlib

    import dummy.types as aas_types
    import dummy.xmlization as aas_xmlization

    instance = Something(
       ... # some constructor arguments
    )

    pth = pathlib.Path(...)
    with pth.open("wt") as fid:
        aas_xmlization.write(instance, fid)
"""


# This code has been automatically generated by aas-core-codegen.
# Do NOT edit or append.


import base64
import io
import math
import os
import sys
from typing import (
    Any,
    Callable,
    Dict,
    Iterator,
    List,
    Mapping,
    Optional,
    Sequence,
    TextIO,
    Tuple,
    TypeVar,
    Union,
    TYPE_CHECKING
)
import xml.etree.ElementTree

if sys.version_info >= (3, 8):
    from typing import (
        Final,
        Protocol
    )
else:
    from typing_extensions import (
        Final,
        Protocol
    )

import dummy.stringification as aas_stringification
import dummy.types as aas_types

# See: https://stackoverflow.com/questions/55076778/why-isnt-this-function-type-annotated-correctly-error-missing-type-parameters
if TYPE_CHECKING:
    PathLike = os.PathLike[Any]
else:
    PathLike = os.PathLike


#: XML namespace in which all the elements are expected to reside
NAMESPACE = 'https://dummy.com'


# region De-serialization


#: XML namespace as a prefix specially tailored for
#: :py:mod:`xml.etree.ElementTree`
_NAMESPACE_IN_CURLY_BRACKETS = f'{{{NAMESPACE}}}'


class Element(Protocol):
    """Behave like :py:meth:`xml.etree.ElementTree.Element`."""

    @property
    def attrib(self) -> Optional[Mapping[str, str]]:
        """Attributes of the element"""
        raise NotImplementedError()

    @property
    def text(self) -> Optional[str]:
        """Text content of the element"""
        raise NotImplementedError()

    @property
    def tail(self) -> Optional[str]:
        """Tail text of the element"""
        raise NotImplementedError()

    @property
    def tag(self) -> str:
        """Tag of the element; with a namespace provided as a ``{...}`` prefix"""
        raise NotImplementedError()

    def clear(self) -> None:
        """Behave like :py:meth:`xml.etree.ElementTree.Element.clear`."""
        raise NotImplementedError()


class HasIterparse(Protocol):
    """Parse an XML document incrementally."""

    # NOTE (mristin, 2022-10-26):
    # ``self`` is not used in this context, but is necessary for Mypy,
    # see: https://github.com/python/mypy/issues/5018 and
    # https://github.com/python/mypy/commit/3efbc5c5e910296a60ed5b9e0e7eb11dd912c3ed#diff-e165eb7aed9dca0a5ebd93985c8cd263a6462d36ac185f9461348dc5a1396d76R9937

    def iterparse(
            self,
            source: TextIO,
            events: Optional[Sequence[str]] = None
    ) -> Iterator[Tuple[str, Element]]:
        """Behave like :py:func:`xml.etree.ElementTree.iterparse`."""


class ElementSegment:
    """Represent an element on a path to the erroneous value."""
    #: Erroneous element
    element: Final[Element]

    def __init__(
            self,
            element: Element
    ) -> None:
        """Initialize with the given values."""
        self.element = element

    def __str__(self) -> str:
        """
        Render the segment as a tag without the namespace.

        We deliberately omit the namespace in the tag names. If you want to actually
        query with the resulting XPath, you have to insert the namespaces manually.
        We did not know how to include the namespace in a meaningful way, as XPath
        assumes namespace prefixes to be defined *outside* of the document. At least
        the path thus rendered is informative, and you should be able to descend it
        manually.
        """
        _, has_namespace, tag_wo_ns = self.element.tag.rpartition('}')
        if not has_namespace:
            return self.element.tag
        else:
            return tag_wo_ns


class IndexSegment:
    """Represent an element in a sequence on a path to the erroneous value."""
    #: Erroneous element
    element: Final[Element]

    #: Index of the element in the sequence
    index: Final[int]

    def __init__(
            self,
            element: Element,
            index: int
    ) -> None:
        """Initialize with the given values."""
        self.element = element
        self.index = index

    def __str__(self) -> str:
        """Render the segment as an element wildcard with the index."""
        return f'*[{self.index}]'


Segment = Union[ElementSegment, IndexSegment]


class Path:
    """Represent the relative path to the erroneous element."""

    def __init__(self) -> None:
        """Initialize as an empty path."""
        self._segments = []  # type: List[Segment]

    @property
    def segments(self) -> Sequence[Segment]:
        """Get the segments of the path."""
        return self._segments

    def _prepend(self, segment: Segment) -> None:
        """Insert the :paramref:`segment` in front of other segments."""
        self._segments.insert(0, segment)

    def __str__(self) -> str:
        """Render the path as a relative XPath.

        We omit the leading ``/`` so that you can easily prefix it as you need.
        """
        return "/".join(str(segment) for segment in self._segments)


class DeserializationException(Exception):
    """Signal that the XML de-serialization could not be performed."""

    #: Human-readable explanation of the exception's cause
    cause: Final[str]

    #: Relative path to the erroneous value
    path: Final[Path]

    def __init__(
            self,
            cause: str
    ) -> None:
        """Initialize with the given :paramref:`cause` and an empty path."""
        self.cause = cause
        self.path = Path()


def _with_elements_cleared_after_yield(
        iterator: Iterator[Tuple[str, Element]]
) -> Iterator[Tuple[str, Element]]:
    """
    Map the :paramref:`iterator` such that the element is ``clear()``'ed
    *after* every ``yield``.

    :param iterator: to be mapped
    :yield: event and element from :paramref:`iterator`
    """
    for event, element in iterator:
        yield event, element
        element.clear()


def something_from_iterparse(
    iterator: Iterator[Tuple[str, Element]]
) -> aas_types.Something:
    """
    Read an instance of :py:class:`.types.Something` from
    the :paramref:`iterator`.

    Example usage:

    .. code-block::

        import pathlib
        import xml.etree.ElementTree as ET

        import dummy.xmlization as aas_xmlization

        path = pathlib.Path(...)
        with path.open("rt") as fid:
            iterator = ET.iterparse(
                source=fid,
                events=['start', 'end']
            )
            instance = aas_xmlization.something_from_iterparse(
                iterator
            )

        # Do something with the ``instance``

    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.Something` read from
        :paramref:`iterator`
    """
    return _read_instance_from_iterparse(
        iterator,
        _read_something_as_element,
        'Something'
    )


def something_from_stream(
    stream: TextIO,
    has_iterparse: HasIterparse = xml.etree.ElementTree
) -> aas_types.Something:
    """
    Read an instance of :py:class:`.types.Something` from
    the :paramref:`stream`.

    Example usage:

    .. code-block::

        import dummy.xmlization as aas_xmlization

        with open_some_stream_over_network(...) as stream:
            instance = aas_xmlization.something_from_stream(
                stream
            )

        # Do something with the ``instance``

    :param stream:
        representing an instance of
        :py:class:`.types.Something` in XML
    :param has_iterparse:
        Module containing ``iterparse`` function.

        Default is to use :py:mod:`xml.etree.ElementTree` from the standard
        library. If you have to deal with malicious input, consider using
        a library such as `defusedxml.ElementTree`_.
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.Something` read from
        :paramref:`stream`
    """
    iterator = has_iterparse.iterparse(
        stream,
        ['start', 'end']
    )
    return something_from_iterparse(
        _with_elements_cleared_after_yield(iterator)
    )


def something_from_file(
    path: PathLike,
    has_iterparse: HasIterparse = xml.etree.ElementTree
) -> aas_types.Something:
    """
    Read an instance of :py:class:`.types.Something` from
    the :paramref:`path`.

    Example usage:

    .. code-block::

        import pathlib
        import dummy.xmlization as aas_xmlization

        path = pathlib.Path(...)
        instance = aas_xmlization.something_from_file(
            path
        )

        # Do something with the ``instance``

    :param path:
        to the file representing an instance of
        :py:class:`.types.Something` in XML
    :param has_iterparse:
        Module containing ``iterparse`` function.

        Default is to use :py:mod:`xml.etree.ElementTree` from the standard
        library. If you have to deal with malicious input, consider using
        a library such as `defusedxml.ElementTree`_.
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.Something` read from
        :paramref:`path`
    """
    with open(os.fspath(path), "rt", encoding='utf-8') as fid:
        iterator = has_iterparse.iterparse(
            fid,
            ['start', 'end']
        )
        return something_from_iterparse(
            _with_elements_cleared_after_yield(iterator)
        )


def something_from_str(
    text: str,
    has_iterparse: HasIterparse = xml.etree.ElementTree
) -> aas_types.Something:
    """
    Read an instance of :py:class:`.types.Something` from
    the :paramref:`text`.

    Example usage:

    .. code-block::

        import pathlib
        import dummy.xmlization as aas_xmlization

        text = "<...>...</...>"
        instance = aas_xmlization.something_from_str(
            text
        )

        # Do something with the ``instance``

    :param text:
        representing an instance of
        :py:class:`.types.Something` in XML
    :param has_iterparse:
        Module containing ``iterparse`` function.

        Default is to use :py:mod:`xml.etree.ElementTree` from the standard
        library. If you have to deal with malicious input, consider using
        a library such as `defusedxml.ElementTree`_.
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.Something` read from
        :paramref:`text`
    """
    iterator = has_iterparse.iterparse(
        io.StringIO(text),
        ['start', 'end']
    )
    return something_from_iterparse(
        _with_elements_cleared_after_yield(iterator)
    )


def from_iterparse(
    iterator: Iterator[Tuple[str, Element]]
) -> aas_types.Class:
    """
    Read an instance from the :paramref:`iterator`.

    The type of the instance is determined by the very first start element.

    Example usage:

    .. code-block::

        import pathlib
        import xml.etree.ElementTree as ET

        import dummy.xmlization as aas_xmlization

        path = pathlib.Path(...)
        with path.open("rt") as fid:
            iterator = ET.iterparse(
                source=fid,
                events=['start', 'end']
            )
            instance = aas_xmlization.from_iterparse(
                iterator
            )

        # Do something with the ``instance``

    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance of :py:class:`.types.Class` read from the :paramref:`iterator`
    """
    return _read_instance_from_iterparse(
        iterator,
        _read_as_element,
        'an instance'
    )


def from_stream(
    stream: TextIO,
    has_iterparse: HasIterparse = xml.etree.ElementTree
) -> aas_types.Class:
    """
    Read an instance from the :paramref:`stream`.

    The type of the instance is determined by the very first start element.

    Example usage:

    .. code-block::

        import dummy.xmlization as aas_xmlization

        with open_some_stream_over_network(...) as stream:
            instance = aas_xmlization.from_stream(
                stream
            )

        # Do something with the ``instance``

    :param stream:
        representing an instance in XML
    :param has_iterparse:
        Module containing ``iterparse`` function.

        Default is to use :py:mod:`xml.etree.ElementTree` from the standard
        library. If you have to deal with malicious input, consider using
        a library such as `defusedxml.ElementTree`_.
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance read from :paramref:`stream`
    """
    iterator = has_iterparse.iterparse(
        stream,
        ['start', 'end']
    )
    return from_iterparse(
        _with_elements_cleared_after_yield(iterator)
    )


def from_file(
    path: PathLike,
    has_iterparse: HasIterparse = xml.etree.ElementTree
) -> aas_types.Class:
    """
    Read an instance from the file at the :paramref:`path`.

    Example usage:

    .. code-block::

        import pathlib
        import dummy.xmlization as aas_xmlization

        path = pathlib.Path(...)
        instance = aas_xmlization.from_file(
            path
        )

        # Do something with the ``instance``

    :param path:
        to the file representing an instance in XML
    :param has_iterparse:
        Module containing ``iterparse`` function.

        Default is to use :py:mod:`xml.etree.ElementTree` from the standard
        library. If you have to deal with malicious input, consider using
        a library such as `defusedxml.ElementTree`_.
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance read from the file at :paramref:`path`
    """
    with open(os.fspath(path), "rt", encoding='utf-8') as fid:
        iterator = has_iterparse.iterparse(
            fid,
            ['start', 'end']
        )
        return from_iterparse(
            _with_elements_cleared_after_yield(iterator)
        )


def from_str(
    text: str,
    has_iterparse: HasIterparse = xml.etree.ElementTree
) -> aas_types.Class:
    """
    Read an instance from the :paramref:`text`.

    Example usage:

    .. code-block::

        import pathlib
        import dummy.xmlization as aas_xmlization

        text = "<...>...</...>"
        instance = aas_xmlization.from_str(
            text
        )

        # Do something with the ``instance``

    :param text:
        representing an instance in XML
    :param has_iterparse:
        Module containing ``iterparse`` function.

        Default is to use :py:mod:`xml.etree.ElementTree` from the standard
        library. If you have to deal with malicious input, consider using
        a library such as `defusedxml.ElementTree`_.
    :raise: :py:class:`DeserializationException` if unexpected input
    :return:
        Instance read from :paramref:`text`
    """
    iterator = has_iterparse.iterparse(
        io.StringIO(text),
        ['start', 'end']
    )
    return from_iterparse(
        _with_elements_cleared_after_yield(iterator)
    )


# NOTE (mristin, 2022-10-08):
# Directly using the iterator turned out to result in very complex function
# designs. The design became much simpler as soon as we considered one look-ahead
# element. We came up finally with the following pattern which all the protected
# reading functions below roughly follow:
#
# ..code-block::
#
#    _read_*(
#       look-ahead element,
#       iterator
#    ) -> result
#
# The reading functions all read from the ``iterator`` coming from
# :py:func:`xml.etree.ElementTree.iterparse` with the argument
# ``events=["start", "end"]``. The exception :py:class:`.DeserializationException`
# is raised in case of unexpected input.
#
# The reading functions are responsible to read the end element corresponding to the
# start look-ahead element.
#
# When it comes to error reporting, we use exceptions. The exceptions are raised in
# the *callee*, as usual. However, the context of the exception, such as the error path,
# is added in the *caller*, as only the caller knows the context of
# the lookahead-element. In particular, prepending the path segment corresponding to
# the lookahead-element is the responsibility of the *caller*, and not of
# the *callee*.


_ValueT = TypeVar("_ValueT")

#: Read the content of an element which has already been opened, and read
#: the corresponding end element as well
_ContentReader = Callable[
    [Element, Iterator[Tuple[str, Element]]],
    _ValueT
]


def _parse_element_tag(element: Element) -> str:
    """
    Extract the tag name without the namespace prefix from :paramref:`element`.

    :param element: whose tag without namespace we want to extract
    :return: tag name without the namespace prefix
    :raise: :py:class:`DeserializationException` if unexpected :paramref:`element`
    """
    if not element.tag.startswith(_NAMESPACE_IN_CURLY_BRACKETS):
        namespace, got_namespace, tag_wo_ns = (
            element.tag.rpartition('}')
        )
        if got_namespace:
            if namespace.startswith('{'):
                namespace = namespace[1:]

            raise DeserializationException(
                f"Expected the element in the namespace {NAMESPACE!r}, "
                f"but got the element {tag_wo_ns!r} in the namespace {namespace!r}"
            )
        else:
            raise DeserializationException(
                f"Expected the element in the namespace {NAMESPACE!r}, "
                f"but got the element {tag_wo_ns!r} without the namespace prefix"
            )

    return element.tag[len(_NAMESPACE_IN_CURLY_BRACKETS):]


def _raise_if_has_tail_or_attrib(
        element: Element
) -> None:
    """
    Check that :paramref:`element` has no trailing text and no attributes.

    :param element: to be verified
    :raise:
        :py:class:`.DeserializationException` if trailing text or attributes;
        conforming to the convention about handling error paths,
        the exception path is left empty.
    """
    if element.tail is not None and len(element.tail.strip()) != 0:
        raise DeserializationException(
            f"Expected no trailing text, but got: {element.tail!r}"
        )

    if element.attrib is not None and len(element.attrib) > 0:
        raise DeserializationException(
            f"Expected no attributes, but got: {element.attrib}"
        )


def _read_end_element(
        element: Element,
        iterator: Iterator[Tuple[str, Element]]
) -> Element:
    """
    Read the end element corresponding to the start :paramref:`element`
    from :paramref:`iterator`.

    :param element: corresponding start element
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    """
    next_event_element = next(iterator, None)
    if next_event_element is None:
        raise DeserializationException(
            f"Expected the end element for {element.tag}, "
            f"but got the end-of-input"
        )

    next_event, next_element = next_event_element
    if next_event != "end" or next_element.tag != element.tag:
        raise DeserializationException(
            f"Expected the end element for {element.tag!r}, "
            f"but got the event {next_event!r} and element {next_element.tag!r}"
        )

    _raise_if_has_tail_or_attrib(next_element)

    return next_element


def _read_named_element(
    element: Element,
    iterator: Iterator[Tuple[str, Element]],
    expected_tag: str,
    read_content: _ContentReader[_ValueT]
) -> _ValueT:
    """
    Verify that :paramref:`element` bears the :paramref:`expected_tag`, and
    delegate the reading of its content to :paramref:`read_content`.

    This is the only place where an element's tag is checked against the tag which
    its container prescribes -- the XML name of a class, ``<v>`` for a list item, or
    ``<v1>``, ``<v2>``, *etc.* for a tuple item.

    :param element: look-ahead element
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :param expected_tag: expected tag of :paramref:`element`
    :param read_content: to read the content of :paramref:`element`
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed value
    """
    tag_wo_ns = _parse_element_tag(element)
    if tag_wo_ns != expected_tag:
        raise DeserializationException(
            f"Expected an element with the tag {expected_tag!r}, "
            f"but got an element with tag: {tag_wo_ns!r}"
        )

    return read_content(element, iterator)


def _read_dispatched(
    element: Element,
    iterator: Iterator[Tuple[str, Element]],
    dispatch: Mapping[str, _ContentReader[_ValueT]],
    expected_what: str
) -> _ValueT:
    """
    Read the instance of :paramref:`element` by dispatching on its own tag.

    An instance element is self-describing: its tag *is* its model type.

    The end element corresponding to :paramref:`element` will be read as well.

    :param element: start element of the instance
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :param dispatch: to read the instance as a sequence, by its model type
    :param expected_what: what we expected to read, for the error messages
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed instance
    """
    tag_wo_ns = _parse_element_tag(element)

    read_as_sequence = dispatch.get(tag_wo_ns, None)
    if read_as_sequence is None:
        raise DeserializationException(
            f"Expected the element tag to be a valid model type "
            f"of {expected_what}, "
            f"but got tag {tag_wo_ns!r}"
        )

    return read_as_sequence(element, iterator)


def _read_properties(
    element: Element,
    iterator: Iterator[Tuple[str, Element]],
    readers: Mapping[str, _ContentReader[Any]]
) -> Mapping[str, Any]:
    """
    Read the properties of an instance as the children of :paramref:`element`.

    The end element corresponding to :paramref:`element` will be read as well.

    The property is marked on the error path here, once for all the properties,
    instead of in every reader: the tag of the child element *is* the XML name of
    the property which we are reading.

    :param element: start element, parent of the properties
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :param readers: to read the content of a property, by its XML name
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed values, by the XML name of the property
    """
    if element.text is not None and len(element.text.strip()) != 0:
        raise DeserializationException(
            f"Expected only XML elements representing the properties "
            f"and whitespace text, but got text: {element.text!r}"
        )

    _raise_if_has_tail_or_attrib(element)

    values = dict()  # type: Dict[str, Any]

    while True:
        # NOTE (mristin):
        # We pull the next property element here instead of delegating it to
        # a helper. A call is not free in Python, and this loop runs once for
        # every property of every instance.
        next_event_element = next(iterator, None)
        if next_event_element is None:
            raise DeserializationException(
                f"Expected a property element or the end element corresponding "
                f"to {element.tag}, but got the end-of-input"
            )

        next_event, prop_element = next_event_element
        if next_event == 'end' and prop_element.tag == element.tag:
            # We reached the end element enclosing the properties.
            break

        if next_event != 'start':
            raise DeserializationException(
                f"Expected a start element corresponding to a property, "
                f"but got event {next_event!r} "
                f"and element {prop_element.tag!r}"
            )

        try:
            tag_wo_ns = _parse_element_tag(prop_element)

            reader = readers.get(tag_wo_ns, None)
            if reader is None:
                raise DeserializationException(
                    f"Expected an element representing a property, "
                    f"but got an element with unexpected tag: {tag_wo_ns!r}"
                )

            values[tag_wo_ns] = reader(prop_element, iterator)
        except DeserializationException as exception:
            exception.path._prepend(ElementSegment(prop_element))
            raise

    return values


def _read_instance_from_iterparse(
    iterator: Iterator[Tuple[str, Element]],
    read_as_element: _ContentReader[_ValueT],
    expected_what: str
) -> _ValueT:
    """
    Read an instance from :paramref:`iterator`, starting at its start element.

    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :param read_as_element: to read the instance, including its end element
    :param expected_what: what we expected to read, for the error messages
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed instance
    """
    next_event_element = next(iterator, None)
    if next_event_element is None:
        raise DeserializationException(
            f"Expected the start element for {expected_what}, "
            f"but got the end-of-input"
        )

    next_event, next_element = next_event_element
    if next_event != 'start':
        raise DeserializationException(
            f"Expected the start element for {expected_what}, "
            f"but got event {next_event!r} and element {next_element.tag!r}"
        )

    try:
        return read_as_element(next_element, iterator)
    except DeserializationException as exception:
        exception.path._prepend(ElementSegment(next_element))
        raise exception


def _read_text_from_element(
    element: Element,
    iterator: Iterator[Tuple[str, Element]]
) -> str:
    """
    Extract the text from the :paramref:`element`, and read
    the end element from :paramref:`iterator`.

    The :paramref:`element` is expected to contain text. Otherwise,
    it is considered as unexpected input.

    :param element: start element enclosing the text
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    """
    _raise_if_has_tail_or_attrib(element)

    text = element.text

    end_element = _read_end_element(
        element,
        iterator,
    )

    if text is None:
        if end_element.text is None:
            raise DeserializationException(
                "Expected an element with text, but got an element with no text."
            )

        text = end_element.text

    return text


def _read_enum_from_element_text(
    element: Element,
    iterator: Iterator[Tuple[str, Element]],
    literal_from_str: Callable[[str], Optional[_ValueT]],
    enum_name: str
) -> _ValueT:
    """
    Parse the text of :paramref:`element` as an enumeration literal, and read
    the corresponding end element from :paramref:`iterator`.

    :param element: start element
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :param literal_from_str: to parse the literal from its string representation
    :param enum_name: name of the enumeration, for the error messages
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed literal
    """
    text = _read_text_from_element(
        element,
        iterator
    )

    literal = literal_from_str(text)
    if literal is None:
        raise DeserializationException(
            f"Not a valid string representation of "
            f"a literal of {enum_name}: {text}"
        )

    return literal


def _read_result_from_element_text(
    element: Element,
    iterator: Iterator[Tuple[str, Element]]
) -> aas_types.Result:
    """
    Parse the text of :paramref:`element` as a literal of
    :py:class:`.types.Result`, and read the corresponding
    end element from :paramref:`iterator`.

    :param element: start element
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed value
    """
    return _read_enum_from_element_text(
        element,
        iterator,
        aas_stringification.result_from_str,
        'Result'
    )


def _read_something_as_sequence(
        element: Element,
        iterator: Iterator[Tuple[str, Element]]
) -> aas_types.Something:
    """
    Read an instance of :py:class:`.types.Something`
    as a sequence of XML-encoded properties.

    The end element corresponding to the :paramref:`element` will be
    read as well.

    :param element: start element, parent of the sequence
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed instance
    """
    values = _read_properties(
        element,
        iterator,
        _READERS_FOR_SOMETHING
    )

    the_some_result: Optional[aas_types.Result] = values.get('someResult')

    if the_some_result is None:
        raise DeserializationException(
            "The required property 'someResult' is missing"
        )

    return aas_types.Something(
        the_some_result
    )


def _read_something_as_element(
    element: Element,
    iterator: Iterator[Tuple[str, Element]]
) -> aas_types.Something:
    """
    Read an instance of :py:class:`.types.Something` from
    :paramref:`iterator`, including the end element.

    :param element: start element
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed instance
    """
    return _read_named_element(
        element,
        iterator,
        'something',
        _read_something_as_sequence
    )


def _read_as_element(
    element: Element,
    iterator: Iterator[Tuple[str, Element]]
) -> aas_types.Class:
    """
    Read an instance from :paramref:`iterator`, including the end element.

    :param element: start element
    :param iterator:
        Input stream of ``(event, element)`` coming from
        :py:func:`xml.etree.ElementTree.iterparse` with the argument
        ``events=["start", "end"]``
    :raise: :py:class:`DeserializationException` if unexpected input
    :return: parsed instance
    """
    return _read_dispatched(
        element,
        iterator,
        _GENERAL_DISPATCH,
        'a concrete instance'
    )


#: Dispatch XML class names to read-as-sequence functions
#: corresponding to the concrete classes
_GENERAL_DISPATCH: Mapping[
    str,
    Callable[
        [
            Element,
            Iterator[Tuple[str, Element]]
        ],
        aas_types.Class
    ]
] = {
    'something': _read_something_as_sequence,
}


#: Read the content of a property of
#: :py:class:`.types.Something`, by the XML name of the property
_READERS_FOR_SOMETHING: Mapping[
    str,
    _ContentReader[Any]
] = {
    'someResult': _read_result_from_element_text,
}


# endregion


# region Serialization


def _write_str_as_element(
    name: str,
    value: str,
    serializer: '_Serializer'
) -> None:
    """
    Write the :paramref:`value` of a string enclosed in
    the :paramref:`name` element.

    :param name: of the corresponding element tag
    :param value: to be serialized
    :param serializer: to write to
    """
    serializer._write_start_element(name)

    # NOTE (mristin, 2022-10-14):
    # We ran ``timeit`` on manual code which escaped XML special characters with
    # a dictionary, and on another snippet which called three ``.replace()``.
    # The code with ``.replace()`` was an order of magnitude faster on our computers.
    #
    # The escaping is written out here, and not put in a function of its own, since
    # a string is the commonest value in a meta-model and a call is not free.
    serializer.stream.write(
        value.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    )

    serializer._write_end_element(name)


def _write_something_as_element(
    name: str,
    that: aas_types.Something,
    serializer: '_Serializer'
) -> None:
    """
    Write :paramref:`that` enclosed in the :paramref:`name` element.

    :param name: of the element tag. Expected to contain no XML special characters.
    :param that: instance to be serialized
    :param serializer: to write to
    """
    serializer._write_start_element(name)
    _write_str_as_element('someResult', that.some_result.value, serializer)
    serializer._write_end_element(name)


class _Serializer(aas_types.AbstractVisitor):
    """Encode instances as XML and write them to :py:attr:`~stream`."""

    #: Stream to be written to when we visit the instances
    stream: Final[TextIO]

    #: Method pointer to be invoked for writing the start element with or without
    #: specifying a namespace (depending on the state of the serializer)
    _write_start_element: Callable[
        [str],
        None
    ]

    #: Method pointer to be invoked for writing an empty element with or without
    #: specifying a namespace (depending on the state of the serializer)
    _write_empty_element: Callable[
        [str],
        None
    ]

    # NOTE (mristin, 2022-10-14):
    # The serialization procedure is quite rigid. We leverage the specifics of
    # the serialization procedure to optimize the code a bit.
    #
    # Namely, we model the writing of the XML elements as a state machine.
    # The namespace is only specified for the very first element. All the subsequent
    # elements will *not* have the namespace specified. We implement that behavior by
    # using pointers to methods, as Python treats the methods as first-class citizens.
    #
    # The ``_write_start_element`` will point to
    # ``_write_first_start_element_with_namespace`` on the *first* invocation.
    # Afterwards, it will be redirected to ``_write_start_element_without_namespace``.
    #
    # Analogously for ``_write_empty_element``.
    #
    # Please see the implementation for the details, but this should give you at least
    # a rough overview.

    def _write_first_start_element_with_namespace(
            self,
            name: str
    ) -> None:
        """
        Write the start element with the tag name :paramref:`name` and specify
        its namespace.

        The :py:attr:`~_write_start_element` is set to
        :py:meth:`~_write_start_element_without_namespace` after the first invocation
        of this method.

        :param name: of the element tag. Expected to contain no XML special characters.
        """
        self.stream.write(f'<{name} xmlns="{NAMESPACE}">')

        # NOTE (mristin, 2022-10-14):
        # Any subsequence call to `_write_start_element` or `_write_empty_element`
        # should not specify the namespace of the element as we specified now already
        # specified it.
        self._write_start_element = self._write_start_element_without_namespace
        self._write_empty_element = self._write_empty_element_without_namespace

    def _write_start_element_without_namespace(
            self,
            name: str
    ) -> None:
        """
        Write the start element with the tag name :paramref:`name`.

        The first element, written *before* this one, is expected to have been
        already written with the namespace specified.

        :param name: of the element tag. Expected to contain no XML special characters.
        """
        self.stream.write(f'<{name}>')

    def _write_end_element(
            self,
            name: str
    ) -> None:
        """
        Write the end element with the tag name :paramref:`name`.

        :param name: of the element tag. Expected to contain no XML special characters.
        """
        self.stream.write(f'</{name}>')

    def _write_first_empty_element_with_namespace(
            self,
            name: str
    ) -> None:
        """
        Write the first (and only) empty element with the tag name :paramref:`name`.

        No elements are expected to be written to the stream afterwards. The element
        includes the namespace specification.

        :param name: of the element tag. Expected to contain no XML special characters.
        """
        self.stream.write(f'<{name} xmlns="{NAMESPACE}"/>')
        self._write_empty_element = self._rase_if_write_element_called_again
        self._write_start_element = self._rase_if_write_element_called_again

    def _rase_if_write_element_called_again(
            self,
            name: str
    ) -> None:
        raise AssertionError(
            f"We expected to call ``_write_first_empty_element_with_namespace`` "
            f"only once. This is an unexpected second call for writing "
            f"an (empty or non-empty) element with the tag name: {name!r}"
        )

    def _write_empty_element_without_namespace(
            self,
            name: str
    ) -> None:
        """
        Write the empty element with the tag name :paramref:`name`.

        The call to this method is expected to occur *after* the enclosing element with
        a specified namespace has been written.

        :param name: of the element tag. Expected to contain no XML special characters.
        """
        self.stream.write(f'<{name}/>')

    def __init__(
        self,
        stream: TextIO
    ) -> None:
        """
        Initialize the visitor to write to :paramref:`stream`.

        The first element will include the :py:attr:`~.NAMESPACE`. Every other
        element will not have the namespace specified.

        :param stream: where to write to
        """
        self.stream = stream
        self._write_start_element = (
            self._write_first_start_element_with_namespace
        )
        self._write_empty_element = (
            self._write_first_empty_element_with_namespace
        )

    def visit_something(
        self,
        that: aas_types.Something
    ) -> None:
        """
        Serialize :paramref:`that` to :py:attr:`~stream` as an XML element.

        The enclosing XML element designates the class of the instance, where its
        children correspond to the properties of the instance.

        :param that: instance to be serialized
        """
        _write_something_as_element('something', that, self)


def write(instance: aas_types.Class, stream: TextIO) -> None:
    """
    Write the XML representation of :paramref:`instance` to :paramref:`stream`.

    Example usage:

    .. code-block::

        import pathlib

        import dummy.types as aas_types
        import dummy.xmlization as aas_xmlization

        instance = Something(
           ... # some constructor arguments
        )

        pth = pathlib.Path(...)
        with pth.open("wt") as fid:
            aas_xmlization.write(instance, fid)

    :param instance: to be serialized
    :param stream: to write to
    """
    serializer = _Serializer(stream)
    serializer.visit(instance)


def to_str(that: aas_types.Class) -> str:
    """
    Serialize :paramref:`that` to an XML-encoded text.

    :param that: instance to be serialized
    :return: :paramref:`that` serialized to XML serialized to text
    """
    writer = io.StringIO()
    write(that, writer)
    return writer.getvalue()


# endregion
