/**
 * Test JSON de/serialization of interfaces.
 */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import * as AasJsonization from "../src/jsonization";
import * as TestCommon from "./common";
import * as TestCommonJsonization from "./commonJsonization";

test("IMixedAbstractMember deserialization fail", () => {
  const jsonable = "This is not a IMixedAbstractMember.";

  const instanceOrError = AasJsonization.mixedAbstractMemberFromJsonable(
    jsonable
  );
  expect(instanceOrError.error.message).toStrictEqual(
    "Expected a JSON object, but got: string"
  );
});

test(
  "IMixedConcreteWithDescendants round-trip " +
  "starting from MixedConcreteWithDescendantsChild OK",
  () => {
  const instance = TestCommonJsonization.loadMinimalMixedConcreteWithDescendantsChild();

  const jsonable = AasJsonization.toJsonable(instance);

  const anotherInstanceOrError = AasJsonization.mixedConcreteWithDescendantsFromJsonable(
    jsonable
  );
  expect(anotherInstanceOrError.error).toBeNull();
  const anotherInstance = anotherInstanceOrError.mustValue();

  const anotherJsonable = AasJsonization.toJsonable(anotherInstance);

  const inequalityError = TestCommon.checkJsonablesEqual(
    jsonable,
    anotherJsonable
  );
  if (inequalityError !== null) {
    throw new Error(
      "The minimal example of IMixedConcreteWithDescendants " +
      "as an instance of MixedConcreteWithDescendantsChild serialized " +
      "to JSON, then de-serialized and serialized again does not match " +
      `the first JSON: ${inequalityError.path}: ${inequalityError.message}`
    );
  }
});

test(
  "IMixedConcreteWithDescendants round-trip " +
  "starting from MixedConcreteWithDescendants OK",
  () => {
  const instance = TestCommonJsonization.loadMinimalMixedConcreteWithDescendants();

  const jsonable = AasJsonization.toJsonable(instance);

  const anotherInstanceOrError = AasJsonization.mixedConcreteWithDescendantsFromJsonable(
    jsonable
  );
  expect(anotherInstanceOrError.error).toBeNull();
  const anotherInstance = anotherInstanceOrError.mustValue();

  const anotherJsonable = AasJsonization.toJsonable(anotherInstance);

  const inequalityError = TestCommon.checkJsonablesEqual(
    jsonable,
    anotherJsonable
  );
  if (inequalityError !== null) {
    throw new Error(
      "The minimal example of IMixedConcreteWithDescendants " +
      "as an instance of MixedConcreteWithDescendants serialized " +
      "to JSON, then de-serialized and serialized again does not match " +
      `the first JSON: ${inequalityError.path}: ${inequalityError.message}`
    );
  }
});

test("IMixedConcreteWithDescendants deserialization fail", () => {
  const jsonable = "This is not a IMixedConcreteWithDescendants.";

  const instanceOrError = AasJsonization.mixedConcreteWithDescendantsFromJsonable(
    jsonable
  );
  expect(instanceOrError.error.message).toStrictEqual(
    "Expected a JSON object, but got: string"
  );
});

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
