/**
 * Test `over*OrEmpty` methods.
 */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import * as TestCommonJsonization from "./commonJsonization";

test("Something.overOptionalListOverlappingPropertyOrEmpty on maximal", () => {
  const instance = TestCommonJsonization.loadMaximalSomething();

  let count = 0;
  for (const _ of instance.overOptionalListOverlappingPropertyOrEmpty()) {
    count++;
  }

  expect(count).toStrictEqual(
    instance.optionalListOverlappingProperty?.length ?? 0,
  );
});

test("Something.overOptionalListOverlappingPropertyOrEmpty on minimal", () => {
  const instance = TestCommonJsonization.loadMinimalSomething();

  let count = 0;
  for (const _ of instance.overOptionalListOverlappingPropertyOrEmpty()) {
    count++;
  }

  expect(count).toStrictEqual(
    instance.optionalListOverlappingProperty?.length ?? 0,
  );
});

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
