/**
 * Test `modelType()` methods.
 */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import * as AasTypes from "../src/types";
import * as AasStringification from "../src/stringification";
import * as TestCommonJsonization from "./commonJsonization";

test("model type of StructuralFirst", () => {
  const instance = TestCommonJsonization.loadMinimalStructuralFirst();

  expect(instance.modelType()).toStrictEqual(
    AasTypes.ModelType.StructuralFirst
  );
});

test("model type from string of StructuralFirst", () => {
  const text = "StructuralFirst";
  const literal = AasStringification.modelTypeFromString(
    text
  );

  expect(literal).toStrictEqual(
    AasTypes.ModelType.StructuralFirst
  );
});

test("model type to string of StructuralFirst", () => {
  const text = AasStringification.mustModelTypeToString(
    AasTypes.ModelType.StructuralFirst
  );

  expect(text).toStrictEqual(
    "StructuralFirst"
  );
});

test("model type of StructuralSecond", () => {
  const instance = TestCommonJsonization.loadMinimalStructuralSecond();

  expect(instance.modelType()).toStrictEqual(
    AasTypes.ModelType.StructuralSecond
  );
});

test("model type from string of StructuralSecond", () => {
  const text = "StructuralSecond";
  const literal = AasStringification.modelTypeFromString(
    text
  );

  expect(literal).toStrictEqual(
    AasTypes.ModelType.StructuralSecond
  );
});

test("model type to string of StructuralSecond", () => {
  const text = AasStringification.mustModelTypeToString(
    AasTypes.ModelType.StructuralSecond
  );

  expect(text).toStrictEqual(
    "StructuralSecond"
  );
});

test("model type of MixedAbstractDescendantOne", () => {
  const instance = TestCommonJsonization.loadMinimalMixedAbstractDescendantOne();

  expect(instance.modelType()).toStrictEqual(
    AasTypes.ModelType.MixedAbstractDescendantOne
  );
});

test("model type from string of MixedAbstractDescendantOne", () => {
  const text = "MixedAbstractDescendantOne";
  const literal = AasStringification.modelTypeFromString(
    text
  );

  expect(literal).toStrictEqual(
    AasTypes.ModelType.MixedAbstractDescendantOne
  );
});

test("model type to string of MixedAbstractDescendantOne", () => {
  const text = AasStringification.mustModelTypeToString(
    AasTypes.ModelType.MixedAbstractDescendantOne
  );

  expect(text).toStrictEqual(
    "MixedAbstractDescendantOne"
  );
});

test("model type of MixedAbstractDescendantTwo", () => {
  const instance = TestCommonJsonization.loadMinimalMixedAbstractDescendantTwo();

  expect(instance.modelType()).toStrictEqual(
    AasTypes.ModelType.MixedAbstractDescendantTwo
  );
});

test("model type from string of MixedAbstractDescendantTwo", () => {
  const text = "MixedAbstractDescendantTwo";
  const literal = AasStringification.modelTypeFromString(
    text
  );

  expect(literal).toStrictEqual(
    AasTypes.ModelType.MixedAbstractDescendantTwo
  );
});

test("model type to string of MixedAbstractDescendantTwo", () => {
  const text = AasStringification.mustModelTypeToString(
    AasTypes.ModelType.MixedAbstractDescendantTwo
  );

  expect(text).toStrictEqual(
    "MixedAbstractDescendantTwo"
  );
});

test("model type of MixedConcreteWithDescendants", () => {
  const instance = TestCommonJsonization.loadMinimalMixedConcreteWithDescendants();

  expect(instance.modelType()).toStrictEqual(
    AasTypes.ModelType.MixedConcreteWithDescendants
  );
});

test("model type from string of MixedConcreteWithDescendants", () => {
  const text = "MixedConcreteWithDescendants";
  const literal = AasStringification.modelTypeFromString(
    text
  );

  expect(literal).toStrictEqual(
    AasTypes.ModelType.MixedConcreteWithDescendants
  );
});

test("model type to string of MixedConcreteWithDescendants", () => {
  const text = AasStringification.mustModelTypeToString(
    AasTypes.ModelType.MixedConcreteWithDescendants
  );

  expect(text).toStrictEqual(
    "MixedConcreteWithDescendants"
  );
});

test("model type of MixedConcreteWithDescendantsChild", () => {
  const instance = TestCommonJsonization.loadMinimalMixedConcreteWithDescendantsChild();

  expect(instance.modelType()).toStrictEqual(
    AasTypes.ModelType.MixedConcreteWithDescendantsChild
  );
});

test("model type from string of MixedConcreteWithDescendantsChild", () => {
  const text = "MixedConcreteWithDescendantsChild";
  const literal = AasStringification.modelTypeFromString(
    text
  );

  expect(literal).toStrictEqual(
    AasTypes.ModelType.MixedConcreteWithDescendantsChild
  );
});

test("model type to string of MixedConcreteWithDescendantsChild", () => {
  const text = AasStringification.mustModelTypeToString(
    AasTypes.ModelType.MixedConcreteWithDescendantsChild
  );

  expect(text).toStrictEqual(
    "MixedConcreteWithDescendantsChild"
  );
});

test("model type of MixedConcreteLeaf", () => {
  const instance = TestCommonJsonization.loadMinimalMixedConcreteLeaf();

  expect(instance.modelType()).toStrictEqual(
    AasTypes.ModelType.MixedConcreteLeaf
  );
});

test("model type from string of MixedConcreteLeaf", () => {
  const text = "MixedConcreteLeaf";
  const literal = AasStringification.modelTypeFromString(
    text
  );

  expect(literal).toStrictEqual(
    AasTypes.ModelType.MixedConcreteLeaf
  );
});

test("model type to string of MixedConcreteLeaf", () => {
  const text = AasStringification.mustModelTypeToString(
    AasTypes.ModelType.MixedConcreteLeaf
  );

  expect(text).toStrictEqual(
    "MixedConcreteLeaf"
  );
});

test("model type of ModelTypedFirst", () => {
  const instance = TestCommonJsonization.loadMinimalModelTypedFirst();

  expect(instance.modelType()).toStrictEqual(
    AasTypes.ModelType.ModelTypedFirst
  );
});

test("model type from string of ModelTypedFirst", () => {
  const text = "ModelTypedFirst";
  const literal = AasStringification.modelTypeFromString(
    text
  );

  expect(literal).toStrictEqual(
    AasTypes.ModelType.ModelTypedFirst
  );
});

test("model type to string of ModelTypedFirst", () => {
  const text = AasStringification.mustModelTypeToString(
    AasTypes.ModelType.ModelTypedFirst
  );

  expect(text).toStrictEqual(
    "ModelTypedFirst"
  );
});

test("model type of ModelTypedSecond", () => {
  const instance = TestCommonJsonization.loadMinimalModelTypedSecond();

  expect(instance.modelType()).toStrictEqual(
    AasTypes.ModelType.ModelTypedSecond
  );
});

test("model type from string of ModelTypedSecond", () => {
  const text = "ModelTypedSecond";
  const literal = AasStringification.modelTypeFromString(
    text
  );

  expect(literal).toStrictEqual(
    AasTypes.ModelType.ModelTypedSecond
  );
});

test("model type to string of ModelTypedSecond", () => {
  const text = AasStringification.mustModelTypeToString(
    AasTypes.ModelType.ModelTypedSecond
  );

  expect(text).toStrictEqual(
    "ModelTypedSecond"
  );
});

test("model type of Something", () => {
  const instance = TestCommonJsonization.loadMinimalSomething();

  expect(instance.modelType()).toStrictEqual(
    AasTypes.ModelType.Something
  );
});

test("model type from string of Something", () => {
  const text = "Something";
  const literal = AasStringification.modelTypeFromString(
    text
  );

  expect(literal).toStrictEqual(
    AasTypes.ModelType.Something
  );
});

test("model type to string of Something", () => {
  const text = AasStringification.mustModelTypeToString(
    AasTypes.ModelType.Something
  );

  expect(text).toStrictEqual(
    "Something"
  );
});

test("model type from invalid string", () => {
  const text = "This is definitely not a valid model type.";
  const literal = AasStringification.modelTypeFromString(
    text
  );

  expect(literal).toBeNull();
});

test("invalid model type to string", () => {
  // The number 9007199254740991 is the maximum safe integer.
  const literal = <AasTypes.ModelType>9007199254740991;
  const text = AasStringification.modelTypeToString(
    literal
  );

  expect(text).toBeNull();
});

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
