/**
 * Test XML de/serialization of interfaces.
 */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import * as AasXmlization from "../src/xmlization";
import * as AasTypes from "../src/types";

import * as TestCommonXmlization from "./commonXmlization";

test("IMixedAbstractMember XML deserialization fail", () => {
  const instanceOrError = AasXmlization.fromXmlString("This is not XML.");
  expect(instanceOrError.error).not.toBeNull();
});

test(
  "IMixedAbstractMember XML deserialization fail via " +
  "mixedAbstractMemberFromXmlString",
  () => {
    const instanceOrError = AasXmlization.mixedAbstractMemberFromXmlString(
      "This is not XML."
    );
    expect(instanceOrError.error).not.toBeNull();
  }
);

test(
  "IMixedConcreteWithDescendants XML round-trip " +
  "starting from MixedConcreteWithDescendantsChild OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalMixedConcreteWithDescendantsChild();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asMixedConcreteWithDescendants(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IMixedConcreteWithDescendants XML round-trip via " +
  "mixedConcreteWithDescendantsFromXmlString starting from MixedConcreteWithDescendantsChild OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalMixedConcreteWithDescendantsChild();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.mixedConcreteWithDescendantsFromXmlString(
      xmlText
    );
    expect(anotherInstanceOrError.error).toBeNull();
  }
);

test(
  "IMixedConcreteWithDescendants XML round-trip " +
  "starting from MixedConcreteWithDescendants OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalMixedConcreteWithDescendants();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asMixedConcreteWithDescendants(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IMixedConcreteWithDescendants XML round-trip via " +
  "mixedConcreteWithDescendantsFromXmlString starting from MixedConcreteWithDescendants OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalMixedConcreteWithDescendants();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.mixedConcreteWithDescendantsFromXmlString(
      xmlText
    );
    expect(anotherInstanceOrError.error).toBeNull();
  }
);

test("IMixedConcreteWithDescendants XML deserialization fail", () => {
  const instanceOrError = AasXmlization.fromXmlString("This is not XML.");
  expect(instanceOrError.error).not.toBeNull();
});

test(
  "IMixedConcreteWithDescendants XML deserialization fail via " +
  "mixedConcreteWithDescendantsFromXmlString",
  () => {
    const instanceOrError = AasXmlization.mixedConcreteWithDescendantsFromXmlString(
      "This is not XML."
    );
    expect(instanceOrError.error).not.toBeNull();
  }
);

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
