// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

#include "./common.hpp"
#include "./common_examples.hpp"
#include "./common_xmlization.hpp"

#include <dummy/iteration.hpp>
#include <dummy/stringification.hpp>

#include <filesystem>

namespace aas = dummy;

namespace test {
namespace common {
namespace examples {

template<typename T>
struct StaticTypeName;

template<>
struct StaticTypeName<
  aas::types::IBox
> {
  static const char* name;
};
const char* StaticTypeName<
  aas::types::IBox
>::name = "IBox";

template<>
struct StaticTypeName<
  aas::types::IBag
> {
  static const char* name;
};
const char* StaticTypeName<
  aas::types::IBag
>::name = "IBag";

template<>
struct StaticTypeName<
  aas::types::IContainer
> {
  static const char* name;
};
const char* StaticTypeName<
  aas::types::IContainer
>::name = "IContainer";

std::shared_ptr<
  aas::types::IBox
> LoadBox(
  const std::filesystem::path& path
) {
  

  std::shared_ptr<
    aas::types::IClass
  > abstract = test::common::xmlization::MustReadInstance(
    path
  );

  std::shared_ptr<
    aas::types::IBox
  > instance(
    std::dynamic_pointer_cast<
      aas::types::IBox
    >(
      abstract
    )
  );

  if (instance == nullptr) {
    throw std::runtime_error(
      aas::common::Concat(
        "Failed to cast the instance to IBox from ",
        path.string()
      )
    );
  }

  return instance;
}

std::shared_ptr<
  aas::types::IBox
> LoadMinBox() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "box"
      / "minimal.xml"
  );

  return LoadBox(
    path
  );
}

std::shared_ptr<
  aas::types::IBox
> LoadMaxBox() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "box"
      / "maximal.xml"
  );

  return LoadBox(
    path
  );
}

std::shared_ptr<
  aas::types::IBag
> LoadBag(
  const std::filesystem::path& path
) {
  

  std::shared_ptr<
    aas::types::IClass
  > abstract = test::common::xmlization::MustReadInstance(
    path
  );

  std::shared_ptr<
    aas::types::IBag
  > instance(
    std::dynamic_pointer_cast<
      aas::types::IBag
    >(
      abstract
    )
  );

  if (instance == nullptr) {
    throw std::runtime_error(
      aas::common::Concat(
        "Failed to cast the instance to IBag from ",
        path.string()
      )
    );
  }

  return instance;
}

std::shared_ptr<
  aas::types::IBag
> LoadMinBag() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "bag"
      / "minimal.xml"
  );

  return LoadBag(
    path
  );
}

std::shared_ptr<
  aas::types::IBag
> LoadMaxBag() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "bag"
      / "maximal.xml"
  );

  return LoadBag(
    path
  );
}

std::shared_ptr<
  aas::types::IContainer
> LoadContainer(
  const std::filesystem::path& path
) {
  

  std::shared_ptr<
    aas::types::IClass
  > abstract = test::common::xmlization::MustReadInstance(
    path
  );

  std::shared_ptr<
    aas::types::IContainer
  > instance(
    std::dynamic_pointer_cast<
      aas::types::IContainer
    >(
      abstract
    )
  );

  if (instance == nullptr) {
    throw std::runtime_error(
      aas::common::Concat(
        "Failed to cast the instance to IContainer from ",
        path.string()
      )
    );
  }

  return instance;
}

std::shared_ptr<
  aas::types::IContainer
> LoadMinContainer() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "container"
      / "minimal.xml"
  );

  return LoadContainer(
    path
  );
}

std::shared_ptr<
  aas::types::IContainer
> LoadMaxContainer() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "container"
      / "maximal.xml"
  );

  return LoadContainer(
    path
  );
}

}  // namespace examples
}  // namespace common
}  // namespace test

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
