// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

#include "dummy/wstringification.hpp"

#define CATCH_CONFIG_MAIN
#include <catch2/catch.hpp>

namespace aas = dummy;

TEST_CASE("Test ModelType round-trip") {
  REQUIRE(
    aas::types::ModelType::kBox
    == aas::wstringification::MustModelTypeFromWstring(
      L"Box"
    )
  );

  REQUIRE(
    aas::wstringification::to_wstring(
      aas::types::ModelType::kBox
    )
    == L"Box"
  );

  REQUIRE(
    aas::types::ModelType::kBag
    == aas::wstringification::MustModelTypeFromWstring(
      L"Bag"
    )
  );

  REQUIRE(
    aas::wstringification::to_wstring(
      aas::types::ModelType::kBag
    )
    == L"Bag"
  );

  REQUIRE(
    aas::types::ModelType::kContainer
    == aas::wstringification::MustModelTypeFromWstring(
      L"Container"
    )
  );

  REQUIRE(
    aas::wstringification::to_wstring(
      aas::types::ModelType::kContainer
    )
    == L"Container"
  );
}

TEST_CASE("Test failure on ModelType") {
  CHECK(
    !aas::wstringification::ModelTypeFromWstring(
      L"Totally utterly invalid"
    ).has_value()
  );

  REQUIRE_THROWS_WITH(
    aas::wstringification::MustModelTypeFromWstring(
      L"Totally utterly invalid"
    ),
    "Unexpected ModelType literal: Totally utterly invalid"
  );
}

TEST_CASE("Test Color round-trip") {
  REQUIRE(
    aas::types::Color::kRed
    == aas::wstringification::MustColorFromWstring(
      L"Red"
    )
  );

  REQUIRE(
    aas::wstringification::to_wstring(
      aas::types::Color::kRed
    )
    == L"Red"
  );

  REQUIRE(
    aas::types::Color::kGreen
    == aas::wstringification::MustColorFromWstring(
      L"Green"
    )
  );

  REQUIRE(
    aas::wstringification::to_wstring(
      aas::types::Color::kGreen
    )
    == L"Green"
  );
}

TEST_CASE("Test failure on Color") {
  CHECK(
    !aas::wstringification::ColorFromWstring(
      L"Totally utterly invalid"
    ).has_value()
  );

  REQUIRE_THROWS_WITH(
    aas::wstringification::MustColorFromWstring(
      L"Totally utterly invalid"
    ),
    "Unexpected Color literal: Totally utterly invalid"
  );
}

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
