/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

using Aas = dummy;  // renamed

// We need to use System.MemoryExtension.SequenceEqual.
using System;  // can't alias
using System.Linq;  // can't alias

using NUnit.Framework;  // can't alias

namespace dummy.Tests
{
    public class TestCopying
    {
        internal class DeepEqualiser
            : Aas.Visitation.AbstractTransformerWithContext<Aas.IClass, bool>
        {
            /// <summary>Compare two byte spans for equal content.</summary>
            /// <remarks>
            /// <c>byte[]</c> implicitly converts to <c>ReadOnlySpan</c>.
            /// See: https://stackoverflow.com/a/48599119/1600678
            /// </remarks>
            private static bool ByteSpansEqual(
                System.ReadOnlySpan<byte> that,
                System.ReadOnlySpan<byte> other)
            {
                return that.SequenceEqual(other);
            }

            public override bool TransformLeaf(
                Aas.ILeaf that,
                Aas.IClass other)
            {
                if (!(other is Aas.Leaf casted))
                {
                    return false;
                }

                return (
                    that.Identifier == casted.Identifier
                    && that.Text == casted.Text);
            }

            public override bool TransformOrderedContainer(
                Aas.IOrderedContainer that,
                Aas.IClass other)
            {
                if (!(other is Aas.OrderedContainer casted))
                {
                    return false;
                }

                return (
                    that.Identifier == casted.Identifier
                    && that.Children.Count == casted.Children.Count
                    && (
                        that.Children
                            .Zip(
                                casted.Children,
                                Transform)
                            .All(item => item))
                    && that.IsSorted == casted.IsSorted);
            }

            public override bool TransformUnorderedContainer(
                Aas.IUnorderedContainer that,
                Aas.IClass other)
            {
                if (!(other is Aas.UnorderedContainer casted))
                {
                    return false;
                }

                return (
                    that.Identifier == casted.Identifier
                    && that.Children.Count == casted.Children.Count
                    && (
                        that.Children
                            .Zip(
                                casted.Children,
                                Transform)
                            .All(item => item)));
            }

            public override bool TransformGlobalAttribute(
                Aas.IGlobalAttribute that,
                Aas.IClass other)
            {
                if (!(other is Aas.GlobalAttribute casted))
                {
                    return false;
                }

                return (
                    that.Kind == casted.Kind);
            }

            public override bool TransformLocalAttribute(
                Aas.ILocalAttribute that,
                Aas.IClass other)
            {
                if (!(other is Aas.LocalAttribute casted))
                {
                    return false;
                }

                return (
                    that.Name == casted.Name);
            }

            public override bool TransformAttributeOperand(
                Aas.IAttributeOperand that,
                Aas.IClass other)
            {
                if (!(other is Aas.AttributeOperand casted))
                {
                    return false;
                }

                return (
                    Transform(
                        that.Attribute,
                        casted.Attribute));
            }

            public override bool TransformStringLiteral(
                Aas.IStringLiteral that,
                Aas.IClass other)
            {
                if (!(other is Aas.StringLiteral casted))
                {
                    return false;
                }

                return (
                    that.Text == casted.Text);
            }

            public override bool TransformNumberLiteral(
                Aas.INumberLiteral that,
                Aas.IClass other)
            {
                if (!(other is Aas.NumberLiteral casted))
                {
                    return false;
                }

                return (
                    that.Number == casted.Number);
            }

            public override bool TransformSomething(
                Aas.ISomething that,
                Aas.IClass other)
            {
                if (!(other is Aas.Something casted))
                {
                    return false;
                }

                return (
                    Transform(
                        that.Root,
                        casted.Root)
                    && ((that.OptionalElement != null && casted.OptionalElement != null)
                        ? Transform(
                                that.OptionalElement,
                                casted.OptionalElement)
                        : that.OptionalElement == null && casted.OptionalElement == null)
                    && Transform(
                        that.Value,
                        casted.Value)
                    && that.Values.Count == casted.Values.Count
                    && (
                        that.Values
                            .Zip(
                                casted.Values,
                                Transform)
                            .All(item => item)));
            }

            private bool Transform(Aas.IUnion that, Aas.IUnion other)
            {
                return Transform(that.Underlying, other.Underlying);
            }
        }  // internal class DeepEqualiser

        private static readonly DeepEqualiser DeepEqualiserInstance = new DeepEqualiser();

        private static bool LeafShallowEquals(
            Aas.Leaf that,
            Aas.Leaf other)
        {
            return that.Identifier == other.Identifier && that.Text == other.Text;
        }

        private static bool OrderedContainerShallowEquals(
            Aas.OrderedContainer that,
            Aas.OrderedContainer other)
        {
            return (
                that.Identifier == other.Identifier
                && that.Children == other.Children
                && that.IsSorted == other.IsSorted);
        }

        private static bool UnorderedContainerShallowEquals(
            Aas.UnorderedContainer that,
            Aas.UnorderedContainer other)
        {
            return (
                that.Identifier == other.Identifier
                && that.Children == other.Children);
        }

        private static bool GlobalAttributeShallowEquals(
            Aas.GlobalAttribute that,
            Aas.GlobalAttribute other)
        {
            return that.Kind == other.Kind;
        }

        private static bool LocalAttributeShallowEquals(
            Aas.LocalAttribute that,
            Aas.LocalAttribute other)
        {
            return that.Name == other.Name;
        }

        private static bool AttributeOperandShallowEquals(
            Aas.AttributeOperand that,
            Aas.AttributeOperand other)
        {
            return that.Attribute == other.Attribute;
        }

        private static bool StringLiteralShallowEquals(
            Aas.StringLiteral that,
            Aas.StringLiteral other)
        {
            return that.Text == other.Text;
        }

        private static bool NumberLiteralShallowEquals(
            Aas.NumberLiteral that,
            Aas.NumberLiteral other)
        {
            return that.Number == other.Number;
        }

        private static bool SomethingShallowEquals(
            Aas.Something that,
            Aas.Something other)
        {
            return (
                that.Root == other.Root
                && that.OptionalElement == other.OptionalElement
                && that.Value == other.Value
                && that.Values == other.Values);
        }

        private static bool LeafDeepEquals(
            Aas.Leaf that,
            Aas.Leaf other)
        {
            return DeepEqualiserInstance.Transform(that, other);
        }

        private static bool OrderedContainerDeepEquals(
            Aas.OrderedContainer that,
            Aas.OrderedContainer other)
        {
            return DeepEqualiserInstance.Transform(that, other);
        }

        private static bool UnorderedContainerDeepEquals(
            Aas.UnorderedContainer that,
            Aas.UnorderedContainer other)
        {
            return DeepEqualiserInstance.Transform(that, other);
        }

        private static bool GlobalAttributeDeepEquals(
            Aas.GlobalAttribute that,
            Aas.GlobalAttribute other)
        {
            return DeepEqualiserInstance.Transform(that, other);
        }

        private static bool LocalAttributeDeepEquals(
            Aas.LocalAttribute that,
            Aas.LocalAttribute other)
        {
            return DeepEqualiserInstance.Transform(that, other);
        }

        private static bool AttributeOperandDeepEquals(
            Aas.AttributeOperand that,
            Aas.AttributeOperand other)
        {
            return DeepEqualiserInstance.Transform(that, other);
        }

        private static bool StringLiteralDeepEquals(
            Aas.StringLiteral that,
            Aas.StringLiteral other)
        {
            return DeepEqualiserInstance.Transform(that, other);
        }

        private static bool NumberLiteralDeepEquals(
            Aas.NumberLiteral that,
            Aas.NumberLiteral other)
        {
            return DeepEqualiserInstance.Transform(that, other);
        }

        private static bool SomethingDeepEquals(
            Aas.Something that,
            Aas.Something other)
        {
            return DeepEqualiserInstance.Transform(that, other);
        }

        [Test]
        public void Test_Leaf_shallow_copy()
        {
            Aas.Leaf instance = (
                Aas.Tests.CommonJsonization.LoadMaximalLeaf());

            var instanceCopy = Aas.Copying.Shallow(instance);

            Assert.IsTrue(
                LeafShallowEquals(
                    instance, instanceCopy),
                "Leaf");
        }  // public void Test_Leaf_shallow_copy

        [Test]
        public void Test_Leaf_deep_copy()
        {
            Aas.Leaf instance = (
                Aas.Tests.CommonJsonization.LoadMaximalLeaf());

            var instanceCopy = Aas.Copying.Deep(instance);

            Assert.IsTrue(
                LeafDeepEquals(
                    instance, instanceCopy),
                "Leaf");
        }  // public void Test_Leaf_deep_copy

        [Test]
        public void Test_OrderedContainer_shallow_copy()
        {
            Aas.OrderedContainer instance = (
                Aas.Tests.CommonJsonization.LoadMaximalOrderedContainer());

            var instanceCopy = Aas.Copying.Shallow(instance);

            Assert.IsTrue(
                OrderedContainerShallowEquals(
                    instance, instanceCopy),
                "OrderedContainer");
        }  // public void Test_OrderedContainer_shallow_copy

        [Test]
        public void Test_OrderedContainer_deep_copy()
        {
            Aas.OrderedContainer instance = (
                Aas.Tests.CommonJsonization.LoadMaximalOrderedContainer());

            var instanceCopy = Aas.Copying.Deep(instance);

            Assert.IsTrue(
                OrderedContainerDeepEquals(
                    instance, instanceCopy),
                "OrderedContainer");
        }  // public void Test_OrderedContainer_deep_copy

        [Test]
        public void Test_UnorderedContainer_shallow_copy()
        {
            Aas.UnorderedContainer instance = (
                Aas.Tests.CommonJsonization.LoadMaximalUnorderedContainer());

            var instanceCopy = Aas.Copying.Shallow(instance);

            Assert.IsTrue(
                UnorderedContainerShallowEquals(
                    instance, instanceCopy),
                "UnorderedContainer");
        }  // public void Test_UnorderedContainer_shallow_copy

        [Test]
        public void Test_UnorderedContainer_deep_copy()
        {
            Aas.UnorderedContainer instance = (
                Aas.Tests.CommonJsonization.LoadMaximalUnorderedContainer());

            var instanceCopy = Aas.Copying.Deep(instance);

            Assert.IsTrue(
                UnorderedContainerDeepEquals(
                    instance, instanceCopy),
                "UnorderedContainer");
        }  // public void Test_UnorderedContainer_deep_copy

        [Test]
        public void Test_GlobalAttribute_shallow_copy()
        {
            Aas.GlobalAttribute instance = (
                Aas.Tests.CommonJsonization.LoadMaximalGlobalAttribute());

            var instanceCopy = Aas.Copying.Shallow(instance);

            Assert.IsTrue(
                GlobalAttributeShallowEquals(
                    instance, instanceCopy),
                "GlobalAttribute");
        }  // public void Test_GlobalAttribute_shallow_copy

        [Test]
        public void Test_GlobalAttribute_deep_copy()
        {
            Aas.GlobalAttribute instance = (
                Aas.Tests.CommonJsonization.LoadMaximalGlobalAttribute());

            var instanceCopy = Aas.Copying.Deep(instance);

            Assert.IsTrue(
                GlobalAttributeDeepEquals(
                    instance, instanceCopy),
                "GlobalAttribute");
        }  // public void Test_GlobalAttribute_deep_copy

        [Test]
        public void Test_LocalAttribute_shallow_copy()
        {
            Aas.LocalAttribute instance = (
                Aas.Tests.CommonJsonization.LoadMaximalLocalAttribute());

            var instanceCopy = Aas.Copying.Shallow(instance);

            Assert.IsTrue(
                LocalAttributeShallowEquals(
                    instance, instanceCopy),
                "LocalAttribute");
        }  // public void Test_LocalAttribute_shallow_copy

        [Test]
        public void Test_LocalAttribute_deep_copy()
        {
            Aas.LocalAttribute instance = (
                Aas.Tests.CommonJsonization.LoadMaximalLocalAttribute());

            var instanceCopy = Aas.Copying.Deep(instance);

            Assert.IsTrue(
                LocalAttributeDeepEquals(
                    instance, instanceCopy),
                "LocalAttribute");
        }  // public void Test_LocalAttribute_deep_copy

        [Test]
        public void Test_AttributeOperand_shallow_copy()
        {
            Aas.AttributeOperand instance = (
                Aas.Tests.CommonJsonization.LoadMaximalAttributeOperand());

            var instanceCopy = Aas.Copying.Shallow(instance);

            Assert.IsTrue(
                AttributeOperandShallowEquals(
                    instance, instanceCopy),
                "AttributeOperand");
        }  // public void Test_AttributeOperand_shallow_copy

        [Test]
        public void Test_AttributeOperand_deep_copy()
        {
            Aas.AttributeOperand instance = (
                Aas.Tests.CommonJsonization.LoadMaximalAttributeOperand());

            var instanceCopy = Aas.Copying.Deep(instance);

            Assert.IsTrue(
                AttributeOperandDeepEquals(
                    instance, instanceCopy),
                "AttributeOperand");
        }  // public void Test_AttributeOperand_deep_copy

        [Test]
        public void Test_StringLiteral_shallow_copy()
        {
            Aas.StringLiteral instance = (
                Aas.Tests.CommonJsonization.LoadMaximalStringLiteral());

            var instanceCopy = Aas.Copying.Shallow(instance);

            Assert.IsTrue(
                StringLiteralShallowEquals(
                    instance, instanceCopy),
                "StringLiteral");
        }  // public void Test_StringLiteral_shallow_copy

        [Test]
        public void Test_StringLiteral_deep_copy()
        {
            Aas.StringLiteral instance = (
                Aas.Tests.CommonJsonization.LoadMaximalStringLiteral());

            var instanceCopy = Aas.Copying.Deep(instance);

            Assert.IsTrue(
                StringLiteralDeepEquals(
                    instance, instanceCopy),
                "StringLiteral");
        }  // public void Test_StringLiteral_deep_copy

        [Test]
        public void Test_NumberLiteral_shallow_copy()
        {
            Aas.NumberLiteral instance = (
                Aas.Tests.CommonJsonization.LoadMaximalNumberLiteral());

            var instanceCopy = Aas.Copying.Shallow(instance);

            Assert.IsTrue(
                NumberLiteralShallowEquals(
                    instance, instanceCopy),
                "NumberLiteral");
        }  // public void Test_NumberLiteral_shallow_copy

        [Test]
        public void Test_NumberLiteral_deep_copy()
        {
            Aas.NumberLiteral instance = (
                Aas.Tests.CommonJsonization.LoadMaximalNumberLiteral());

            var instanceCopy = Aas.Copying.Deep(instance);

            Assert.IsTrue(
                NumberLiteralDeepEquals(
                    instance, instanceCopy),
                "NumberLiteral");
        }  // public void Test_NumberLiteral_deep_copy

        [Test]
        public void Test_Something_shallow_copy()
        {
            Aas.Something instance = (
                Aas.Tests.CommonJsonization.LoadMaximalSomething());

            var instanceCopy = Aas.Copying.Shallow(instance);

            Assert.IsTrue(
                SomethingShallowEquals(
                    instance, instanceCopy),
                "Something");
        }  // public void Test_Something_shallow_copy

        [Test]
        public void Test_Something_deep_copy()
        {
            Aas.Something instance = (
                Aas.Tests.CommonJsonization.LoadMaximalSomething());

            var instanceCopy = Aas.Copying.Deep(instance);

            Assert.IsTrue(
                SomethingDeepEquals(
                    instance, instanceCopy),
                "Something");
        }  // public void Test_Something_deep_copy
    }  // class TestCopying
}  // namespace dummy.Tests

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
