/**
 * Provide de/serialization of AAS classes to/from XML.
 *
 * The implementation is incremental and follows a SAX-style parsing approach.
 */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import * as AasCommon from "./common";
import * as AasTypes from "./types";
import * as AasStringification from "./stringification";

import {
  CdataToken,
  CloseTagToken,
  CommentToken,
  EndToken,
  OpenTagToken,
  TextToken,
  XmlAnyToken,
  XmlSaxParser
} from "xmlsax-typescript";

const NAMESPACE = "https://dummy.com";

/**
 * Represent a property name segment in an XML path.
 */
export class NameSegment {
  readonly name: string;

  constructor(name: string) {
    this.name = name;
  }
}

/**
 * Represent an index segment in an XML path.
 */
export class IndexSegment {
  readonly index: number;

  constructor(index: number) {
    this.index = index;
  }
}

export type Segment = NameSegment | IndexSegment;

/**
 * Represent a relative path to the erroneous XML value.
 */
export class Path {
  private readonly _segments = new Array<Segment>();

  segments(): Array<Segment> {
    return this._segments;
  }

  prepend(segment: Segment): void {
    this._segments.unshift(segment);
  }

  toString(): string {
    if (this._segments.length === 0) {
      return "";
    }

    const parts = new Array<string>();
    for (const segment of this._segments) {
      if (segment instanceof NameSegment) {
        if (parts.length === 0) {
          parts.push(segment.name);
        } else {
          parts.push(`.${segment.name}`);
        }
      } else if (segment instanceof IndexSegment) {
        parts.push(`[${segment.index}]`);
      }
    }

    return parts.join("");
  }
}

/**
 * Signal that XML de-serialization could not be performed.
 */
export class DeserializationError {
  readonly message: string;
  readonly path: Path;

  constructor(message: string, path: Path | null = null) {
    this.message = message;
    this.path = path ?? new Path();
  }
}

/**
 * Signal that XML serialization could not be performed.
 */
export class SerializationError {
  readonly message: string;
  readonly path: Path;

  constructor(message: string, path: Path | null = null) {
    this.message = message;
    this.path = path ?? new Path();
  }
}

function newDeserializationError<T>(
  message: string
): AasCommon.Either<T, DeserializationError> {
  return new AasCommon.Either<T, DeserializationError>(
    null,
    new DeserializationError(message)
  );
}

/**
 * Parse a value from `cursor`.
 *
 * Every parser in this module wears this one shape, which is what lets them
 * compose: a parser can be given to another parser without a closure, since
 * everything it needs comes from the `cursor` and from its own definition.
 * The name says what a parser consumes -- a `parse*Content` stops right before
 * the closing tag of the element which the caller has opened, while
 * a `parse*Element` and a `dispatchParse*Element` read an element of their own,
 * its tags included.
 *
 * @typeParam T - type of the parsed value
 */
type ContentParser<T> = (
  cursor: XmlCursor
) => AasCommon.Either<T, DeserializationError>;

function currentTokenKind(cursor: XmlCursor): string {
  const token = cursor.current();
  if (token === null) {
    return "end-of-token-stream";
  }

  return token.kind;
}

function localNameOfTag(tag: unknown): string {
  const aTag = tag as {
    name?: unknown,
    local?: unknown,
    localName?: unknown
  };

  if (typeof aTag.local === "string") {
    return aTag.local;
  }
  if (typeof aTag.localName === "string") {
    return aTag.localName;
  }
  if (typeof aTag.name === "string") {
    const colonIndex = aTag.name.indexOf(":");
    if (colonIndex >= 0) {
      return aTag.name.substring(colonIndex + 1);
    }
    return aTag.name;
  }

  return "";
}

function namespaceOfTag(tag: unknown): string {
  const aTag = tag as { uri?: unknown, namespaceURI?: unknown };
  if (typeof aTag.uri === "string") {
    return aTag.uri;
  }
  if (typeof aTag.namespaceURI === "string") {
    return aTag.namespaceURI;
  }
  return "";
}

function checkExpectedOpenTagNamespace(
  openTag: OpenTagToken
): DeserializationError | null {
  const namespace = namespaceOfTag(openTag.tag);
  if (namespace !== NAMESPACE) {
    return new DeserializationError(
      "Expected XML namespace " +
        `'${NAMESPACE}', but got '${namespace}'`
    );
  }

  return null;
}

/**
 * Read the next property's opening tag while parsing the sequence of
 * properties of `className`, advancing `cursor` past it.
 *
 * @param cursor - to be read from
 * @param className - name of the class being parsed, for error reporting
 * @returns
 * the next property's opening tag, or `null` if the closing tag of
 * `className` was reached instead, or an error
 */
function nextPropertyOpenTag(
  cursor: XmlCursor,
  className: string
): OpenTagToken | DeserializationError | null {
  const token = cursor.current();
  if (token === null) {
    return new DeserializationError(
      `Unexpected end of token stream while parsing ${className}`
    );
  }

  if (token instanceof CloseTagToken) {
    return null;
  }

  if (!(token instanceof OpenTagToken)) {
    return new DeserializationError(
      "Expected an XML property start element or the closing element of " +
      `${className}, but got token kind: ${token.kind}`
    );
  }

  const namespaceError = checkExpectedOpenTagNamespace(token);
  if (namespaceError !== null) {
    return namespaceError;
  }

  cursor.advance();
  return token;
}

function checkExpectedCloseTag(
  closeTag: CloseTagToken,
  expectedLocalName: string
): DeserializationError | null {
  const namespace = namespaceOfTag(closeTag.tag);
  if (namespace !== NAMESPACE) {
    return new DeserializationError(
      "Expected XML namespace " +
        `'${NAMESPACE}', but got '${namespace}'`
    );
  }

  const observedLocalName = localNameOfTag(closeTag.tag);
  if (observedLocalName !== expectedLocalName) {
    return new DeserializationError(
      `Expected closing XML element '${expectedLocalName}', ` +
      `but got '${observedLocalName}'`
    );
  }

  return null;
}

/**
 * Read the next token from `cursor`, expecting it to be the closing XML
 * element named `expectedLocalName`, and consume it.
 */
function consumeCloseTag(
  cursor: XmlCursor,
  expectedLocalName: string
): DeserializationError | null {
  const closeTag = cursor.current();
  if (!(closeTag instanceof CloseTagToken)) {
    return new DeserializationError(
      `Expected a closing element '${expectedLocalName}', ` +
      `but got token kind: ${currentTokenKind(cursor)}`
    );
  }

  const closeError = checkExpectedCloseTag(closeTag, expectedLocalName);
  if (closeError !== null) {
    return closeError;
  }

  cursor.advance();
  return null;
}

/**
 * Read the next non-ignorable token from `cursor`, expecting it to be
 * an opening XML element in the expected namespace.
 *
 * This is shared by the parsing of a single list item, a single tuple
 * item, and the dispatch-parsing of an interface.
 *
 * @param cursor - to read from
 * @returns the opening tag, or an error
 */
function readNextOpenTag(
  cursor: XmlCursor
): AasCommon.Either<OpenTagToken, DeserializationError> {
  cursor.skipIgnorable();
  const token = cursor.current();
  if (token === null) {
    return newDeserializationError<OpenTagToken>(
      "Expected an XML element, but got end of token stream"
    );
  }
  if (!(token instanceof OpenTagToken)) {
    return newDeserializationError<OpenTagToken>(
      `Expected an XML element, but got token kind: ${token.kind}`
    );
  }

  const namespaceError = checkExpectedOpenTagNamespace(token);
  if (namespaceError !== null) {
    return new AasCommon.Either<OpenTagToken, DeserializationError>(
      null,
      namespaceError
    );
  }

  return new AasCommon.Either<OpenTagToken, DeserializationError>(token, null);
}

/**
 * Parse the content of the XML element which the caller has opened, and consume
 * the corresponding closing element named `localName`.
 *
 * This is the one thing which every value of an XML element has in common,
 * whatever it holds: the property loop of a class calls it directly, since
 * it has already read the opening tag and switched on its local name, and
 * `parseNamedElement` calls it after reading an opening tag of its own.
 *
 * A property loop assigns *both* halves of the result -- the value as well as
 * the error -- without looking at either first. The loop returns as soon as
 * the error is set, so the `null` value which comes with an error is never
 * read, and the property's variable needs no guard.
 *
 * @param cursor - to read from
 * @param localName - local name of the element which the caller has opened
 * @param parseContent - parses the content of the element
 * @returns parsed value, or an error
 * @typeParam T - type of the parsed value
 */
function parseElementContent<T>(
  cursor: XmlCursor,
  localName: string,
  parseContent: ContentParser<T>
): AasCommon.Either<T, DeserializationError> {
  const parsedOrError = parseContent(cursor);
  if (parsedOrError.error !== null) {
    return parsedOrError;
  }

  const closeError = consumeCloseTag(cursor, localName);
  if (closeError !== null) {
    return new AasCommon.Either<T, DeserializationError>(null, closeError);
  }

  return parsedOrError;
}

/**
 * Read the next XML element from `cursor`, expecting it to be named
 * `expectedLocalName`, parse its content with `parseContent` and consume
 * the matching closing element.
 *
 * This is what an item of a list or of a tuple is parsed with -- a scalar item
 * in an element tagged `"v"`, `"v1"`, `"v2"`, *etc.*, and an item whose concrete
 * class is statically known in an element named after that class. Rejecting
 * an unexpected element on its local name alone spares us parsing its full
 * (possibly deeply nested) content only to discover the mismatch afterwards.
 *
 * @param cursor - to read from
 * @param expectedLocalName - the expected local name of the element
 * @param parseContent - parses the content of the element
 * @returns parsed value, or an error
 * @typeParam T - type of the parsed value
 */
function parseNamedElement<T>(
  cursor: XmlCursor,
  expectedLocalName: string,
  parseContent: ContentParser<T>
): AasCommon.Either<T, DeserializationError> {
  const startTagOrError = readNextOpenTag(cursor);
  if (startTagOrError.error !== null) {
    return new AasCommon.Either<T, DeserializationError>(
      null,
      startTagOrError.error
    );
  }
  const startTag = startTagOrError.mustValue();

  const observedLocalName = localNameOfTag(startTag.tag);
  if (observedLocalName !== expectedLocalName) {
    return newDeserializationError<T>(
      `Expected the element '${expectedLocalName}', ` +
        `but got '${observedLocalName}'`
    );
  }

  cursor.advance();

  return parseElementContent(cursor, expectedLocalName, parseContent);
}

/**
 * Parse a sequence of list items from `cursor`, stopping (without consuming)
 * at the first closing element.
 *
 * The caller is expected to read and verify the property's own closing
 * element afterwards.
 *
 * @param cursor - to read from
 * @param parseItem - parses a single list item
 * @returns the parsed items, or an error
 * @typeParam T - type of a single list item
 */
function parseList<T>(
  cursor: XmlCursor,
  parseItem: ContentParser<T>
): AasCommon.Either<Array<T>, DeserializationError> {
  const items = new Array<T>();
  let itemIndex = 0;

  cursor.skipIgnorable();
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const maybeClose = cursor.current();
    if (maybeClose === null) {
      return newDeserializationError<Array<T>>(
        "Expected an XML element corresponding to a list item " +
          "or property closing element, but got end of token stream"
      );
    }

    if (maybeClose instanceof CloseTagToken) {
      break;
    }

    const itemOrError = parseItem(cursor);
    if (itemOrError.error !== null) {
      itemOrError.error.path.prepend(new IndexSegment(itemIndex));
      return new AasCommon.Either<Array<T>, DeserializationError>(
        null,
        itemOrError.error
      );
    }

    items.push(itemOrError.mustValue());
    itemIndex++;
    cursor.skipIgnorable();
  }

  return new AasCommon.Either<Array<T>, DeserializationError>(items, null);
}

/**
 * Cursor over parsed XML SAX tokens.
 */
class XmlCursor {
  private readonly _tokens: Array<XmlAnyToken>;
  private _index = 0;

  constructor(tokens: Array<XmlAnyToken>) {
    this._tokens = tokens;
  }

  current(): XmlAnyToken | null {
    if (this._index >= this._tokens.length) {
      return null;
    }
    return this._tokens[this._index];
  }

  advance(): void {
    if (this._index < this._tokens.length) {
      this._index++;
    }
  }

  skipIgnorable(): void {
    // eslint-disable-next-line no-constant-condition
    while (true) {
      const token = this.current();
      if (token === null) {
        break;
      }

      if (token instanceof CommentToken) {
        this.advance();
        continue;
      }

      if (token instanceof TextToken || token instanceof CdataToken) {
        if (token.text.trim().length === 0) {
          this.advance();
          continue;
        }
      }

      break;
    }
  }
}

function tokenizeXml(
  xml: string
): AasCommon.Either<Array<XmlAnyToken>, DeserializationError> {
  const parser = new XmlSaxParser({ allowDoctype: false, xmlns: true });
  const tokens = new Array<XmlAnyToken>();

  try {
    for (const token of parser.feed(xml)) {
      tokens.push(token);
    }
    for (const token of parser.close()) {
      if (!(token instanceof EndToken)) {
        tokens.push(token);
      }
    }
  } catch (error) {
    return newDeserializationError<Array<XmlAnyToken>>(
      `Failed to parse XML: ${error}`
    );
  }

  return new AasCommon.Either<Array<XmlAnyToken>, DeserializationError>(
    tokens,
    null
  );
}

function readRequiredRootOpenTag(
  cursor: XmlCursor
): AasCommon.Either<OpenTagToken, DeserializationError> {
  cursor.skipIgnorable();

  const token = cursor.current();
  if (token === null) {
    return newDeserializationError<OpenTagToken>(
      "Expected a root XML element, but got an empty token stream"
    );
  }

  if (!(token instanceof OpenTagToken)) {
    return newDeserializationError<OpenTagToken>(
      `Expected a root XML start element, but got token kind: ${token.kind}`
    );
  }

  const namespaceError = checkExpectedOpenTagNamespace(token);
  if (namespaceError !== null) {
    return new AasCommon.Either<OpenTagToken, DeserializationError>(
      null,
      namespaceError
    );
  }

  cursor.advance();

  return new AasCommon.Either<OpenTagToken, DeserializationError>(
    token,
    null
  );
}

/**
 * Consume the text (or CDATA) content at `cursor`, if any.
 *
 * The caller is responsible for reading and verifying the closing element
 * afterwards.
 */
function parseTextContent(cursor: XmlCursor): string {
  cursor.skipIgnorable();

  let text = "";
  const maybeText = cursor.current();
  if (maybeText instanceof TextToken || maybeText instanceof CdataToken) {
    text = maybeText.text;
    cursor.advance();
    cursor.skipIgnorable();
  }

  return text;
}

/**
 * Read the next XML element from `cursor` and parse it with the parser which
 * `parsersByLocalName` gives for the element's local name.
 *
 * An abstract class, a concrete class with descendants and a named union all
 * prescribe no element tag of their own, so the tag is what tells us which
 * parser to use. The set of local names which are accepted is the only thing
 * which distinguishes one such dispatch from another, so it is the only thing
 * which is generated -- the reading itself lives here.
 *
 * @param cursor - to read from
 * @param expectedWhat - what we expected to read, for the error message
 * @param parsersByLocalName - parser of the content, by the element's local name
 * @returns parsed instance, or an error
 * @typeParam T - type of the parsed instance
 */
function dispatchParseElement<T>(
  cursor: XmlCursor,
  expectedWhat: string,
  parsersByLocalName: ReadonlyMap<string, ContentParser<T>>
): AasCommon.Either<T, DeserializationError> {
  const startTagOrError = readNextOpenTag(cursor);
  if (startTagOrError.error !== null) {
    return new AasCommon.Either<T, DeserializationError>(
      null,
      startTagOrError.error
    );
  }

  const localName = localNameOfTag(startTagOrError.mustValue().tag);

  const parseContent = parsersByLocalName.get(localName);
  if (parseContent === undefined) {
    return newDeserializationError<T>(
      `Expected an instance of ${expectedWhat}, but got: ${localName}`
    );
  }

  cursor.advance();

  return parseElementContent(cursor, localName, parseContent);
}

/**
 * Report that the property `localName` occurred more than once.
 *
 * The check itself sits in the property loop, right in front of the parse, since
 * only the loop knows whether the property's variable has been set already. This
 * is only the error, so that the message is written once instead of at every one
 * of the property cases.
 */
function duplicatePropertyError(localName: string): DeserializationError {
  return new DeserializationError(
    "Property " + localName + " occurred more than once"
  );
}

function parseBooleanContent(
  cursor: XmlCursor
): AasCommon.Either<boolean, DeserializationError> {
  const text = parseTextContent(cursor);

  if (text === "true" || text === "1") {
    return new AasCommon.Either<boolean, DeserializationError>(true, null);
  }
  if (text === "false" || text === "0") {
    return new AasCommon.Either<boolean, DeserializationError>(false, null);
  }

  return newDeserializationError<boolean>(
    `Expected xs:boolean text, but got: ${text}`
  );
}

function parseIntegerContent(
  cursor: XmlCursor
): AasCommon.Either<number, DeserializationError> {
  const text = parseTextContent(cursor);

  if (!/^[+-]?\d+$/.test(text)) {
    return newDeserializationError<number>(
      `Expected integer text, but got: ${text}`
    );
  }

  const value = Number(text);
  if (!Number.isInteger(value)) {
    return newDeserializationError<number>(
      `Expected integer text, but got: ${text}`
    );
  }

  return new AasCommon.Either<number, DeserializationError>(value, null);
}

function parseFloatContent(
  cursor: XmlCursor
): AasCommon.Either<number, DeserializationError> {
  const text = parseTextContent(cursor);

  if (text === "INF") {
    return new AasCommon.Either<number, DeserializationError>(Infinity, null);
  }
  if (text === "-INF") {
    return new AasCommon.Either<number, DeserializationError>(-Infinity, null);
  }
  if (text === "NaN") {
    return new AasCommon.Either<number, DeserializationError>(NaN, null);
  }

  const value = Number(text);
  if (Number.isNaN(value)) {
    return newDeserializationError<number>(
      `Expected xs:double text, but got: ${text}`
    );
  }

  return new AasCommon.Either<number, DeserializationError>(value, null);
}

function parseStringContent(
  cursor: XmlCursor
): AasCommon.Either<string, DeserializationError> {
  return new AasCommon.Either<string, DeserializationError>(
    parseTextContent(cursor),
    null
  );
}

function parseBase64EncodedBytesContent(
  cursor: XmlCursor
): AasCommon.Either<Uint8Array, DeserializationError> {
  const decodedOrError = AasCommon.base64Decode(parseTextContent(cursor));
  if (decodedOrError.error !== null) {
    return newDeserializationError<Uint8Array>(
      decodedOrError.error
    );
  }

  return new AasCommon.Either<Uint8Array, DeserializationError>(
    decodedOrError.mustValue(),
    null
  );
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function parseTuple3<T0, T1, T2>(
  cursor: XmlCursor,
  parseItem0: ContentParser<T0>,
  parseItem1: ContentParser<T1>,
  parseItem2: ContentParser<T2>
): AasCommon.Either<[T0, T1, T2], DeserializationError> {
  const item0OrError = parseItem0(cursor);
  if (item0OrError.error !== null) {
    item0OrError.error.path.prepend(new IndexSegment(0));
    return new AasCommon.Either<[T0, T1, T2], DeserializationError>(
      null,
      item0OrError.error
    );
  }

  const item1OrError = parseItem1(cursor);
  if (item1OrError.error !== null) {
    item1OrError.error.path.prepend(new IndexSegment(1));
    return new AasCommon.Either<[T0, T1, T2], DeserializationError>(
      null,
      item1OrError.error
    );
  }

  const item2OrError = parseItem2(cursor);
  if (item2OrError.error !== null) {
    item2OrError.error.path.prepend(new IndexSegment(2));
    return new AasCommon.Either<[T0, T1, T2], DeserializationError>(
      null,
      item2OrError.error
    );
  }

  return new AasCommon.Either<[T0, T1, T2], DeserializationError>(
    [
      item0OrError.mustValue(),
      item1OrError.mustValue(),
      item2OrError.mustValue()
    ],
    null
  );
}

function parseListOfMixedUnionContent(
  cursor: XmlCursor
): AasCommon.Either<Array<AasTypes.MixedUnion>, DeserializationError> {
  return parseList<AasTypes.MixedUnion>(cursor, dispatchParseMixedUnionElement);
}

function parseListOfModelTypedUnionContent(
  cursor: XmlCursor
): AasCommon.Either<Array<AasTypes.ModelTypedUnion>, DeserializationError> {
  return parseList<AasTypes.ModelTypedUnion>(cursor, dispatchParseModelTypedUnionElement);
}

function parseListOfStructuralUnionContent(
  cursor: XmlCursor
): AasCommon.Either<Array<AasTypes.StructuralUnion>, DeserializationError> {
  return parseList<AasTypes.StructuralUnion>(cursor, dispatchParseStructuralUnionElement);
}

function parseTuple3OfStructuralUnion_MixedUnion_ModelTypedUnionContent(
  cursor: XmlCursor
): AasCommon.Either<[AasTypes.StructuralUnion, AasTypes.MixedUnion, AasTypes.ModelTypedUnion], DeserializationError> {
  return parseTuple3<AasTypes.StructuralUnion, AasTypes.MixedUnion, AasTypes.ModelTypedUnion>(
    cursor,
    dispatchParseStructuralUnionElement,
    dispatchParseMixedUnionElement,
    dispatchParseModelTypedUnionElement
  );
}

/**
 * Parse the sequence of properties of an instance
 * of {@link types!StructuralFirst}.
 *
 * The opening tag is expected to have been already read by the caller, and
 * the caller is expected to read and verify the corresponding closing tag
 * after this function returns successfully. This is the contract of
 * a `ContentParser`, so this function is used as one wherever an instance
 * of {@link types!StructuralFirst} is embedded.
 */
function parseStructuralFirstFromSequence(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.StructuralFirst, DeserializationError> {
  let theUniqueToFirst: string | null = null;

  const className = AasTypes.StructuralFirst.name;

  cursor.skipIgnorable();
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const nextTagOrError = nextPropertyOpenTag(cursor, className);
    if (nextTagOrError === null) {
      break;
    }
    if (nextTagOrError instanceof DeserializationError) {
      return new AasCommon.Either<AasTypes.StructuralFirst, DeserializationError>(
        null,
        nextTagOrError
      );
    }

    const propertyLocalName = localNameOfTag(nextTagOrError.tag);

    let propertyError: DeserializationError | null = null;
    switch (propertyLocalName) {
      case "uniqueToFirst": {
        if (theUniqueToFirst !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, parseStringContent);
        propertyError = parsed.error;
        theUniqueToFirst = parsed.value;
        break;
      }

      default: {
        propertyError = new DeserializationError(
          `Unexpected XML property: ${propertyLocalName}`
        );
        break;
      }
    }

    if (propertyError !== null) {
      propertyError.path.prepend(new NameSegment(propertyLocalName));
      return new AasCommon.Either<AasTypes.StructuralFirst, DeserializationError>(
        null,
        propertyError
      );
    }

    cursor.skipIgnorable();
  }

  if (theUniqueToFirst === null) {
    return newDeserializationError<AasTypes.StructuralFirst>(
      "The required property 'uniqueToFirst' is missing"
    );
  }

  const instance = new AasTypes.StructuralFirst(
    theUniqueToFirst
  );
  return new AasCommon.Either<AasTypes.StructuralFirst, DeserializationError>(
    instance,
    null
  );
}

/**
 * Parse the sequence of properties of an instance
 * of {@link types!StructuralSecond}.
 *
 * The opening tag is expected to have been already read by the caller, and
 * the caller is expected to read and verify the corresponding closing tag
 * after this function returns successfully. This is the contract of
 * a `ContentParser`, so this function is used as one wherever an instance
 * of {@link types!StructuralSecond} is embedded.
 */
function parseStructuralSecondFromSequence(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.StructuralSecond, DeserializationError> {
  let theUniqueToSecond: string | null = null;

  const className = AasTypes.StructuralSecond.name;

  cursor.skipIgnorable();
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const nextTagOrError = nextPropertyOpenTag(cursor, className);
    if (nextTagOrError === null) {
      break;
    }
    if (nextTagOrError instanceof DeserializationError) {
      return new AasCommon.Either<AasTypes.StructuralSecond, DeserializationError>(
        null,
        nextTagOrError
      );
    }

    const propertyLocalName = localNameOfTag(nextTagOrError.tag);

    let propertyError: DeserializationError | null = null;
    switch (propertyLocalName) {
      case "uniqueToSecond": {
        if (theUniqueToSecond !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, parseStringContent);
        propertyError = parsed.error;
        theUniqueToSecond = parsed.value;
        break;
      }

      default: {
        propertyError = new DeserializationError(
          `Unexpected XML property: ${propertyLocalName}`
        );
        break;
      }
    }

    if (propertyError !== null) {
      propertyError.path.prepend(new NameSegment(propertyLocalName));
      return new AasCommon.Either<AasTypes.StructuralSecond, DeserializationError>(
        null,
        propertyError
      );
    }

    cursor.skipIgnorable();
  }

  if (theUniqueToSecond === null) {
    return newDeserializationError<AasTypes.StructuralSecond>(
      "The required property 'uniqueToSecond' is missing"
    );
  }

  const instance = new AasTypes.StructuralSecond(
    theUniqueToSecond
  );
  return new AasCommon.Either<AasTypes.StructuralSecond, DeserializationError>(
    instance,
    null
  );
}

/**
 * Parse the sequence of properties of an instance
 * of {@link types!MixedAbstractDescendantOne}.
 *
 * The opening tag is expected to have been already read by the caller, and
 * the caller is expected to read and verify the corresponding closing tag
 * after this function returns successfully. This is the contract of
 * a `ContentParser`, so this function is used as one wherever an instance
 * of {@link types!MixedAbstractDescendantOne} is embedded.
 */
function parseMixedAbstractDescendantOneFromSequence(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.MixedAbstractDescendantOne, DeserializationError> {
  let theUniqueToAbstractDescendantOne: string | null = null;

  const className = AasTypes.MixedAbstractDescendantOne.name;

  cursor.skipIgnorable();
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const nextTagOrError = nextPropertyOpenTag(cursor, className);
    if (nextTagOrError === null) {
      break;
    }
    if (nextTagOrError instanceof DeserializationError) {
      return new AasCommon.Either<AasTypes.MixedAbstractDescendantOne, DeserializationError>(
        null,
        nextTagOrError
      );
    }

    const propertyLocalName = localNameOfTag(nextTagOrError.tag);

    let propertyError: DeserializationError | null = null;
    switch (propertyLocalName) {
      case "uniqueToAbstractDescendantOne": {
        if (theUniqueToAbstractDescendantOne !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, parseStringContent);
        propertyError = parsed.error;
        theUniqueToAbstractDescendantOne = parsed.value;
        break;
      }

      default: {
        propertyError = new DeserializationError(
          `Unexpected XML property: ${propertyLocalName}`
        );
        break;
      }
    }

    if (propertyError !== null) {
      propertyError.path.prepend(new NameSegment(propertyLocalName));
      return new AasCommon.Either<AasTypes.MixedAbstractDescendantOne, DeserializationError>(
        null,
        propertyError
      );
    }

    cursor.skipIgnorable();
  }

  if (theUniqueToAbstractDescendantOne === null) {
    return newDeserializationError<AasTypes.MixedAbstractDescendantOne>(
      "The required property 'uniqueToAbstractDescendantOne' is missing"
    );
  }

  const instance = new AasTypes.MixedAbstractDescendantOne(
    theUniqueToAbstractDescendantOne
  );
  return new AasCommon.Either<AasTypes.MixedAbstractDescendantOne, DeserializationError>(
    instance,
    null
  );
}

/**
 * Parse the sequence of properties of an instance
 * of {@link types!MixedAbstractDescendantTwo}.
 *
 * The opening tag is expected to have been already read by the caller, and
 * the caller is expected to read and verify the corresponding closing tag
 * after this function returns successfully. This is the contract of
 * a `ContentParser`, so this function is used as one wherever an instance
 * of {@link types!MixedAbstractDescendantTwo} is embedded.
 */
function parseMixedAbstractDescendantTwoFromSequence(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.MixedAbstractDescendantTwo, DeserializationError> {
  let theUniqueToAbstractDescendantTwo: string | null = null;

  const className = AasTypes.MixedAbstractDescendantTwo.name;

  cursor.skipIgnorable();
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const nextTagOrError = nextPropertyOpenTag(cursor, className);
    if (nextTagOrError === null) {
      break;
    }
    if (nextTagOrError instanceof DeserializationError) {
      return new AasCommon.Either<AasTypes.MixedAbstractDescendantTwo, DeserializationError>(
        null,
        nextTagOrError
      );
    }

    const propertyLocalName = localNameOfTag(nextTagOrError.tag);

    let propertyError: DeserializationError | null = null;
    switch (propertyLocalName) {
      case "uniqueToAbstractDescendantTwo": {
        if (theUniqueToAbstractDescendantTwo !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, parseStringContent);
        propertyError = parsed.error;
        theUniqueToAbstractDescendantTwo = parsed.value;
        break;
      }

      default: {
        propertyError = new DeserializationError(
          `Unexpected XML property: ${propertyLocalName}`
        );
        break;
      }
    }

    if (propertyError !== null) {
      propertyError.path.prepend(new NameSegment(propertyLocalName));
      return new AasCommon.Either<AasTypes.MixedAbstractDescendantTwo, DeserializationError>(
        null,
        propertyError
      );
    }

    cursor.skipIgnorable();
  }

  if (theUniqueToAbstractDescendantTwo === null) {
    return newDeserializationError<AasTypes.MixedAbstractDescendantTwo>(
      "The required property 'uniqueToAbstractDescendantTwo' is missing"
    );
  }

  const instance = new AasTypes.MixedAbstractDescendantTwo(
    theUniqueToAbstractDescendantTwo
  );
  return new AasCommon.Either<AasTypes.MixedAbstractDescendantTwo, DeserializationError>(
    instance,
    null
  );
}

/**
 * Parse the sequence of properties of an instance
 * of {@link types!MixedConcreteWithDescendants}.
 *
 * The opening tag is expected to have been already read by the caller, and
 * the caller is expected to read and verify the corresponding closing tag
 * after this function returns successfully. This is the contract of
 * a `ContentParser`, so this function is used as one wherever an instance
 * of {@link types!MixedConcreteWithDescendants} is embedded.
 */
function parseMixedConcreteWithDescendantsFromSequence(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.MixedConcreteWithDescendants, DeserializationError> {
  let theSomeBaseProperty: string | null = null;

  const className = AasTypes.MixedConcreteWithDescendants.name;

  cursor.skipIgnorable();
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const nextTagOrError = nextPropertyOpenTag(cursor, className);
    if (nextTagOrError === null) {
      break;
    }
    if (nextTagOrError instanceof DeserializationError) {
      return new AasCommon.Either<AasTypes.MixedConcreteWithDescendants, DeserializationError>(
        null,
        nextTagOrError
      );
    }

    const propertyLocalName = localNameOfTag(nextTagOrError.tag);

    let propertyError: DeserializationError | null = null;
    switch (propertyLocalName) {
      case "someBaseProperty": {
        if (theSomeBaseProperty !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, parseStringContent);
        propertyError = parsed.error;
        theSomeBaseProperty = parsed.value;
        break;
      }

      default: {
        propertyError = new DeserializationError(
          `Unexpected XML property: ${propertyLocalName}`
        );
        break;
      }
    }

    if (propertyError !== null) {
      propertyError.path.prepend(new NameSegment(propertyLocalName));
      return new AasCommon.Either<AasTypes.MixedConcreteWithDescendants, DeserializationError>(
        null,
        propertyError
      );
    }

    cursor.skipIgnorable();
  }

  if (theSomeBaseProperty === null) {
    return newDeserializationError<AasTypes.MixedConcreteWithDescendants>(
      "The required property 'someBaseProperty' is missing"
    );
  }

  const instance = new AasTypes.MixedConcreteWithDescendants(
    theSomeBaseProperty
  );
  return new AasCommon.Either<AasTypes.MixedConcreteWithDescendants, DeserializationError>(
    instance,
    null
  );
}

/**
 * Parse the sequence of properties of an instance
 * of {@link types!MixedConcreteWithDescendantsChild}.
 *
 * The opening tag is expected to have been already read by the caller, and
 * the caller is expected to read and verify the corresponding closing tag
 * after this function returns successfully. This is the contract of
 * a `ContentParser`, so this function is used as one wherever an instance
 * of {@link types!MixedConcreteWithDescendantsChild} is embedded.
 */
function parseMixedConcreteWithDescendantsChildFromSequence(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.MixedConcreteWithDescendantsChild, DeserializationError> {
  let theSomeBaseProperty: string | null = null;
  let theSomeChildProperty: string | null = null;

  const className = AasTypes.MixedConcreteWithDescendantsChild.name;

  cursor.skipIgnorable();
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const nextTagOrError = nextPropertyOpenTag(cursor, className);
    if (nextTagOrError === null) {
      break;
    }
    if (nextTagOrError instanceof DeserializationError) {
      return new AasCommon.Either<AasTypes.MixedConcreteWithDescendantsChild, DeserializationError>(
        null,
        nextTagOrError
      );
    }

    const propertyLocalName = localNameOfTag(nextTagOrError.tag);

    let propertyError: DeserializationError | null = null;
    switch (propertyLocalName) {
      case "someBaseProperty": {
        if (theSomeBaseProperty !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, parseStringContent);
        propertyError = parsed.error;
        theSomeBaseProperty = parsed.value;
        break;
      }

      case "someChildProperty": {
        if (theSomeChildProperty !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, parseStringContent);
        propertyError = parsed.error;
        theSomeChildProperty = parsed.value;
        break;
      }

      default: {
        propertyError = new DeserializationError(
          `Unexpected XML property: ${propertyLocalName}`
        );
        break;
      }
    }

    if (propertyError !== null) {
      propertyError.path.prepend(new NameSegment(propertyLocalName));
      return new AasCommon.Either<AasTypes.MixedConcreteWithDescendantsChild, DeserializationError>(
        null,
        propertyError
      );
    }

    cursor.skipIgnorable();
  }

  if (theSomeBaseProperty === null) {
    return newDeserializationError<AasTypes.MixedConcreteWithDescendantsChild>(
      "The required property 'someBaseProperty' is missing"
    );
  }

  if (theSomeChildProperty === null) {
    return newDeserializationError<AasTypes.MixedConcreteWithDescendantsChild>(
      "The required property 'someChildProperty' is missing"
    );
  }

  const instance = new AasTypes.MixedConcreteWithDescendantsChild(
    theSomeBaseProperty,
    theSomeChildProperty
  );
  return new AasCommon.Either<AasTypes.MixedConcreteWithDescendantsChild, DeserializationError>(
    instance,
    null
  );
}

/**
 * Parse the sequence of properties of an instance
 * of {@link types!MixedConcreteLeaf}.
 *
 * The opening tag is expected to have been already read by the caller, and
 * the caller is expected to read and verify the corresponding closing tag
 * after this function returns successfully. This is the contract of
 * a `ContentParser`, so this function is used as one wherever an instance
 * of {@link types!MixedConcreteLeaf} is embedded.
 */
function parseMixedConcreteLeafFromSequence(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.MixedConcreteLeaf, DeserializationError> {
  let theUniqueToConcreteLeaf: string | null = null;

  const className = AasTypes.MixedConcreteLeaf.name;

  cursor.skipIgnorable();
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const nextTagOrError = nextPropertyOpenTag(cursor, className);
    if (nextTagOrError === null) {
      break;
    }
    if (nextTagOrError instanceof DeserializationError) {
      return new AasCommon.Either<AasTypes.MixedConcreteLeaf, DeserializationError>(
        null,
        nextTagOrError
      );
    }

    const propertyLocalName = localNameOfTag(nextTagOrError.tag);

    let propertyError: DeserializationError | null = null;
    switch (propertyLocalName) {
      case "uniqueToConcreteLeaf": {
        if (theUniqueToConcreteLeaf !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, parseStringContent);
        propertyError = parsed.error;
        theUniqueToConcreteLeaf = parsed.value;
        break;
      }

      default: {
        propertyError = new DeserializationError(
          `Unexpected XML property: ${propertyLocalName}`
        );
        break;
      }
    }

    if (propertyError !== null) {
      propertyError.path.prepend(new NameSegment(propertyLocalName));
      return new AasCommon.Either<AasTypes.MixedConcreteLeaf, DeserializationError>(
        null,
        propertyError
      );
    }

    cursor.skipIgnorable();
  }

  if (theUniqueToConcreteLeaf === null) {
    return newDeserializationError<AasTypes.MixedConcreteLeaf>(
      "The required property 'uniqueToConcreteLeaf' is missing"
    );
  }

  const instance = new AasTypes.MixedConcreteLeaf(
    theUniqueToConcreteLeaf
  );
  return new AasCommon.Either<AasTypes.MixedConcreteLeaf, DeserializationError>(
    instance,
    null
  );
}

/**
 * Parse the sequence of properties of an instance
 * of {@link types!ModelTypedFirst}.
 *
 * The opening tag is expected to have been already read by the caller, and
 * the caller is expected to read and verify the corresponding closing tag
 * after this function returns successfully. This is the contract of
 * a `ContentParser`, so this function is used as one wherever an instance
 * of {@link types!ModelTypedFirst} is embedded.
 */
function parseModelTypedFirstFromSequence(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.ModelTypedFirst, DeserializationError> {
  let theSomeProperty: string | null = null;

  const className = AasTypes.ModelTypedFirst.name;

  cursor.skipIgnorable();
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const nextTagOrError = nextPropertyOpenTag(cursor, className);
    if (nextTagOrError === null) {
      break;
    }
    if (nextTagOrError instanceof DeserializationError) {
      return new AasCommon.Either<AasTypes.ModelTypedFirst, DeserializationError>(
        null,
        nextTagOrError
      );
    }

    const propertyLocalName = localNameOfTag(nextTagOrError.tag);

    let propertyError: DeserializationError | null = null;
    switch (propertyLocalName) {
      case "someProperty": {
        if (theSomeProperty !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, parseStringContent);
        propertyError = parsed.error;
        theSomeProperty = parsed.value;
        break;
      }

      default: {
        propertyError = new DeserializationError(
          `Unexpected XML property: ${propertyLocalName}`
        );
        break;
      }
    }

    if (propertyError !== null) {
      propertyError.path.prepend(new NameSegment(propertyLocalName));
      return new AasCommon.Either<AasTypes.ModelTypedFirst, DeserializationError>(
        null,
        propertyError
      );
    }

    cursor.skipIgnorable();
  }

  if (theSomeProperty === null) {
    return newDeserializationError<AasTypes.ModelTypedFirst>(
      "The required property 'someProperty' is missing"
    );
  }

  const instance = new AasTypes.ModelTypedFirst(
    theSomeProperty
  );
  return new AasCommon.Either<AasTypes.ModelTypedFirst, DeserializationError>(
    instance,
    null
  );
}

/**
 * Parse the sequence of properties of an instance
 * of {@link types!ModelTypedSecond}.
 *
 * The opening tag is expected to have been already read by the caller, and
 * the caller is expected to read and verify the corresponding closing tag
 * after this function returns successfully. This is the contract of
 * a `ContentParser`, so this function is used as one wherever an instance
 * of {@link types!ModelTypedSecond} is embedded.
 */
function parseModelTypedSecondFromSequence(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.ModelTypedSecond, DeserializationError> {
  let theSomeProperty: string | null = null;

  const className = AasTypes.ModelTypedSecond.name;

  cursor.skipIgnorable();
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const nextTagOrError = nextPropertyOpenTag(cursor, className);
    if (nextTagOrError === null) {
      break;
    }
    if (nextTagOrError instanceof DeserializationError) {
      return new AasCommon.Either<AasTypes.ModelTypedSecond, DeserializationError>(
        null,
        nextTagOrError
      );
    }

    const propertyLocalName = localNameOfTag(nextTagOrError.tag);

    let propertyError: DeserializationError | null = null;
    switch (propertyLocalName) {
      case "someProperty": {
        if (theSomeProperty !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, parseStringContent);
        propertyError = parsed.error;
        theSomeProperty = parsed.value;
        break;
      }

      default: {
        propertyError = new DeserializationError(
          `Unexpected XML property: ${propertyLocalName}`
        );
        break;
      }
    }

    if (propertyError !== null) {
      propertyError.path.prepend(new NameSegment(propertyLocalName));
      return new AasCommon.Either<AasTypes.ModelTypedSecond, DeserializationError>(
        null,
        propertyError
      );
    }

    cursor.skipIgnorable();
  }

  if (theSomeProperty === null) {
    return newDeserializationError<AasTypes.ModelTypedSecond>(
      "The required property 'someProperty' is missing"
    );
  }

  const instance = new AasTypes.ModelTypedSecond(
    theSomeProperty
  );
  return new AasCommon.Either<AasTypes.ModelTypedSecond, DeserializationError>(
    instance,
    null
  );
}

/**
 * Parse the sequence of properties of an instance
 * of {@link types!Something}.
 *
 * The opening tag is expected to have been already read by the caller, and
 * the caller is expected to read and verify the corresponding closing tag
 * after this function returns successfully. This is the contract of
 * a `ContentParser`, so this function is used as one wherever an instance
 * of {@link types!Something} is embedded.
 */
function parseSomethingFromSequence(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.Something, DeserializationError> {
  let theStructuralProperty: AasTypes.StructuralUnion | null = null;
  let theMixedProperty: AasTypes.MixedUnion | null = null;
  let theModelTypedProperty: AasTypes.ModelTypedUnion | null = null;
  let theListStructuralProperty: Array<AasTypes.StructuralUnion> | null = null;
  let theListMixedProperty: Array<AasTypes.MixedUnion> | null = null;
  let theListModelTypedProperty: Array<AasTypes.ModelTypedUnion> | null = null;
  let theTupleProperty: [AasTypes.StructuralUnion, AasTypes.MixedUnion, AasTypes.ModelTypedUnion] | null = null;
  let theOptionalStructuralProperty: AasTypes.StructuralUnion | null = null;
  let theOptionalMixedProperty: AasTypes.MixedUnion | null = null;
  let theOptionalModelTypedProperty: AasTypes.ModelTypedUnion | null = null;

  const className = AasTypes.Something.name;

  cursor.skipIgnorable();
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const nextTagOrError = nextPropertyOpenTag(cursor, className);
    if (nextTagOrError === null) {
      break;
    }
    if (nextTagOrError instanceof DeserializationError) {
      return new AasCommon.Either<AasTypes.Something, DeserializationError>(
        null,
        nextTagOrError
      );
    }

    const propertyLocalName = localNameOfTag(nextTagOrError.tag);

    let propertyError: DeserializationError | null = null;
    switch (propertyLocalName) {
      case "structuralProperty": {
        if (theStructuralProperty !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(
          cursor,
          propertyLocalName,
          dispatchParseStructuralUnionElement
        );
        propertyError = parsed.error;
        theStructuralProperty = parsed.value;
        break;
      }

      case "mixedProperty": {
        if (theMixedProperty !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(
          cursor,
          propertyLocalName,
          dispatchParseMixedUnionElement
        );
        propertyError = parsed.error;
        theMixedProperty = parsed.value;
        break;
      }

      case "modelTypedProperty": {
        if (theModelTypedProperty !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(
          cursor,
          propertyLocalName,
          dispatchParseModelTypedUnionElement
        );
        propertyError = parsed.error;
        theModelTypedProperty = parsed.value;
        break;
      }

      case "listStructuralProperty": {
        if (theListStructuralProperty !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(
          cursor,
          propertyLocalName,
          parseListOfStructuralUnionContent
        );
        propertyError = parsed.error;
        theListStructuralProperty = parsed.value;
        break;
      }

      case "listMixedProperty": {
        if (theListMixedProperty !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(cursor, propertyLocalName, parseListOfMixedUnionContent);
        propertyError = parsed.error;
        theListMixedProperty = parsed.value;
        break;
      }

      case "listModelTypedProperty": {
        if (theListModelTypedProperty !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(
          cursor,
          propertyLocalName,
          parseListOfModelTypedUnionContent
        );
        propertyError = parsed.error;
        theListModelTypedProperty = parsed.value;
        break;
      }

      case "tupleProperty": {
        if (theTupleProperty !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(
          cursor,
          propertyLocalName,
          parseTuple3OfStructuralUnion_MixedUnion_ModelTypedUnionContent
        );
        propertyError = parsed.error;
        theTupleProperty = parsed.value;
        break;
      }

      case "optionalStructuralProperty": {
        if (theOptionalStructuralProperty !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(
          cursor,
          propertyLocalName,
          dispatchParseStructuralUnionElement
        );
        propertyError = parsed.error;
        theOptionalStructuralProperty = parsed.value;
        break;
      }

      case "optionalMixedProperty": {
        if (theOptionalMixedProperty !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(
          cursor,
          propertyLocalName,
          dispatchParseMixedUnionElement
        );
        propertyError = parsed.error;
        theOptionalMixedProperty = parsed.value;
        break;
      }

      case "optionalModelTypedProperty": {
        if (theOptionalModelTypedProperty !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(
          cursor,
          propertyLocalName,
          dispatchParseModelTypedUnionElement
        );
        propertyError = parsed.error;
        theOptionalModelTypedProperty = parsed.value;
        break;
      }

      default: {
        propertyError = new DeserializationError(
          `Unexpected XML property: ${propertyLocalName}`
        );
        break;
      }
    }

    if (propertyError !== null) {
      propertyError.path.prepend(new NameSegment(propertyLocalName));
      return new AasCommon.Either<AasTypes.Something, DeserializationError>(
        null,
        propertyError
      );
    }

    cursor.skipIgnorable();
  }

  if (theStructuralProperty === null) {
    return newDeserializationError<AasTypes.Something>(
      "The required property 'structuralProperty' is missing"
    );
  }

  if (theMixedProperty === null) {
    return newDeserializationError<AasTypes.Something>(
      "The required property 'mixedProperty' is missing"
    );
  }

  if (theModelTypedProperty === null) {
    return newDeserializationError<AasTypes.Something>(
      "The required property 'modelTypedProperty' is missing"
    );
  }

  if (theListStructuralProperty === null) {
    return newDeserializationError<AasTypes.Something>(
      "The required property 'listStructuralProperty' is missing"
    );
  }

  if (theListMixedProperty === null) {
    return newDeserializationError<AasTypes.Something>(
      "The required property 'listMixedProperty' is missing"
    );
  }

  if (theListModelTypedProperty === null) {
    return newDeserializationError<AasTypes.Something>(
      "The required property 'listModelTypedProperty' is missing"
    );
  }

  if (theTupleProperty === null) {
    return newDeserializationError<AasTypes.Something>(
      "The required property 'tupleProperty' is missing"
    );
  }

  const instance = new AasTypes.Something(
    theStructuralProperty,
    theMixedProperty,
    theModelTypedProperty,
    theListStructuralProperty,
    theListMixedProperty,
    theListModelTypedProperty,
    theTupleProperty,
    theOptionalStructuralProperty,
    theOptionalMixedProperty,
    theOptionalModelTypedProperty
  );
  return new AasCommon.Either<AasTypes.Something, DeserializationError>(
    instance,
    null
  );
}

const PARSERS_OF_MIXED_ABSTRACT_MEMBER = new Map<
  string,
  ContentParser<AasTypes.IMixedAbstractMember>
>([
  ["mixedAbstractDescendantOne", parseMixedAbstractDescendantOneFromSequence],
  ["mixedAbstractDescendantTwo", parseMixedAbstractDescendantTwoFromSequence]
]);

/**
 * Dispatch-parse an instance
 * of {@link types!IMixedAbstractMember} from the next
 * XML element in `cursor`, based on the element's local name.
 *
 * @param cursor - to read from
 * @returns the parsed instance, or an error
 */
function dispatchParseMixedAbstractMemberElement(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.IMixedAbstractMember, DeserializationError> {
  return dispatchParseElement(cursor, "IMixedAbstractMember", PARSERS_OF_MIXED_ABSTRACT_MEMBER);
}

/**
 * Parse an XML string as an instance
 * of {@link types!IMixedAbstractMember}.
 *
 * @param xml - XML string to parse
 * @returns parsed instance, or an error
 */
export function mixedAbstractMemberFromXmlString(
  xml: string
): AasCommon.Either<AasTypes.IMixedAbstractMember, DeserializationError> {
  if (xml.length === 0) {
    return newDeserializationError<AasTypes.IMixedAbstractMember>(
      "Expected an XML document, but got an empty string"
    );
  }

  const tokensOrError = tokenizeXml(xml);
  if (tokensOrError.error !== null) {
    return new AasCommon.Either<AasTypes.IMixedAbstractMember, DeserializationError>(
      null,
      tokensOrError.error
    );
  }

  const cursor = new XmlCursor(tokensOrError.mustValue());

  const instanceOrError = dispatchParseMixedAbstractMemberElement(cursor);
  if (instanceOrError.error !== null) {
    return instanceOrError;
  }

  cursor.skipIgnorable();
  if (cursor.current() !== null) {
    return newDeserializationError<AasTypes.IMixedAbstractMember>(
      "Expected no tokens after the root XML element, but got token kind: " +
        currentTokenKind(cursor)
    );
  }

  return instanceOrError;
}

const PARSERS_OF_MIXED_CONCRETE_WITH_DESCENDANTS = new Map<
  string,
  ContentParser<AasTypes.MixedConcreteWithDescendants>
>([
  ["mixedConcreteWithDescendantsChild", parseMixedConcreteWithDescendantsChildFromSequence],
  ["mixedConcreteWithDescendants", parseMixedConcreteWithDescendantsFromSequence]
]);

/**
 * Dispatch-parse an instance
 * of {@link types!MixedConcreteWithDescendants} from the next
 * XML element in `cursor`, based on the element's local name.
 *
 * @param cursor - to read from
 * @returns the parsed instance, or an error
 */
function dispatchParseMixedConcreteWithDescendantsElement(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.MixedConcreteWithDescendants, DeserializationError> {
  return dispatchParseElement(
    cursor,
    "MixedConcreteWithDescendants",
    PARSERS_OF_MIXED_CONCRETE_WITH_DESCENDANTS
  );
}

/**
 * Parse an XML string as an instance
 * of {@link types!MixedConcreteWithDescendants}.
 *
 * @param xml - XML string to parse
 * @returns parsed instance, or an error
 */
export function mixedConcreteWithDescendantsFromXmlString(
  xml: string
): AasCommon.Either<AasTypes.MixedConcreteWithDescendants, DeserializationError> {
  if (xml.length === 0) {
    return newDeserializationError<AasTypes.MixedConcreteWithDescendants>(
      "Expected an XML document, but got an empty string"
    );
  }

  const tokensOrError = tokenizeXml(xml);
  if (tokensOrError.error !== null) {
    return new AasCommon.Either<AasTypes.MixedConcreteWithDescendants, DeserializationError>(
      null,
      tokensOrError.error
    );
  }

  const cursor = new XmlCursor(tokensOrError.mustValue());

  const instanceOrError = dispatchParseMixedConcreteWithDescendantsElement(cursor);
  if (instanceOrError.error !== null) {
    return instanceOrError;
  }

  cursor.skipIgnorable();
  if (cursor.current() !== null) {
    return newDeserializationError<AasTypes.MixedConcreteWithDescendants>(
      "Expected no tokens after the root XML element, but got token kind: " +
        currentTokenKind(cursor)
    );
  }

  return instanceOrError;
}

const PARSERS_OF_STRUCTURAL_UNION = new Map<
  string,
  ContentParser<AasTypes.StructuralUnion>
>([
  ["structuralFirst", parseStructuralFirstFromSequence],
  ["structuralSecond", parseStructuralSecondFromSequence]
]);

/**
 * Dispatch-parse an instance
 * of {@link types!StructuralUnion} from the next
 * XML element in `cursor`, based on the element's local name.
 *
 * @param cursor - to read from
 * @returns the parsed instance, or an error
 */
function dispatchParseStructuralUnionElement(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.StructuralUnion, DeserializationError> {
  return dispatchParseElement(cursor, "StructuralUnion", PARSERS_OF_STRUCTURAL_UNION);
}

const PARSERS_OF_MIXED_UNION = new Map<
  string,
  ContentParser<AasTypes.MixedUnion>
>([
  ["mixedAbstractDescendantOne", parseMixedAbstractDescendantOneFromSequence],
  ["mixedAbstractDescendantTwo", parseMixedAbstractDescendantTwoFromSequence],
  ["mixedConcreteWithDescendantsChild", parseMixedConcreteWithDescendantsChildFromSequence],
  ["mixedConcreteWithDescendants", parseMixedConcreteWithDescendantsFromSequence],
  ["mixedConcreteLeaf", parseMixedConcreteLeafFromSequence]
]);

/**
 * Dispatch-parse an instance
 * of {@link types!MixedUnion} from the next
 * XML element in `cursor`, based on the element's local name.
 *
 * @param cursor - to read from
 * @returns the parsed instance, or an error
 */
function dispatchParseMixedUnionElement(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.MixedUnion, DeserializationError> {
  return dispatchParseElement(cursor, "MixedUnion", PARSERS_OF_MIXED_UNION);
}

const PARSERS_OF_MODEL_TYPED_UNION = new Map<
  string,
  ContentParser<AasTypes.ModelTypedUnion>
>([
  ["modelTypedFirst", parseModelTypedFirstFromSequence],
  ["modelTypedSecond", parseModelTypedSecondFromSequence]
]);

/**
 * Dispatch-parse an instance
 * of {@link types!ModelTypedUnion} from the next
 * XML element in `cursor`, based on the element's local name.
 *
 * @param cursor - to read from
 * @returns the parsed instance, or an error
 */
function dispatchParseModelTypedUnionElement(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.ModelTypedUnion, DeserializationError> {
  return dispatchParseElement(cursor, "ModelTypedUnion", PARSERS_OF_MODEL_TYPED_UNION);
}

const ROOT_DISPATCH_BY_LOCAL_NAME = new Map<
  string,
  ContentParser<AasTypes.Class>
>([
  ["structuralFirst", parseStructuralFirstFromSequence],
  ["structuralSecond", parseStructuralSecondFromSequence],
  ["mixedAbstractDescendantOne", parseMixedAbstractDescendantOneFromSequence],
  ["mixedAbstractDescendantTwo", parseMixedAbstractDescendantTwoFromSequence],
  ["mixedConcreteWithDescendants", parseMixedConcreteWithDescendantsFromSequence],
  ["mixedConcreteWithDescendantsChild", parseMixedConcreteWithDescendantsChildFromSequence],
  ["mixedConcreteLeaf", parseMixedConcreteLeafFromSequence],
  ["modelTypedFirst", parseModelTypedFirstFromSequence],
  ["modelTypedSecond", parseModelTypedSecondFromSequence],
  ["something", parseSomethingFromSequence]
]);

/**
 * Parse an XML string as an AAS instance.
 *
 * @param xml - XML string to parse
 * @returns parsed AAS instance or an error
 */
export function fromXmlString(
  xml: string
): AasCommon.Either<AasTypes.Class, DeserializationError> {
  if (xml.length === 0) {
    return newDeserializationError<AasTypes.Class>(
      "Expected an XML document, but got an empty string"
    );
  }

  const tokensOrError = tokenizeXml(xml);
  if (tokensOrError.error !== null) {
    return new AasCommon.Either<AasTypes.Class, DeserializationError>(
      null,
      tokensOrError.error
    );
  }

  const cursor = new XmlCursor(tokensOrError.mustValue());

  const rootOpenTagOrError = readRequiredRootOpenTag(cursor);
  if (rootOpenTagOrError.error !== null) {
    return new AasCommon.Either<AasTypes.Class, DeserializationError>(
      null,
      rootOpenTagOrError.error
    );
  }

  const rootOpenTag = rootOpenTagOrError.mustValue();
  const rootLocalName = localNameOfTag(rootOpenTag.tag);

  const dispatch = ROOT_DISPATCH_BY_LOCAL_NAME.get(rootLocalName);
  if (dispatch === undefined) {
    return newDeserializationError<AasTypes.Class>(
      `Unexpected root XML element: ${rootLocalName}`
    );
  }

  const instanceOrError = dispatch(cursor);
  if (instanceOrError.error !== null) {
    return instanceOrError;
  }

  const closeError = consumeCloseTag(cursor, rootLocalName);
  if (closeError !== null) {
    return new AasCommon.Either<AasTypes.Class, DeserializationError>(
      null,
      closeError
    );
  }

  cursor.skipIgnorable();
  if (cursor.current() !== null) {
    return newDeserializationError<AasTypes.Class>(
      "Expected no tokens after the root XML element, but got token kind: " +
        currentTokenKind(cursor)
    );
  }

  return instanceOrError;
}

type SerializedElement = {
  localName: string;
  innerXml: string;
};

function openTag(localName: string, withNamespace = false): string {
  if (withNamespace) {
    return `<${localName} xmlns="${NAMESPACE}">`;
  }

  return `<${localName}>`;
}

function closeTag(localName: string): string {
  return `</${localName}>`;
}

/**
 * Push `content` wrapped in its own `localName` element onto `parts`.
 *
 * We push the opening tag, the content and the closing tag as three separate
 * entries instead of pre-concatenating them, so that ``parts.join("")`` at
 * the top level copies the (possibly large, deeply nested) `content` exactly
 * once.
 */
function writeVElement(
  parts: Array<string>,
  localName: string,
  content: string
): void {
  parts.push(openTag(localName));
  parts.push(content);
  parts.push(closeTag(localName));
}

/**
 * Push a class instance already serialized to XML parts onto `parts`, wrapped
 * in its own element as given by {@link SerializedElement.localName}.
 */
function writeClassElement(
  parts: Array<string>,
  serialized: SerializedElement
): void {
  parts.push(openTag(serialized.localName));
  parts.push(serialized.innerXml);
  parts.push(closeTag(serialized.localName));
}

function escapeXmlText(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function serializeBooleanText(value: boolean): string {
  return value ? "true" : "false";
}

function serializeIntegerText(value: number): string {
  if (!Number.isInteger(value)) {
    throw new Error(`Expected an integer, but got: ${value}`);
  }

  return `${value}`;
}

function serializeFloatText(value: number): string {
  if (Number.isNaN(value)) {
    return "NaN";
  }
  if (value === Infinity) {
    return "INF";
  }
  if (value === -Infinity) {
    return "-INF";
  }

  return `${value}`;
}

function serializeStringText(value: string): string {
  return escapeXmlText(value);
}

function serializeBase64EncodedBytesText(value: Uint8Array): string {
  return escapeXmlText(AasCommon.base64Encode(value));
}

/**
 * Serialize an AAS instance to XML parts.
 */
class Serializer extends AasTypes.AbstractTransformer<SerializedElement> {


/**
   * Serialize `that` to an XML element representation.
   *
   * @param that - instance to be serialized
   * @returns serialized XML element representation
   */
  transformStructuralFirst(
    that: AasTypes.StructuralFirst
  ): SerializedElement {
  const parts = new Array<string>();

  writeVElement(parts, "uniqueToFirst", serializeStringText(that.uniqueToFirst));

  return {
      localName: "structuralFirst",
      innerXml: parts.join("")
    };
  }

/**
   * Serialize `that` to an XML element representation.
   *
   * @param that - instance to be serialized
   * @returns serialized XML element representation
   */
  transformStructuralSecond(
    that: AasTypes.StructuralSecond
  ): SerializedElement {
  const parts = new Array<string>();

  writeVElement(parts, "uniqueToSecond", serializeStringText(that.uniqueToSecond));

  return {
      localName: "structuralSecond",
      innerXml: parts.join("")
    };
  }

/**
   * Serialize `that` to an XML element representation.
   *
   * @param that - instance to be serialized
   * @returns serialized XML element representation
   */
  transformMixedAbstractDescendantOne(
    that: AasTypes.MixedAbstractDescendantOne
  ): SerializedElement {
  const parts = new Array<string>();

  writeVElement(parts, "uniqueToAbstractDescendantOne", serializeStringText(that.uniqueToAbstractDescendantOne));

  return {
      localName: "mixedAbstractDescendantOne",
      innerXml: parts.join("")
    };
  }

/**
   * Serialize `that` to an XML element representation.
   *
   * @param that - instance to be serialized
   * @returns serialized XML element representation
   */
  transformMixedAbstractDescendantTwo(
    that: AasTypes.MixedAbstractDescendantTwo
  ): SerializedElement {
  const parts = new Array<string>();

  writeVElement(parts, "uniqueToAbstractDescendantTwo", serializeStringText(that.uniqueToAbstractDescendantTwo));

  return {
      localName: "mixedAbstractDescendantTwo",
      innerXml: parts.join("")
    };
  }

/**
   * Serialize `that` to an XML element representation.
   *
   * @param that - instance to be serialized
   * @returns serialized XML element representation
   */
  transformMixedConcreteWithDescendants(
    that: AasTypes.MixedConcreteWithDescendants
  ): SerializedElement {
  const parts = new Array<string>();

  writeVElement(parts, "someBaseProperty", serializeStringText(that.someBaseProperty));

  return {
      localName: "mixedConcreteWithDescendants",
      innerXml: parts.join("")
    };
  }

/**
   * Serialize `that` to an XML element representation.
   *
   * @param that - instance to be serialized
   * @returns serialized XML element representation
   */
  transformMixedConcreteWithDescendantsChild(
    that: AasTypes.MixedConcreteWithDescendantsChild
  ): SerializedElement {
  const parts = new Array<string>();

  writeVElement(parts, "someBaseProperty", serializeStringText(that.someBaseProperty));

  writeVElement(parts, "someChildProperty", serializeStringText(that.someChildProperty));

  return {
      localName: "mixedConcreteWithDescendantsChild",
      innerXml: parts.join("")
    };
  }

/**
   * Serialize `that` to an XML element representation.
   *
   * @param that - instance to be serialized
   * @returns serialized XML element representation
   */
  transformMixedConcreteLeaf(
    that: AasTypes.MixedConcreteLeaf
  ): SerializedElement {
  const parts = new Array<string>();

  writeVElement(parts, "uniqueToConcreteLeaf", serializeStringText(that.uniqueToConcreteLeaf));

  return {
      localName: "mixedConcreteLeaf",
      innerXml: parts.join("")
    };
  }

/**
   * Serialize `that` to an XML element representation.
   *
   * @param that - instance to be serialized
   * @returns serialized XML element representation
   */
  transformModelTypedFirst(
    that: AasTypes.ModelTypedFirst
  ): SerializedElement {
  const parts = new Array<string>();

  writeVElement(parts, "someProperty", serializeStringText(that.someProperty));

  return {
      localName: "modelTypedFirst",
      innerXml: parts.join("")
    };
  }

/**
   * Serialize `that` to an XML element representation.
   *
   * @param that - instance to be serialized
   * @returns serialized XML element representation
   */
  transformModelTypedSecond(
    that: AasTypes.ModelTypedSecond
  ): SerializedElement {
  const parts = new Array<string>();

  writeVElement(parts, "someProperty", serializeStringText(that.someProperty));

  return {
      localName: "modelTypedSecond",
      innerXml: parts.join("")
    };
  }

/**
   * Serialize `that` to an XML element representation.
   *
   * @param that - instance to be serialized
   * @returns serialized XML element representation
   */
  transformSomething(
    that: AasTypes.Something
  ): SerializedElement {
  const parts = new Array<string>();

  parts.push(openTag("structuralProperty"));
    writeClassElement(parts, this.transform(that.structuralProperty));
    parts.push(closeTag("structuralProperty"));

  parts.push(openTag("mixedProperty"));
    writeClassElement(parts, this.transform(that.mixedProperty));
    parts.push(closeTag("mixedProperty"));

  parts.push(openTag("modelTypedProperty"));
    writeClassElement(parts, this.transform(that.modelTypedProperty));
    parts.push(closeTag("modelTypedProperty"));

  parts.push(openTag("listStructuralProperty"));
    for (const itemListStructuralProperty of that.listStructuralProperty) {
      writeClassElement(parts, this.transform(itemListStructuralProperty));
    }
    parts.push(closeTag("listStructuralProperty"));

  parts.push(openTag("listMixedProperty"));
    for (const itemListMixedProperty of that.listMixedProperty) {
      writeClassElement(parts, this.transform(itemListMixedProperty));
    }
    parts.push(closeTag("listMixedProperty"));

  parts.push(openTag("listModelTypedProperty"));
    for (const itemListModelTypedProperty of that.listModelTypedProperty) {
      writeClassElement(parts, this.transform(itemListModelTypedProperty));
    }
    parts.push(closeTag("listModelTypedProperty"));

  parts.push(openTag("tupleProperty"));
    writeClassElement(parts, this.transform(that.tupleProperty[0]));
    writeClassElement(parts, this.transform(that.tupleProperty[1]));
    writeClassElement(parts, this.transform(that.tupleProperty[2]));
    parts.push(closeTag("tupleProperty"));

  if (that.optionalStructuralProperty !== null) {
      parts.push(openTag("optionalStructuralProperty"));
      writeClassElement(parts, this.transform(that.optionalStructuralProperty));
      parts.push(closeTag("optionalStructuralProperty"));
    }

  if (that.optionalMixedProperty !== null) {
      parts.push(openTag("optionalMixedProperty"));
      writeClassElement(parts, this.transform(that.optionalMixedProperty));
      parts.push(closeTag("optionalMixedProperty"));
    }

  if (that.optionalModelTypedProperty !== null) {
      parts.push(openTag("optionalModelTypedProperty"));
      writeClassElement(parts, this.transform(that.optionalModelTypedProperty));
      parts.push(closeTag("optionalModelTypedProperty"));
    }

  return {
      localName: "something",
      innerXml: parts.join("")
    };
  }
}

const SERIALIZER = new Serializer();

/**
 * Serialize an AAS instance as an XML string.
 *
 * @param that - AAS instance to serialize
 * @returns serialized XML string
 */
export function toXmlString(that: AasTypes.Class): string {
  const serialized = SERIALIZER.transform(that);
  const parts = new Array<string>();
  parts.push(openTag(serialized.localName, true));
  parts.push(serialized.innerXml);
  parts.push(closeTag(serialized.localName));
  return parts.join("");
}

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
